### ISSUE TITLE
🐛 [BUG]开启Tabs后登录或从根路径进来就会报错

### ISSUE THREAD

**Issue by DongWenHai** [ant-design/ant-design-pro#10070]
### 🐛 bug 描述

开启Tabs后登录或从根路径进来就会报错
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (mf-dep____vendor.a83636a4.js:275402:15)
    at scheduleUpdateOnFiber (mf-dep____vendor.a83636a4.js:273434:3)
    at dispatchAction (mf-dep____vendor.a83636a4.js:267743:5)
    at mf-dep____vendor.a83636a4.js:242442:7
    at invokePassiveEffectCreate (mf-dep____vendor.a83636a4.js:275086:20)
    at HTMLUnknownElement.callCallback (mf-dep____vendor.a83636a4.js:255549:14)
    at Object.invokeGuardedCallbackDev (mf-dep____vendor.a83636a4.js:255598:16)
    at invokeGuardedCallback (mf-dep____vendor.a83636a4.js:255660:31)
    at flushPassiveEffectsImpl (mf-dep____vendor.a83636a4.js:275173:9)
    at unstable_runWithPriority (mf-dep____vendor.a83636a4.js:287396:12)
    at runWithPriority$1 (mf-dep____vendor.a83636a4.js:262880:10)
    at flushPassiveEffects (mf-dep____vendor.a83636a4.js:275046:14)
    at performSyncWorkOnRoot (mf-dep____vendor.a83636a4.js:273868:3)
    at mf-dep____vendor.a83636a4.js:262931:26
    at unstable_runWithPriority (mf-dep____vendor.a83636a4.js:287396:12)
    at runWithPriority$1 (mf-dep____vendor.a83636a4.js:262880:10)
    at flushSyncCallbackQueueImpl (mf-dep____vendor.a83636a4.js:262926:9)
    at flushSyncCallbackQueue (mf-dep____vendor.a83636a4.js:262913:3)
    at flushPassiveEffectsImpl (mf-dep____vendor.a83636a4.js:275219:3)
    at unstable_runWithPriority (mf-dep____vendor.a83636a4.js:287396:12)
    at runWithPriority$1 (mf-dep____vendor.a83636a4.js:262880:10)
    at flushPassiveEffects (mf-dep____vendor.a83636a4.js:275046:14)
    at mf-dep____vendor.a83636a4.js:274923:11
    at workLoop (mf-dep____vendor.a83636a4.js:287345:34)
    at flushWork (mf-dep____vendor.a83636a4.js:287318:14)
    at MessagePort.performWorkUntilDeadline (mf-dep____vendor.a83636a4.js:287085:27)
index.js:1 The above error occurred in the <ForwardRef> component:

    at http://localhost:8000/mf-dep____vendor.a83636a4.js:242324:32
    at http://localhost:8000/mf-dep____vendor.a83636a4.js:118942:53
    at Menu (http://localhost:8000/mf-dep____vendor.a83636a4.js:119061:90)
    at div
    at div
    at aside
    at http://localhost:8000/mf-dep____vendor.a83636a4.js:116081:31
    at SiderMenu (http://localhost:8000/mf-dep____vendor.a83636a4.js:89064:25)
    at SiderMenuWrapper (http://localhost:8000/mf-dep____vendor.a83636a4.js:89323:24)
    at section
    at http://localhost:8000/mf-dep____vendor.a83636a4.js:116374:63
    at http://localhost:8000/mf-dep____vendor.a83636a4.js:116337:66
    at div
    at Provider (http://localhost:8000/mf-dep____vendor.a83636a4.js:296094:31)
    at BaseProLayout (http://localhost:8000/mf-dep____vendor.a83636a4.js:85588:71)
    at ProLayoutProvider (http://localhost:8000/mf-dep____vendor.a83636a4.js:86067:21)
    at ProLayout (http://localhost:8000/mf-dep____vendor.a83636a4.js:85909:18)
    at http://localhost:8000/.umi__plugin-layout__Layout.async.js:217:66
    at Suspense
    at RemoteComponent (http://localhost:8000/mf-dep____vendor.a83636a4.js:95149:33)
    at Routes (http://localhost:8000/mf-dep____vendor.a83636a4.js:94839:85)
    at Router (http://localhost:8000/mf-dep____vendor.a83636a4.js:96478:15)
    at BrowserRoutes (http://localhost:8000/mf-dep____vendor.a83636a4.js:94814:13)
    at FormProvider (http://localhost:8000/mf-dep____vendor.a83636a4.js:142367:31)
    at LocaleProvider (http://localhost:8000/mf-dep____vendor.a83636a4.js:117072:90)
    at ProviderChildren (http://localhost:8000/mf-dep____vendor.a83636a4.js:109973:24)
    at LocaleReceiver (http://localhost:8000/mf-dep____vendor.a83636a4.js:116946:90)
    at ConfigProvider (http://localhost:8000/mf-dep____vendor.a83636a4.js:110088:13)
    at _LocaleContainer (http://localhost:8000/src_umi_umi_ts.async.js:3319:146)
    at Provider (http://localhost:8000/src_umi_umi_ts.async.js:1556:74)
    at InitialStateProvider (http://localhost:8000/src_umi_umi_ts.async.js:1830:140)
    at Provider (http://localhost:8000/src_umi_umi_ts.async.js:3954:34)
    at ProviderWrapper (http://localhost:8000/src_umi_umi_ts.async.js:4169:137)
    at KeepAliveLayout (http://localhost:8000/src_umi_umi_ts.async.js:2342:143)
    at Browser (http://localhost:8000/mf-dep____vendor.a83636a4.js:94876:104)

### 📷 复现步骤 | Recurrence steps

开启Tabs登录可能因为tabs必须有一项，而登录后有一瞬间tabs有一项name为undefined,然后重定向就会报错

### © 版本信息

- Ant Design Pro 版本: [6.0.0-beta.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by coderlcb** [comment]
我也是退出登录后再登录，或者偶尔登录时报这个错。。。

**Comment by DongWenHai** [comment]
> 

![image](https://user-images.githubusercontent.com/34147892/181671563-9eb4b436-dec1-4a69-b3ba-f600cfd28e9c.png)
把路由配置里面的根路径重定向去掉就不会报错了

**Comment by coderlcb** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/34147892/181671563-9eb4b436-dec1-4a69-b3ba-f600cfd28e9c.png) 把路由配置里面的根路径重定向去掉就不会报错了

感谢！
