### ISSUE TITLE
🐛 [BUG]配置terserOptions, 编译报错: Invalid config keys: terserOptions

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro#10118]
### 🐛 bug 描述

依据[umijs官网说明](https://v3.umijs.org/zh-CN/config#terseroptions)配置`terserOptions`, 执行`npm run start`和`npm run build`报错: 
```
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: terserOptions
    at Function.validateConfig (D:\桌面\ops-web\node_modules\@umijs\core\dist\config\config.js:179:31)
    at Config.getConfig (D:\桌面\ops-web\node_modules\@umijs\core\dist\config\config.js:60:12)
    at Service.resolveConfig (D:\桌面\ops-web\node_modules\@umijs\core\dist\service\service.js:279:97)
    at Service.run (D:\桌面\ops-web\node_modules\@umijs\core\dist\service\service.js:236:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (D:\桌面\ops-web\node_modules\umi\dist\service\service.js:74:12)
    at async run (D:\桌面\ops-web\node_modules\umi\dist\cli\cli.js:55:7) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
fatal - A complete log of this run can be found in:
fatal - D:\桌面\ops-web\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 📷 复现步骤 | Recurrence steps

- `config/config.ts`中配置`terserOptions`:  
```
...
terserOptions: {
    compress: {
      drop_console: true,
      drop_debugger: true,
      pure_funcs: ['console.log'],
    },
  },
...
```  
- 运行或者打包项目

### 🏞 期望结果 | Expected results
配置`terser`后可正常运行或者打包项目, 或者给出解决方案

### 💻 复现代码 | Recurrence code
随便使用`npx @ant-design/pro-cli create myapp`, umi版本选择`umi@4`, 创建项目, 然后在`config/config.ts`中配置`terserOptions`

### © 版本信息

- Ant Design Pro 版本:  最新版
- umi 版本: v4
- 浏览器环境: chrome pc
- 开发环境: windows 11

### 🚑 其他信息

最新版的问题一大堆, 生产环境使用千万慎重选择, 掉坑里了!!!

**Comment by drizzlesconsin** [comment]
需要通过这个 https://umijs.org/docs/api/config#jsminifier-webpack 配置


```diff
// config/config.ts

+ jsMinifier: 'terser',
- terserOptions: {
+ jsMinifierOptions:"
    compress: {
      drop_console: true,
      drop_debugger: true,
      pure_funcs: ['console.log'],
    },
  },
```

**Comment by darkfiredarkhalo** [comment]
> ```diff
> jsMinifier: 'terser',
> ```

非常感谢!, 成功了!
