### ISSUE TITLE
🐛 [BUG]error - jsMinifier: esbuild is not supported when there is ie in the targets, you can use jsMinifier: 'terser'

### ISSUE THREAD

**Issue by uvd** [ant-design/ant-design-pro#10115]
### 🐛 bug 描述

yarn build 

### 📷 复现步骤 | Recurrence steps

```
$ max build
Hello PRO
Using openapi Plugin
info  - Umi v4.0.11
error - jsMinifier: esbuild is not supported when there is ie in the targets, you can use jsMinifier: 'terser'
fatal - Error: IE is not supported
    at getEsBuildTarget (/Users/mac/work/673/admin_web/node_modules/@umijs/preset-umi/node_modules/@umijs/bundler-webpack/dist/utils/getEsBuildTarget.js:31:11)
    at addCompressPlugin (/Users/mac/work/673/admin_web/node_modules/@umijs/preset-umi/node_modules/@umijs/bundler-webpack/dist/config/compressPlugin.js:55:70)
    at getConfig (/Users/mac/work/673/admin_web/node_modules/@umijs/preset-umi/node_modules/@umijs/bundler-webpack/dist/config/config.js:140:53)
    at async Proxy.build (/Users/mac/work/673/admin_web/node_modules/@umijs/preset-umi/node_modules/@umijs/bundler-webpack/dist/build.js:52:25)
    at async Command.fn (/Users/mac/work/673/admin_web/node_modules/@umijs/preset-umi/dist/commands/build.js:144:17)
    at async Service.run (/Users/mac/work/673/admin_web/node_modules/umi/node_modules/@umijs/core/dist/service/service.js:270:15)
    at async Service.run2 (/Users/mac/work/673/admin_web/node_modules/umi/dist/service/service.js:74:12)
    at async run (/Users/mac/work/673/admin_web/node_modules/umi/dist/cli/cli.js:55:7)
fatal - A complete log of this run can be found in:
fatal - /Users/mac/work/673/admin_web/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0 beta1]
- umi 版本  v4.0.11
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by enjkvbej** [comment]
+1

**Comment by enjkvbej** [comment]
+1

**Comment by wxk666** [comment]
估计是新版本有点问题, 我用的老的yarn.lock文件就好了, 新部署的项目出现的问题

**Comment by enjkvbej** [comment]
> 估计是新版本有点问题, 我用的老的yarn.lock文件就好了, 新部署的项目出现的问题

umi版本吗 请问是哪个版本？还是antd？

**Comment by chenshuai2144** [comment]
把 target 里面的 ie11 去掉。umi 新版本不兼容 ie11了

**Comment by sorrycc** [comment]
因为用了 esbuild 就兼容不了 IE 11，这两个是冲突的。所以要么去掉 targets 里 ie 11 的配置，要么配 jsMinifier: 'terser'。

**Comment by BeatsKitano** [comment]
@sorrycc 你这人太不懂事了，这种库就是用来踩坑的。
cli新建一个工程，然后无法build，给出的文档位置都是打不开的。人生很无聊，就是需要找找这种乐趣。
全局搜索搜一下`targets:` 应该有`ie: 11`

**Comment by roseqin368** [comment]
![screenshot-20220829-115010](https://user-images.githubusercontent.com/74444483/187119524-de888eb6-28cf-4ae1-bb0e-4f36fe5f46bb.png)

**Comment by 13396022881wei** [comment]
怎么解决这bug

**Comment by ZHUIMEN** [comment]
今天 项目打包 上线用 Umi v4.0.19打包各种问题 一顿爬楼 

![image](https://user-images.githubusercontent.com/30618748/189310899-ebfecd8a-2a0f-464c-a999-1fc9141225da.png)
