### ISSUE TITLE
🐛 [BUG] 新版本初始化都有问题

### ISSUE THREAD

**Issue by marlti7** [ant-design/ant-design-pro#10132]
> @umijs/bundler-vite@4.0.0-canary.20220628.2 postinstall /Users/mq-zy/Documents/suihu-cms/node_modules/@umijs/max-plugin-openapi/node_modules/@umijs/bundler-vite
> node scripts/linkDeps.js

> ant-design-pro@6.0.0-beta.1 postinstall /Users/mq-zy/Documents/suihu-cms
> max setup

/Users/mq-zy/Documents/suihu-cms/node_modules/@umijs/utils/dist/isStyleFile.js:39
  return AUTO_CSS_MODULE_EXTS.includes(ext ?? (0, import_path.extname)(filename));
                                            ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mq-zy/Documents/suihu-cms/node_modules/@umijs/utils/dist/index.js:91:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@6.0.0-beta.1 postinstall: `max setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@6.0.0-beta.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mq-zy/.npm/_logs/2022-08-15T03_23_11_112Z-debug.log
➜  suihu-cms npm install       

> ant-design-pro@6.0.0-beta.1 postinstall /Users/mq-zy/Documents/suihu-cms
> max setup

/Users/mq-zy/Documents/suihu-cms/node_modules/@umijs/utils/dist/isStyleFile.js:39
  return AUTO_CSS_MODULE_EXTS.includes(ext ?? (0, import_path.extname)(filename));

**Comment by LChloe** [comment]
是的 我也是这个问题：6.0beta版本

**Comment by ttjimsen** [comment]
给个坑呀，还没人上来解决？

**Comment by deep-sleep-still** [comment]
> 

我刚才也碰到这个问题，弄的版本原因，把node升级到最新的版本，重新安装一下依赖就可以解决了

**Comment by deep-sleep-still** [comment]
> 是的 我也是这个问题：6.0beta版本

我刚才也碰到这个问题，node版本原因，把node升级到最新的版本，重新安装一下依赖就可以解决了

**Comment by chenshuai2144** [comment]
升级下 node 版本，16 就可以的
