### ISSUE TITLE
🐛 [BUG]pro创建脚手架build报错

### ISSUE THREAD

**Issue by jounzhang** [ant-design/ant-design-pro#10154]
### 🐛 bug 描述
根据官方文档，使用pro创建项目
# 使用 npm
npm i @ant-design/pro-cli -g
pro create myapp

? 🐂 使用 umi@4 还是 umi@3 ? (Use arrow keys)
❯ umi@4
  umi@3

PS D:\workspace\project\axinfu\stream_web> npm run build

> ant-design-pro@6.0.0-beta.1 build
> max build

Hello PRO
info  - Umi v4.0.12
error - jsMinifier: esbuild is not supported when there is ie in the targets, you can use jsMinifier: 'terser'
fatal - Error: IE is not supported
    at getEsBuildTarget (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\utils\getEsBuildTarget.js:31:11)
    at addCompressPlugin (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\config\compressPlugin.js:55:70)
    at getConfig (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\config\config.js:140:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Proxy.build (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+bundler-webpack@4.0.12_xnp4kzegbjokq62cajex2ovgkm\node_modules\@umijs\bundler-webpack\dist\build.js:52:25)
    at async Command.fn (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+preset-umi@4.0.12_kbunkbeezhexeikqzjunp6h7bq\node_modules\@umijs\preset-umi\dist\commands\build.js:144:17)
    at async Service.run (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\@umijs+core@4.0.12\node_modules\@umijs\core\dist\service\service.js:270:15)
    at async Service.run2 (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\umi@4.0.12_llqjcapggugs3ytnsdohj4a7a4\node_modules\umi\dist\service\service.js:74:12)
    at async run (D:\workspace\project\axinfu\stream_web\node_modules\.pnpm\umi@4.0.12_llqjcapggugs3ytnsdohj4a7a4\node_modules\umi\dist\cli\cli.js:55:7)
fatal - A complete log of this run can be found in:
fatal - D:\workspace\project\axinfu\stream_web\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
PS D:\workspace\project\axinfu\stream_web> 

需要怎么配置才能正常build，不需要支持es5。

**Comment by kungege** [comment]
在 `config/config.ts` 中移除 
```js 
targets: {
    ie: 11,
  },
 ```
