### ISSUE TITLE
🧐[问题 | question]  ant-design-pro v5版本 使用pnpm安装依赖dependency出错.

### ISSUE THREAD

**Issue by ohaTgxK9956562414460** [ant-design/ant-design-pro#10165]
### 🧐 问题描述 | Problem description
ant-design-pro V5 使用pnpm安装依赖dependency出错。
请问如何调整，可以正常使用pnpm来管理dependency

### 💻 示例代码 | Sample code

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: ~/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1916, reused 1832, downloaded 0, added 1903, done

> ant-design-pro@6.0.0-beta.1 postinstall ~/workspace/code/github/umi_4/myapp
> max setup

✘ [ERROR] Cannot start service: Host version "0.14.49" does not match binary version "0.14.36"

1 error
fatal - Error: Parse config file failed: [~/workspace/code/github/umi_4/myapp/config/config.ts]
    at Function.getUserConfig (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+core@4.0.13/node_modules/@umijs/core/dist/config/config.js:143:17)
    at Config.getUserConfig (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+core@4.0.13/node_modules/@umijs/core/dist/config/config.js:51:19)
    at Service.run (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+core@4.0.13/node_modules/@umijs/core/dist/service/service.js:195:37)
    at Service.run2 (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+umi@4.0.13_sp7uudkmluzvlzxxblnicjjpby/node_modules/umi/dist/service/service.js:74:23)
    at run (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+umi@4.0.13_sp7uudkmluzvlzxxblnicjjpby/node_modules/umi/dist/cli/cli.js:55:42)
    at Object.<anonymous> (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+max@4.0.13_fqkmyig3ujbgvysgdtjoijg3li/node_modules/@umijs/max/dist/cli.js:19:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  [cause]: Error: Parse file failed: [~/workspace/code/github/umi_4/myapp/config/config.ts]
      at transform (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+utils@4.0.13/node_modules/@umijs/utils/dist/register.js:49:11)
      at revert.ext (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+utils@4.0.13/node_modules/@umijs/utils/dist/register.js:55:62)
      at Module._compile (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+utils@4.0.13/node_modules/@umijs/utils/compiled/pirates/index.js:1:1609)
      at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Object.newLoader [as .ts] (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+utils@4.0.13/node_modules/@umijs/utils/compiled/pirates/index.js:1:1684)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Function.getUserConfig (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+@umijs+core@4.0.13/node_modules/@umijs/core/dist/config/config.js:141:54) {
    [cause]: Error: The service was stopped
        at ~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+esbuild@0.14.49/node_modules/esbuild/lib/main.js:1381:29
        at ~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+esbuild@0.14.49/node_modules/esbuild/lib/main.js:666:9
        at Socket.afterClose (~/workspace/code/github/umi_4/myapp/node_modules/.pnpm/registry.npmmirror.com+esbuild@0.14.49/node_modules/esbuild/lib/main.js:644:7)
        at Socket.emit (node:events:539:35)
        at endReadableNT (node:internal/streams/readable:1345:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
  }
}
fatal - A complete log of this run can be found in:
fatal - ~/workspace/code/github/umi_4/myapp/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
 ELIFECYCLE  Command failed with exit code 1.

### 🚑 其他信息 | Other information

pnpm: 7.9.4

OS: macOS12.5

Node：v16.16.0

浏览器 | browser：

**Comment by fz6m** [comment]
如果 pnpm 创建项目遇到问题，目前的解决办法是，暂时锁定项目 esbuild 版本：

```ts
// package.json
{
  "pnpm": {
    "overrides": {
      "esbuild": "0.15.10"
    }
  }
}
```

**Comment by chenshuai2144** [comment]
重新更新一下，我试了一下是可以的
