### ISSUE TITLE
🧐[问题 | question] 为什么今天从pro上拉下来的项目运行不了？

### ISSUE THREAD

**Issue by 18046163690** [ant-design/ant-design-pro#10170]
### 🧐 问题描述 | Problem description

error Couldn't find a package.json file in "C:\\Users\\admin\\Desktop\\app"
    at Service.run2 (C:\Users\admin\Desktop\app\myapp\node_modules\umi\dist\service\service.js:74:23)
    at C:\Users\admin\Desktop\app\myapp\node_modules\umi\dist\cli\forkedDev.js:24:19
    at Object.<anonymous> (C:\Users\admin\Desktop\app\myapp\node_modules\umi\dist\cli\forkedDev.js:37:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by chenshuai2144** [comment]
清空一下依赖重新安装一下
