### ISSUE TITLE
🐛 [BUG]执行 a

### ISSUE THREAD

**Issue by manneia** [ant-design/ant-design-pro#10282]
### 🐛 bug 描述

<Error: 编译失败
    at module.exports (D:\Project\新建文件夹\myapp\node_modules\node-import-ts\lib\index.js:29:15)
    at D:\Project\新建文件夹\myapp\node_modules\@ant-design\pro-cli\src\i18n\getLocalFileList.js:52:22
    at Array.map (<anonymous>)
    at module.exports (D:\Project\新建文件夹\myapp\node_modules\@ant-design\pro-cli\src\i18n\getLocalFileList.js:52:6)
    at module.exports (D:\Project\新建文件夹\myapp\node_modules\@ant-design\pro-cli\src\i18n\index.js:49:21)
    at Object.<anonymous> (D:\Project\新建文件夹\myapp\node_modules\@ant-design\pro-cli\cli.js:41:32)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by dingtianxiu** [comment]
#10273
