### ISSUE TITLE
🧐[问题 | question]启动项目正常，build之后报错。

### ISSUE THREAD

**Issue by skiinaurora** [ant-design/ant-design-pro#10319]
### 🧐 问题描述 | Problem description
开发完成了，运行npm run build，将打包后的内容部署到nginx上，登录界面正常显示，登录之后白屏，报的错是这个：
        
    TypeError: Cannot read properties of null (reading 'dispatcher')
    at jt (umi.27e27f52.js:167:41107)
    at on (umi.27e27f52.js:167:41770)
    at $e (umi.27e27f52.js:279:54752)
    at mf (umi.27e27f52.js:283:9220)
    at uf (umi.27e27f52.js:283:992)
    at wf (umi.27e27f52.js:283:920)
    at yd (umi.27e27f52.js:283:771)
    at Hd (umi.27e27f52.js:281:11160)
    at umi.27e27f52.js:279:39567
    at v.unstable_runWithPriority (umi.27e27f52.js:283:64584)

### 💻 示例代码 | Sample code
package.json文件
```
{
  "name": "ant-design-pro",
  "version": "6.0.0-beta.1",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 max build",
    "build": "max build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "max setup",
    "lint": "npm run lint:js && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src ",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "openapi": "max openapi",
    "playwright": "playwright install && playwright test",
    "prepare": "husky install",
    "prettier": "prettier -c --write \"src/**/*\"",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev max dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev max dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev max dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev max dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev max dev",
    "test:e2e": "node ./tests/run-tests.js",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/charts": "^1.4.2",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.0.0",
    "@umijs/route-utils": "^2.1.3",
    "antd": "^4.20.0",
    "classnames": "^2.3.0",
    "flv.js": "^1.6.2",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-color": "^2.19.3",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.11.1",
    "@umijs/max": "^4.0.0-rc.22",
    "@umijs/openapi": "^1.3.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "eslint": "^7.32.0",
    "gh-pages": "^3.2.0",
    "husky": "^7.0.4",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "swagger-ui-dist": "^4.12.0",
    "typescript": "^4.5.0",
    "umi-presets-pro": "^1.0.1",
    "umi-serve": "^1.9.10"
  },
  "engines": {
    "node": ">=12.0.0"
  }
}
```

### 🚑 其他信息 | Other information
[OS:]
![屏幕截图 2022-10-23 181729](https://user-images.githubusercontent.com/105364939/197386820-87e6c5ea-01c7-4f0b-b7f9-dd8eb7f207b9.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案 | Solution

根据报错信息和提供的示例代码，可以初步推测出问题出在 `umi` 框架上。

一种可能的情况是，执行 `npm run build` 时出现了错误，导致打包过程中产生了异常，最终导致打包后的代码无法正常使用。

推荐的解决方案如下：

1. 检查 `package.json` 文件中 `dependencies` 和 `devDependencies` 是否正确配置，是否存在版本冲突或重复安装的包。

2. 检查代码中是否存在语法、逻辑等错误，可以通过运行 `npm run lint` 命令检查代码，或者通过 `npm run test` 命令运行测试，确保代码质量和稳定性。

3. 可以将 `NODE_ENV` 设置为 `"production"`，在本地重新运行应用程序进行测试，了解运行日志和错误信息的详细信息。从而更好的理解问题产生的原因和解决方案。

4. 可以尝试升级 `umi` 框架和相关依赖包的版本，或者换用其他的 UI 框架套件。

在排查问题过程中，可以参考以下有用的文档：

- [umi.js 官方文档](https://umijs.org/zh-CN/docs/getting-started)
- [React 官方文档](https://reactjs.org/docs/getting-started.html)
- [Ant Design Pro 官方文档](https://pro.ant.design/docs/getting-started-cn)

**Comment by Jim523424zf** [comment]
jsMinifier: 'terser',
