### ISSUE TITLE
🧐[问题 | question] ant design pro + qiankun进行配置，依赖均使用默认的版本，从master项目页面菜单访问slave，报错`Iframe has not been created yet.`

### ISSUE THREAD

**Issue by kuaikaiyun** [ant-design/ant-design-pro#10351]
### 🧐 问题描述 | Problem description

我根据`https://v3.umijs.org/zh-CN/plugins/plugin-qiankun`页面的提示，使用ant design pro + qiankun进行配置，依赖均使用默认的版本，从master项目页面菜单访问slave，报错`Iframe has not been created yet.`

具体复现步骤如下（代码仓库在结尾）：

1. 使用命令`pro create master`创建master项目，选择umi4

2. 在master的`config.ts`文件中加入：

   ```javascript
   qiankun: {
       master: {
         // 注册子应用信息
         apps: [
           {
             name: 'app1', // 唯一 id
             entry: '//localhost:8001', // html entry
           },
         ],
       },
     },
   ```

3. 在master的`routes.ts`加入路由配置：

   ```javascript
     {
       name: 'app1Name',
       path: '/app1',
       microApp: 'app1',
     },
   ```

4. 在master项目执行命令启动`tyarn run dev`

5. 使用命令`pro create slave`创建slave项目，选择umi4

6. 在slave的`config.ts`中加入：

   ```javascript
     qiankun: {
       slave: {},
     },
   ```

7. 在slave创建`.env`文件，配置`PORT=8001`

8. 在slave项目执行命令启动`tyarn run dev`

9. 从localhost:8000访问打开app1Name菜单，报错`Iframe has not been created yet.`

   ```
   [webpack] connecting...
   client.js:54 [webpack] connected.
   2mf-va_remoteEntry.js:692 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
       at __webpack_require__ (mf-va_remoteEntry.js:692:42)
       at eval (mf-va_remoteEntry.js:46:105)
       at __webpack_require__.m.<computed> (remotes loading:1285:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at fn (hot module replacement:62:1)
       at ./src/.umi/core/polyfill.ts (plugin.ts:67:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at fn (hot module replacement:62:1)
       at ./src/.umi/umi.ts (index.ts:4:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at Function.fn (hot module replacement:62:1)
       at async eval (umi.js:2:1)
   __webpack_require__ @ mf-va_remoteEntry.js:692
   eval @ mf-va_remoteEntry.js:46
   __webpack_require__.m.<computed> @ remotes loading:1285
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   ./src/.umi/core/polyfill.ts @ plugin.ts:67
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   ./src/.umi/umi.ts @ index.ts:4
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   Promise.catch（异步）
   （匿名） @ MicroApp.tsx:205
   （匿名） @ MicroApp.tsx:202
   invokePassiveEffectCreate @ mf-dep____vendor.6bd2a932.js:273694
   callCallback @ mf-dep____vendor.6bd2a932.js:254157
   invokeGuardedCallbackDev @ mf-dep____vendor.6bd2a932.js:254206
   invokeGuardedCallback @ mf-dep____vendor.6bd2a932.js:254268
   flushPassiveEffectsImpl @ mf-dep____vendor.6bd2a932.js:273781
   unstable_runWithPriority @ mf-dep____vendor.6bd2a932.js:287401
   runWithPriority$1 @ mf-dep____vendor.6bd2a932.js:261488
   flushPassiveEffects @ mf-dep____vendor.6bd2a932.js:273654
   （匿名） @ mf-dep____vendor.6bd2a932.js:273531
   workLoop @ mf-dep____vendor.6bd2a932.js:287350
   flushWork @ mf-dep____vendor.6bd2a932.js:287323
   performWorkUntilDeadline @ mf-dep____vendor.6bd2a932.js:287090
   mf-va_remoteEntry.js:692 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
       at __webpack_require__ (mf-va_remoteEntry.js:692:42)
       at eval (mf-va_remoteEntry.js:46:105)
       at __webpack_require__.m.<computed> (remotes loading:1285:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at fn (hot module replacement:62:1)
       at ./src/.umi/core/polyfill.ts (plugin.ts:67:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at fn (hot module replacement:62:1)
       at ./src/.umi/umi.ts (index.ts:4:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at Function.fn (hot module replacement:62:1)
       at async eval (umi.js:2:1)
   __webpack_require__ @ mf-va_remoteEntry.js:692
   eval @ mf-va_remoteEntry.js:46
   __webpack_require__.m.<computed> @ remotes loading:1285
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   ./src/.umi/core/polyfill.ts @ plugin.ts:67
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   ./src/.umi/umi.ts @ index.ts:4
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   Promise.then（异步）
   （匿名） @ MicroApp.tsx:180
   invokePassiveEffectCreate @ mf-dep____vendor.6bd2a932.js:273694
   callCallback @ mf-dep____vendor.6bd2a932.js:254157
   invokeGuardedCallbackDev @ mf-dep____vendor.6bd2a932.js:254206
   invokeGuardedCallback @ mf-dep____vendor.6bd2a932.js:254268
   flushPassiveEffectsImpl @ mf-dep____vendor.6bd2a932.js:273781
   unstable_runWithPriority @ mf-dep____vendor.6bd2a932.js:287401
   runWithPriority$1 @ mf-dep____vendor.6bd2a932.js:261488
   flushPassiveEffects @ mf-dep____vendor.6bd2a932.js:273654
   （匿名） @ mf-dep____vendor.6bd2a932.js:273531
   workLoop @ mf-dep____vendor.6bd2a932.js:287350
   flushWork @ mf-dep____vendor.6bd2a932.js:287323
   performWorkUntilDeadline @ mf-dep____vendor.6bd2a932.js:287090
   mf-va_remoteEntry.js:692 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
       at __webpack_require__ (mf-va_remoteEntry.js:692:42)
       at eval (mf-va_remoteEntry.js:46:105)
       at __webpack_require__.m.<computed> (remotes loading:1285:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at fn (hot module replacement:62:1)
       at ./src/.umi/core/polyfill.ts (plugin.ts:67:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at fn (hot module replacement:62:1)
       at ./src/.umi/umi.ts (index.ts:4:1)
       at options.factory (react refresh:6:1)
       at __webpack_require__ (bootstrap:24:1)
       at Function.fn (hot module replacement:62:1)
       at async eval (umi.js:2:1)
   __webpack_require__ @ mf-va_remoteEntry.js:692
   eval @ mf-va_remoteEntry.js:46
   __webpack_require__.m.<computed> @ remotes loading:1285
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   ./src/.umi/core/polyfill.ts @ plugin.ts:67
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   ./src/.umi/umi.ts @ index.ts:4
   options.factory @ react refresh:6
   __webpack_require__ @ bootstrap:24
   fn @ hot module replacement:62
   Promise.catch（异步）
   （匿名） @ MicroApp.tsx:205
   （匿名） @ MicroApp.tsx:202
   invokePassiveEffectCreate @ mf-dep____vendor.6bd2a932.js:273694
   callCallback @ mf-dep____vendor.6bd2a932.js:254157
   invokeGuardedCallbackDev @ mf-dep____vendor.6bd2a932.js:254206
   invokeGuardedCallback @ mf-dep____vendor.6bd2a932.js:254268
   flushPassiveEffectsImpl @ mf-dep____vendor.6bd2a932.js:273781
   unstable_runWithPriority @ mf-dep____vendor.6bd2a932.js:287401
   runWithPriority$1 @ mf-dep____vendor.6bd2a932.js:261488
   flushPassiveEffects @ mf-dep____vendor.6bd2a932.js:273654
   （匿名） @ mf-dep____vendor.6bd2a932.js:273531
   workLoop @ mf-dep____vendor.6bd2a932.js:287350
   flushWork @ mf-dep____vendor.6bd2a932.js:287323
   performWorkUntilDeadline @ mf-dep____vendor.6bd2a932.js:287090
   index.js:1 Uncaught Error: Iframe has not been created yet.
       at ve (index.js:1:1)
       at window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__.iframeReady (index.js:1:1)
       at Module.<anonymous> (<anonymous>:2:299992)
       at r (<anonymous>:2:110)
       at <anonymous>:2:904
       at <anonymous>:2:915
       at e.onload (index.js:1:1)
       at HTMLBodyElement.appendChildOrInsertBefore [as appendChild] (mf-dep____vendor.6bd2a932.js:199054:41)
       at me (index.js:1:1)
       at index.js:1:1
       at index.js:1:1
   ve @ index.js:1
   window.__REACT_ERROR_OVERLAY_GLOBAL_HOOK__.iframeReady @ index.js:1
   （匿名） @ VM74:2
   r @ VM74:2
   （匿名） @ VM74:2
   （匿名） @ VM74:2
   e.onload @ index.js:1
   appendChildOrInsertBefore @ mf-dep____vendor.6bd2a932.js:199054
   me @ index.js:1
   （匿名） @ index.js:1
   （匿名） @ index.js:1
   load（异步）
   me @ index.js:1
   （匿名） @ index.js:1
   （匿名） @ index.js:1
   Promise.then（异步）
   （匿名） @ index.js:1
   （匿名） @ index.js:1
   l @ index.js:1
   index.js:1 Could not get the stack frames of error: Error: Iframe has not been created yet.
       at ve (index.js:1:1)
       at me (index.js:1:1)
       at eval (index.js:1:1)
       at eval (index.js:1:1)
   ```

### 💻 示例代码 | Sample code

复现仓库地址：
`https://github.com/kuaikaiyun/ant-design-pro-qiankun-issue-project.git`

### 🚑 其他信息 | Other information

经过测试，master项目跳转到`https://gitclone.com/github.com/umijs/plugins.git`项目中的qiankun示例子应用，不会出现此问题
使用qiankun示例中的master跳转到 ant design pro + qiankun 的子应用也不会出现问题；
仅上文 ant design pro + qiankun 主应用和子应用跳转时页面会崩溃报错；

请问这个是配置问题还是兼容性的BUG呢？我该怎么解决这个问题，感谢

OS: Window 10

Node：v14.21.1

浏览器 | browser：Chrome 版本 105.0.5195.127（正式版本） （64 位）

**Comment by kuaikaiyun** [comment]
已解决，关闭mfsu即可，需要注意的是，最新版本的不能是注释掉就关闭了，而是要标记为false，也就是mfsu: false,

**Comment by xXAvoraXx** [comment]
How to make qiankun with ant design pro v6?
ant design pro v6如何制作乾坤
