### ISSUE TITLE
🧐[问题 | question]初始化脚手架出错

### ISSUE THREAD

**Issue by miaoyahong** [ant-design/ant-design-pro#10456]
### 🧐 问题描述 | Problem description

初始化脚手架出错
 Object.fromEntries is not a function

### 💻 示例代码 | Sample code
pro create myapp
C:\Users\miaoyahong\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\npm-registry-fetch\node_modules\@npmcli\fs\lib\fs.js:6
const fsSync = Object.fromEntries(Object.entries(fs).filter(([k, v]) =>
                      ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (C:\Users\miaoyahong\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\npm-registry-fetch\node_modules\@npmcli\fs\lib\fs.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\miaoyahong\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\npm-registry-fetch\node_modules\@npmcli\fs\lib\index.js:2:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/30410291/209419255-be76ce06-3099-4e00-96a4-363e13fa53ac.png)

OS:

Node：

浏览器 | browser：

**Comment by miaoyahong** [comment]
node版本过低的问题
