### ISSUE TITLE
🐛 [BUG]问题1： 代码刷下来，登陆进入首页，js报错， 问题2： 选中二级菜单，点击展开菜单，菜单名称出现在左上角

### ISSUE THREAD

**Issue by pc110** [ant-design/ant-design-pro#10576]
问题1： 代码刷下来，登陆进入首页，js报错
index.js:1 Warning: React does not recognize the `suffixCls` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `suffixcls` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at section
    at http://localhost:8002/mf-dep____vendor.45fcd2fe.js:126897:42
    at Layout
    at div
    at BaseProLayout (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:67973:13)
    at FormProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:212985:31)
    at ProviderChildren (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:115903:5)
    at ConfigProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:116024:54)
    at div
    at SWRConfig (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:301083:13)
    at ConfigProviderContainer (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:80815:24)
    at FormProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:212985:31)
    at LocaleProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:128440:5)
    at ProviderChildren (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:115903:5)
    at ConfigProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:116024:54)
    at ProConfigProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:80927:24)
    at FormProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:212985:31)
    at ProviderChildren (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:115903:5)
    at ConfigProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:116024:54)
    at ProLayout (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:68276:28)
    at http://localhost:8002/umi__plugin-layout__Layout.async.js:209:66
    at Suspense
    at RemoteComponent (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:106069:25)
    at Routes (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:105605:76)
    at Router (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:286093:15)
    at BrowserRoutes (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:105567:23)
    at r (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:284062:7350)
    at FormProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:212985:31)
    at LocaleProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:128440:5)
    at ProviderChildren (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:115903:5)
    at ConfigProvider (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:116024:54)
    at _LocaleContainer (http://localhost:8002/src_umi_umi_ts.async.js:3046:117)
    at Provider (http://localhost:8002/src_umi_umi_ts.async.js:1725:74)
    at InitialStateProvider (http://localhost:8002/src_umi_umi_ts.async.js:2022:111)
    at Provider (http://localhost:8002/src_umi_umi_ts.async.js:3661:34)
    at ProviderWrapper (http://localhost:8002/src_umi_umi_ts.async.js:3863:108)
    at Browser (http://localhost:8002/mf-dep____vendor.45fcd2fe.js:105670:68)
console.<computed> @ index.js:1
printWarning @ mf-dep____vendor.45fcd2fe.js:254036
error @ mf-dep____vendor.45fcd2fe.js:254010
validateProperty$1 @ mf-dep____vendor.45fcd2fe.js:257707
warnUnknownProperties @ mf-dep____vendor.45fcd2fe.js:257753
validateProperties$2 @ mf-dep____vendor.45fcd2fe.js:257777
validatePropertiesInDevelopment @ mf-dep____vendor.45fcd2fe.js:263491
setInitialProperties @ mf-dep____vendor.45fcd2fe.js:263780
finalizeInitialChildren @ mf-dep____vendor.45fcd2fe.js:264900
completeWork @ mf-dep____vendor.45fcd2fe.js:276138
completeUnitOfWork @ mf-dep____vendor.45fcd2fe.js:280541
performUnitOfWork @ mf-dep____vendor.45fcd2fe.js:280513
workLoopSync @ mf-dep____vendor.45fcd2fe.js:280411
renderRootSync @ mf-dep____vendor.45fcd2fe.js:280379
performConcurrentWorkOnRoot @ mf-dep____vendor.45fcd2fe.js:279683
workLoop @ mf-dep____vendor.45fcd2fe.js:295747
flushWork @ mf-dep____vendor.45fcd2fe.js:295720
performWorkUntilDeadline @ mf-dep____vendor.45fcd2fe.js:296014
queue.<computed> @ mf-dep____vendor.45fcd2fe.js:178098
run @ mf-dep____vendor.45fcd2fe.js:178072
eventListener @ mf-dep____vendor.45fcd2fe.js:178083

问题2： 选中二级菜单，点击展开菜单，菜单名称出现在左上角
![image](https://user-images.githubusercontent.com/29336835/222408753-8a9e9ecf-909a-486e-b000-643917477bff.png)

**Comment by lgcgo** [comment]
+1

**Comment by fxx3344** [comment]
+1

**Comment by Maples-tainedRedDust** [comment]
+1

**Comment by Chen-913** [comment]
我遇到了相同的问题
![image](https://user-images.githubusercontent.com/72293244/222938806-ee1c1703-e910-4a59-a818-b57eb2b62463.png)
现在v4版本是稳定可用的吗？我想找个稳定一点的版本

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


v4版本已经发布过几个版本了，目前来看稳定性已经相对较高，但是由于每个项目的具体业务和依赖情况不同，还是建议在升级前认真测试，并备份好代码。

针对你所遇到的问题，我们可以具体分析一下：

问题1：

报错信息提示 React 并不认识 DOM 元素上的 `suffixCls ` 属性。你需要检查你的代码中，是否有意向将它作为一个自定义属性呈现在 DOM 元素上，如果是的话，需要将它以小写的 `suffixcls ` 格式漏出去。如果不是，那么可能是这个属性不应该出现在这个 DOM 元素上，需要剔除。

具体的解决方法，可以考虑采用以下两种方式中的一种：

- 扫描你的代码，搜索 `suffixCls` ，找出出现它的位置，确认是否有误。
- 检查所使用的组件库文档，确认 `suffixCls` 是否与该组件库的使用方式有关。也许可以查看组件库或者代码示例，进一步理解如何消除这个报错。

问题2：

这可能与组件样式的设置有关，你需要检查你的代码，看看是否设置了合适的样式，或者依赖的组件库是否有一致的样式设置。

具体的解决方法，可以考虑采用以下两种方式中的一种：

- 检查你的代码，看看是否对对相应的组件引入了不正确的样式文件，或者对样式设置错误。
- 检查组件库文档，了解组件的样式设置，以便更好的应用和覆盖组件的样式。

参考文档：

- React 官方文档：https://reactjs.org/
- Ant Design 组件库官方文档：https://ant.design/docs/react/introduce-cn

**Comment by zFitness** [comment]
+1

**Comment by zFitness** [comment]
```
const BasicLayout = /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_2__.forwardRef((props, ref) => {
  const {
    direction
  } = react__WEBPACK_IMPORTED_MODULE_2__.useContext(_config_provider__WEBPACK_IMPORTED_MODULE_3__.ConfigContext);
  const [siders, setSiders] = react__WEBPACK_IMPORTED_MODULE_2__.useState([]);
  const {
      prefixCls: customizePrefixCls,
      className,
      rootClassName,
      children,
      hasSider,
      tagName: Tag
    } = props,

```

**Comment by pc110** [comment]
> prefixCls
? 什么意思

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


`prefixCls` 是 Ant Design 组件库中常用的一个属性，用于设置当前组件的 class 前缀。

例如，在使用 Ant Design 的布局组件 `Layout` 时，你可以通过设置 `prefixCls` 来自定义类名的前缀，从而控制样式的覆盖和定制。具体使用方式可以查看对应的文档。

对于其他组件，也可以通过设置 `prefixCls` 控制样式和定制样式名。

需要注意的是，这个属性并不是 React 官方的支持属性，而是很多 Ant Design 组件中都会提供的一种定制化拓展方式，具体实现也会因组件而异。

**Comment by chenshuai2144** [comment]
suffixCls 看起来是内部实现

浮动是antd的bug

都等 antd 更新吧

**Comment by yaohwu** [comment]
> 浮动是antd的bug

这个有对应的 issue 或者其他 bug 编号可以跟进么？

**Comment by yaohwu** [comment]
https://github.com/ant-design/pro-components/issues/6722#issuecomment-1543127909
