### ISSUE TITLE
新建的react18项目，不能直接使用pro组件，报错提示process is not defined  

### ISSUE THREAD

**Issue by zhouzhiqing8426** [ant-design/ant-design-pro#10705]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/73320996/234642126-a4e15c2c-6e5a-4d12-8f82-6defdcdf0725.png">
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/73320996/234642239-9f97ede8-2d4b-4a5a-9bc0-3b77d89a0ed5.png">
我需要如何配置

**Comment by WangDianhang** [comment]
碰到一样的问题，react18+antd pro +webpack, 

ReferenceError: process is not defined
    at http://localhost:3000/static/js/vendors-node_modules_ant-design_pro-table_es_Table_js.chunk.js:23154:5
    at mountMemo (http://localhost:3000/static/js/bundle.js:25611:23)
    at Object.useMemo (http://localhost:3000/static/js/bundle.js:25996:20)
    at useMemo (http://localhost:3000/static/js/bundle.js:42162:25)
    at ConfigProviderContainer (http://localhost:3000/static/js/vendors-node_modules_ant-design_pro-table_es_Table_js.chunk.js:23148:62)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:24839:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:28125:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:29421:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:34384:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33653:16)

**Comment by Vsnoy** [comment]
请问老哥是如何解决的？我也碰到这个问题了。

**Comment by Vsnoy** [comment]
> 碰到一样的问题，react18+antd pro +webpack, 
> 
> 
> 
> ReferenceError: process is not defined
> 
>     at http://localhost:3000/static/js/vendors-node_modules_ant-design_pro-table_es_Table_js.chunk.js:23154:5
> 
>     at mountMemo (http://localhost:3000/static/js/bundle.js:25611:23)
> 
>     at Object.useMemo (http://localhost:3000/static/js/bundle.js:25996:20)
> 
>     at useMemo (http://localhost:3000/static/js/bundle.js:42162:25)
> 
>     at ConfigProviderContainer (http://localhost:3000/static/js/vendors-node_modules_ant-design_pro-table_es_Table_js.chunk.js:23148:62)
> 
>     at renderWithHooks (http://localhost:3000/static/js/bundle.js:24839:22)
> 
>     at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:28125:17)
> 
>     at beginWork (http://localhost:3000/static/js/bundle.js:29421:20)
> 
>     at beginWork$1 (http://localhost:3000/static/js/bundle.js:34384:18)
> 
>     at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33653:16)

老哥你解决了吗？我也碰到同样的问题了。

**Comment by WangDianhang** [comment]
webpack 临时加
plugins: [
        new webpack.DefinePlugin({
            'process': { env: { NODE_ENV:    JSON.stringify('production') } },
        }),
］
