### ISSUE TITLE
pro create myapp 报错,不知道是哪里的问题.

### ISSUE THREAD

**Issue by MonstorMonstor** [ant-design/ant-design-pro#10881]
### 🧐 问题描述 | Problem description

全局安装@ant-design/pro-cli后
使用命令创建项目出现报错

### 💻 示例代码 | Sample code
pro create antD-test
### 🚑 其他信息 | Other information
报错信息如下:
C:\Users\86132\AppData\Roaming\nvm\v16.18.1\node_modules\@ant-design\pro-cli\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 128: git clone https://github.com/ant-design/ant-design-pro --depth=1 antD-test
    at makeError (C:\Users\86132\AppData\Roaming\nvm\v16.18.1\node_modules\@ant-design\pro-cli\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\86132\AppData\Roaming\nvm\v16.18.1\node_modules\@ant-design\pro-cli\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AntDesignProGenerator.writing (C:\Users\86132\AppData\Roaming\nvm\v16.18.1\node_modules\@ant-design\pro-cli\src\create\generators\ant-design-pro\index.js:119:5) {
  shortMessage: 'Command failed with exit code 128: git clone https://github.com/ant-design/ant-design-pro --depth=1 antD-test',
  command: 'git clone https://github.com/ant-design/ant-design-pro --depth=1 antD-test',
  escapedCommand: 'git clone "https://github.com/ant-design/ant-design-pro" "--depth=1" antD-test',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
![Uploading image.png…]()

OS: win11 

Node：16.18.1

**Comment by dongweiq** [comment]
我的也是这个问他

**Comment by dongweiq** [comment]
我的也有这个问题，请问你是怎么解决的呢

**Comment by hyqc** [comment]
同问

**Comment by LLL1st** [comment]
同问
