### ISSUE TITLE
macOs 下 eslint 缺少 LogicalExpression module

### ISSUE THREAD

**Issue by Jwiayou** [ant-design/ant-design-pro#1125]
运行 `npm run lint` 报错如下：

```
> ant-design-pro@1.1.0 lint /Users/jiangwei/myProfile/ant-design-pro
> eslint --ext .js src mock tests && npm run lint:style

Cannot find module './LogicalExpression'
Referenced from: /Users/jiangwei/myProfile/ant-design-pro/node_modules/eslint-config-airbnb/index.js
Referenced from: /Users/jiangwei/myProfile/ant-design-pro/.eslintrc
Error: Cannot find module './LogicalExpression'
Referenced from: /Users/jiangwei/myProfile/ant-design-pro/node_modules/eslint-config-airbnb/index.js
Referenced from: /Users/jiangwei/myProfile/ant-design-pro/.eslintrc
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jiangwei/myProfile/ant-design-pro/node_modules/jsx-ast-utils/lib/values/expressions/index.js:33:26)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.1.0 lint: `eslint --ext .js src mock tests && npm run lint:style`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@1.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jiangwei/.npm/_logs/2018-03-18T13_42_54_853Z-debug.log
```

**Comment by chenshuai2144** [comment]
这个应该重新安装一下就好了，LogicalExpression是 eslint 自带的
