### ISSUE TITLE
🧐[问题 | question]移除i18n国际化时报错TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by apex-zhan** [ant-design/ant-design-pro#11263]
### 🧐 问题描述 | Problem description
 const arrayList = getLocaleFileList(absSrcPath, absPagesPath)[locale].map(({ path }) =>
                                                                       ^

TypeError: Cannot read properties of undefined (reading 'map')

 const arrayList = getLocaleFileList(absSrcPath, absPagesPath)[locale].map(({ path }) =>
                                                                       ^

TypeError: Cannot read properties of undefined (reading 'map')
    at module.exports (D:\学习文件\BI-frontend\zxwbi-frontend\node_modules\@ant-design\pro-cli\src\i18n\getLocalFileList.js:48:72)
    at module.exports (D:\学习文件\BI-frontend\zxwbi-frontend\node_modules\@ant-design\pro-cli\src\i18n\index.js:49:21)
    at Object.<anonymous> (D:\学习文件\BI-frontend\zxwbi-frontend\node_modules\@ant-design\pro-cli\cli.js:41:32)

### 🚑 其他信息 | Other information

OS:window

Node：v18.10.0
![微信图片_20240621172837](https://github.com/ant-design/ant-design-pro/assets/141353752/eb9077d1-d3e5-4409-9cdd-a99e55658686)

浏览器 | browser：

**Comment by apex-zhan** [comment]
已解决：向我这样改成功了
![微信图片_20240621190412](https://github.com/ant-design/ant-design-pro/assets/141353752/c9cb15f8-0422-4a15-a38d-14bc32c0d87f)

**Comment by afc163** [comment]
该问题与 #11262 重复，均为移除国际化时出现的错误。请移步 #11262 继续讨论。

V6 版本可通过 `npm run i18n-remove` 一键移除国际化，建议升级到 V6。
