### ISSUE TITLE
🐛 [BUG] 移除i18n国际化时候报错TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by apex-zhan** [ant-design/ant-design-pro#11262]
### 🐛 bug 描述

求助 [BUG] 移除i18n国际化时候报错
### 📷 复现步骤 | Recurrence steps
 const arrayList = getLocaleFileList(absSrcPath, absPagesPath)[locale].map(({ path }) =>
                                                                       ^
TypeError: Cannot read properties of undefined (reading 'map')
    at module.exports (D:\学习文件\BI-frontend\zxwbi-frontend\node_modules\@ant-design\pro-cli\src\i18n\getLocalFileList.js:48:72)
    at module.exports (D:\学习文件\BI-frontend\zxwbi-frontend\node_modules\@ant-design\pro-cli\src\i18n\index.js:49:21)
    at Object.<anonymous> (D:\学习文件\BI-frontend\zxwbi-frontend\node_modules\@ant-design\pro-cli\cli.js:41:32)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.10.0

 const arrayList = getLocaleFileList(absSrcPath, absPagesPath)[locale].map(({ path }) =>
                                                                       ^
TypeError: Cannot read properties of undefined (reading 'map')
### 🏞 期望结果 | Expected results

移除成功
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by apex-zhan** [comment]
已解决，改报错路径下的文件呜呜呜
