### ISSUE TITLE
🐛 [BUG]根据文档执行创建安装之后，运行报错

### ISSUE THREAD

**Issue by haioa** [ant-design/ant-design-pro#11388]
### 看到很多人有这个问题，注释掉
![image](https://github.com/user-attachments/assets/d10beb38-6d68-4228-9c9e-5eaf83eecad8)
### 📷 复现步骤 | Recurrence steps

```
Uncaught Error: Absolute route path "/*" nested under path "/user" is not valid. An absolute child route path must start with the combined path of all its parent routes.
    at invariant (mf-dep____vendor.e9baa7dc.js:498659:20)
    at mf-dep____vendor.e9baa7dc.js:498753:59
    at Array.forEach (<anonymous>)
    at flattenRoutes (mf-dep____vendor.e9baa7dc.js:498744:10)
    at mf-dep____vendor.e9baa7dc.js:498764:7
    at Array.forEach (<anonymous>)
    at flattenRoutes (mf-dep____vendor.e9baa7dc.js:498744:10)
    at matchRoutes (mf-dep____vendor.e9baa7dc.js:498720:18)
    at mf-dep____vendor.e9baa7dc.js:282214:108
    at mf-dep____vendor.e9baa7dc.js:282312:7
    at commitHookEffectListMount (mf-dep____vendor.e9baa7dc.js:490422:26)
    at commitPassiveMountOnFiber (mf-dep____vendor.e9baa7dc.js:492198:13)
    at commitPassiveMountEffects_complete (mf-dep____vendor.e9baa7dc.js:492163:9)
    at commitPassiveMountEffects_begin (mf-dep____vendor.e9baa7dc.js:492150:7)
    at commitPassiveMountEffects (mf-dep____vendor.e9baa7dc.js:492138:3)
    at flushPassiveEffectsImpl (mf-dep____vendor.e9baa7dc.js:494311:3)
    at flushPassiveEffects (mf-dep____vendor.e9baa7dc.js:494256:14)
    at mf-dep____vendor.e9baa7dc.js:494041:9
    at workLoop (mf-dep____vendor.e9baa7dc.js:517426:34)
    at flushWork (mf-dep____vendor.e9baa7dc.js:517399:14)
    at performWorkUntilDeadline (mf-dep____vendor.e9baa7dc.js:517693:21)
    at queue.<computed> (mf-dep____vendor.e9baa7dc.js:529388:7)
    at run (mf-dep____vendor.e9baa7dc.js:529362:5)
    at MessagePort.eventListener (mf-dep____vendor.e9baa7dc.js:529373:3)
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by HJ1281581411** [comment]
解开注释，放在最外层路由的最后一个

**Comment by lichdkimba** [comment]
> 解开注释，放在最外层路由的最后一个

有点无语了，官方脚手架怎么还有这种问题

**Comment by baiyuanyong** [comment]
按照文档初始化项目，运行不起来，无语了

**Comment by mhkz** [comment]
我也是运行不起来

**Comment by tomiaa12** [comment]
同

**Comment by 986823307** [comment]
> 解开注释，放在最外层路由的最后一个

没用，访问根目录还是跳过了登录直接跳转到了首页

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design-pro/pull/11528
