### ISSUE TITLE
🐛 [BUG] build之后空白，react-dom.production.min.js:188 TypeError: Cannot read properties of null (reading 'applyPlugins')

### ISSUE THREAD

**Issue by minlib** [ant-design/ant-design-pro#11393]
### 🐛 bug 描述

1. 旧版本升级后，但是build之后访问空白，本地可以运行
2. 直接把代码下到本地，build 发布后访问空白，本地可以运行

错误如下：
react-dom.production.min.js:188 TypeError: Cannot read properties of null (reading 'applyPlugins')
    at I (localeExports.ts:205:26)
    at N (localeExports.ts:265:25)
    at c (locale.tsx:37:33)

### 🏞 期望结果 | Expected results
期望发布后可以正常访问

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. windows]

**Comment by minlib** [comment]
这个问题应当被重视，升级之后系统就崩了，官方代码也存在这个问题！！！

请重视，请紧急处理
请重视，请紧急处理
请重视，请紧急处理

**Comment by baiyuanyong** [comment]
已经两个月没有commit了，项目人员已经被优化了

**Comment by cyqhhj** [comment]
我今天也遇到同样的问题，开发没问题，发布出来就报错
![微信截图_20241206172900](https://github.com/user-attachments/assets/c6fe78df-4e96-4ffe-b32b-1bfb54f5c63b)

**Comment by minlib** [comment]
感觉没人用了？ 这么严重的问题都没人解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月6日(周五) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design-pro] 🐛 [BUG] build之后空白，react-dom.production.min.js:188 TypeError: Cannot read properties of null (reading 'applyPlugins') (Issue #11393)




 
我今天也遇到同样的问题，开发没问题，发布出来就报错
 _20241206172900.png (view on web)

**Comment by cyqhhj** [comment]
我找到原因了，发现是umi默认开启了 mako 极速开发，开发和发布的时候有些错误都不会提示出来，关闭mako即可发现错误，处理错误后就正常了。

**Comment by minlib** [comment]
优秀啊，具体在哪里关闭呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月9日(周一) 中午11:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design-pro] 🐛 [BUG] build之后空白，react-dom.production.min.js:188 TypeError: Cannot read properties of null (reading 'applyPlugins') (Issue #11393)




 
我找到原因了，发现是umi默认开启了 mako 极速开发，开发和发布的时候有些错误都不会提示出来，关闭mako即可发现错误，处理错误后就正常了。

**Comment by minlib** [comment]
thanks



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月9日(周一) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design-pro] 🐛 [BUG] build之后空白，react-dom.production.min.js:188 TypeError: Cannot read properties of null (reading 'applyPlugins') (Issue #11393)




  
优秀啊，具体在哪里关闭呢？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月9日(周一) 中午11:57 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [ant-design/ant-design-pro] 🐛 [BUG] build之后空白，react-dom.production.min.js:188 TypeError: Cannot read properties of null (reading 'applyPlugins') (Issue #11393) 我找到原因了，发现是umi默认开启了 mako 极速开发，开发和发布的时候有些错误都不会提示出来，关闭mako即可发现错误，处理错误后就正常了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
在config.ts里面，注释掉mako: {},

**Comment by ijisen** [comment]
thanks

**Comment by mimajiushi** [comment]
thanks

**Comment by afc163** [comment]
该问题与 #11431 重复，均为构建部署后出现的 404/空白页面问题。请移步 #11431 继续讨论。

常见解决方案：Nginx 配置 `try_files $uri /index.html;`，或启用 `exportStatic` 配置。
部署文档：https://pro.ant.design/zh-CN/docs/deploy
