### ISSUE TITLE
怎么用idea开发，编译

### ISSUE THREAD

**Issue by kway000** [ant-design/ant-design-pro#1264]
我已安装了node插件

**Comment by kway000** [comment]
E:\project\src\release\web\my-project\src\index.js:1
(function (exports, require, module, __filename, __dirname) { import '@babel/polyfill';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Uncaught SyntaxError: Unexpected token import
  createScript	
  runInThisContext	
  Module._compile	
  Module._extensions..js	
  Module.load	
  tryModuleLoad	
  Module._load	
  Module.runMain	
  startup	
  (anonymous function)	
Waiting for the debugger to disconnect...

**Comment by chenshuai2144** [comment]
你这个错误一般是 node 版本太低了
升级一波吧

**Comment by kway000** [comment]
![version](https://user-images.githubusercontent.com/5449320/38800146-1b504c92-4199-11e8-8436-650a3ce0eba7.png)

这个是我的版本号，node版本是最新的
