### ISSUE TITLE
nmp install failed

### ISSUE THREAD

**Issue by qiantao1001** [ant-design/ant-design-pro#1338]
- OS: macOS 10.13.4
- node version: v8.11.1
- npm version: 5.6.0

```bash
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! Unexpected end of JSON input while parsing near '...icfCSTndwHMhUhLJw+pa4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas/.npm/_logs/2018-04-21T06_58_44_300Z-debug.log
```

Log info:
```log
5042 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...icfCSTndwHMhUhLJw+pa4'
5042 verbose stack     at JSON.parse (<anonymous>)
5042 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
5042 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
5042 verbose stack     at <anonymous>
5042 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
5043 verbose cwd /Users/thomas/Codes/ant-design-pro
5044 verbose Darwin 17.5.0
5045 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
5046 verbose node v8.11.1
5047 verbose npm  v5.6.0
5048 error Unexpected end of JSON input while parsing near '...icfCSTndwHMhUhLJw+pa4'
5049 verbose exit [ 1, true ]
```

**Comment by afc163** [comment]
Try cnpm
