### ISSUE TITLE
初始化项目 npm install命令执行后出错。

### ISSUE THREAD

**Issue by roc2539** [ant-design/ant-design-pro#1386]
Unhandled rejection RangeError: Maximum call stack size exceededill install loa
    at RegExp.test (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/aproba/index.js:38:16
    at Array.forEach (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:33:11)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2018-04-27T07_45_27_462Z-debug.log

**Comment by roc2539** [comment]
使用 cnpm好了

**Comment by a854363956** [comment]
Call exceeds the maximum time, check the network

**Comment by roc2539** [comment]
thank you
