### ISSUE TITLE
npm run build 打包错误，请问这种报错怎么解决？

### ISSUE THREAD

**Issue by pingGuoNiki** [ant-design/ant-design-pro#1521]
$ npm run build

> ant-design-pro@1.2.1 build F:\financial_logistics
> cross-env ESLINT=none roadhog build

Failed to compile.

Failed to minify the bundle. Error: index.acf6c1b0.js from UglifyJs
Unexpected token: name (Log) [index.acf6c1b0.js:537,6]
    at doneHandler (F:\financial_logistics\node_modules\af-webpack\lib\build.js:91:27)
    at emitRecords.err (F:\financial_logistics\node_modules\webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (F:\financial_logistics\node_modules\webpack\lib\Compiler.js:371:38)
    at emitAssets.err (F:\financial_logistics\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (F:\financial_logistics\node_modules\webpack\lib\Compiler.js:364:12)
    at next (F:\financial_logistics\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (F:\financial_logistics\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at next (F:\financial_logistics\node_modules\tapable\lib\Tapable.js:220:14)
    at callback (F:\financial_logistics\node_modules\copy-webpack-plugin\dist\index.js:126:17)
    at Compiler.afterEmit (F:\financial_logistics\node_modules\copy-webpack-plugin\dist\index.js:220:13)
    at Compiler.applyPluginsAsyncSeries1 (F:\financial_logistics\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (F:\financial_logistics\node_modules\webpack\lib\Compiler.js:361:9)
    at require.forEach.err (F:\financial_logistics\node_modules\webpack\lib\Compiler.js:350:15)
    at F:\financial_logistics\node_modules\webpack\node_modules\async\dist\async.js:473:16
    at iteratorCallback (F:\financial_logistics\node_modules\webpack\node_modules\async\dist\async.js:1050:13)
    at F:\financial_logistics\node_modules\webpack\node_modules\async\dist\async.js:958:16
Read more here: http://bit.ly/2tRViJ9

[graceful-process#5628] exit with code:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.2.1 build: `cross-env ESLINT=none roadhog build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-05-22T02_29_16_172Z-debug.log

**Comment by chenshuai2144** [comment]
你引用的第三方库，没有转化成 es5就放上来了，
换掉它

**Comment by pingGuoNiki** [comment]
请问那如何把这些库转化为es5呢

**Comment by chenshuai2144** [comment]
去 github 提 issue催作者改。
你用的 webpack 还是 roadhog？
