### ISSUE TITLE
pro new 命令新建工程出错

### ISSUE THREAD

**Issue by lsdlab** [ant-design/ant-design-pro#153]
报错信息：

```
? input project name: vpan_admin
? witch directory do you want to init to ? (default is current directory ./): vpan_admin
Success to download repo https://github.com/ant-design/ant-design-pro to /Users/Chen/vpan_admin
⠋ Auto installing...use npm: npm
⠋ Auto installing...npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
⠧ Auto installing...npm ERR! Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"d'
⠇ Auto installing...
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Chen/.npm/_logs/2017-11-10T05_37_19_211Z-debug.log
npm install end
Visit https://pro.ant.design to learn more.
```

日志最后一部分：

```
3247 silly resolveWithNewModule warning@3.0.0 checking installable status
3248 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"d'
3248 verbose stack     at JSON.parse (<anonymous>)
3248 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
3248 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
3248 verbose stack     at <anonymous>
3248 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
3249 verbose cwd /Users/Chen/vpan_admin/vpan_admin
3250 verbose Darwin 16.7.0
3251 verbose argv "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/bin/npm" "install"
3252 verbose node v8.9.1
3253 verbose npm  v5.5.1
3254 error Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"d'
3255 verbose exit [ 1, true ]
```

求教各位大佬，什么问题，顺带问下，这个命令新建出来的是一个比较空的工程还是里面已经是和  preview 一样有很多示例在里面了？

**Comment by nikogu** [comment]
@lsdlab 看起来是 github 的包已经下载好了，但是 `npm install` 报错了，你可以尝试自己安装一下，看看，然后看看你的 npm 和 node 版本

和 preview 一样，有很多事例

**Comment by afc163** [comment]
一般是网络问题，建议使用 cnpm。
