### ISSUE TITLE
访问项目自带部分mock数据

### ISSUE THREAD

**Issue by itstrive** [ant-design/ant-design-pro#1610]
通过cli安装的pro项目，默认好像没有访问到，自带mock中的数据。

随意在 `.roadhogrc.mock.js` 里面写个console.log，控制台出现错误

```
CHANGED .\.roadhogrc.mock.js
{ Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\workspace-yuanhe\my-project\ant-pro\.roadhogrc.mock.js:3:30)
    at Module._compile (module.js:635:30)
    at Module._compile (F:\workspace-yuanhe\my-project\ant-pro\node_modules\.npminstall\pirates\3.0.2\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:646:10)
    at Object.newLoader [as .js] (F:\workspace-yuanhe\my-project\ant-pro\node_modules\.npminstall\pirates\3.0.2\pirates\lib\index.js:96:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at getConfig (F:\workspace-yuanhe\my-project\ant-pro\node_modules\.npminstall\roadhog\2.4.2\roadhog\lib\utils\mock.js:47:12)
    at realApplyMock (F:\workspace-yuanhe\my-project\ant-pro\node_modules\.npminstall\roadhog\2.4.2\roadhog\lib\utils\mock.js:109:18) code: 'MODULE_NOT_FOUND' }

Failed to parse mock config.

Error in Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
```

`babel-runtime` 已经安装ok了，也几次删除 `node_modules`重安装了，但问题依旧。

看network请求，返回的每次都是index.ejs的页面内容。

难道需要启动什么mock server之类的服务么？

看了下 'package.json' 的 'scripts'.'start'里面运行了一个 `roadhog dev` ,也全局安装了 roadhog了。

目的：访问本地mock数据，就是pro自带的那一堆。哪块姿势不对呢？

**Comment by chenshuai2144** [comment]
必须 yarn start 的
