### ISSUE TITLE
Creating a regular expression using literals in dva's effects(dva 的effects中使用字面量创建正则表达式 打包出错)

### ISSUE THREAD

**Issue by tz310200** [ant-design/ant-design-pro#1946]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）    ^2.4.2
- Nodejs and Npm version（Nodejs 和 Npm 版本） v8.11.3   (npm 6.1.0)
- Operating environment (e.g. OS name) and its version（操作系统版本）:  windows10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

```
effects: {
...
  *getMenuData({ callback }, { call, put }) {
...
         const httpRegExp = /(?<=^\/)https?\S*/i;
          // const httpRegExp = new RegExp('(?<=^\\/)https?\\S*', 'i');  
          const match = httpRegExp.exec(item.menuUrl);
...
}
...
}
```
使用注释部分则不会报错
#### What do you expected?（预期的正常效果）

打包成功

#### What happen?（发生了何种非正常现象）

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\quangao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.1.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.0.0-beta.1~prebuild: ant-design-pro@2.0.0-beta.1
6 info lifecycle ant-design-pro@2.0.0-beta.1~build: ant-design-pro@2.0.0-beta.1
7 verbose lifecycle ant-design-pro@2.0.0-beta.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.0.0-beta.1~build: PATH: C:\Users\quangao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\zouwendi\03private Tools\ttool-client\node_modules\.bin;C:\Program Files\Java\jdk1.8.0_73\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:/develop_tools/apache-maven-3.5.0\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\quangao\AppData\Local\Android\sdk\platform-tools;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\Users\quangao\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\quangao\AppData\Local\Programs\Python\Python36\;C:\Users\quangao\Anaconda3;C:\Users\quangao\Anaconda3\Library\mingw-w64\bin;C:\Users\quangao\Anaconda3\Library\usr\bin;C:\Users\quangao\Anaconda3\Library\bin;C:\Users\quangao\Anaconda3\Scripts;C:\Ruby25-x64\bin;C:\Ruby24-x64\bin;C:\Users\quangao\AppData\Local\Microsoft\WindowsApps;C:\Users\quangao\AppData\Roaming\npm
9 verbose lifecycle ant-design-pro@2.0.0-beta.1~build: CWD: D:\zouwendi\03private Tools\ttool-client
10 silly lifecycle ant-design-pro@2.0.0-beta.1~build: Args: [ '/d /s /c', 'cross-env ESLINT=none roadhog build' ]
11 silly lifecycle ant-design-pro@2.0.0-beta.1~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.0.0-beta.1~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.0.0-beta.1 build: `cross-env ESLINT=none roadhog build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\quangao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\quangao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ant-design-pro@2.0.0-beta.1
15 verbose cwd D:\zouwendi\03private Tools\ttool-client
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\quangao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.0.0-beta.1 build: `cross-env ESLINT=none roadhog build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.0.0-beta.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

#### Re-producible online demo (可复现的在线demo)

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

.webpackrc.js

```
const path = require('path');
const { prefix } = require('./src/utils/Constant');
var SERVICE_URL = 'http://127.0.0.1:8084/';
export default {
  entry: 'src/index.js',
  extraBabelPlugins: [['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
      publicPath: '/',
    },
  },
  externals: {
    '@antv/data-set': 'DataSet',
    bizcharts: 'BizCharts',
    rollbar: 'rollbar',
  },
  alias: {
    components: path.resolve(__dirname, 'src/components/'),
  },
  proxy: {
    [prefix + '/api/**']: {
      target: SERVICE_URL,
      changeOrigin: true,
      secure: false,
    },
    [prefix + '/auth/**']: {
      target: SERVICE_URL,
      changeOrigin: true,
      secure: false,
    },
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  lessLoaderOptions: {
    javascriptEnabled: true,
  },
  disableDynamicImport: true,
  publicPath: prefix + '/',
  hash: true,
};

```

**Comment by chenshuai2144** [comment]
@sorrycc
