### ISSUE TITLE
最新版本，配置mock代理时报错

### ISSUE THREAD

**Issue by lixiaolihua** [ant-design/ant-design-pro#2019]
mock配置
```javascript
{
  'GET /api/(.*)': 'http://localhost:7008/api/',
}
```

错误信息
```
CHANGED ./.roadhogrc.mock.js
Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}
    at Object.createConfig (/Users/lihua/example/temp-antd-pro/node_modules/http-proxy-middleware/lib/config-factory.js:43:11)
    at new HttpProxyMiddleware (/Users/lihua/example/temp-antd-pro/node_modules/http-proxy-middleware/lib/index.js:17:30)
    at module.exports (/Users/lihua/example/temp-antd-pro/node_modules/http-proxy-middleware/index.js:4:10)
    at createProxy (/Users/lihua/example/temp-antd-pro/node_modules/roadhog/lib/utils/mock.js:81:43)
    at Object.keys.forEach.key (/Users/lihua/example/temp-antd-pro/node_modules/roadhog/lib/utils/mock.js:132:21)
    at Array.forEach (<anonymous>)
    at realApplyMock (/Users/lihua/example/temp-antd-pro/node_modules/roadhog/lib/utils/mock.js:120:23)
    at applyMock (/Users/lihua/example/temp-antd-pro/node_modules/roadhog/lib/utils/mock.js:88:5)
    at FSWatcher.watcher.on.path (/Users/lihua/example/temp-antd-pro/node_modules/roadhog/lib/utils/mock.js:167:5)
    at emitOne (events.js:116:13)
    at FSWatcher.emit (events.js:211:7)
    at FSWatcher.<anonymous> (/Users/lihua/example/temp-antd-pro/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/Users/lihua/example/temp-antd-pro/node_modules/chokidar/index.js:238:5)
    at FSWatcher.<anonymous> (/Users/lihua/example/temp-antd-pro/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (/Users/lihua/example/temp-antd-pro/node_modules/chokidar/lib/fsevents-handler.js:210:7)
    at /Users/lihua/example/temp-antd-pro/node_modules/chokidar/lib/fsevents-handler.js:216:35

Failed to parse mock config.

Error in [HPM] Missing "target" option. Example
Error: {target: "http://www.example.org"}
```

**Comment by forMine** [comment]
直接在config.js中配置代理吧
