### ISSUE TITLE
 [HPM] Missing "target" option. Example:

### ISSUE THREAD

**Issue by imandarava** [ant-design/ant-design-pro#2020]
>npm run start:no-proxy

> ant-design-pro@1.4.4 start:no-proxy G:\nodejs\home_cluby_cn
> cross-env NO_PROXY=true ESLINT=none roadhog dev

  build [==                  ] 10%Error: [HPM] Missing "target" option. Example: {target: "http://www.example.org"}
    at Object.createConfig (G:\nodejs\home_cluby_cn\node_modules\http-proxy-middleware\lib\config-factory.js:43:11)
    at new HttpProxyMiddleware (G:\nodejs\home_cluby_cn\node_modules\http-proxy-middleware\lib\index.js:17:30)
    at module.exports (G:\nodejs\home_cluby_cn\node_modules\http-proxy-middleware\index.js:4:10)
    at createProxy (G:\nodejs\home_cluby_cn\node_modules\roadhog\lib\utils\mock.js:81:43)
Compiled successfully!

You can now view Your App in the browser.

  Local:            http://localhost:8000/
  On Your Network:  http://192.168.0.103:8000/

Note that the development build is not optimized.
To create a production build, use npm run build.

**Comment by chenshuai2144** [comment]
@sorrycc  底层库更新了？

**Comment by sorrycc** [comment]
@yesmeck

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design-pro/issues/2019
