### ISSUE TITLE
打包出错:Invalid data, chunk must be a string or buffer, not undefined

### ISSUE THREAD

**Issue by skyFi** [ant-design/ant-design-pro#2086]
```
TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at Socket.write (net.js:701:11)
    at nodeDeprecate (/home/node/code/node_modules/_deprecate@1.1.0@deprecate/index.js:22:22)
    at deprecate (/home/node/code/node_modules/_deprecate@1.1.0@deprecate/index.js:11:3)
    at Object.<anonymous> (/home/node/code/node_modules/_af-webpack@0.22.11@af-webpack/lib/getConfig.js:81:26)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/node/code/node_modules/_af-webpack@0.22.11@af-webpack/getConfig.js:1:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

**Comment by skyFi** [comment]
@wangweida 我这里错误还是一样的。。。

```
> cross-env ESLINT=none roadhog build


Warning: DISABLE_ESLINT is deprecated, use ESLINT=none instead has been deprecated.
TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at Socket.write (net.js:701:11)
    at nodeDeprecate (/home/node/code/node_modules/_deprecate@1.1.0@deprecate/index.js:22:22)
    at deprecate (/home/node/code/node_modules/_deprecate@1.1.0@deprecate/index.js:11:3)
    at Object.<anonymous> (/home/node/code/node_modules/_af-webpack@0.22.11@af-webpack/lib/getConfig.js:81:26)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/node/code/node_modules/_af-webpack@0.22.11@af-webpack/getConfig.js:1:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

**Comment by skyFi** [comment]
@wangweida 确实是 `DISABLE_ESLINT` 的问题，我是写在 环境变量 里的，you save my life ^o^
