### ISSUE TITLE
IE版本：11.165.17134.0 更新版本：11.0.75异常

### ISSUE THREAD

**Issue by beeant0512** [ant-design/ant-design-pro#2143]
对象不支持“assign”属性或方法

   at createLoadableComponent (http://localhost:8000/umi.js:88436:3)
   at Loadable (http://localhost:8000/umi.js:88585:3)
   at _default (http://localhost:8000/umi.js:107289:3)
   at ./src/pages/.umi/router.js (http://localhost:8000/umi.js:111917:1)
   at __webpack_require__ (http://localhost:8000/umi.js:773:12)
   at fn (http://localhost:8000/umi.js:131:13)
   at render (http://localhost:8000/umi.js:112486:3)
   at Anonymous function (http://localhost:8000/umi.js:112491:3)
   at run (http://localhost:8000/umi.js:41985:13)
   at Anonymous function (http://localhost:8000/umi.js:42002:30)
   at flush (http://localhost:8000/umi.js:40962:9)"

**Comment by sorrycc** [comment]
在 umi-plugin-react@1.0.1 里修复了。
