### ISSUE TITLE
下载2.0后, cnpm start报错

### ISSUE THREAD

**Issue by kxw0620** [ant-design/ant-design-pro#2155]
按文档步骤安装ant design pro 2.0 后, 执行 cnpm start报错,如下: 
module.js:549
    throw err;
    ^

Error: Cannot find module 'umi-build-dev/lib/fork'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\100-5elink\web-react\AntDesign-v2\node_modules\_umi@2.0.1@umi\lib\scripts\dev.js:3:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kxw\AppData\Roaming\npm-cache\_logs\2018-09-04T08_49_07_287Z-debug.log

**Comment by chenshuai2144** [comment]
包没装全。重新安装吧
