### ISSUE TITLE
2.0 路径别名问题

### ISSUE THREAD

**Issue by wudihaike** [ant-design/ant-design-pro#2176]
开发工具:IntelliJ IDEA
升级到2.0后出现了如下问题
![20180905144047](https://user-images.githubusercontent.com/15355139/45075761-c52b1080-b11a-11e8-832f-474317aeed87.png)
虽然项目正常运行但是无法智能引用方法,对开发造成一定困扰,请问是否有什么插件?
麻烦告知

**Comment by chenshuai2144** [comment]
vscode有，IntelliJ IDEA 就不是很了解了

**Comment by sorrycc** [comment]
根目录新建 `webpack.config.js`，内容如下：

```js
module.exports = {
  resolve: {
    alias: { '@': 'src' }
  }
}
```

**Comment by Freewayy** [comment]
> module.exports = { resolve: { alias: { '@': 'src' } } }
@sorrycc 
您好，按照您提供的方法在根目录新建了webpack.config.js，然后运行之后报如下错误
我的根目录下还有个.webpackrc配置文件，不知道有没有关系

/Users/mac/Desktop/pea/proper-enterprise-app/node_modules/af-webpack/lib/applyWebpackConfig.js:39
    return customConfigFn(config, {
           ^
TypeError: customConfigFn is not a function
    at applyWebpackConfig (/Users/mac/Desktop/pea/proper-enterprise-app/node_modules/af-webpack/lib/applyWebpackConfig.js:39:12)
    at getConfig (/Users/mac/Desktop/pea/proper-enterprise-app/node_modules/af-webpack/lib/getConfig.js:509:53)
    at _default (/Users/mac/Desktop/pea/proper-enterprise-app/node_modules/roadhog/lib/getWebpackConfig.js:33:33)
    at Object.runDev [as default] (/Users/mac/Desktop/pea/proper-enterprise-app/node_modules/roadhog/lib/dev.js:65:55)
    at Object.<anonymous> (/Users/mac/Desktop/pea/proper-enterprise-app/node_modules/roadhog/lib/scripts/realDev.js:18:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
