### ISSUE TITLE
Cache is corrupted.

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#2255]
Cache is corrupted.
RangeError: "size" argument must not be larger than 2147483647    at Function.Buffer.allocUnsafe (buffer.js:253:3)
    at alloc (/Users/iss/ss-oms/node_modules/hard-source-webpack-plugin/lib/SerializerAppend2.js:46:17)
    at Append2._readFile (/Users/iss/ss-oms/node_modules/hard-source-webpack-plugin/lib/SerializerAppend2.js:160:14)
    at <anonymous>

<--- Last few GCs --->

[8736:0x102801c00]     7086 ms: Mark-sweep 965.9 (979.0) -> 965.9 (979.0) MB, 49.1 / 0.0 ms  allocation failure GC in old space requested
[8736:0x102801c00]     7203 ms: Mark-sweep 965.9 (979.0) -> 965.7 (977.5) MB, 116.6 / 0.0 ms  last resort GC in old space requested
[8736:0x102801c00]     7253 ms: Mark-sweep 965.7 (977.5) -> 965.7 (977.5) MB, 50.3 / 0.0 ms  last resort GC in old space requested

**Comment by chenshuai2144** [comment]
清除缓存
