### ISSUE TITLE
注册成功以后，跳转注册成功界面报错

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#2307]
如题！

报错信息如下：

umi.js:1 TypeError: Cannot read property 'type' of undefined
    at umi.js:1
    at t.value (13.async.js:1)
    at La (umi.js:1)
    at xa (umi.js:1)
    at Ha (umi.js:1)
    at Ko (umi.js:1)
    at Object.enqueueSetState (umi.js:1)
    at a.b.setState (umi.js:1)
    at a.onStateChange (umi.js:1)
    at m (umi.js:1)
umi.js:1 uncaught at t TypeError: Cannot read property 'type' of undefined
    at https://preview.pro.ant.design/umi.js:1:165984
    at t.value (https://preview.pro.ant.design/13.async.js:1:3557)
    at La (https://preview.pro.ant.design/umi.js:1:1113890)
    at xa (https://preview.pro.ant.design/umi.js:1:1109569)
    at Ha (https://preview.pro.ant.design/umi.js:1:1109185)
    at Ko (https://preview.pro.ant.design/umi.js:1:1107696)
    at Object.enqueueSetState (https://preview.pro.ant.design/umi.js:1:1076263)
    at a.b.setState (https://preview.pro.ant.design/umi.js:1:959900)
    at a.onStateChange (https://preview.pro.ant.design/umi.js:1:13877)
    at m (https://preview.pro.ant.design/umi.js:1:842457)

**Comment by chenshuai2144** [comment]
show code

**Comment by chenshuai2144** [comment]
和这个有关？
https://github.com/ant-design/ant-design-pro/commit/de86a30cc717ab8945e8fdb56604dbbac7f91b5e
