### ISSUE TITLE
Build failed: Cannot find module '@babel/runtime/core-js/object/keys'

### ISSUE THREAD

**Issue by chinawzc** [ant-design/ant-design-pro#2323]
When i run build, it shows this error:

Build failed: Cannot find module '@babel/runtime/core-js/object/keys'
{ Error: Cannot find module '@babel/runtime/core-js/object/keys'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/node/code/.webpackrc.js:10:36)
    at Module._compile (module.js:643:30)
    at Module._compile (/home/node/code/node_modules/_pirates@3.0.2@pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:654:10)
    at Object.newLoader [as .js] (/home/node/code/node_modules/_pirates@3.0.2@pirates/lib/index.js:96:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at getUserConfig (/home/node/code/node_modules/_af-webpack@0.22.11@af-webpack/lib/getUserConfig/index.js:116:14)
    at resolve (/home/node/code/node_modules/_roadhog@2.4.5@roadhog/lib/build.js:38:51) code: 'MODULE_NOT_FOUND' }

**Comment by chenshuai2144** [comment]
一般是网路问题 请尝试重新安装，或者使用 cnpm
