### ISSUE TITLE
在项目npm run build后遇到 TypeError: cannot read property `thisCompilation` of undefined

### ISSUE THREAD

**Issue by SollyTaylor** [ant-design/ant-design-pro#2350]
```
root@cicd-core:/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform# npm run build

> ant-design-pro@2.0.0-beta.1 build /home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform
> cross-env ESLINT=none roadhog build
Build failed: Cannot read property 'compilation' of undefined
TypeError: Cannot read property 'compilation' of undefined
    at ProgressPlugin.apply (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/webpack/lib/ProgressPlugin.js:121:19)
    at Compiler.apply (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/roadhog/node_modules/webpack/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/roadhog/node_modules/webpack/lib/webpack.js:33:19)
    at buildWebpack (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/roadhog/node_modules/af-webpack/lib/build.js:100:41)
    at build (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/roadhog/node_modules/af-webpack/lib/build.js:117:3)
    at resolve (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/roadhog/lib/build.js:52:24)
    at new Promise (<anonymous>)
    at Object._default [as default] (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/roadhog/lib/build.js:31:10)
    at Object.<anonymous> (/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform/node_modules/roadhog/lib/scripts/build.js:22:28)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
```
我怀疑是webpack的版本问题，查看了版本webpack的版本是最新的：
```

root@cicd-core:/home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform# npm list webpack
ant-design-pro@2.0.0-beta.1 /home/gitlab-runner/builds/3d17ee71/0/Taylor/xbs-web-reform
├─┬ ant-design-pro@2.0.0
│ └─┬ umi@2.0.3
│   └─┬ umi-build-dev@1.0.3
│     └─┬ af-webpack@1.0.1
│       └── webpack@4.19.1  deduped
└── webpack@4.19.1
``` 

我当前的node版本和npm版本是：

```
root@cicd-core:~# node -v
v8.12.0
root@cicd-core:~# npm -v
6.4.1
```

**Comment by chenshuai2144** [comment]
你使用的某个 loader 不支持 webpack4的原因吧
