### ISSUE TITLE
1.0升级到2.0出现以下报错。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#2361]
主要是因为 ~@/utils/utils.less 找不到。。
比如我的一个JS文件引入的代码是：
@import "~@/utils/utils.less";

但是最后报错。报错信息如下：
Error { Error: Cannot find module '@/utils/utils.less' from 'E:\workspace\gitlab_repo\manager-xyzy-antd'
    at module.exports (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less-plugin-npm-import\node_modules\resolve\lib\sync.js:33:11)
    at NpmFileManager.resolve (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less-plugin-npm-import\lib\npm-file-manager.js:29:16)
    at NpmFileManager.loadFile (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less-plugin-npm-import\lib\npm-file-manager.js:52:29)
    at ImportManager.push (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\import-manager.js:118:35)
    at ImportVisitor.processImportNode (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\visitors\import-visitor.js:87:28)
    at ImportVisitor.visitImport (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\visitors\import-visitor.js:49:22)
    at Visitor.visit (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\visitors\visitor.js:74:32)
    at Visitor.visitArray (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\visitors\visitor.js:100:22)
    at Ruleset.accept (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\tree\ruleset.js:30:30)
    at Visitor.visit (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\visitors\visitor.js:81:18)
    at ImportVisitor.run (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\visitors\import-visitor.js:22:27)
    at Object.parse (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\parser\parser.js:189:22)
    at Object.parse (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\parse.js:61:18)
    at Object.render (E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\render.js:25:18)
    at E:\workspace\gitlab_repo\manager-xyzy-antd\node_modules\less\lib\less\render.js:16:24
    at new Promise (<anonymous>)
  type: 'Syntax',
  filename: 'E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\antd\\lib\\style\\themes\\default.less',
  index: undefined,
  line: null,
  callLine: NaN,
  callExtract: undefined,
  column: -1,
  extract: [ undefined, undefined, '@import "../color/colors";' ],
  message: 'Cannot find module \'@/utils/utils.less\' from \'E:\\workspace\\gitlab_repo\\manager-xyzy-antd\'',
  stack: 'Error: Cannot find module \'@/utils/utils.less\' from \'E:\\workspace\\gitlab_repo\\manager-xyzy-antd\'\n    at module.exports (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less-plugin-npm-import\\node_modules\\resolve\\lib\\sync.js:33:11)\n    at NpmFileManager.resolve (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less-plugin-npm-import\\lib\\npm-file-manager.js:29:16)\n    at NpmFileManager.loadFile (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less-plugin-npm-import\\lib\\npm-file-manager.js:52:29)\n    at ImportManager.push (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\import-manager.js:118:35)\n    at ImportVisitor.processImportNode (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\visitors\\import-visitor.js:87:28)\n    at ImportVisitor.visitImport (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\visitors\\import-visitor.js:49:22)\n    at Visitor.visit (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\visitors\\visitor.js:74:32)\n    at Visitor.visitArray (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\visitors\\visitor.js:100:22)\n    at Ruleset.accept (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\tree\\ruleset.js:30:30)\n    at Visitor.visit (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\visitors\\visitor.js:81:18)\n    at ImportVisitor.run (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\visitors\\import-visitor.js:22:27)\n    at Object.parse (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\parser\\parser.js:189:22)\n    at Object.parse (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\parse.js:61:18)\n    at Object.render (E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\render.js:25:18)\n    at E:\\workspace\\gitlab_repo\\manager-xyzy-antd\\node_modules\\less\\lib\\less\\render.js:16:24\n    at new Promise (<anonymous>)' }
[DEBUG] [change] config\router.config.js
[DEBUG] [add] config\router.config.js___jb_tmp___
[DEBUG] [change] config\router.config.js
[DEBUG] [unlink] config\router.config.js___jb_tmp___
[DEBUG] [change] config\router.config.js

**Comment by xgj1988** [comment]
`> @import "~@/utils/utils.less";`  其实这句话的意思，应该是在 node_moduls 下面去找撒。其实我没懂为什么2.0 要改成这样

**Comment by xgj1988** [comment]
额，改用单引号就可以了。

**Comment by xgj1988** [comment]
但是为什么用单引号谁能解释一下。

**Comment by UserFengFeng** [comment]
我改成单引号也不行为什么？

**Comment by Block2** [comment]
我改成单引号也不行
