### ISSUE TITLE
npm run lint - 报错 - Configuration for rule "import/extensions" is invalid

### ISSUE THREAD

**Issue by mygodwzy** [ant-design/ant-design-pro#2407]
在master分支上，执行npm run lint报错。

错误信息如下：
```
"C:\Program Files\JetBrains\WebStorm 2018.1\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run lint --scripts-prepend-node-path=auto

> ant-design-pro@2.0.0 lint D:\workspace\javascript\ant-design-pro
> eslint --ext .js src mock tests && npm run lint:style

D:\workspace\javascript\ant-design-pro\node_modules\eslint-config-airbnb-base\rules\imports.js:
	Configuration for rule "import/extensions" is invalid:
	Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
	Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
	Value "ignorePackages" should be equal to one of the allowed values.
	Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should match some schema in anyOf.

Referenced from: D:\workspace\javascript\ant-design-pro\node_modules\eslint-config-airbnb-base\index.js
Referenced from: D:\workspace\javascript\ant-design-pro\node_modules\eslint-config-airbnb\index.js
Referenced from: D:\workspace\javascript\ant-design-pro\.eslintrc.js
Error: D:\workspace\javascript\ant-design-pro\node_modules\eslint-config-airbnb-base\rules\imports.js:
	Configuration for rule "import/extensions" is invalid:
	Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
	Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
	Value "ignorePackages" should be equal to one of the allowed values.
	Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should match some schema in anyOf.

Referenced from: D:\workspace\javascript\ant-design-pro\node_modules\eslint-config-airbnb-base\index.js
Referenced from: D:\workspace\javascript\ant-design-pro\node_modules\eslint-config-airbnb\index.js
Referenced from: D:\workspace\javascript\ant-design-pro\.eslintrc.js
    at validateRuleOptions (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-validator.js:133:19)
    at Object.keys.forEach.id (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-validator.js:176:9)
    at Array.forEach (<anonymous>)
    at validateRules (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-validator.js:175:30)
    at Object.validate (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-validator.js:262:5)
    at loadFromDisk (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-file.js:521:19)
    at load (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-file.js:564:20)
    at configExtends.reduceRight (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (D:\workspace\javascript\ant-design-pro\node_modules\eslint\lib\config\config-file.js:408:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ant-design-pro@2.0.0 lint: `eslint --ext .js src mock tests && npm run lint:style`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-09-26T06_17_04_821Z-debug.log

Process finished with exit code 2
```
关键报错信息：
```
Configuration for rule "import/extensions" is invalid:
Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should NOT have more than 1 items.
Value "ignorePackages" should be equal to one of the allowed values.
Value ["ignorePackages",{"js":"never","mjs":"never","jsx":"never"}] should match some schema in anyOf.
```

**Comment by chenshuai2144** [comment]
更新一下 eslint 的版本
