### ISSUE TITLE
npm start error - Plugin umi-plugin-ga can't be resolved

### ISSUE THREAD

**Issue by esofar** [ant-design/ant-design-pro#2412]
```
> ant-design-pro@2.0.0 start E:\React\ant-design-pro
> cross-env APP_TYPE=site umi dev

Plugin umi-plugin-ga can't be resolved
Error: Plugin umi-plugin-ga can't be resolved
    at map.p (E:\React\ant-design-pro\node_modules\_umi-build-dev@1.0.3@umi-build-dev\lib\getPlugins.js:84:13)
    at Array.map (<anonymous>)
    at pluginToPath (E:\React\ant-design-pro\node_modules\_umi-build-dev@1.0.3@umi-build-dev\lib\getPlugins.js:67:26)
    at getUserPlugins (E:\React\ant-design-pro\node_modules\_umi-build-dev@1.0.3@umi-build-dev\lib\getPlugins.js:92:23)
    at _default (E:\React\ant-design-pro\node_modules\_umi-build-dev@1.0.3@umi-build-dev\lib\getPlugins.js:57:10)
    at Service.resolvePlugins (E:\React\ant-design-pro\node_modules\_umi-build-dev@1.0.3@umi-build-dev\lib\Service.js:75:38)
    at new Service (E:\React\ant-design-pro\node_modules\_umi-build-dev@1.0.3@umi-build-dev\lib\Service.js:66:25)
    at Object.<anonymous> (E:\React\ant-design-pro\node_modules\_umi@2.0.3@umi\lib\scripts\realDev.js:28:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2018-09-26T08_24_17_700Z-debug.log
```

**Comment by zxl78585** [comment]
@esofar 最好用cnpm吧，npm国内不太好使，除非，你有梯子

**Comment by esofar** [comment]
@zxl78585 
has the same problem using `cnpm start`.

**Comment by chenshuai2144** [comment]
`cnpm install`

**Comment by esofar** [comment]
@chenshuai2144 nice.

**Comment by mgadirocks** [comment]
`npm start `still gives this error, Can anyone help, please?

**Comment by zxl78585** [comment]
@mgadirocks plase paste your error info

**Comment by mgadirocks** [comment]
Getting same error what is showing here. :( @zxl78585

**Comment by zxl78585** [comment]
@mgadirocks you can install a cnpm and use cnpm install

**Comment by zxl78585** [comment]
@mgadirocks Sometimes，npm always could't find some packages
