### ISSUE TITLE
ant design pro 目录下 npm install 报错

### ISSUE THREAD

**Issue by louisluckydoggie** [ant-design/ant-design-pro#2417]
```
ant-design-pro-2.0 npm install showdown --save
Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree
    at RegExp.test (<anonymous>)
    at /Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/aproba/index.js:38:16
    at Array.forEach (<anonymous>)
    at module.exports (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/aproba/index.js:33:11)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/Users/louis/.nvm/versions/node/v10.0.0/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/louis/.npm/_logs/2018-09-27T06_44_32_215Z-debug.log
```
其他目录下 install 没问题。

**Comment by chenshuai2144** [comment]
与 pro 无关。
