### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by WG-Com** [ant-design/ant-design-pro#2453]
```
> umi build


WARNING!!
umi-plugin-polyfills is deprecated, use config.targets instead.

Compiling

● webpack █████████████████████████ building modules (26%) 138/142 modules 4 active
  node_modules/_umi-plugin-locale@2.1.1@umi-plugin-locale/lib/locale.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-29T16_24_44_917Z-debug.log


```

**Comment by WG-Com** [comment]
```
 node --version
v10.11.0

```

**Comment by WG-Com** [comment]
window , centos 都不行

**Comment by WG-Com** [comment]
每次报的错误还不一样呢：
```
> umi build


WARNING!!
umi-plugin-polyfills is deprecated, use config.targets instead.




Compiling

● webpack █████████████████████████ building modules (26%) 138/143 modules 5 active
  node_modules/_umi@2.1.1@umi/lib/link.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-29T16_30_51_858Z-debug.log

```

**Comment by WG-Com** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build', '-p' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.0.0~prebuild: ant-design-pro@2.0.0
6 info lifecycle ant-design-pro@2.0.0~build: ant-design-pro@2.0.0
7 verbose lifecycle ant-design-pro@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/test/bi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle ant-design-pro@2.0.0~build: CWD: /root/test/x
10 silly lifecycle ant-design-pro@2.0.0~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.0.0~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.0.0 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid ant-design-pro@2.0.0
15 verbose cwd /root/test/bi
16 verbose Linux 3.10.0-693.2.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "-p"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.0.0 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]



```

**Comment by chenshuai2144** [comment]
升级 umi2.0
