### ISSUE TITLE
generateMock.js is not working

### ISSUE THREAD

**Issue by codesignist** [ant-design/ant-design-pro#2472]
When I try generate mock data:
`npm run generate-mock`

It returns an error:
```(node:18580) UnhandledPromiseRejectionWarning: Error: Bad character escape sequence
    at error (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:3365:15)
    at Module.error (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:13425:9)
    at tryParse (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:13091:16)
    at Module.setSource (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:13156:33)
    at E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:21420:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
(node:18580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18580) UnhandledPromiseRejectionWarning: Error: Bad character escape sequence
    at error (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:3365:15)
    at Module.error (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:13425:9)
    at tryParse (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:13091:16)
    at Module.setSource (E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:13156:33)
    at E:\works_2018\exkit\packages\admin\node_modules\merge-umi-mock-data\node_modules\rollup\dist\rollup.js:21420:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
(node:18580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)```

**Comment by chenshuai2144** [comment]
Looks like a relationship with the node.js version

**Comment by AnInputForce** [comment]
我也碰上了这个问题，
大神的建议是换个 node的版本试试？

> Looks like a relationship with the node.js version
