### ISSUE TITLE
TypeError: e is undefined

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#248]
https://sentry.io/ant-design/ant-design-pro/issues/407466603/

```
TypeError: e is undefined
  at mouseout (/as/g/:20:10510)
  at _registEvents/< (/as/g/:20:2636)
  at r (/index.js:1:372743)
  at EventListener.handleEvent*_instrumentTryCatch/</</< (/index.js:1:379682)
  at _registEvents (/as/g/:20:2594)
...
(45 additional frame(s) were not displayed)
```

**Comment by nikogu** [comment]
@afc163 这个 `sentry` 是不是要加权限才能看 =。-

**Comment by afc163** [comment]
免费套餐不能加 member。

**Comment by afc163** [comment]
https://rollbar.com/afc163/ant-design/items/5/

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/pull/370
