### ISSUE TITLE
v2.0.0 开发环境的热更新很慢

### ISSUE THREAD

**Issue by Huooo** [ant-design/ant-design-pro#2494]
ant-design-pro v2.0.0

查看了关于热更新的问题，好像开发环境下这个热更新很慢的问题依然存在，开始以为是我开启代理的原因，但是关闭也是非预期更新，想请问官方是否有相关解决方案，v2.0.0 好像是使用 dva 的 hmr 来做热更新，而不是之前的 roadhog 。

---

ant-design-pro v2.0.0

I view all questions about hot update, but the question that hot update very slowly still is not solved. At first I thought it was the proxy of network, however, it still update slowly when I close proxy. So, please, is there any way to solve this problem? And, v2.0.0 use dva hmr to achieve hot update instead of roadhog.

**Comment by chenshuai2144** [comment]
卡在95%？

**Comment by Huooo** [comment]
不是，代码更新之后，iTerm2 进程确实更新了一次而且编译完成，但是浏览器中查看 network 和页面并没有相应的代码和更改，然后我以为是我保存次数太少，然后我就多保存了几次，差不多间隔一段时间后才会更新到浏览器中。Mac 上。可有这种情况？

**Comment by chenshuai2144** [comment]
更新一下 umi？

**Comment by jinrichardJIN** [comment]
同遇到这样的问题
`
● webpack █████████████████████████ emitting (95%) unnamed compat plugin
`像上面这样，每次更新less的时候就会出现这样的问题，需要重新**npm start**

**Comment by chenshuai2144** [comment]
@jinrichardJIN 
如果不需要换主题的功能，可以删掉 plugin.config.js

**Comment by jinrichardJIN** [comment]
@chenshuai2144 嗯，谢谢，编译速度有改善。

**Comment by zhouzixing** [comment]
@chenshuai2144 一模一样这个问题我也遇到了 但是我不想重开一个项目 可否有好的解决办法

**Comment by LJZJIANG** [comment]
我现在也遇到问题了，用的Mac Pro开发。代码更改后，页面并没有刷新，就算强制刷新浏览器也不行，界面也没有改变。依旧是原来的代码。

**Comment by GJBlog** [comment]
@chenshuai2144  删除plugin.config.js之后确实不会出现  webpack █████████████████████████ emitting (95%) unnamed compat plugin 这个了

**Comment by frontendWangqun** [comment]
> 同遇到这样的问题
> `● webpack █████████████████████████ emitting (95%) unnamed compat plugin`像上面这样，每次更新less的时候就会出现这样的问题，需要重新**npm start**

mac 上面，请问现在解决了这个问题了吗？less文件修改后热更新卡在95%那里，哎，什么时候解决啊

**Comment by chenshuai2144** [comment]
@frontendWangqun 
https://beta.pro.ant.design/blog/change-theme-cn

**Comment by frontendWangqun** [comment]
> @frontendWangqun
> https://beta.pro.ant.design/blog/change-theme-cn

现在遇到一个问题是：mac vscode下面运行，故意改错逻辑js代码会报错，当撤销代码修改保持正常逻辑热更新之后页面上会有  ： Unhandled Rejection (Error): Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/src/pages/List/TableList.js: Unexpected token (120:14)

[0m [90m 118 | [39m  }[33m;[39m[0m
[0m [90m 119 | [39m[0m
[0m[31m[1m>[22m[39m[90m 120 | [39m  backward [33m=[39m () [33m=[39m[0m
[0m [90m     | [39m              [31m[1m^[22m[39m[0m
[0m [90m 121 | [39m    [36mconst[39m { currentStep } [33m=[39m [36mthis[39m[33m.[39mstate[33m;[39m[0m
[0m [90m 122 | [39m    [36mthis[39m[33m.[39msetState({[0m
[0m [90m 123 | [39m      currentStep[33m:[39m currentStep [33m-[39m [35m1[39m[33m,[39m[0m
    at Object.raise (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:6322:17)
    at Object.unexpected (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:7638:16)
    at Object.parseParenAndDistinguishExpression (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:8968:12)
    at Object.parseExprAtom (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:8731:21)
    at Object.parseExprAtom (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:3596:20)
    at Object.parseExprSubscripts (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:8385:23)
    at Object.parseMaybeUnary (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:8365:21)
    at Object.parseExprOps (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:8252:23)
    at Object.parseMaybeConditional (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:8225:23)
    at Object.parseMaybeAssign (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:8172:21)
    at Object.parseClassProperty (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10778:25)
    at Object.pushClassProperty (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10734:30)
    at Object.parseClassMemberWithIsStatic (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10673:14)
    at Object.parseClassMember (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10607:10)
    at /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10562:14
    at Object.withTopicForbiddingContext (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:9657:14)
▶ 17 stack frames were collapsed.
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;


这样的错误，其他ide没有这样的问题

**Comment by frontendWangqun** [comment]
> @jinrichardJIN
> 如果不需要换主题的功能，可以删掉 plugin.config.js

1. 删除这个plugin.config.js文件，运行报错，
2. 故意修改错误less代码有以下报错——————出现下面的错误，这个时候不管你修改js还是less都不能热更新了
● Webpack █████████████████████████ emitting (95%) unnamed compat plugin


Error [LessError: Unrecognised input] {
  message: 'Unrecognised input',
  stack: undefined,
  type: 'Parse',
  filename: 'input',
  index: 57934,
  line: 2413,
  column: 6,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    '      background-color: ',
    '      &.antd-pro-pages-dashboard-analysis-active {',
    '        color: #fff;'
  ]
}


麻烦官方给我解决方案哦，感谢

**Comment by huntdream** [comment]
> > @jinrichardJIN
> > 如果不需要换主题的功能，可以删掉 plugin.config.js
> 
> 1. 删除这个plugin.config.js文件，运行报错，
> 2. 故意修改错误less代码有以下报错——————出现下面的错误，这个时候不管你修改js还是less都不能热更新了
>    ● Webpack █████████████████████████ emitting (95%) unnamed compat plugin
> 
> Error [LessError: Unrecognised input] {
> message: 'Unrecognised input',
> stack: undefined,
> type: 'Parse',
> filename: 'input',
> index: 57934,
> line: 2413,
> column: 6,
> callLine: NaN,
> callExtract: undefined,
> extract: [
> ' background-color: ',
> ' &.antd-pro-pages-dashboard-analysis-active {',
> ' color: #fff;'
> ]
> }
> 
> 麻烦官方给我解决方案哦，感谢

不能直接删除plugin.config.js，因为在config.js中被引用到，在config.js中注释掉最后一行参数：chainWebpack: webpackPlugin

**Comment by menciusKael** [comment]
我同样的配置，连续保存三次，每次热更新时间都不一样，有4s的，有10秒的，有15秒的，这是为啥呢
