### ISSUE TITLE
响应出来的对象Response对象全部为空

### ISSUE THREAD

**Issue by silsuer** [ant-design/ant-design-pro#2714]
按照官网的方法 `cnpm install` 之后，

由于项目是前后端分离的，

所以在 `request.js` 中暂时先补全了整个URL，并配置了 `mode: 'no-cors'`，解决跨域问题，

这个时候前端可以发送数据，在network中可以看到

但是后端并没有接受到数据，

之后将发送的对象使用 `FormData` 包装一下，后端就可以接受到数据了，在 `network`中可以看到响应，

但是问题在这里出现了, `request.js`中：

```
 return fetch(url, newOptions)
    .then(response => {
      console.log(response);
    })
```

此时打印出来的 `Response`得 `status`为0，其余属性均为空:

```
Response
   body: null
   bodyUsed: false 
   headers: Headers
   __proto__: Headers
   ok: false
   redirected: false
   status: 0
   statusText: ""
   type: "opaque"
   url: ""
```

求解~

**Comment by silsuer** [comment]
已经解决了，解决办法： 更换了fetch包，不再使用 `dva/fetch` ，期待官方回复

**Comment by chenshuai2144** [comment]
console.log(response.json());

**Comment by silsuer** [comment]
@chenshuai2144 
```
Promise {<rejected>: SyntaxError: Unexpected end of input
    at checkStatus (http://localhost:8000/umi.js:39209:24)}
__proto__: Promise
[[PromiseStatus]]: "rejected"
[[PromiseValue]]: SyntaxError: Unexpected end of input at checkStatus (http://localhost:8000/umi.js:39209:24)
message: "Unexpected end of input"
stack: "SyntaxError: Unexpected end of input↵    at checkStatus (http://localhost:8000/umi.js:39209:24)"
```

并没有用处...
