### ISSUE TITLE
pro升级2.0 启动报错

### ISSUE THREAD

**Issue by gggtuujat** [ant-design/ant-design-pro#2729]
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/wangdongxiao/bts/bts-web/node_modules/mini-css-extract-plugin/dist/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/wangdongxiao/bts/bts-web/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/wangdongxiao/bts/bts-web/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.3.0 start: `umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by chenshuai2144** [comment]
请重新安装包！

**Comment by crossjs** [comment]
重新安装包没法解决，需要全局安装 webpack。
