### ISSUE TITLE
pro1.3 升级2.0 启动报错

### ISSUE THREAD

**Issue by gggtuujat** [ant-design/ant-design-pro#2745]
TypeError: Cannot read property 'component' of undefined
    at patchRoute (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfigFromConfig.js:40:13)
    at routes.forEach.route (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfigFromConfig.js:34:5)
    at Array.forEach (<anonymous>)
    at patchRoutes (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfigFromConfig.js:33:10)
    at patchRoute (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfigFromConfig.js:106:5)
    at routes.forEach.route (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfigFromConfig.js:34:5)
    at Array.forEach (<anonymous>)
    at patchRoutes (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfigFromConfig.js:33:10)
    at _default (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfigFromConfig.js:25:3)
    at _default (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/routes/getRouteConfig.js:27:52)
    at Object.fetchRoutes (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/plugins/commands/getRouteManager.js:23:51)
    at api.registerCommand (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/plugins/commands/dev/index.js:31:19)
    at Service.run (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi-build-dev/lib/Service.js:338:12)
    at Object.<anonymous> (/Users/wangdongxiao/bts/bts-web测试/node_modules/umi/lib/scripts/realDev.js:28:47)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by yutingzhao1991** [comment]
感觉像是 routes 配置的问题。

**Comment by gggtuujat** [comment]
> 感觉像是 routes 配置的问题。

你是对的,是它的问题
