### ISSUE TITLE
npm start 启动报错

### ISSUE THREAD

**Issue by Jin-Yang** [ant-design/ant-design-pro#2818]
在 Centos 启动时报如下的错误。

```
TypeError: Object.values is not a function
    at hasRunning (/ant-design-pro-2.1.1/node_modules/webpackbar/dist/index.js:55:33)
    at WebpackBarPlugin.render (/ant-design-pro-2.1.1/node_modules/webpackbar/dist/index.js:182:9)
    at invokeFunc (/ant-design-pro-2.1.1/node_modules/lodash/lodash.js:10335:23)
    at leadingEdge (/ant-design-pro-2.1.1/node_modules/lodash/lodash.js:10345:26)
    at WebpackBarPlugin.debounced [as _render] (/ant-design-pro-2.1.1/node_modules/lodash/lodash.js:10412:20)
    at WebpackBarPlugin.updateProgress (/ant-design-pro-2.1.1/node_modules/webpackbar/dist/index.js:160:10)
    at WebpackBarPlugin.handler (/ant-design-pro-2.1.1/node_modules/webpackbar/dist/index.js:68:55)
    at compiler.hooks.compilation.tap.compilation (/ant-design-pro-2.1.1/node_modules/webpack/lib/ProgressPlugin.js:126:5)
    at SyncHook.eval (eval at create (/ant-design-pro-2.1.1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/ant-design-pro-2.1.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/ant-design-pro-2.1.1/node_modules/webpack/lib/Compiler.js:504:26)
    at hooks.beforeCompile.callAsync.err (/ant-design-pro-2.1.1/node_modules/webpack/lib/Compiler.js:540:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/ant-design-pro-2.1.1/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/ant-design-pro-2.1.1/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/ant-design-pro-2.1.1/node_modules/webpack/lib/Compiler.js:535:28)
    at compiler.hooks.watchRun.callAsync.err (/ant-design-pro-2.1.1/node_modules/webpack/lib/Watching.js:77:18)
(node:29348) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

搞不懂为啥。

**Comment by afc163** [comment]
node 版本太老了，升级上来。
