### ISSUE TITLE
umi 一直缺少依赖

### ISSUE THREAD

**Issue by JerryChin** [ant-design/ant-design-pro#2905]
执行 `cnpm install ` 安装所有包后， `npm start` 报以下错误：

```
D:\workspace\web\ant-design-pro>npm start

> ant-design-pro@2.1.1 start D:\workspace\web\ant-design-pro
> cross-env APP_TYPE=site umi dev

{ Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\workspace\web\ant-design-pro\node_modules\_antd-theme-generator@1.1.4@antd-theme-generator\index.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (D:\workspace\web\ant-design-pro\node_modules\_pirates@4.0.0@pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (D:\workspace\web\ant-design-pro\node_modules\_pirates@4.0.0@pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32) code: 'MODULE_NOT_FOUND' }
×  error     Cannot find module 'react-router/matchPath'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.1.1 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.SKY-20170327BBW\AppData\Roaming\npm-cache\_logs\2018-11-19T07_22_57_911Z-debug.log

```

请问如何解决？

**Comment by a854363956** [comment]
Maybe you can try   

> npm i glob

**Comment by JerryChin** [comment]
@a854363956 已经试了，安装一个又冒出另一个。

**Comment by wangchao117** [comment]
在Mac上遇到同样问题，node版本10.13.0,但在window上没问题，win上node版本10.13.0

**Comment by wangchao117** [comment]
> @wangchao117 我是 Window 10 x64，node 版本跟你一样。

我在win10上能正常运行，你用cnpm安装的依赖，该用cnpm去跑下试试

**Comment by wangchao117** [comment]
> glob 是个很基础的库，你也许应该使用 cnpm
我的npm源指向的淘宝镜像，所以用npm和cnpm应该都一样

**Comment by wangchao117** [comment]
> glob 是个很基础的库，你也许应该使用 cnpm

我的npm源指向的淘宝镜像，所以用npm和cnpm应该都一样

**Comment by xiaohuoni** [comment]
@wangchao117 不太一样

**Comment by wangchao117** [comment]
> @wangchao117 不太一样

OK，我试下cnpm

**Comment by wangchao117** [comment]
> cnpm 里面有很多黑科技的

好吧，尝试下

**Comment by a854363956** [comment]
@wangchao117   为什么不尝试一下VPN或者SS ，一般我都直接翻墙的 - - ！

**Comment by theprimone** [comment]
> cnpm 里面有很多黑科技的

我服了，真可以。
