### ISSUE TITLE
更改工程名字npm start启动报错

### ISSUE THREAD

**Issue by crazyKii** [ant-design/ant-design-pro#2929]
比如将默认项目名字ant-design-pro更改为hms-frontend，npm start 报错，报错信息如下：
``
  $ npm start
> hms-frontend@2.1.1 start C:\Users\Administrator\Desktop\Idea Projects\work\frontend\hms-frontend
> cross-env APP_TYPE=site umi dev

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'cross-spawn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Idea Projects\work\frontend\hms-frontend\node_modules\_cross-env@5.2.0@cross-env\dist\index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hms-frontend@2.1.1 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hms-frontend@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-20T13_43_10_152Z-debug.log
``

**Comment by stu4355226** [comment]
試了一下....我的可以編過... window10 pro.
![image](https://user-images.githubusercontent.com/14792007/48797551-58ee9080-ecb7-11e8-8f7b-b0daac978e4e.png)
