### ISSUE TITLE
为什么一定要在document.ejs中引入dataset.js?

### ISSUE THREAD

**Issue by Dollyn** [ant-design/ant-design-pro#2961]
试了一下，去掉后就不行了，感觉这样做应该是有什么原因的。。。

如题， 希望有人能够解释一下背后的原因。。

另外，antd-pro引用的是0.9.6版本， 同时在bizchart官网给的例子(Codepen)中用的是0.8.6版本，例如桑基图示例中配的例子：
https://bizcharts.net/products/bizCharts/demo/detail?id=relation-sankey&selectedKey=%E5%85%B3%E7%B3%BB%E5%9B%BE
有什么区别吗。

因为目前我们遇到了一个奇怪的问题， 我们一个页面中按照这个示例写了个桑基图，如果用pro带的这个0.9.6， 同样的数据有的时候就会爆一个类似死循环（或者是递归）的错误：

> uncaught at _callee RangeError: Maximum call stack size exceeded
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48154)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48315)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)
    at t (https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js:1:48394)

而把document.ejs中引入的dataset换成了0.8.6（  <script type="text/javascript" src="//gw.alipayobjects.com/os/antv/assets/data-set/0.8.6/data-set.min.js"></script>
）以后就没有问题了。

感觉自己踩了个大坑， 这样改不知道会不会挖个更大的坑。。。

**Comment by chenshuai2144** [comment]
很简单，g2需要，不要想太多
