### ISSUE TITLE
 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '.ant-pagination-item-1.2' is not a valid selector.

### ISSUE THREAD

**Issue by junhwong** [ant-design/ant-design-pro#3204]
版本：
```json
"dependencies": {
    "@babel/runtime": "^7.1.5",
    "antd": "^3.10.9",
    "bizcharts": "^3.4.0",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "@antv/data-set": "^0.10.0",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "enquire-js": "^0.2.1",
    "hash.js": "^1.1.5",
    "lodash": "^4.17.10",
    "lodash-decorators": "^6.0.0",
    "memoize-one": "^4.0.0",
    "moment": "^2.22.2",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^2.4.0",
    "prop-types": "^15.5.10",
    "qs": "^6.6.0",
    "rc-animate": "^2.4.4",
    "react": "^16.6.3",
    "react-container-query": "^0.11.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.6.3",
    "react-fittext": "^1.0.0",
    "react-media": "^1.8.0",
    "react-router-dom": "^4.3.1"
  },
  "devDependencies": {
    "@types/react": "^16.7.7",
    "@types/react-dom": "^16.0.10",
    "antd-pro-merge-less": "^0.2.0",
    "antd-theme-webpack-plugin": "^1.1.8",
    "babel-eslint": "^10.0.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.7.0",
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-compat": "^2.6.2",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.11.1",
    "gh-pages": "^2.0.1",
    "husky": "^1.2.0",
    "jest-puppeteer": "^3.5.1",
    "lint-staged": "^8.1.0",
    "merge-umi-mock-data": "^0.0.3",
    "mockjs": "^1.0.1-beta3",
    "prettier": "1.15.2",
    "pro-download": "^1.0.1",
    "stylelint": "^9.8.0",
    "stylelint-config-prettier": "^4.0.0",
    "stylelint-config-standard": "^18.0.0",
    "tslint": "^5.10.0",
    "tslint-config-prettier": "^1.10.0",
    "tslint-react": "^3.6.0",
    "umi": "^2.2.8",
    "umi-plugin-react": "^1.2.0"
  },
```

错误描述：偶尔出现，刷新一下又好了，我不知道原因也不知道如复现（多数时候是好的）

```
Pagination.js:88 Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '.ant-pagination-item-1.2' is not a valid selector.
    at Pagination.componentDidUpdate (http://localhost:8000/umi.dll.js:182830:51)
    at commitLifeCycles (http://localhost:8000/umi.dll.js:225581:22)
    at commitAllLifeCycles (http://localhost:8000/umi.dll.js:226867:7)
    at HTMLUnknownElement.callCallback (http://localhost:8000/umi.dll.js:209754:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8000/umi.dll.js:209804:16)
    at invokeGuardedCallback (http://localhost:8000/umi.dll.js:209861:31)
    at commitRoot (http://localhost:8000/umi.dll.js:227063:7)
    at completeRoot (http://localhost:8000/umi.dll.js:228517:3)
    at performWorkOnRoot (http://localhost:8000/umi.dll.js:228446:9)
    at performWork (http://localhost:8000/umi.dll.js:228354:7)
    at performSyncWork (http://localhost:8000/umi.dll.js:228328:3)
    at requestWork (http://localhost:8000/umi.dll.js:228197:5)
    at scheduleWork (http://localhost:8000/umi.dll.js:228006:5)
    at Object.enqueueSetState (http://localhost:8000/umi.dll.js:221918:5)
    at Connect.umi../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:8000/umi.dll.js:237634:16)
    at Connect.onStateChange (http://localhost:8000/umi.dll.js:231827:16)
    at Object.notify (http://localhost:8000/umi.dll.js:232499:21)
    at Subscription.notifyNestedSubs (http://localhost:8000/umi.dll.js:232538:20)
    at Connect.onStateChange (http://localhost:8000/umi.dll.js:231824:16)
    at dispatch (http://localhost:8000/umi.dll.js:242295:7)
    at http://localhost:8000/umi.dll.js:240139:22
    at http://localhost:8000/umi.dll.js:110020:18
    at http://localhost:8000/umi.dll.js:233512:18
    at dispatch (http://localhost:8000/umi.dll.js:241838:18)
    at http://localhost:8000/umi.dll.js:241672:12
    at http://localhost:8000/umi.dll.js:240668:52
    at exec (http://localhost:8000/umi.dll.js:241352:5)
    at flush (http://localhost:8000/umi.dll.js:241393:5)
    at asap (http://localhost:8000/umi.dll.js:241366:5)
    at runPutEffect (http://localhost:8000/umi.dll.js:240665:25)
    at runEffect (http://localhost:8000/umi.dll.js:240614:184)
    at next (http://localhost:8000/umi.dll.js:240494:9)
    at currCb (http://localhost:8000/umi.dll.js:240567:7)
```

```
index.js:2178 The above error occurred in the <Pagination> component:
    in Pagination (created by LocaleReceiver)
    in LocaleReceiver (created by Pagination)
    in Pagination (created by Table)
    in div (created by Spin)
    in AnimateChild (created by Animate)
    in div (created by Animate)
    in Animate (created by Spin)
    in Spin (created by Table)
    in div (created by Table)
    in Table (created by StandardTable)
    in div (created by StandardTable)
    in StandardTable (created by TableList)
    in div (created by TableList)
    in div (created by Card)
    in div (created by Card)
    in Card (created by TableList)
    in div (created by GridContent)
    in GridContent (created by Connect(GridContent))
    in Connect(GridContent) (created by PageHeaderWrapper)
    in div (created by PageHeaderWrapper)
    in div (created by PageHeaderWrapper)
    in PageHeaderWrapper (created by Connect(PageHeaderWrapper))
    in Connect(PageHeaderWrapper) (created by TableList)
    in TableList (created by Form(TableList))
    in Form(TableList) (created by Connect(Form(TableList)))
    in Connect(Form(TableList)) (created by LoadableComponent)
    in LoadableComponent (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Route)
    in Switch (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Component)
    in Switch (created by Component)
    in Authorized (created by BasicLayout)
    in div (created by Basic)
    in Basic (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by Media)
    in Media
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by LoadableComponent)
    in LoadableComponent (created by Component)
    in Component (created by Component)
    in Authorized (created by _default)
    in _default (created by Component)
    in Component (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by ret)
    in ret (created by _default)
    in Switch (created by _default)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by _default)
    in Unknown (created by InjectIntl(Component))
    in InjectIntl(Component) (created by _default)
    in IntlProvider (created by _default)
    in LocaleProvider (created by _default)
    in _default (created by _default)
    in _default
    in Provider (created by DvaContainer)
    in DvaContainer
```

**Comment by chenshuai2144** [comment]
这个问题很奇怪，试着更新到最新版本呢？
