### ISSUE TITLE
npm start error message 

### ISSUE THREAD

**Issue by afish177** [ant-design/ant-design-pro#3213]
Warning: DISABLE_ESLINT is deprecated, use ESLINT=none instead has been deprecated.
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type undefined
    at validChunk (_stream_writable.js:258:10)
    at WriteStream.Writable.write (_stream_writable.js:292:21)
    at nodeDeprecate (F:\GitPro\ant-design-pro\node_modules\deprecate\index.js:22:22)
    at deprecate (F:\GitPro\ant-design-pro\node_modules\deprecate\index.js:11:3)
    at Object.<anonymous> (F:\GitPro\ant-design-pro\node_modules\af-webpack\lib\getConfig.js:81:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\GitPro\ant-design-pro\node_modules\af-webpack\getConfig.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

**Comment by sxd-mike** [comment]
遇到一样的问题，请问有找到问题的原因吗

**Comment by chenshuai2144** [comment]
感觉是 node 版本造成的

**Comment by ctocto** [comment]
@afish177 @sxd-mike 请问解决了吗

**Comment by wangdaochen** [comment]
@afish177 @ @   解决了吗，请指教

**Comment by Victoriacsl** [comment]
@afish177 @sxd-mike 请问解决了吗

**Comment by Victoriacsl** [comment]
DISABLE_ESLINT 已经弃用, 需要使用 ESLINT=none  , 
修改方式:
"start": "cross-env ESLINT=none roadhog dev",
"build": "cross-env ESLINT=none roadhog build",

**Comment by dengtingsheng** [comment]
thanks
