### ISSUE TITLE
Linter fails on the current master

### ISSUE THREAD

**Issue by visheshd** [ant-design/ant-design-pro#3435]
Currently `npm run lint` fails with following 

```
Error: Cannot find module 'typescript-eslint-parser'
    at ModuleResolver.resolve (/project/packages/web-client/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at loadFromDisk (/project/packages/web-client/node_modules/eslint/lib/config/config-file.js:514:42)
    at Object.load (/project/packages/web-client/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (/project/packages/web-client/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/project/packages/web-client/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/project/packages/web-client/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/project/packages/web-client/node_modules/eslint/lib/config.js:342:29)
    at processText (/project/packages/web-client/node_modules/eslint/lib/cli-engine.js:180:33)
    at processFile (/project/packages/web-client/node_modules/eslint/lib/cli-engine.js:240:12)
    at fileList.map.fileInfo (/project/packages/web-client/node_modules/eslint/lib/cli-engine.js:612:40)```

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51446973-f0be3880-1d53-11e9-9fab-651a80033652.png)
It's work for me. Did you run `npm install` before `npm run lint`?

**Comment by chenshuai2144** [comment]
try` cnpm install`

**Comment by ztplz** [comment]
There is no need to use `cnpm`.

**Comment by a854363956** [comment]
@visheshd  Please check the network, it may be because the network shield can not download, it is recommended to use VPN.
