### ISSUE TITLE
在Centos上git clone的工程，npm start能跑起来吗？

### ISSUE THREAD

**Issue by CloserWU** [ant-design/ant-design-pro#3484]
如题，在Centos系统上
```bash
git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project
cd my-project
npm install
npm start
```
报错如下，
```shell
> ant-design-pro@2.2.1 start /root/my-project
> cross-env APP_TYPE=site umi dev

/root/my-project/node_modules/antd-pro-merge-less/loopAllLess.js:10
const loopAllLess = async parents => {
                          ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Module._compile (/root/my-project/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:586:10)
    at Object.newLoader [as .js] (/root/my-project/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
/root/my-project/node_modules/umi-build-dev/lib/UserConfig.js:186
      throw new Error(msg);
      ^

Error: 配置文件 "config/config.js" 解析出错，请检查语法。

SyntaxError: Unexpected identifier
    at onError (/root/my-project/node_modules/umi-build-dev/lib/UserConfig.js:186:13)
    at requireFile (/root/my-project/node_modules/umi-build-dev/lib/UserConfig.js:97:12)
    at UserConfig.getConfig (/root/my-project/node_modules/umi-build-dev/lib/UserConfig.js:189:72)
    at Service.init (/root/my-project/node_modules/umi-build-dev/lib/Service.js:288:31)
    at Service.run (/root/my-project/node_modules/umi-build-dev/lib/Service.js:326:10)
    at Object.<anonymous> (/root/my-project/node_modules/umi/lib/scripts/realDev.js:28:47)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

```
npm  版本 3.10.10
node 版本 v6.14.3
npm install过程中没有什么异样，只有几个warn，文件没有修改过
```shell
npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

> husky@1.3.1 install /root/my-project/node_modules/husky
> node husky install

```

所以Ant Design Pro在Centos上，npm start能跑吗？

**Comment by CloserWU** [comment]
是node版本太低了，需要升级
