### ISSUE TITLE
npm run start 失败

### ISSUE THREAD

**Issue by JerryMissTom** [ant-design/ant-design-pro#3485]
报错如下：
```
TypeError: Cannot read property 'pullAll' of undefined
    at _default (/Users/web/node_modules/umi-plugin-dll/lib/buildDll.js:28:26)
    at Promise (/Users/web/node_modules/umi-plugin-dll/lib/index.js:28:29)
    at new Promise (<anonymous>)
    at api.register (/Users/web/node_modules/umi-plugin-dll/lib/index.js:27:12)
    at /Users/web/node_modules/umi-build-dev/lib/Service.js:230:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/web/node_modules/umi-build-dev/lib/Service.js:42:103)
    at _next (/Users/web/node_modules/umi-build-dev/lib/Service.js:44:194)
    at /Users/web/node_modules/umi-build-dev/lib/Service.js:44:364
    at new Promise (<anonymous>)
    at /Usersweb/node_modules/umi-build-dev/lib/Service.js:44:97
    at Service._applyPluginsAsync (/Users/web/node_modules/umi-build-dev/lib/Service.js:251:7)
    at api.registerCommand (/Users/web/node_modules/umi-build-dev/lib/plugins/commands/dev/index.js:96:13)
    at Service.run (/Users/web/node_modules/umi-build-dev/lib/Service.js:346:12)
    at Object.<anonymous> (/Users/web/node_modules/umi/lib/scripts/realDev.js:28:47)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

```
我删除node-modules，清空缓存重新npm install，仍然还失败。
后来将`config.js`中下面内容给注释了就可以重新跑了；
```
     // ...(!process.env.TEST && os.platform() === 'darwin'
      //   ? {
      //     dll: {
      //       include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
      //       exclude: ['@babel/runtime'],
      //     },
      //     hardSource: true,
      //   }
      //   : {}),
```

**Comment by chenshuai2144** [comment]
windows?

**Comment by JerryMissTom** [comment]
@chenshuai2144  
Mac OS :10.13.6   
Node: v10.14.1
之前合并过使用Windows电脑开发的同事的代码，他安装了几个第三方库，我合并代码并先npm install，然后运行 npm run start就报错了。

**Comment by chenshuai2144** [comment]
感觉是用了什么不兼容的东西
dll 可以显著的增加构建速度，你可以帮我们排查一下吗?

**Comment by JerryMissTom** [comment]
他添加的几个包是
```
dependencies: 
    "events": "^3.0.0",
    "fs": "0.0.1-security",
    "loader-utils": "^1.2.3",
    "react-treeview": "^0.4.7",
    "react-xml-parser": "^1.0.8",
    "xml-js": "^1.6.9",
    "xml2js": "^0.4.19"
```
```
devDependencies:
    "antd-theme-webpack-plugin": "^1.2.0",  //版本号升级
     "extract-text-webpack-plugin": "^4.0.0-beta.0", // 新增
    "umi-plugin-react": "^1.4.1"   //版本号升级
```
我明天将其逐个安装，然后测试是否可以`npm run start`，排查下到底是哪个库造成的

**Comment by chenshuai2144** [comment]
估计是fs，怎么能有包叫这个名字

**Comment by JerryMissTom** [comment]
事实上他的代码中就没用到这个库，我后来使用未合并之前的代码打包，也是报错。

**Comment by JerryMissTom** [comment]
等他过年回来了，仔细问下他那个fs库具体是啥情况
