### ISSUE TITLE
Error running test:all 

### ISSUE THREAD

**Issue by Cadabrum** [ant-design/ant-design-pro#3543]
Windows 10, NodeJS v10.15.0
npm install
npm test:all

All 14 tests are failing with the same error:

    Enzyme Internal Error: configured enzyme adapter did not inherit from the EnzymeAdapter base class

      at validateAdapter (node_modules/umi-test/node_modules/enzyme/build/validateAdapter.js:25:11)
      at Object.merge [as configure] (node_modules/umi-test/node_modules/enzyme/build/configuration.js:28:38)
      at Object.<anonymous> (node_modules/umi-test/lib/setupTests.js:11:17)

**Comment by chenshuai2144** [comment]
更新一喜依赖包，jest 升级了

**Comment by SevenGuns** [comment]
MacOS 10.14.1, NodeJS v10.15.1
cnpm i
npm run test:all
`Validation Error:

  Options: setupTestFrameworkScriptFile and setupFilesAfterEnv cannot be used together.
  Please change your configuration to only use setupFilesAfterEnv.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html`
![20190227205523](https://user-images.githubusercontent.com/23354928/53491810-3e0b9380-3ad2-11e9-9b75-b4af2d67f8d7.png)
