### ISSUE TITLE
Tests are failing with "Error: Failed to launch chrome"

### ISSUE THREAD

**Issue by EvgenyOrekhov** [ant-design/ant-design-pro#3721]
Steps to reproduce:

1. `git clone`
2. `npm it`

Expected result: all tests should pass.

Actual result: 

```text
Error: Failed to launch chrome!
[0308/022616.868018:ERROR:content_main_runner_impl.cc(303)] --no-sandbox should be used together with --no--zygote


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/__w/1/s/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/__w/1/s/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:202:15)
    at Interface.close (readline.js:395:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

CI is green, but it is failing. Here is the log for the latest commit, for example: https://dev.azure.com/ant-design/ant-design-pro/_build/results?buildId=809

**Comment by chenshuai2144** [comment]
In some environments you may need to turn this feature off than the sandbox feature that does not support chorme
config in https://github.com/ant-design/ant-design-pro/blob/master/jest-puppeteer.config.js

**Comment by EvgenyOrekhov** [comment]
@chenshuai2144 What feature are you talking about? How should I change `jest-puppeteer.config.js` to make it work?

**Comment by chenshuai2144** [comment]
you can remove all config
