### ISSUE TITLE
npm run test 报错提示：SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Veath** [ant-design/ant-design-pro#3824]
步骤：1、创建demo.test.js
```js
 import Dafy from '@dafy/dafy-evoke-app';
   describe('fixedZero tests', () => {
     it('call dafy', () => {
          expect(new Dafy()).toEqual(10);
       });
   });
```

2、npm run test
3、 报错代码：
```js
 /Users//xxxxxx/system/node_modules/@babel/runtime/helpers/esm/objectSpread.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import defineProperty from "./defineProperty";
                                                                                                    ^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:451:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:493:19)
      at Object.<anonymous> (node_modules/@dafy/dafy-evoke-app/lib/index.js:5:45)
```

**Comment by chenshuai2144** [comment]
Dafy 里面是不是有什么奇怪的代码？

**Comment by Veath** [comment]
> Dafy 里面是不是有什么奇怪的代码？
@chenshuai2144   可以正常build、start。run test 就会报错。
dafy，文件顶部有以下内容（babel）
位置:5:45报错
```js
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

var _objectSpread2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/objectSpread"));

var _objectWithoutProperties2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/objectWithoutProperties"));

var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/classCallCheck"));

var _createClass2 = _interopRequireDefault(require("@babel/runtime/helpers/esm/createClass"));
```

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/54935152-b000bc80-4f5a-11e9-850e-ab8631234b43.png)

404，`@dafy/dafy-evoke-app` 是私库？

**Comment by sorrycc** [comment]
重复了，在 https://github.com/umijs/umi/issues/2159 跟进吧。
