### ISSUE TITLE
operation not permitted, open 'D:\projects\puncars\puncars-site\.temp\ant-design-pro.less'

### ISSUE THREAD

**Issue by hardevhmh** [ant-design/ant-design-pro#3855]
build [=================== ] 95%error { Error: EPERM: operation not permitted, open 'D:\projects\puncars\puncars-site\.temp\ant-design-pro.less'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at loopAllLess.then (D:\projects\puncars\puncars-site\node_modules\antd-pro-merge-less\index.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -4048,
  syscall: 'open',
  code: 'EPERM',
  path:
   'D:\\projects\\puncars\\puncars-site\\.temp\\ant-design-pro.less' }

**Comment by chenshuai2144** [comment]
没有权限，你删除一下那个文件夹，然后重新运行一下就好了
