### ISSUE TITLE
ERROR in ./mock/matchMock.js

### ISSUE THREAD

**Issue by mbaric1** [ant-design/ant-design-pro#3940]
Hello,

Found problem with building application.

Steps:

1. npm install
2. npm run build

First problem is with node ./scripts/generateMock

```
> node ./scripts/generateMock

get files: api.js, chart.js, geographic.js, notices.js, profile.js, route.js, rule.js, user.js
(node:12776) UnhandledPromiseRejectionWarning: SyntaxError: ant-design-pro\node_modules\merge-umi-mock-data\allMock.js: Bad character escape sequence (9:51)

   7 | import route from "ant-design-pro\mock\route.js";
   8 | import rule from "ant-design-pro\mock\rule.js";
>  9 | import user from "ant-design-pro\mock\user.js";
     |                                                    ^
  10 |
  11 | const data = {...api,...chart,...geographic,...notices,...profile,...route,...rule,...user};
  12 |
    at Parser.raise (ant-design-pro\node_modules\@babel\parser\lib\index.js:3851:17)
    at Parser.readHexChar (ant-design-pro\node_modules\@babel\parser\lib\index.js:4967:14)
    at Parser.readCodePoint (ant-design-pro\node_modules\@babel\parser\lib\index.js:4774:19)
    at Parser.readEscapedChar (ant-design-pro\node_modules\@babel\parser\lib\index.js:4899:29)
    at Parser.readString (ant-design-pro\node_modules\@babel\parser\lib\index.js:4794:21)
    at Parser.getTokenFromCode (ant-design-pro\node_modules\@babel\parser\lib\index.js:4479:14)
    at Parser.nextToken (ant-design-pro\node_modules\@babel\parser\lib\index.js:4049:12)
    at Parser.next (ant-design-pro\node_modules\@babel\parser\lib\index.js:3989:10)
    at Parser.eat (ant-design-pro\node_modules\@babel\parser\lib\index.js:3994:12)
    at Parser.eatContextual (ant-design-pro\node_modules\@babel\parser\lib\index.js:5129:44)
(node:12776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 ```

Second problem is where build fails:
```
WARNING in ../node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/express/lib/application.js
 @ ../node_modules/express/lib/express.js
 @ ../node_modules/express/index.js
 @ ./api.js

ERROR in ./mock/matchMock.js
Module not found: Error: Can't resolve './index' in 'ant-design-pro\lambda\mock'
 @ ./mock/matchMock.js 5:17-35
 @ ./api.js
```

File index doesn't exist in
`ant-design-pro\lambda\mock`

Thanks!

**Comment by chenshuai2144** [comment]
use latest master.
this is a  AWS functions. you can remove it

**Comment by mbaric1** [comment]
Thanks. I managed to build it now.

**Comment by hst-Sunday** [comment]
@mbaric1 
I am the same, how can you solve it?
