### ISSUE TITLE
故意修改导致代码逻辑错误，再撤销错误代码返回正常代码之后热更新之后会有个报错页面（Unhandled Rejection (Error):或者SyntaxError）类似的错误

### ISSUE THREAD

**Issue by frontendWangqun** [ant-design/ant-design-pro#4173]
1：修改js文件会有以下错误——————Unhandled Rejection (Error): Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/src/pages/Dashboard/Analysis.js: Unexpected token (73:10)

[0m [90m 71 | [39m[0m
[0m [90m 72 | [39m  selectDate [33m=[39m type [0m
[0m[31m[1m>[22m[39m[90m 73 | [39m    [36mconst[39m { dispatch } [33m=[39m [36mthis[39m[33m.[39mprops[33m;[39m[0m
[0m [90m    | [39m          [31m[1m^[22m[39m[0m
[0m [90m 74 | [39m    [36mthis[39m[33m.[39msetState({[0m
[0m [90m 75 | [39m      rangePickerValue[33m:[39m getTimeDistance(type)[33m,[39m[0m
[0m [90m 76 | [39m    })[33m;[39m[0m
    at Object.raise (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:6322:17)
    at Object.unexpected (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:7638:16)
    at Object.parseClassMemberWithIsStatic (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10711:12)
    at Object.parseClassMember (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10607:10)
    at /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10562:14
    at Object.withTopicForbiddingContext (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:9657:14)
    at Object.parseClassBody (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10539:10)
    at Object.parseClass (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10513:22)
    at Object.parseStatementContent (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:9805:21)
    at Object.parseStatement (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:9763:17)
    at Object.parseBlockOrModuleBlockBody (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10340:25)
    at Object.parseBlockBody (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:10327:10)
    at Object.parseTopLevel (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:9692:10)
    at Object.parse (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:11209:17)
    at parse (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/parser/lib/index.js:11233:26)
    at parser (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
▶ 17 stack frames were collapsed.
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

2：修改less文件会有以下报错——————Unhandled Rejection (Error): Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

        color: 
      }
    ^
Unrecognised input. Possibly missing opening '{'
      in /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/src/pages/List/TableList.less (line 27, column 6)
    at /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/af-webpack/node_modules/webpack/lib/NormalModule.js:301:20
    at /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/chuyan/Documents/React/antdesign-pro/ant-design-pro/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
▶ 6 stack frames were collapsed.
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/pages/List/TableList.js
http://localhost:8000/p__List__TableList.async.js:296:74
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

有时候终端会有这个错，再怎么修改文件就一直卡在那，必须重新start了● Webpack █████████████████████████ emitting (95%) unnamed compat plugin

Error [LessError: Unrecognised input] {
  message: 'Unrecognised input',
  stack: undefined,
  type: 'Parse',
  filename: 'input',
  index: 57923,
  line: 2413,
  column: 6,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    '      color: ',
    '      &.antd-pro-pages-dashboard-analysis-active {',
    '        color: #fff;'
  ]
}

**Comment by chenshuai2144** [comment]
已过时。
