### ISSUE TITLE
Unknown browser kaios 

### ISSUE THREAD

**Issue by undefinedor** [ant-design/ant-design-pro#4206]
```Module build failed (from ./node_modules/_mini-css-extract-plugin@0.6.0@mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/_postcss-loader@3.0.0@postcss-loader/src/index.js):
BrowserslistError: Unknown browser kaios
    at checkName (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_browserslist@4.3.7@browserslist/index.js:126:20)
    at Function.select (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_browserslist@4.3.7@browserslist/index.js:730:18)
    at /opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_browserslist@4.3.7@browserslist/index.js:157:33
    at Array.reduce (&lt;anonymous&gt;)
    at resolve (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_browserslist@4.3.7@browserslist/index.js:138:18)
    at browserslist (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_browserslist@4.3.7@browserslist/index.js:246:16)
    at isSupported (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_caniuse-api@3.0.0@caniuse-api/dist/index.js:62:37)
    at /opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_postcss-reduce-initial@4.0.3@postcss-reduce-initial/dist/index.js:40:60
    at initializePlugin (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_cssnano@4.1.10@cssnano/dist/index.js:31:51)
    at runLoaders (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_webpack@4.28.4@webpack/lib/NormalModule.js:301:20)
    at /opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:367:11
    at /opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/opt/jenkins/node10.15/nodejs-backend-website/nodejs-backend-website/node_modules/_postcss-loader@3.0.0@postcss-loader/src/index.js:208:9)

 @ ./node_modules/_antd@3.18.1@antd/es/notification/style/index.js 2:0-22
 @ ./src/global.js
 @ ./src/pages/.umi-production/umi.js
 @ multi ./src/pages/.umi-production/umi.js

 error  in ./src/global.less

```

**Comment by undefinedor** [comment]
咋整，，懵逼中。。。

**Comment by afc163** [comment]
http://zh.lmgtfy.com/?q=BrowserslistError%3A+Unknown+browser+kaios

**Comment by undefinedor** [comment]
@afc163 已经尝试过谷歌出来的各种解决方式。有人说browserslist 偏低 有人说需要加个resolutions。 本地环境一直没有问题，docker构建就会出现这个问题。。。自认为不是伸手党。所以这个答复感觉更无聊。

**Comment by afc163** [comment]
我只是帮你找更多信息，多的我也帮不到你。

**Comment by undefinedor** [comment]
@afc163  = = ！那。。谢谢。。我再查查依赖。。
