### ISSUE TITLE
umi block add ant-design-pro/exception404 报错

### ISSUE THREAD

**Issue by zywkuo** [ant-design/ant-design-pro#4379]
umi block add ant-design-pro/exception404 或者403 ，在安装的时候需要
npm install ant-design-pro@^2.1.1 umi-request@^1.0.0-beta.1 呢，接着就是因为冲突报错了。
<img width="1016" alt="WX20190604-155926@2x" src="https://user-images.githubusercontent.com/21994183/58861884-02402580-86e2-11e9-86b0-02ec004c5657.png">

**Comment by chenshuai2144** [comment]
@yutingzhao1991  这个也需要关注一下，我们可能需要一个新的 package 的 merge 工具。

**Comment by afc163** [comment]
反馈好多，尽快兼容一下老的调用方式。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4386

**Comment by xiaohuoni** [comment]
我也加一个
```sh
$ npx umi block add DashboardAnalysis  --path=/dashboard/analysis
✔ Parse url and args
✔ Git fetch
✔ Git checkout master
✔ Git pull
✖  error     AssertionError [ERR_ASSERTION]: /Users/xiaohuoni/.umi/blocks/github.com/umijs/umi-blocks/DashboardAnalysis don't exists 
    at /Users/xiaohuoni/.config/yarn/global/node_modules/alita/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:231:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/xiaohuoni/.config/yarn/global/node_modules/alita/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:36:103)
    at _next (/Users/xiaohuoni/.config/yarn/global/node_modules/alita/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:38:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by zning1994** [comment]
我在#4534 做了一定分析，这个错误应该跟`config.ts`的`defaultGitUrl`设置有关系。
