### ISSUE TITLE
(node:2776) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted,

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design-pro#4387]
(node:2776) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, rmdir 'E:\gateway\gateway_webs\release\aspnet_client\system_web\4_0_30319'
    at Object.fs.rmdirSync (fs.js:846:18)
    at rmkidsSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:304:9)
    at E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:304:9)
    at E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:304:9)
    at E:\gateway\gateway_webs\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
(node:2776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (
rejection id: 1)
(node:2776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

之前执行npm run build时都是好的，这几天打包老是报错，有没有人遇到过这个问题啊

**Comment by chenshuai2144** [comment]
`operation not permitted `  试着删除一下node_modules，是个简单的权限不足问题

**Comment by xiaoshui222** [comment]
> `operation not permitted ` 试着删除一下node_modules，是个简单的权限不足问题

我删了node_modules 后重新下载也不行，是我的node版本低了吗，现在node是8.11.1
