### ISSUE TITLE
win10 下使用 gitbash 添加模块有问题

### ISSUE THREAD

**Issue by aprilyzl0405** [ant-design/ant-design-pro#4388]
使用gitbash 添加模块报错，如下：

```
$ npx umi block add DashboardAnalysis  --path=/dashboard/analysis
√ Parse url and args
√ Git fetch
√ Git checkout master
√ Git pull
  Generate files
   create src\pages\D:\Software\Git\dashboard\analysis\components\IntroduceRow.tsx
internal/fs/utils.js:284
  return this._checkModeProperty(S_IFDIR);
              ^

RangeError: Maximum call stack size exceeded
    at Stats.isDirectory (internal/fs/utils.js:284:15)
    at sync (D:\WorkSpace\ant-design-pro\node_modules\mkdirp\index.js:92:27)
    at sync (D:\WorkSpace\ant-design-pro\node_modules\mkdirp\index.js:77:24)
    at sync (D:\WorkSpace\ant-design-pro\node_modules\mkdirp\index.js:78:17)
    at sync (D:\WorkSpace\ant-design-pro\node_modules\mkdirp\index.js:78:17)
```

重点是在 Generate files 时生成的路径错误，会不会是 gitbash 环境变量的问题，因为 win 下面使用 gitbash 作为终端工具的人还是挺多的，所以我觉得这算一个问题。

**Comment by chenshuai2144** [comment]
考虑不周。

**Comment by hnsylitao** [comment]
+1 遇到了相同的问题

**Comment by aprilyzl0405** [comment]
这个问题貌似并没有解决，cmd一直是没出现问题的，但到了gitbash就会出现，这个路径出问题了
![image](https://user-images.githubusercontent.com/24885455/61603950-42e40600-ac72-11e9-8d66-84fd25459454.png)
