### ISSUE TITLE
使用github最新的代码安装npm run fetch:blocks报错

### ISSUE THREAD

**Issue by annpeter** [ant-design/ant-design-pro#4421]
Unhandled rejection RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/aproba/index.js:38:16
    at Array.forEach (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:33:11)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
npm ERR! cb() never called!

**Comment by chenshuai2144** [comment]
你使用了 cnpm 安装包吗？
你应该使用 cnpm i --by=npm

**Comment by annpeter** [comment]
是用cnpm 安装的包呢

**Comment by annpeter** [comment]
是用cnpm安装的包，不行 试过很多次 @chenshuai2144

**Comment by chenshuai2144** [comment]
` cnpm i --by=npm`
cnpm 装的包 ，npm 不兼容
