### ISSUE TITLE
cnpm create umi创建项目，选择JavaScript版本，然后cnpm run fetch:blocks报错

### ISSUE THREAD

**Issue by annpeter** [ant-design/ant-design-pro#4422]
``` 
~/Documents/MyCode/open-source/ant-design-pro  cnpm run fetch:blocks

> ant-design-pro@1.0.0 fetch:blocks /Users/annpeter/Documents/MyCode/open-source/ant-design-pro
> node ./scripts/fetch-blocks.js

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/annpeter/Documents/MyCode/open-source/ant-design-pro/config/config.ts'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at getNewRouteCode (/Users/annpeter/Documents/MyCode/open-source/ant-design-pro/scripts/repalceRouter.js:9:31)
    at Object.<anonymous> (/Users/annpeter/Documents/MyCode/open-source/ant-design-pro/scripts/fetch-blocks.js:78:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**Comment by annpeter** [comment]
修改fetch-blocks.js，将
const relativePath = path.join(__dirname, '../config/config.ts');
改为
const relativePath = path.join(__dirname, '../config/config.js');

然后继续执行cnpm run fetch:blocks，还是报错
`
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.3.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN workbox-webpack-plugin@3.6.3 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/annpeter/Documents/MyCode/open-source/ant-design-pro/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/.bin/parser
npm ERR! code EEXIST
npm ERR! Refusing to delete /Users/annpeter/Documents/MyCode/open-source/ant-design-pro/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/.bin/parser: containing path /Users/annpeter/Documents/MyCode/open-source/ant-design-pro/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/@babel/parser isn't under npm's control
npm ERR! File exists: /Users/annpeter/Documents/MyCode/open-source/ant-design-pro/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/.bin/parser
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/annpeter/.npm/_logs/2019-06-11T00_56_57_153Z-debug.log


    at /Users/annpeter/Documents/MyCode/open-source/ant-design-pro/node_modules/_umi-build-dev@1.9.3@umi-build-dev/lib/plugins/commands/block/index.js:333:21
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/annpeter/Documents/MyCode/open-source/ant-design-pro/node_modules/_umi-build-dev@1.9.3@umi-build-dev/lib/plugins/commands/block/index.js:38:103)
    at _throw (/Users/annpeter/Documents/MyCode/open-source/ant-design-pro/node_modules/_umi-build-dev@1.9.3@umi-build-dev/lib/plugins/commands/block/index.js:40:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)

install register success
`

**Comment by chenshuai2144** [comment]
你确定是最新的？

> 第二个错误是你的包问题。用 cnpm 安装

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4389
