### ISSUE TITLE
使用umi block add ant-design-pro/UserLogin报错，并附分析

### ISSUE THREAD

**Issue by zning1994** [ant-design/ant-design-pro#4534]
刚才在使用`umi block add ant-design-pro/UserLogin`的时候报错，报错信息如下：

```shell
➜    oeup06 umi block add ant-design-pro/UserLogin
✔ Parse url and args
✔ Git fetch
✔ Git checkout master
✔ Git pull
✖  error     AssertionError [ERR_ASSERTION]: /Users/ZNing/.umi/blocks/github.com/ant-design/pro-blocks/ant-design-pro/UserLogin don't exists
    at /Users/ZNing/OfflineProgramming/oeup06/node_modules/_umi-build-dev@1.9.6@umi-build-dev/lib/plugins/commands/block/index.js:141:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ZNing/OfflineProgramming/oeup06/node_modules/_umi-build-dev@1.9.6@umi-build-dev/lib/plugins/commands/block/index.js:40:103)
    at _next (/Users/ZNing/OfflineProgramming/oeup06/node_modules/_umi-build-dev@1.9.6@umi-build-dev/lib/plugins/commands/block/index.js:42:194)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

我发现好像这个功能在下载模块到本地之后，本地获取模块地址的时候有问题

```shell
➜  oeup06 cd /Users/ZNing/.umi/blocks/github.com/ant-design/pro-blocks/ant-design-pro/UserLogin
cd: no such file or directory: /Users/ZNing/.umi/blocks/github.com/ant-design/pro-blocks/ant-design-pro/UserLogin
➜  oeup06 cd /Users/ZNing/.umi/blocks/github.com/ant-design/pro-blocks/
➜  pro-blocks git:(master) ls
AccountCenter          Exception403           ListCardList           README.md              jsconfig.json
AccountSettings        Exception404           ListSearch             README.zh-CN.md        package.json
DashboardAnalysis      Exception500           ListSearchApplications ResultFail             tsconfig.json
DashboardMonitor       FormAdvancedForm       ListSearchArticles     ResultSuccess          typings.d.ts
DashboardWorkplace     FormBasicForm          ListSearchProjects     UserLogin
EditorFlow             FormStepForm           ListTableList          UserRegister
EditorKoni             LICENSE                ProfileAdvanced        UserRegisterResult
EditorMind             ListBasicList          ProfileBasic           _scripts
➜  pro-blocks git:(master) cd UserLogin
➜  UserLogin git:(master) ls
README.md    package.json snapshot.png src
➜  UserLogin git:(master) pwd
/Users/ZNing/.umi/blocks/github.com/ant-design/pro-blocks/UserLogin
```

如果没看错的话，本地路径在获取的时候，多加了一层`ant-design-pro`的路径，所以导致了`umi block add ant-design-pro/UserLogin`命令报错。

因为不知道怎么解决这个问题，故发上来提一个issue。

我的系统macOS，命令行工具是iterm 2，➜  标志是命令输入。

**Comment by zning1994** [comment]
后续：经过测试，使用`umi block add https://github.com/ant-design/pro-blocks/tree/master/UserLogin`可以正常安装。我发现在config.ts文件里面有个这个配置项：
```typescript
  block: {
    defaultGitUrl: 'https://github.com/ant-design/pro-blocks',
  }
```
是不是这个配置项有点小问题？麻烦大佬关注一下~

**Comment by chenshuai2144** [comment]
以官网为准

`umi block add UserLogin `

umi block add ant-design-pro/UserLogin  这个是比较旧的，会下载到 umi-blocks 里面的 js 区块中。

**Comment by zning1994** [comment]
> 以官网为准
> 
> `umi block add UserLogin `
> 
> `umi block add ant-design-pro/UserLogin` 这个是比较旧的，会下载到 umi-blocks 里面的 js 区块中。
> 
> ` defaultGitUrl: 'https://github.com/ant-design/pro-blocks',` 相当于前缀，会去这个 repo 里面去找

@chenshuai2144 好像官网现在的文档还没更新这种方式呀，还是block link……建议大佬尽早更新啦

**Comment by chenshuai2144** [comment]
我正在加。区块分散在好几个地方

**Comment by lovelock** [comment]
萌新入门, 看文档看的满头大包, 文档里写的东西在脚手架生成的代码里根本找不到...

**Comment by chenshuai2144** [comment]
@lovelock 能详细说一下嘛？

**Comment by lovelock** [comment]
@chengs 比如这里 https://pro.ant.design/docs/router-and-nav-cn
在v4版本里面启动后只有一个欢迎
![image](https://user-images.githubusercontent.com/2208731/60241526-155fa300-98e6-11e9-899d-8baaead20142.png)
这里改一下, 直接就挂了, 还怎么继续呀...现在看可能是文档没有跟上新版本. 像您在[知乎](https://zhuanlan.zhihu.com/p/67498559)说的, block这块是一个很大的改动, 我觉得文档应该首先介绍这里, 免得像我这样的一进来就受挫...🙏

**Comment by chenshuai2144** [comment]
@lovelock  这个没有说清楚，这只是个数据的 demo。新开个 issue 帮我记一下

**Comment by lovelock** [comment]
@chenshuai2144 [这里](https://github.com/ant-design/ant-design-pro/issues/4639)
