### ISSUE TITLE
npm start 报错 Plugin apply failed: Cannot read property 'ssr' of undefined

### ISSUE THREAD

**Issue by Tom-baby** [ant-design/ant-design-pro#4557]
Plugin apply failed: Cannot read property 'ssr' of undefined
✖  error     TypeError: Cannot read property 'ssr' of undefined
    at Array.api.modifyAFWebpackOpts (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/plugins/afwebpack-config/index.js:76:22)
    at register.opts (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/PluginAPI.js:144:57)
    at reduce (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/Service.js:216:16)
    at Array.reduce (<anonymous>)
    at Service.applyPlugins (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/Service.js:212:42)
    at _default (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-plugin-dll@1.5.0@umi-plugin-dll/lib/buildDll.js:51:29)
    at Promise (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-plugin-dll@1.5.0@umi-plugin-dll/lib/index.js:28:29)
    at new Promise (<anonymous>)
    at api.register (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-plugin-dll@1.5.0@umi-plugin-dll/lib/index.js:27:12)
    at /Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/Service.js:243:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/Service.js:42:103)
    at _next (/Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/Service.js:44:194)
    at /Users/wenzhous/tmp/react/my-project/dome/node_modules/_umi-build-dev@1.10.0@umi-build-dev/lib/Service.js:44:364
    at new Promise (<anonymous>)

**Comment by topwood** [comment]
应该是umi升级导致的

**Comment by Tom-baby** [comment]
问题已解决
package.json中 
"umi-plugin-react": "~1.8.4"

**Comment by Tom-baby** [comment]
> 问题已解决
> package.json中
> "umi-plugin-react": "~1.8.4"



> 应该是umi升级导致的

嗯 已经解决 谢谢🙏
