### ISSUE TITLE
安装带有依赖项的block失败

### ISSUE THREAD

**Issue by gisfinder** [ant-design/ant-design-pro#4574]
安装有依赖项的就会失败，如安装 monitor，就会失败，错误消息如下，日志记录见附件。
[2019-06-21T05_59_01_920Z-debug.log](https://github.com/ant-design/ant-design-pro/files/3313240/2019-06-21T05_59_01_920Z-debug.log)

D:\study\antdPV4>npx umi block add DashboardMonitor  --path=/dashboard/monitor
√ � Parse url and args
√ � Git fetch
√ � Git checkout master
√ � Git pull
× Install additional dependencies @types/lodash.debounce@^4.0.6,bizcharts@^3.5.3-beta.0,bizcharts-plugin-slider@^2.1.1-beta.1,lodash.debounce@^4.0.8,numeral@^2.0.6,react-fittext@^1.0.0,umi-plugin-block-dev@^1.0.0,mockjs@^1.0.1-beta3 with npm --registry https://registry.npm.taobao.org
×  error     Error: Error: Command failed: npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 umi-plugin-block-dev@^1.0.0 mockjs@^1.0.1-beta3 --registry=https://registry.npm.taobao.org --save
Unhandled rejection RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at D:\Program Files\nodejs\node_modules\npm\node_modules\aproba\index.js:38:16
    at Array.forEach (<anonymous>)
    at module.exports (D:\Program Files\nodejs\node_modules\npm\node_modules\aproba\index.js:33:11)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:37:3)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (D:\Program Files\nodejs\node_modules\npm\lib\install\flatten-tree.js:39:14)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chu.baohua\AppData\Roaming\npm-cache\_logs\2019-06-21T05_59_01_920Z-debug.log

    at D:\study\antdPV4\node_modules\_umi-build-dev@1.10.2@umi-build-dev\lib\plugins\commands\block\util.js:254:17
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\study\antdPV4\node_modules\_umi-build-dev@1.10.2@umi-build-dev\lib\plugins\commands\block\util.js:30:103)
    at _throw (D:\study\antdPV4\node_modules\_umi-build-dev@1.10.2@umi-build-dev\lib\plugins\commands\block\util.js:32:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by chenshuai2144** [comment]
block 默认会使用 npm，你安装是使用了 cnpm 吗？

**Comment by gisfinder** [comment]
是用cnpm安装的。

**Comment by gisfinder** [comment]
最近更新了一下umi的版本，看这个帖子：[https://github.com/ant-design/ant-design-pro/issues/4549](url)
上面说新版的umi可以自动选择registry项。于是更新了umi，查看umi的版本已经更新成功，版本为2.8.2然后重新创建pro项目，而创建项目里的package.json项中umi的版本还是2.7.2.

不知这个是否跟安装block不成功有关

**Comment by afc163** [comment]
![image](https://user-images.githubusercontent.com/507615/59912287-4fddc180-9448-11e9-8356-9ec036b7e2b2.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/4421

**Comment by afc163** [comment]
这是个大问题，`umi block add` 需要用用户使用的命令进行安装。

- cnpm
- npm
- yarn

**Comment by afc163** [comment]
tnpm 和 cnpm 就会出现这样的问题。

**Comment by chenshuai2144** [comment]
try use  https://umijs.org/zh/guide/umi-ui.html
