### ISSUE TITLE
npm run build报错，新增.webpackrc.js无法解决问题

### ISSUE THREAD

**Issue by wsdqr001** [ant-design/ant-design-pro#4599]
npm run build的时候报错，报错信息如下：

/app/work/git/turnover/virgo-web/node_modules/update-notifier/index.js:132
...options
^^^

SyntaxError: Unexpected token ...
at createScript (vm.js:74:10)
at Object.runInThisContext (vm.js:116:10)
at Module._compile (module.js:533:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object. (/app/work/git/turnover/virgo-web/node_modules/umi/lib/cli.js:27:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Virgo@2.3.1 build: umi build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Virgo@2.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

按照指引新增了.webpackrc.js，内容如下：
export default {
es5ImcompatibleVersions: true,
extraBabelIncludes: ['node_modules/update-notifier', 'node_modules/consola'],
};
仍然无法解决问题。

**Comment by wsdqr001** [comment]
求助大神 @sorrycc @afc163 @chenshuai2144 ，是否只能通过升级node版本解决呢？目前node版本v8.1.1。

**Comment by chenshuai2144** [comment]
update-notifier 你这个包是用来干什么的？

**Comment by wsdqr001** [comment]
> update-notifier

└─┬ umi@2.8.3
  └── update-notifier@3.0.0

umi默认安装的，我开发中没有手动安装。

**Comment by chenshuai2144** [comment]
那你升级到 node10 试试，umi 的测试都在 node10 上

**Comment by wsdqr001** [comment]
> 那你升级到 node10 试试，umi 的测试都在 node10 上

升级到V10已经可以了，谢谢啦
