### ISSUE TITLE
block安装失败

### ISSUE THREAD

**Issue by BinaryHao** [ant-design/ant-design-pro#4616]
PS C:\Users\HaoYanbing\Desktop\ant-design-pro> umi block add ant-design-pro/TableList
√ 😁 Parse url and args
√ 🚒 Git fetch
√ 🚪 Git checkout master
√ 🚀 Git pull
×  error     AssertionError [ERR_ASSERTION]: C:\Users\HaoYanbing\.umi\blocks\github.com\ant-design\pro-blocks\ant-design-pro\TableList don't exists
    at C:\Users\HaoYanbing\Desktop\ant-design-pro\node_modules\_umi-build-dev@1.10.4@umi-build-dev\lib\plugins\commands\block\index.js:145:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\HaoYanbing\Desktop\ant-design-pro\node_modules\_umi-build-dev@1.10.4@umi-build-dev\lib\plugins\commands\block\index.js:42:103)
    at _next (C:\Users\HaoYanbing\Desktop\ant-design-pro\node_modules\_umi-build-dev@1.10.4@umi-build-dev\lib\plugins\commands\block\index.js:44:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7216) UnhandledPromiseRejectionWarning: FetchError: request to https://registry.npmjs.org/ failed, reason: connect ETIMEDOUT 104.16.19.35:443
    at ClientRequest.<anonymous> (C:\Users\HaoYanbing\Desktop\ant-design-pro\node_modules\_node-fetch@2.6.0@node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chenshuai2144** [comment]
use `umi block add TableList`

具体看我们的官网
