### ISSUE TITLE
执行 npx umi block add DashboardAnalysis --path=/dashboard/analysis 报错

### ISSUE THREAD

**Issue by wencongNew** [ant-design/ant-design-pro#4663]
E:\projects>npx umi block add DashboardAnalysis --path=/dashboard/analysis
√ 😁  Parse url and args
√ 🚒 Git fetch
√ 🚪 Git checkout master
√ 🚀 Git pull
×  error     AssertionError [ERR_ASSERTION]: C:\Users\onlyedu\.umi\blocks\github.com\umijs\umi-blocks\DashboardAnalysis don 't exists
    at C:\Users\onlyedu\AppData\Roaming\npm-cache\_npx\4700\node_modules\umi\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:145:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\onlyedu\AppData\Roaming\npm-cache\_npx\4700\node_modules\umi\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:42:103)
    at _next (C:\Users\onlyedu\AppData\Roaming\npm-cache\_npx\4700\node_modules\umi\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:44:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by afc163** [comment]
请在 pro 项目根目录下做操作。

**Comment by chenshuai2144** [comment]
@wencongNew 可以先用 umi block 查看。

**Comment by afc163** [comment]
beter => better
