### ISSUE TITLE
umi  block 错误的缓存无法自动清理

### ISSUE THREAD

**Issue by xland** [ant-design/ant-design-pro#4664]
```
PS D:\project\ya_client> npx umi block add DashboardAnalysis --path=/dashboard/analysis
√ 😁  Parse url and args
√ 🚒 Git fetch
× 🚪 Git checkout master
×  error     Error: Error: Command failed: git checkout master
error: pathspec 'master' did not match any file(s) known to git


    at D:\project\ya_client\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:261:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\project\ya_client\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:39:103)
    at _throw (D:\project\ya_client\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:41:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by xland** [comment]
一旦某次add block超时，ctrl+c强行停止后，
以后就再也安装不成功了；

不知道是不是这样

**Comment by xland** [comment]
超级管理员下运行：

```
D:\project\yaui>npx umi block add DashboardAnalysis --path=/dashboard/analysis
√ 😁  Parse url and args
√ 🚒 Git fetch
× 🚪 Git checkout master
×  error     Error: Error: Command failed: git checkout master
error: pathspec 'master' did not match any file(s) known to git


    at D:\project\yaui\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:261:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\project\yaui\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:39:103)
    at _throw (D:\project\yaui\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:41:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)

D:\project\yaui>
```

**Comment by chenshuai2144** [comment]
这个看起来是 git 没找到。 我找个 window 重现一下。

**Comment by xland** [comment]
嗯！多谢！git在我的环境变量里的

**Comment by xland** [comment]
@chenshuai2144 
如果一时搞不定，我有没有办法手动下载相关的代码，放到我自己的目录下
多谢

**Comment by chenshuai2144** [comment]
应该是下载了一个不完整的 block 造成的。
block 会缓存你的下载。
在 node 中运行 `os.homedir()`，这个目录中有个.umi 的文件夹，删除这个文件夹重下载就好了

**Comment by tomsure** [comment]
> 
在 node 中运行 os.homedir()，这个目录中有个.umi 的文件夹，删除这个文件夹重下载就好了
> 
这一步怎么操作？
![image](https://user-images.githubusercontent.com/15616904/60391950-c22b6180-9b2c-11e9-9498-89f1ee86567b.png)

**Comment by xland** [comment]
@tomsure 

```
PS C:\Users\allen> node
> os.homedir()
'C:\\Users\\allen'
>
```

这不操作只是为了让你找到node的home目录

**Comment by tomsure** [comment]
确实是z找到.umi文件夹删掉就可以了,但是下一步时候又出现错误
![image](https://user-images.githubusercontent.com/15616904/60392249-58618680-9b31-11e9-84eb-eef9303e2666.png)

**Comment by xland** [comment]
cnpm 貌似是有问题的
