### ISSUE TITLE
 npm run start 错误 `UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions`

### ISSUE THREAD

**Issue by klionet** [ant-design/ant-design-pro#4754]
创建了新的ts v4项目后，安装完依赖后，执行 start 时出现错误提示，但没有影响编译。
提示信息
```
umi v2.8.9
nodejs v10.15.3
```

```> umi dev

  build [==                  ] 10%Starting the development server...

(node:17480) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\Users\bms\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\Users\bms\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\Users\bms\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\Users\bms\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\Users\bms\node_modules\readdirp\index.js:163:23)
(node:17480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17480) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\Users\bms\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\Users\bms\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\Users\bms\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\Users\bms\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\Users\bms\node_modules\readdirp\index.js:163:23)
(node:17480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17480) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\Users\bms\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\Users\bms\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\Users\bms\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\Users\bms\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\Users\bms\node_modules\readdirp\index.js:163:23)
(node:17480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:17480) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\Users\bms\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\Users\bms\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\Users\bms\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\Users\bms\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\Users\bms\node_modules\readdirp\index.js:163:23)
(node:17480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:17480) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\Users\bms\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\Users\bms\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\Users\bms\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\Users\bms\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\Users\bms\node_modules\readdirp\index.js:163:23)
(node:17480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:17480) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\Users\bms\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\Users\bms\node_modules\chokidar\index.js:191:16)
    at WatchHelper.wh.filterPath.entry [as filterPath] (C:\Users\bms\node_modules\chokidar\lib\nodefs-handler.js:524:38)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\Users\bms\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\Users\bms\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\Users\bms\node_modules\readdirp\index.js:163:23)
(node:17480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
  build [=================== ] 95%Extracted theme color css content length: 9569
Build completed in 20.304s

 DONE  Compiled successfully in 20316ms                                                                         21:40:32


  App running at:
  - Local:   http://localhost:8000/ (copied to clipboard)
  - Network: http://192.168.0.106:8000/

 WAIT  Compiling...                                                                                             21:40:33


  build [=================== ] 95%Extracted theme color css content length: 9569
Build completed in 0.808s

 DONE  Compiled successfully in 809ms```

是什么在报错呢？

**Comment by chenshuai2144** [comment]
有点神奇，在umi提个issue吧，这个不是用法问题。

**Comment by theprimone** [comment]
同样的问题，虽然不影响使用。。。有解决吗？

**Comment by wing324** [comment]
Same issue as here

**Comment by theprimone** [comment]
@wing324 删掉 node_modules 重装就好了
