### ISSUE TITLE
使用jenkins自动化部署，yarn install过程中大部分失败，不知是否能指点下

### ISSUE THREAD

**Issue by wuxin2014** [ant-design/ant-design-pro#4790]
![企业微信截图_6562c6e7-9df9-4d28-9a99-9d09b66d729a](https://user-images.githubusercontent.com/6781980/61038314-6354ca80-a3ff-11e9-8019-96d1a65db7bf.png)

**Comment by chenshuai2144** [comment]
你可以修改源变成淘宝源

**Comment by xoptimal** [comment]
淘宝源依旧有这个问题, 在V4环境下~  @chenshuai2144   能解决下问题吗,  翻墙也存在这个问题, 很紧急~ 发包发现这个问题, 能提供下解决方案吗

**Comment by xoptimal** [comment]
往往下载的包都存在问题~

本地调试也有问题: 
```
UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions

(node:10216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
```

**Comment by xoptimal** [comment]
```
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
18 verbose stack     at inflatableChild (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
18 verbose stack     at BB.each (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
18 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Object.gotValue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
18 verbose stack     at Object.gotAccum (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
18 verbose stack     at Object.tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
18 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
18 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
18 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
18 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
18 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
18 verbose stack     at runCallback (timers.js:705:18)
18 verbose stack     at tryOnImmediate (timers.js:676:5)
19 verbose cwd /data/jenkins/workspace/hr-dashboard-service-web
20 verbose Linux 3.10.0-514.el7.x86_64
21 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
22 verbose node v10.15.0
23 verbose npm  v6.4.1
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]
```

**Comment by xoptimal** [comment]
```
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@4.0.1" has unmet peer dependency "@typescript-eslint/parser@1.x".
warning "umi-plugin-react > umi-plugin-dva > dva@2.6.0-beta.6" has incorrect peer dependency "react@^16.18.4".
warning "umi-plugin-react > umi-plugin-dva > dva@2.6.0-beta.6" has incorrect peer dependency "react-dom@^16.18.4".
warning "umi-plugin-react > umi-plugin-dva > babel-plugin-dva-hmr@0.4.2" has unmet peer dependency "redbox-react@1.x".
warning "umi-plugin-react > umi-plugin-dva > dva-loading@3.0.6" has unmet peer dependency "dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0".
warning "umi-plugin-react > umi-plugin-dva > dva > connected-react-router@6.5.0" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning "@umijs/fabric > @typescript-eslint/eslint-plugin > tsutils@3.14.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev".
warning "@umijs/fabric > @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@1.11.0" has unmet peer dependency "typescript@*".
warning "@umijs/fabric > @typescript-eslint/parser > @typescript-eslint/experimental-utils@1.11.1-alpha.11" has unmet peer dependency "typescript@*".
warning " > jsdom-global@3.0.2" has unmet peer dependency "jsdom@>=10.0.0".
[5/5] Building fresh packages...
[-/7] ⠂ waiting...
[-/7] ⠂ waiting...
[-/7] ⠂ waiting...
[6/7] ⠄ puppeteer
[-/7] ⠄ waiting...
```

**Comment by xoptimal** [comment]
yarn registry 已经换成淘宝源了

**Comment by xoptimal** [comment]
package.json
```
{
  "name": "ant-design-pro",
  "version": "1.0.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "fetch:blocks": "node ./scripts/fetch-blocks.js",
    "format-imports": "import-sort --write '**/*.{js,jsx,ts,tsx}'",
    "lint": "npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "check-prettier lint",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "prettier": "prettier -c --write **/*",
    "start": "cross-env PORT=8093 umi dev",
    "start:no-mock": "cross-env MOCK=none umi dev",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint-staged"
    }
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write",
      "git add"
    ],
    "**/*.{js,jsx}": "npm run lint-staged:js",
    "**/*.{js,ts,tsx}": "npm run lint-staged:js"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/pro-layout": "^4.5.7",
    "@antv/data-set": "^0.10.2",
    "ant-design-pro": "^2.1.1",
    "antd": "^3.19.1",
    "classnames": "^2.2.6",
    "dva": "^2.4.1",
    "jsencrypt": "^2.3.1",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.1",
    "memoize-one": "^5.0.4",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "^3.0.0",
    "prop-types": "^15.7.2",
    "qs": "^6.7.0",
    "query-string": "^6.0.0",
    "rc-animate": "^2.8.3",
    "react": "^16.8.6",
    "react-container-query": "^0.11.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.8.6",
    "react-media": "^1.9.2",
    "react-media-hook2": "^1.0.5",
    "redux": "^4.0.1",
    "umi": "^2.7.2",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-pro-block": "^1.3.2",
    "umi-plugin-react": "^1.8.2",
    "umi-request": "^1.0.7"
  },
  "devDependencies": {
    "@ant-design/colors": "^3.1.0",
    "@types/classnames": "^2.2.7",
    "@types/history": "^4.7.2",
    "@types/jest": "^24.0.13",
    "@types/lodash": "^4.14.133",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.8.19",
    "@types/react-document-title": "^2.0.3",
    "@types/react-dom": "^16.8.4",
    "@umijs/fabric": "^1.0.4",
    "babel-eslint": "^10.0.1",
    "chalk": "^2.4.2",
    "check-prettier": "^1.0.3",
    "cross-env": "^5.2.0",
    "cross-port-killer": "^1.1.1",
    "enzyme": "^3.9.0",
    "eslint": "^5.16.0",
    "gh-pages": "^2.0.1",
    "husky": "^2.3.0",
    "import-sort-cli": "^6.0.0",
    "import-sort-parser-babylon": "^6.0.0",
    "import-sort-parser-typescript": "^6.0.0",
    "import-sort-style-module": "^6.0.0",
    "jest-puppeteer": "^4.2.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^8.1.7",
    "mockjs": "^1.0.1-beta3",
    "node-fetch": "^2.6.0",
    "prettier": "^1.17.1",
    "slash2": "^2.0.0",
    "stylelint": "^10.1.0",
    "umi-types": "^0.3.8",
    "webpack-theme-color-replacer": "^1.1.5"
  },
  "optionalDependencies": {
    "puppeteer": "^1.17.0"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "checkFiles": [
    "src/**/*.js*",
    "src/**/*.ts*",
    "src/**/*.less",
    "config/**/*.js*",
    "scripts/**/*.js"
  ]
}

```

**Comment by xoptimal** [comment]
@chenshuai2144  大哥你能抽空协助下吗,  发着包 , 阻塞了现在 TAT

**Comment by chenshuai2144** [comment]
puppeteer 可以配置国内源？你们的 服务器是固定的吗？

**Comment by Master-H** [comment]
有人解决这个问题了吗
