### ISSUE TITLE
使用jenkins自动化部署，install 异常

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-pro#4798]
错误信息:
```
+ npm install
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-12T11_04_17_223Z-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
log: 
```
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
18 verbose stack     at inflatableChild (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
18 verbose stack     at BB.each (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
18 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Object.gotValue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
18 verbose stack     at Object.gotAccum (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
18 verbose stack     at Object.tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
18 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
18 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
18 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
18 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
18 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
18 verbose stack     at runCallback (timers.js:705:18)
18 verbose stack     at tryOnImmediate (timers.js:676:5)
19 verbose cwd /data/jenkins/workspace/web
20 verbose Linux 3.10.0-514.el7.x86_64
21 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
22 verbose node v10.15.0
23 verbose npm  v6.4.1
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]
```

已经换成淘宝镜像源,  打包直接报错~
PRO版本: v4.0

**Comment by chenshuai2144** [comment]
看起来是npm版本的问题。试着用yarn呢
