### ISSUE TITLE
npm run i18n-remove报错

### ISSUE THREAD

**Issue by onek12** [ant-design/ant-design-pro#4856]
按文档里面
`$ yarn create  umi`
`>ant-design-pro   && > js`
然后add pages
`$ npm run fetch:blocks`

什么都没改，接着就打算删除国际化部分code
`$ npm run i18n-remove`
嗯。。 错误如下

`
D:\work\ant\ant-admin-new>npm run i18n-remove

 ant-design-pro@1.0.0 i18n-remove D:\work\ant\ant-admin-new
 pro i18n-remove --locale=zh-CN --write

√ �️‍  find js or ts files
- �  load all locale file and build ts D:\work\ant\ant-admin-new\src\locales\zh-CN.js:1
import component from './zh-CN/component';
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at module.exports (D:\work\ant\ant-admin-new\node_modules\@ant-design\pro-cli\node_modules\import-fresh\index.js:28:9)
    at D:\work\ant\ant-admin-new\node_modules\@ant-design\pro-cli\src\i18n\getLocalFileList.js:57:14
    at Array.map (<anonymous>)
    at module.exports (D:\work\ant\ant-admin-new\node_modules\@ant-design\pro-cli\src\i18n\getLocalFileList.js:53:6)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.0.0 i18n-remove: `pro i18n-remove --locale=zh-CN --write`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.0.0 i18n-remove script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\work\apps\nodejs\node_cache\_logs\2019-07-20T06_48_22_142Z-debug.log
`
求正确去除国际化的姿势.....（手动删除替换文案是不可能的...）

**Comment by onek12** [comment]
TS的没问题..  刚试了下。   js版的会有上述问题。

大神呢？  来大神拯救下迷茫的萌新吧 。

**Comment by chenshuai2144** [comment]
js 的支持没弄好。
你可以先用 ts 然后转换成 js

**Comment by afc163** [comment]
@chenshuai2144 你应该先加个提示。
