### ISSUE TITLE
今天安装antd.pro又出现严重问题

### ISSUE THREAD

**Issue by tgy3300** [ant-design/ant-design-pro#4863]
`? Select the boilerplate type (Use arrow keys)
> ant-design-pro  - Create project with a layout-only ant-design-pro boilerplate
? Select the boilerplate type ant-design-pro
> Generate failed { Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Local\Yarn\Data\global
\node_modules\umi-utils\lib\getFastGithub.js:8:41)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) code: 'MODUL
E_NOT_FOUND' }
error Command failed.
Exit code: 1
Command: C:\Users\Administrator\AppData\Local\Yarn\bin\create-umi
Arguments: zl-pro-antd-project-190724
Directory: F:\mywwwroot\centoswww\app
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this c
ommand.`

**Comment by tgy3300** [comment]
问题重现步骤
1、运行：yarn create umi zl-pro-antd-project-190725
2、选择 ant-design-pro 回车
3、就出现 Generate failed { Error: Cannot find module 'node-fetch' 的错误

**Comment by yuelei1995** [comment]
我也是，今天怎么也加载不了，一直是node-fetch ，尝试过很多方法，都不可以

**Comment by tgy3300** [comment]
@chenshuai2144

**Comment by Redspitee** [comment]
全局安装一下 node-fetch： npm install node-fetch -g，系统已经提示了你没这个模块

**Comment by yuelei1995** [comment]
> 全局安装一下 node-fetch： npm install node-fetch -g，系统已经提示了你没这个模块

试过了 还是会提示

**Comment by Tim1023** [comment]
same issue

**Comment by wang125309** [comment]
我也碰到，怎么办

**Comment by undefinedor** [comment]
一样问题。。
```shell
? Select the boilerplate type ant-design-pro
> Generate failed { Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/wang/.npm/_npx/76521/lib/node_modules/create-umi/node_modules/umi-utils/lib/getFastGithub.js:8:41)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by BenlovedLamphere** [comment]
我也遇到这个问题，不知道可有办法解决

**Comment by hovenjay** [comment]
我也是遇到这个问题，全局安装了提示中的组件之后，仍然提示找不到模块。

**Comment by sorrycc** [comment]
修复了。

**Comment by tgy3300** [comment]
@sorrycc ,,没有呀，还是有问题，我重新安装了umi，再安装antd.pro  ，同样的问题还是存在

**Comment by hovenjay** [comment]
> 修复了。
@sorrycc 更新了 umi 版本后，依旧报错的。
```
? Select the boilerplate type ant-design-pro
? Which language do you want to use? JavaScript
> git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> [Sylvanas] Prepare js environment...
> [JS] Clean up...
> Clean up...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, unlink 'D:\WorkSpace\op-frontend\.git\objects\pack\tmp_pack_Md9Vca'
    at Object.unlinkSync (fs.js:956:3)
    at rimrafSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:254:15)
    at options.readdirSync.forEach.f (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at rimrafSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at options.readdirSync.forEach.f (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by BenlovedLamphere** [comment]
> > 修复了。
> > @sorrycc 更新了 umi 版本后，依旧报错的。
> 
> ```
> ? Select the boilerplate type ant-design-pro
> ? Which language do you want to use? JavaScript
> > git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> > [Sylvanas] Prepare js environment...
> > [JS] Clean up...
> > Clean up...
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EBUSY: resource busy or locked, unlink 'D:\WorkSpace\op-frontend\.git\objects\pack\tmp_pack_Md9Vca'
>     at Object.unlinkSync (fs.js:956:3)
>     at rimrafSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:254:15)
>     at options.readdirSync.forEach.f (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
>     at Array.forEach (<anonymous>)
>     at rmkidsSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
>     at rmdirSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
>     at rimrafSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
>     at options.readdirSync.forEach.f (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
>     at Array.forEach (<anonymous>)
>     at rmkidsSync (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
> Emitted 'error' event at:
>     at Immediate.setImmediate (C:\Users\Jason\AppData\Roaming\npm\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:436:22)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> ```

我修复后倒是不报错了，就是安装　Rigster和Login怎么都装不上，不是找不到block　路径就是找不到　package.json，放弃了，回去用2.3了.......

**Comment by hovenjay** [comment]
> 我修复后倒是不报错了，就是安装　Rigster和Login怎么都装不上，不是找不到block　路径就是找不到　package.json，放弃了，回去用2.3了.......

@BenlovedLamphere 你试试在 `npm create umi` 命令执行完成之后，再执行 `npm install` ，然后再添加示例代码进来。

**Comment by John-Yue** [comment]
还是有问题，升级了umi，还是不能安装
`Select the boilerplate type ant-design-pro
> Generate failed { Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/john-yue/.config/yarn/global/node_modules/create-umi/node_modules/umi-utils/lib/getFastGithub.js:8:41)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3) code: 'MODULE_NOT_FOUND' }`

**Comment by John-Yue** [comment]
> 还是有问题，升级了umi，还是不能安装
> 
> > Select the boilerplate type ant-design-pro
> > Generate failed { Error: Cannot find module 'node-fetch'
> > at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
> > at Function.Module._load (internal/modules/cjs/loader.js:575:25)
> > at Module.require (internal/modules/cjs/loader.js:705:19)
> > at require (internal/modules/cjs/helpers.js:14:16)
> > at Object. (/Users/john-yue/.config/yarn/global/node_modules/create-umi/node_modules/umi-utils/lib/getFastGithub.js:8:41)
> > at Module._compile (internal/modules/cjs/loader.js:799:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
> > at Module.load (internal/modules/cjs/loader.js:666:32)
> > at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
> > at Function.Module._load (internal/modules/cjs/loader.js:598:3) code: 'MODULE_NOT_FOUND' }`

更新到最新版本好了...

**Comment by tgy3300** [comment]
> > 还是有问题，升级了umi，还是不能安装
> > > Select the boilerplate type ant-design-pro
> > > Generate failed { Error: Cannot find module 'node-fetch'
> > > at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
> > > at Function.Module._load (internal/modules/cjs/loader.js:575:25)
> > > at Module.require (internal/modules/cjs/loader.js:705:19)
> > > at require (internal/modules/cjs/helpers.js:14:16)
> > > at Object. (/Users/john-yue/.config/yarn/global/node_modules/create-umi/node_modules/umi-utils/lib/getFastGithub.js:8:41)
> > > at Module._compile (internal/modules/cjs/loader.js:799:30)
> > > at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
> > > at Module.load (internal/modules/cjs/loader.js:666:32)
> > > at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
> > > at Function.Module._load (internal/modules/cjs/loader.js:598:3) code: 'MODULE_NOT_FOUND' }`
> 
> 更新到最新版本好了...

更新什么到最新版本，，我cnpm install -g umi到最新了，还是不行

**Comment by tgy3300** [comment]
@chenshuai2144 ，，

问题重现步骤
1、运行：yarn create umi zl-pro-antd-project-190725
2、选择 ant-design-pro 回车
3、就出现 Generate failed { Error: Cannot find module 'node-fetch' 的错误

**Comment by qiangyongjun918** [comment]
同样有问题

**Comment by chenshuai2144** [comment]
@qiangyongjun918  试试用 yarn create umi
