### ISSUE TITLE
v4版本按照官网整合v2版本的区块报错如下，求大佬解答

### ISSUE THREAD

**Issue by jsonq666** [ant-design/ant-design-pro#4896]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\Desktop\Ant Design Pro\umi\node_modules\@ant-design\pro-cli\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.0.0 fetch:blocks: `pro fetch-blocks`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.0.0 fetch:blocks script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-07-24T06_53_03_768Z-debug.log

**Comment by chenshuai2144** [comment]
你的安装依赖可额能有点问题。
Ant Design Pro 竟然包含空格
