### ISSUE TITLE
移出国际化模块报错

### ISSUE THREAD

**Issue by perany** [ant-design/ant-design-pro#4914]
使用npm create umi新建的js项目，执行npm run i18n-remove报错。
```
$ npm run i18n-remove

> ant-design-pro@1.0.0 i18n-remove /Users/work/workspace/temp/test-js
> pro i18n-remove --locale=zh-CN --write

✔ 🕵️‍  find js or ts files
⠋ 📦  load all locale file and build ts /Users/work/workspace/temp/test-js/src/locales/zh-CN.js:1
(function (exports, require, module, __filename, __dirname) { import component from './zh-CN/component';
                                                                     ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.0.0 i18n-remove: `pro i18n-remove --locale=zh-CN --write`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@1.0.0 i18n-remove script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pengyl/.npm/_logs/2019-07-25T07_23_43_535Z-debug.log
```

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4856
请尽量不要使用 js
