### ISSUE TITLE
npm run fetch:blocks 报错：command not found

### ISSUE THREAD

**Issue by hyb851005** [ant-design/ant-design-pro#5003]
cmd:
   'umi block add https://github.com/ant-design/pro-blocks/tree/master/UserLogin --path=/user/login --js' }
{ Error: Command failed: umi block add https://github.com/ant-design/pro-blocks/tree/master/UserLogin --path=/user/login --js
/bin/sh: umi: command not found

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)

**Comment by chenshuai2144** [comment]
你没有安装依赖，就直接使用  fetch:blocks？

**Comment by reallyzhang** [comment]
一是使用cnpm块一些，二是先cnpm i 一下，pro-cli在dev依赖库中
