### ISSUE TITLE
puppeteer command failed

### ISSUE THREAD

**Issue by Xeelong** [ant-design/ant-design-pro#5046]
+ 安装依赖出现如下问题：

`
error E:\Demo\ant-design-pro\node_modules\puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: E:\Demo\ant-design-pro\node_modules\puppeteer
Output:
ERROR: Failed to download Chromium r674921! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (E:\Demo\ant-design-pro\node_modules\puppeteer\lib\helper.js:111:15)
    at Object.<anonymous> (E:\Demo\ant-design-pro\node_modules\puppeteer\install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

找了很久没有头绪，按照文档一步一步操作还是这样。

**Comment by huntdream** [comment]
puppeteer下载Chromium驱动失败了，科学上网，或者去掉puppeteer的依赖，正常开发不需要这个库，写测试的时候可能会需要用到

**Comment by Xeelong** [comment]
> puppeteer下载Chromium驱动失败了，科学上网，或者去掉puppeteer的依赖，正常开发不需要这个库，写测试的时候可能会需要用到

万分感谢，问题解决了。但是去掉optionalDependencies下的puppeteer依赖，甚至是去掉jest-puppeteer依赖，并没有解决以上问题。但是不知道为什么直接clone github上的代码再使用科学上网安装依赖就没问题了。

**Comment by huntdream** [comment]
试了一下，去掉两个依赖确实没有用。但是项目跑起来是没有问题的

**Comment by chenshuai2144** [comment]
大家用的有点少，主要用于测试和截图，我移动到 optionaldependencies  好了

**Comment by afc163** [comment]
移动到 optionalDependencies 其实没什么卵用。
