### ISSUE TITLE
新建项目 选择如下 JavaScript会抛出异常

### ISSUE THREAD

**Issue by chujc** [ant-design/ant-design-pro#5153]
```
? Select the boilerplate type ant-design-pro
? Which language do you want to use? JavaScript
> git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> [Sylvanas] Prepare js environment...
events.js:180
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (28:1):

  26 | }
  27 |
> 28 | @connect(({ login, loading }: ConnectState) => ({
     | ^
  29 |   userLogin: login,
  30 |   submitting: loading.effects['login/login'],
  31 | }))
    at Object.raise (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:6344:17)
    at Object.expectOnePlugin (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:7674:18)
    at Object.parseDecorator (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9970:10)
    at Object.parseDecorators (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9952:30)
    at Object.parseStatement (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9785:12)
    at Object.parseBlockOrModuleBlockBody (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10364:25)
    at Object.parseBlockBody (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10351:10)
    at Object.parseTopLevel (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9717:10)
    at Object.parse (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:11233:17)
    at parse (/Users/john/.config/yarn/global/node_modules/@babel/parser/lib/index.js:11269:38)
Emitted 'error' event at:
    at Immediate.<anonymous> (/Users/john/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:436:22)
    at processImmediate (internal/timers.js:439:21) {
  pos: 855,
  loc: Position { line: 28, column: 0 },
  missingPlugin: [ 'decorators-legacy', 'decorators' ],
  code: 'BABEL_PARSE_ERROR'
}
```
选择JavaScript抛出异常如上， ts文件并未替换为js文件 但可以npm start 正常运行

**Comment by chenshuai2144** [comment]
看起来是一个插件失效了。
@zombieJ

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/63676675-0cc01600-c81e-11e9-9c5b-6d0adaf72a42.png)
我这里无法重现

**Comment by chujc** [comment]
> ![图片](https://user-images.githubusercontent.com/11746742/63676675-0cc01600-c81e-11e9-9c5b-6d0adaf72a42.png)
> 我这里无法重现

我在另外一台机器测试也是可行的，可能是这台机器环境问题导致的

**Comment by chujc** [comment]
> > ![图片](https://user-images.githubusercontent.com/11746742/63676675-0cc01600-c81e-11e9-9c5b-6d0adaf72a42.png)
> > 我这里无法重现
> 
> 我在另外一台机器测试也是可行的，可能是这台机器环境问题导致的

抱歉没有详细测试就上传了，我找到出现这类问题的解决方法了，就是根据提示的文件路径 删除对应路径的缓存文件 我使用的是mac os 只需要根据提示删除/Users/john/.config/yarn 文件就可以了，我估计是umi的版本问题导致的
