### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by liushouqian** [ant-design/ant-design-pro#5221]
git clone https://github.com/ant-design/ant-design-pro --depth=1 C:\ProgramData\Niagara4.6\vykon\stations\EasyIBMSDemo\shared
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at notFoundError (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\14276\node_modules\create-umi\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\14276\node_modules\create-umi\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\14276\node_modules\create-umi\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\14276\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by swdcode** [comment]
me too

**Comment by swdcode** [comment]
win10的问题吧 我用win7的下下来了

**Comment by liushouqian** [comment]
> me too



> win10的问题吧 我用win7的下下来了

我是win10用的vscode里面的终端，是这个结果。然后用CMD就成功的下下来了。但是我同事用他的电脑出现了另一个问题。。

**Comment by wshuai222333** [comment]
我也是这个问题  有的新的解决方案吗
