### ISSUE TITLE
下载sudo umi block add EditorKoni

### ISSUE THREAD

**Issue by dundishi** [ant-design/ant-design-pro#5287]
sudo umi block add EditorKoni报错
 AssertionError [ERR_ASSERTION]: /Users/xs01/.umi/blocks/github.com/umijs/umi-blocks/EditorKoni don't exists 
    at /usr/local/share/.config/yarn/global/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:165:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/local/share/.config/yarn/global/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:46:103)
    at _next (/usr/local/share/.config/yarn/global/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:48:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by chenshuai2144** [comment]
先执行 一下 `umi block clear`
