### ISSUE TITLE
[BUG]执行 yarn i18n-remove 出现“编译错误”

### ISSUE THREAD

**Issue by tomgao365** [ant-design/ant-design-pro#5354]
**bug 描述** 
下载最新的 pro ，js 版或 ts 版，执行 `yarn i18n-remove` ，都会抛出编译错误的异常。
错误如下：
```bash
✔ 🕵️‍  find js or ts files
⠋ 📦  load all locale file and build ts /Users/tom/web/antd-pro-ts/node_modules/@types/react-redux/index.d.ts (92,85): Namespace '"/Users/tom/web/antd-pro-ts/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.
/Users/tom/web/antd-pro-ts/node_modules/@types/react-redux/index.d.ts (92,85): Namespace '"/Users/tom/web/antd-pro-ts/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.
/Users/tom/web/antd-pro-ts/node_modules/node-import-ts/lib/index.js:28
        throw new Error("编译失败");
        ^

Error: 编译失败
    at module.exports (/Users/tom/web/antd-pro-ts/node_modules/node-import-ts/lib/index.js:28:15)
    at arrayList.map.filePath (/Users/tom/web/antd-pro-ts/node_modules/@ant-design/pro-cli/src/i18n/getLocalFileList.js:52:22)
    at Array.map (<anonymous>)
    at module.exports (/Users/tom/web/antd-pro-ts/node_modules/@ant-design/pro-cli/src/i18n/getLocalFileList.js:52:6)
    at module.exports (/Users/tom/web/antd-pro-ts/node_modules/@ant-design/pro-cli/src/i18n/index.js:47:21)
    at Object.<anonymous> (/Users/tom/web/antd-pro-ts/node_modules/@ant-design/pro-cli/cli.js:36:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
error Command failed with exit code 1.

```

**复现步骤** 
直接执行 `yarn i18n-remove`

**期望结果** 
移除国际化

**复现代码**

**版本信息:**

- Ant Design Pro 版本: 4.0.0
- umi 版本
- 浏览器环境
- 开发环境 [MacOS 10.14.6 & Windows 10]

**Comment by tomgao365** [comment]
应该是 umi-types 依赖升级造成的，之前的`^0.3.8` 正常，最新的 `^0.4.1` 失败

**Comment by gaorubin1990** [comment]
这么久了这个问题有进展不，最新版的依然报错

**Comment by tomgao365** [comment]
@gaorubin1990 木有，我是改成 0.38 解决的

**Comment by gaorubin1990** [comment]
> @gaorubin1990 木有，我是改成 0.38 解决的

只需要把这一个包降成0.3.8就可以吗？会不会引起其他问题

**Comment by chenshuai2144** [comment]
fixed in https://github.com/chenshuai2144/node-require-ts/commit/154510ac515a9b960fef3f0cc52acb546545519a
