### ISSUE TITLE
安装区块 [ListBasicList] 报错, 代码安装了还未做过任何改动

### ISSUE THREAD

**Issue by medivh-jay** [ant-design/ant-design-pro#5389]
**bug 描述** [详细地描述 bug，让大家都能理解]
使用 npm umi block list 获取区块列表然后选择 ListBasicList 区块之后安装，其中询问是否需要把ts转为js的时候选择了y, 然后转,转不成功, 报 SyntaxError: unknown: Identifier 'List' has already been declared
**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
创建一个目录并在终端执行yarn create umi
选择 ant design pro 安装 ant-design-pro 基本框架
安装成功之后，在目录下执行 npm umi block list
在终端输出列表中选择 ListBasicList
输出安装区块路径不输入直接回车
将 Typescript 区块转为 js? (y/N)  输入 y 回车
删除 i18n 代码? (y/N) 输入 n 回车
等待执行结果,出错, 整个过程如下
```bash
▶ npx umi block list
✔ 🚣  fetch block list
✔ 🔍  find block list form https://github.com/ant-design/pro-blocks
? ⛰  请选择区块（共 30 个 ) 📦  ListBasicList  预览 (https://preview.pro.ant.design/list/basic/list)
? 🏗  请输入输出安装区块的路径 
? 🤔  将 Typescript 区块转化为 js? Yes
? 🌎  删除 i18n 代码?  No
✔ 😁  Parse url and args
✔ 🚒  Git fetch
✔ 🚛  Git checkout master
✔ 🚀  Git pull
  📦  install dependencies package
  🔥  Generate files
   create src/pages/list/basic/list/_mock.ts
   create src/pages/list/basic/list/data.d.ts
   create src/pages/list/basic/list/index.tsx
   create src/pages/list/basic/list/model.ts
   create src/pages/list/basic/list/service.ts
   create src/pages/list/basic/list/style.less
   create src/pages/list/basic/list/utils/utils.less
✔ 🔥  Generate files
⠋ 🤔  TypeScript to JavaScript✖  error     SyntaxError: unknown: Identifier 'List' has already been declared (62:6) 

  60 |   }),
  61 | )
> 62 | class List extends Component<
     |       ^
  63 |   ListProps,
  64 |   ListState
  65 | > {
    at Object.raise (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:6414:17)
    at TypeScriptScopeHandler.checkRedeclarationInScope (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:3770:12)
    at TypeScriptScopeHandler.declareName (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:3736:12)
    at TypeScriptScopeHandler.declareName (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:3846:11)
    at Object.checkLVal (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:8147:22)
    at Object.checkLVal (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:5745:15)
    at Object.parseClassId (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:11013:14)
    at Object.parseClassId (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:5526:11)
    at Object.parseClass (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:10730:10)
    at Object.parseStatementContent (/Users/snqu/Downloads/github.com/starter-admin/node_modules/@babel/parser/lib/index.js:10026:21)
⠏ 🤔  TypeScript to JavaScript
```

**期望结果** [描述你原本期望看到的结果]
成功安装 ListBasicList 区块
**复现代码** [提供可复现的代码，仓库，或线上示例]
```bash
mkdir ant-design-pro
cd ant-design-pro
yarn create umi
// 选择 ant-design-pro
npm install
npm start
// 新建终端
npx umi block list
// 选择 ListBasicList 区块
```

**版本信息:**

- umi 版本 2.9.6
- 浏览器环境 最新Chrome
- 开发环境 [e.g. mac OS]
- npm 版本 6.11.3
- node 版本 12.11.1
- yarn 版本 1.19.1

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
> 请输入输出安装区块的路径

这个名字输入一下试试呢，我在本地无法测试

**Comment by medivh-jay** [comment]
> > 请输入输出安装区块的路径
> 
> 这个名字输入一下试试呢，我在本地无法再现

大概是这样的，就是我不输入名字用默认的就会有这个问题，已经不知道啥地方已经有一个 List 了，不过只要我输入另外的名字，那就不会冲突了，因为不输入名字时默认class名字就是 List

**Comment by chenshuai2144** [comment]
> 不输入名字时默认class名字就是 List

这是个 bug

**Comment by baymaxbowen** [comment]
import中会有一个List 然后这个组件的名称也是List，需要将组件的名称改一下（别忘记还有最后一行的组件名）

**Comment by chenshuai2144** [comment]
@baymaxbowen  试试 umi ui，体验更好

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/2871 同一个问题

**Comment by chenshuai2144** [comment]
在 umi 中跟踪吧
