### ISSUE TITLE
关于npx react-codemod rename-unsafe-lifecycles修改三个周期名称失败的问题。

### ISSUE THREAD

**Issue by lyylovelife** [ant-design/ant-design-pro#5457]
**问题描述** [关于npx react-codemod rename-unsafe-lifecycles修改三个周期名称失败的问题。]
componentWillMount → UNSAFE_componentWillMount
componentWillReceiveProps → UNSAFE_componentWillReceiveProps
componentWillUpdate → UNSAFE_componentWillUpdate

**示例代码** 
在项目文件夹下执行npx react-codemod rename-unsafe-lifecycles会出现下面一些错误信息：

TypeError: Cannot read property 'process' of undefined
    at process (C:\Users\yy\AppData\Roaming\npm-cache\_npx\16076\node_modules\react-codemod\node_modules\flow-parser/flow_parser.js:308:70)
    at Object.<anonymous> (C:\Users\yy\AppData\Roaming\npm-cache\_npx\16076\node_modules\react-codemod\node_modules\flow-parser/flow_parser.js:2:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (C:\Users\yy\AppData\Roaming\npm-cache\_npx\16076\node_modules\react-codemod\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (C:\Users\yy\AppData\Roaming\npm-cache\_npx\16076\node_modules\react-codemod\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
All done.
Results:
367 errors
0 unmodified
0 skipped
0 ok

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
rename-unsafe-lifecycles 这些东西都是 node modules 中，你修改不掉的。

之所以报错是因为我们依赖的第三方包没有更新完成。
