### ISSUE TITLE
[问题]  Loading chunk 4 failed.

### ISSUE THREAD

**Issue by HSdiana** [ant-design/ant-design-pro#5459]
**问题描述** [详细地描述问题，让大家都能理解]
本地运行不报错，线上部署之后，切换页面就报错

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]
umi.55283c0e.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 4 failed.
(missing: http://teacher.dev.homeworkdone.cn/4.c5f9a789.async.js)
    at Function.i.e (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:2177)
    at component (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:1478737)
    at y.resolve (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:150859)
    at r.value (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:150396)
    at new r (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:150201)
    at La (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:1852230)
    at Zi (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:1868280)
    at vu (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:1906514)
    at Lu (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:1891274)
    at Fu (http://teacher.dev.homeworkdone.cn/umi.55283c0e.js:1:1891199)

**Comment by chenshuai2144** [comment]
你需要清空一下缓存了，umi.js 和这些 chunk是一一对应的。可能你的umijs是比较旧的版本。

**Comment by chenshuai2144** [comment]
umijs/umi#1421 (comment)
也试试这个

**Comment by HSdiana** [comment]
> [umijs/umi#1421](https://github.com/umijs/umi/issues/1421) (comment)
> 也试试这个

后端配置了https之后好了，怀疑是被墙了
