### ISSUE TITLE
npx umi block add xxxx添加区块以及 npx umi block list预览区块不成功

### ISSUE THREAD

**Issue by xishanxu** [ant-design/ant-design-pro#5471]
**问题描述** [问题如题]

**示例代码** [ 前面是warn  后面开始报错
npm ERR! path /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/.bin/parser
npm ERR! code EEXIST
npm ERR! Refusing to delete /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/.bin/parser: containing path /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/@babel/parser isn't under npm's control
npm ERR! File exists: /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/umi-build-dev/node_modules/@babel/traverse/node_modules/.bin/parser
npm ERR! Move it away, and try again.
npm timing npm Completed in 46669ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2019-10-23T06_05_27_109Z-debug.log

> husky@3.0.9 preuninstall /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_husky@3.0.9@husky
> node husky uninstall

husky > Uninstalling git hooks
Command failed: git rev-parse --show-toplevel --git-common-dir
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to uninstall

    at /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/installDependencies.js:201:15
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/installDependencies.js:72:103)
    at _throw (/Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/installDependencies.js:74:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
]

**其他信息** [系统 macOS ， node版本：v10.16.2，npm版本6.9.0]
  怎么解决呢？  使用过cnpm yarn 以及npm 都不成功

**Comment by chenshuai2144** [comment]
执行一下 umi block clean hao'le

**Comment by xishanxu** [comment]
error     Error: Please run umi help block to checkout the usage
    at /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:104:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:62:103)
    at _next (/Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:64:194)
    at /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:64:364
    at new Promise (<anonymous>)
    at /Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:64:97
    at _block (/Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:109:19)
    at block (/Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:79:19)
    at api.registerCommand (/Users/apple/Desktop/xishanxu/umiStudy/antd-pro/create/node_modules/_umi-build-dev@1.13.13@umi-build-dev/lib/plugins/commands/block/index.js:157:12)  







又报错了  执行这一句




------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 下午4:48
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "self"<825983767@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] npx umi block add xxxx添加区块以及 npx umi block list预览区块不成功 (#5471)




执行一下 umi block clean hao'le

**Comment by chenshuai2144** [comment]
参数写错了。用 umi 吧。或者用 umi block list
