### ISSUE TITLE
启动项目报错：SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by summerinsect** [ant-design/ant-design-pro#5491]
### 🧐 问题描述

项目创建安装以后，npm start  或者  yarn start
都启动失败

```
> ant-design-pro@1.0.0 start /Users/admin/Documents/MyWorkspace/2019/fbs-admin
> umi dev

(node:34525) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Config.load (/Users/admin/Documents/MyWorkspace/2019/fbs-admin/node_modules/umi-ui/lib/Config.js:113:24)
    at new Config (/Users/admin/Documents/MyWorkspace/2019/fbs-admin/node_modules/umi-ui/lib/Config.js:108:10)
    at new UmiUI (/Users/admin/Documents/MyWorkspace/2019/fbs-admin/node_modules/umi-ui/lib/UmiUI.js:230:19)
    at /Users/admin/Documents/MyWorkspace/2019/fbs-admin/node_modules/umi/lib/scripts/dev.js:63:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/admin/Documents/MyWorkspace/2019/fbs-admin/node_modules/umi/lib/scripts/dev.js:49:103)
    at _next (/Users/admin/Documents/MyWorkspace/2019/fbs-admin/node_modules/umi/lib/scripts/dev.js:51:194)
    at /Users/admin/Documents/MyWorkspace/2019/fbs-admin/node_modules/umi/lib/scripts/dev.js:51:364
    at new Promise (<anonymous>)
(node:34525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34525) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### 🚑 其他信息

macos: 10.15
node: 10.15.0
npm: 6.4.1

![Screen Shot 2019-10-28 at 10 30 00 AM](https://user-images.githubusercontent.com/6075540/67647625-efb6d900-f96d-11e9-8b52-54c3a581d12b.png)

**Comment by summerinsect** [comment]
解决了
/Users/admin/.umi/ui/   下有两个文件 data.json 和 shared-data
都删除就可以启动了
