### ISSUE TITLE
怎么删除已安装的block 删除文件夹后报错

### ISSUE THREAD

**Issue by venlee1993** [ant-design/ant-design-pro#5492]
Error: Cannot find module 'E:\workspace\lazs_admin\src\pages\y'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at routes.reduce (E:\workspace\lazs_admin\node_modules\_umi-build-dev@1.13.13@umi-build-dev\lib\plugins\commands\block\ui\index.js:39:47)
    at Array.reduce (<anonymous>)
    at getRouteComponents (E:\workspace\lazs_admin\node_modules\_umi-build-dev@1.13.13@umi-build-dev\lib\plugins\commands\block\ui\index.js:37:19)
    at routes.reduce (E:\workspace\lazs_admin\node_modules\_umi-build-dev@1.13.13@umi-build-dev\lib\plugins\commands\block\ui\index.js:47:28)
    at Array.reduce (<anonymous>)
    at getRouteComponents (E:\workspace\lazs_admin\node_modules\_umi-build-dev@1.13.13@umi-build-dev\lib\plugins\commands\block\ui\index.js:37:19)
    at generateRouteComponents (E:\workspace\lazs_admin\node_modules\_umi-build-dev@1.13.13@umi-build-dev\lib\plugins\commands\block\ui\index.js:58:23)
    at Array.api.modifyAFWebpackOpts.memo (E:\workspace\lazs_admin\node_modules\_umi-build-dev@1.13.13@umi-build-dev\lib\plugins\commands\block\ui\index.js:68:7)
npm ERR! code ELIFECYCLE

**Comment by chenshuai2144** [comment]
他的引用和 config js 的依赖也要相应的删除，全局搜索一下

**Comment by deadash** [comment]
删除只能手动删除么？
