### ISSUE TITLE
🧐[问题]引入ts声明文件后，编译报错

### ISSUE THREAD

**Issue by LbhFront-end** [ant-design/ant-design-pro#5550]
### 🧐 问题描述

使用了阿里的 `pont` 根据后端的 swagger 自动生成对应的接口，里面有自动生成的 `api.d.ts`声明文件。
根据 `pont`作者的描述，想解决下面出现的问题
![image](https://user-images.githubusercontent.com/30042334/68185915-c89b7f80-ffdd-11e9-85d0-e53b56360fd4.png)
在 `SecurityLayout.tsx`引入了声明文件，但是编译报错
### 💻 示例代码
![image](https://user-images.githubusercontent.com/30042334/68185849-8d994c00-ffdd-11e9-8b0f-e192a449dee2.png)
**报错信息**
```shell
 error  in ./src/services/api.d.ts

Module build failed (from ./node_modules/_ts-loader@6.0.3@ts-loader/index.js):
Error: Debug Failure. Output generation failed
    at Object.transpileModule (F:\GitLab\M2B-TS\node_modules\_typescript@3.5.2@typescript\lib\typescript.js:109382:29)
    at getTranspilationEmit (F:\GitLab\M2B-TS\node_modules\_ts-loader@6.0.3@ts-loader\dist\index.js:283:74)
    at successLoader (F:\GitLab\M2B-TS\node_modules\_ts-loader@6.0.3@ts-loader\dist\index.js:66:15)
    at Object.loader (F:\GitLab\M2B-TS\node_modules\_ts-loader@6.0.3@ts-loader\dist\index.js:22:12)

 @ ./src/layouts/SecurityLayout.tsx 30:0-30
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/_af-webpack@1.11.7@af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```

### 🚑 其他信息

自动生成的文件夹
![image](https://user-images.githubusercontent.com/30042334/68186030-0e584800-ffde-11e9-914d-575f6a58c89c.png)
**tsconfig.json**
```json
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "esnext",
    "lib": [
      "esnext",
      "dom"
    ],
    "sourceMap": true,
    "baseUrl": ".",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowJs": true,
    "experimentalDecorators": true,
    "strict": true,
    "paths": {
      "@/*": [
        "./src/*"
      ]
    }
  },
  "include": ["./src/services/api.d.ts", "./src/**/*"],
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "src/services",
    "tslint:latest",
    "tslint-config-prettier"
  ]
}
````

**api.d.ts**
```ts
type ObjectMap<Key extends string | number | symbol = any, Value = any> = {
  [key in Key]: Value;
};

declare namespace defs {
  export class Batch {
    /** 接收的处理数量 */
    batchTotal?: number;

    /** 结果代码 */
    code?: number;

    /** 执行失败的项 */
    error?: Array<defs.Error>;

    /** 执行成功的项 */
    success?: Array<defs.Success>;
  }

 }

```

**尝试**
修改为
```ts
/// <reference path="@/services/api.d.ts"/>
```
代码编译成功，但是找不到该文件里面的声明的 `API`、`defs`

**Comment by LbhFront-end** [comment]
```ts
import * as defs from '@/services/baseClass'
/// <reference path="@/services/api.d.ts"/>
```
修改成上面的内容后 解决了问题

**Comment by chenshuai2144** [comment]
你不能直接 import d.ts 的，编译之后 d.ts 文件会直接消失。

你只要将其命名为 d.ts 放到项目中，他就会默认被导入，无需声明。

你可以使用 pro 的 tsconfig，里面 typing.d.ts 使用同样的远离写入的

**Comment by LbhFront-end** [comment]
> > 你的业务代码我帮你删掉了，这种东西最好不要传上来，非要传也要打马赛克
> 
> 你不能直接 import d.ts 的，编译之后 d.ts 文件会直接消失。
> 
> 你只要将其命名为 d.ts 放到项目中，他就会默认被导入，无需声明。
> 
> 你可以使用 pro 的 tsconfig，里面 typing.d.ts 使用同样的远离写入的

好的，明白了 谢谢
