### ISSUE TITLE
yarn start后出错 🐛[BUG]

### ISSUE THREAD

**Issue by cicna** [ant-design/ant-design-pro#5758]
### 在项目中输入yarn start后，出现以下错误：

{ Error: Cannot find module 'slash2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Abc\config/config.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }
🚀 Starting Umi UI using umi@2.12.6...
⛽️ Ready on http://localhost:3000/
{ Error: Cannot find module 'slash2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Abc\config/config.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }
C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\umi-build-dev\lib\UserConfig.js:165
      throw e;
      ^

Error: Cannot find module 'slash2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Abc\config/config.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 win10
python 3.8.0
node v10.17.0
yarn 1.21.1
umi@2.12.6
serve@11.2.0
now@16.7.0

**Comment by lattemj** [comment]
Cannot find module 'slash2' 这不已经告诉你没这个模块了啊

**Comment by chenshuai2144** [comment]
你需要先安装所有的模块，才能启动。
