### ISSUE TITLE
🐛[BUG] Import Typescript file from config results in SyntaxError

### ISSUE THREAD

**Issue by mxschmitt** [ant-design/ant-design-pro#5915]
# 🐛 Bug Report

## System

- Ant Design Pro Layout: 4.10.10
- umi: 2.13.3
- Browser: Chrome
- Operating System: mac OS

## Description

It's not possible to import a Typescript file from the project e.g. in this case `src/constants/backend.ts` into the `config.ts`. It will lead to the following error:

```
yarn run v1.21.1
$ UMI_UI=none HTTPS=true umi dev
/Users/max/Development/project-name/frontend/src/constants/backend.ts:1
export enum PriorityChoices {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:891:16)
    at Module._compile (internal/modules/cjs/loader.js:941:27)
    at Module._compile (/Users/max/Development/project-name/frontend/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Object.newLoader [as .ts] (/Users/max/Development/project-name/frontend/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/max/Development/project-name/frontend/config/config.ts:4:1)
/Users/max/Development/project-name/frontend/src/constants/backend.ts:1
export enum PriorityChoices {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:891:16)
    at Module._compile (internal/modules/cjs/loader.js:941:27)
    at Module._compile (/Users/max/Development/project-name/frontend/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Object.newLoader [as .ts] (/Users/max/Development/project-name/frontend/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/max/Development/project-name/frontend/config/config.ts:4:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chenshuai2144** [comment]
Give me a minimal reproduction？

**Comment by mxschmitt** [comment]
@chenshuai2144 
repo: https://github.com/mxschmitt/antd-design-pro-issue-5915/
commit: https://github.com/mxschmitt/antd-design-pro-issue-5915/commit/27ae2ffa00537765e22ed9a50fc420724f830bab

**Comment by chenshuai2144** [comment]
You cannot use any non-node.js code in config.js unless placed in the config folder
