### ISSUE TITLE
npm run fetch:blocks下着下着就卡住不动，试了很多次都不行

### ISSUE THREAD

**Issue by shuibin20172016** [ant-design/ant-design-pro#5924]
npm run fetch:blocks下着下着就卡住不动，试了很多次都不行

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-cli
试试这个办法，debug一下为什么

**Comment by heweigeng1** [comment]
我也是这种情况,用umi 的ui添加组件也是报错

**Comment by chenshuai2144** [comment]
@heweigeng1  贴出来报错信息？

**Comment by heweigeng1** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/13012420/73671465-f334cb80-46e5-11ea-8cd1-23b21a243af3.png)

**Comment by heweigeng1** [comment]
√ �🔍  find block list form https://gitee.com/ant-design/ant-design-blocks/raw/master/umi-block.js
√ �🔍  find block list form https://gitee.com/ant-design/pro-blocks/raw/master/umi-block.js
Execute task error Error: Error: Command failed: git checkout master

**Comment by heweigeng1** [comment]
![image](https://user-images.githubusercontent.com/13012420/73673478-a3580380-46e9-11ea-85f0-65b361de2de7.png)

**Comment by heweigeng1** [comment]
@chenshuai2144 应该都是gitee的问题?

**Comment by tomgao365** [comment]
```bash
⠋ 📦  install basicform  to: /form/basic-form{ _: [ 'fetch-blocks' ], branch: 'antd@4' }
✔ 😁  Parse url and args
✔ 🚒  Git fetch
⠋ 🚛  Git checkout antd@4已经位于 'antd@4'
您的分支与上游分支 'origin/antd@4' 一致。
✔ 🚛  Git checkout antd@4
⠸ 🚀  Git pull已经是最新的。
✔ 🚀  Git pull
⠋ 📦  install dependencies package✖  error     Error: find dependencies conflict between block and your project:* @ant-design/icons: ^4.0.0-alpha.19(your project) not compatible with 4.0.0-alpha.19(block) 
    at /Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/installDependencies.js:158:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/installDependencies.js:72:103)
    at _next (/Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/installDependencies.js:74:194)
    at /Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/installDependencies.js:74:364
    at new Promise (<anonymous>)
    at /Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/installDependencies.js:74:97
    at _installDependencies (/Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/installDependencies.js:227:31)
    at installDependencies (/Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/installDependencies.js:104:31)
    at /Users/tom/Gao/we-hub/antd-pro/node_modules/umi-build-dev/lib/plugins/commands/block/addBlock.js:300:44
⠙ 📦  install dependencies package
```

卡在这里了。

**Comment by chenshuai2144** [comment]
好了，已经修复了，重试一下

**Comment by tomgao365** [comment]
@chenshuai2144  多次尝试，都出现安装了1个或多个block后卡主不动了，也没有错误信息

node: v10.18.1
os: macOS 10.15.3

**Comment by chenshuai2144** [comment]
@tomgao365  是 fetch:blocks 吗？

**Comment by tomgao365** [comment]
@chenshuai2144 是的 fetch:blocks ，试了十来次，没成功过。大都卡在第一次成功了，就不动了。没错错误信息。只有一次，执行到 /form/basic-form 卡在了。

**Comment by chenshuai2144** [comment]
@tomgao365  https://github.com/ant-design/ant-design-pro-cli
试试这个办法，debug一下为什么

> 发现家里的长城宽带封锁了好多的网络

**Comment by tomgao365** [comment]
@chenshuai2144 刚刚又重新创建项目尝试，用的就是文档提供的 debug 方法，第一个 block 创建完成后就没有继续执行下去，没有错误日志。下面是完整的执行信息。

```bash
antd-pro yarn fetch:blocks
yarn run v1.21.1
$ DEBUG=pro-cli pro fetch-blocks --branch antd@4 && npm run prettier
⚠ 🧐  find config.ts ...
✔ 🧐  find config.js ...
⠋ 📦  install login  to: /user/login{ _: [ 'fetch-blocks' ], branch: 'antd@4' }
✔ 😁  Parse url and args
✔ 🚒  Git fetch
⠋ 🚛  Git checkout antd@4已经位于 'antd@4'
您的分支与上游分支 'origin/antd@4' 一致。
✔ 🚛  Git checkout antd@4
⠼ 🚀  Git pull已经是最新的。
✔ 🚀  Git pull
✔ 📦  install dependencies package
  🔥  Generate files
   create src/pages/user/login/_mock.ts
   create src/pages/user/login/components/Login/LoginContext.tsx
   create src/pages/user/login/components/Login/LoginItem.tsx
   create src/pages/user/login/components/Login/LoginSubmit.tsx
   create src/pages/user/login/components/Login/LoginTab.tsx
   create src/pages/user/login/components/Login/index.less
   create src/pages/user/login/components/Login/index.tsx
   create src/pages/user/login/components/Login/map.tsx
   create src/pages/user/login/index.tsx
   create src/pages/user/login/locales/en-US.ts
   create src/pages/user/login/locales/zh-CN.ts
   create src/pages/user/login/locales/zh-TW.ts
   create src/pages/user/login/model.ts
   create src/pages/user/login/service.ts
   create src/pages/user/login/style.less
   create src/pages/user/login/utils/utils.ts
✔ 🔥  Generate files
✔ 🤔  TypeScript to JavaScript
✔ ⛱  Write route /user/login to /Users/tom/Gao/we-hub/antd-pro/config/config.js
✔  success   ✨  Probable url http://localhost:8000/user/login (copied to clipboard) for view the block.

```

node: v10.18.1
yarn: v1.21.1
os: macOS 10.15.3
宽带: 中国移动(河南省洛阳市)

**Comment by tomgao365** [comment]
😂又试了几次，同样的问题，其中 ts 版卡在 `install not-find  to: /exception/404`，
js 版卡在 `/user/login`,`/dashboard/monitor`,`/list/card-list`。Debug 没有错误信息，卡在完成这些模块完成之后。

**Comment by chenshuai2144** [comment]
用umi ui 添加吧，你的操作系统是什么？

**Comment by tomgao365** [comment]
@chenshuai2144 Ok，我单个下载试试。node已经升级到最新的稳定版 12,同样的情况。

**Comment by tomgao365** [comment]
@chenshuai2144 通过 `umi block add ` 一个个安装模块，还是经常出现安装完成后卡主的情况，这应该就是造成批量的 `yarn fetch:blocks` 执行出现上述问题的原因。

**Comment by chenshuai2144** [comment]
试着升级一下最新版本，换了一种结束的方案

**Comment by tomgao365** [comment]
@chenshuai2144 👍，可以正常执行，生成所有block了。

**Comment by hui9464** [comment]
> https://github.com/ant-design/ant-design-pro-cli
> 试试这个方法，debug一下为什么

具体怎么使用，不太看的懂文档。要输入怎样的命令进行debug

**Comment by tomgao365** [comment]
@hui9464 
看看这个 https://github.com/ant-design/ant-design-pro-cli#debug 
改改 package.json 里的 fetch:blocks 脚本
