### ISSUE TITLE
ant-design-pro-cli error

### ISSUE THREAD

**Issue by qinly** [ant-design/ant-design-pro#593]
## yarn 
yarn global add ant-design-pro-cli
yarn global v1.3.2
[1/4] 🔍  Resolving packages...
warning ant-design-pro-cli > unzip2 > fstream > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
error Couldn't find package "create-error-class" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Error: Couldn't find package "duplexer3" on the "npm" registry.
    at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:103:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
Error: Couldn't find package "is-retry-allowed" on the "npm" registry.
    at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:103:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

## npm
npm install ant-design-pro-cli -g
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: timed-out@^4.0.0 (node_modules/ant-design-pro-cli/node_modules/got/node_modules/timed-out):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: OK: timed-out@^4.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: is-retry-allowed@^1.0.0 (node_modules/ant-design-pro-cli/node_modules/got/node_modules/is-retry-allowed):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: OK: is-retry-allowed@^1.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: duplexer3@^0.1.4 (node_modules/ant-design-pro-cli/node_modules/got/node_modules/duplexer3):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: OK: duplexer3@^0.1.4

npm ERR! code E404
npm ERR! 404 OK: create-error-class@^3.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*/.npm/_logs/2018-01-06T19_31_18_353Z-debug.log

## log info
2438 warn 404 SKIPPING OPTIONAL DEPENDENCY: OK: duplexer3@^0.1.4
2439 verbose stack Error: 404 OK: create-error-class@^3.0.0
2439 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
2439 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2439 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
2439 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
2439 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2439 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2439 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
2439 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
2439 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2439 verbose stack     at runCallback (timers.js:773:18)
2439 verbose stack     at tryOnImmediate (timers.js:734:5)
2439 verbose stack     at processImmediate [as _immediateCallback] (timers.js:711:5)
2440 verbose cwd /Users/qinly
2441 verbose Darwin 17.4.0
2442 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "install" "ant-design-pro-cli" "-g"
2443 verbose node v9.3.0
2444 verbose npm  v5.5.1
2445 error code E404
2446 error 404 OK: create-error-class@^3.0.0
2447 verbose exit [ 1, true ]

```
yarn 1.3.1
node v9.3.0
npm  v5.5.1
```

**Comment by qinly** [comment]
问题已经找到。镜像没有create-error-class，刚在 https://npm.taobao.org/sync/connect 同步了 create-error-class
