### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by mofengfs** [ant-design/ant-design-pro#5990]
### 1.
![q1](https://user-images.githubusercontent.com/16655229/74957571-b5080d80-5442-11ea-9eae-4c01e4b1a94f.jpg)
### 2.
![q2](https://user-images.githubusercontent.com/16655229/74957893-2778ed80-5443-11ea-910c-01a2ef281b7a.jpg)

### 4.
![q4](https://user-images.githubusercontent.com/16655229/74957861-1e881c00-5443-11ea-81b3-cf315597fb44.jpg)
### 7.
![q6](https://user-images.githubusercontent.com/16655229/74957818-1203c380-5443-11ea-95e9-a0eace83b428.jpg)

### log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd F:\WorkSpace\healthtest\tapp
6 verbose Windows_NT 10.0.14393
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v10.15.2
9 verbose npm  v6.4.1
10 error missing script: start
11 verbose exit [ 1, true ]
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. win10]

**Comment by chenshuai2144** [comment]
you should use `npm run dev`

**Comment by rit23kumar** [comment]
npm run dev
Giving same error
