### ISSUE TITLE
🐛[BUG]yarn create umi命令初始化ant-design-pro项目报错

### ISSUE THREAD

**Issue by microud** [ant-design/ant-design-pro#6020]
### 🐛 bug 描述

使用命令 `yarn create umi` 初始化项目，一路回车，最终提示如下

```bash
➜  project yarn create umi
yarn create v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-umi@0.20.1" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? TypeScript
? 🦄 Time to use better, faster and latest antd@4! Yes
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at /Users/microud/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:653:22
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/microud/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:668:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments:
Directory: /Users/microud/WebstormProjects/project
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### 🏞 期望结果

可以在当前目录下生成项目文件

### © 版本信息

- 操作系统：macOS 10.14.6
- Node版本：v10.16.3
- Yarn版本：1.17.3

**Comment by chenshuai2144** [comment]
试试 yarn create umi，看起来是依赖有些问题

**Comment by microud** [comment]
先移除了原来的create-umi，然后tyarn再创建是一样的错误，需要我贴一下yarn.lock吗？

**Comment by microud** [comment]
`yeoman-generator`在yarn.lock中的信息
```
yeoman-generator@^4.0.1:
  version "4.6.0"
  resolved "https://registry.yarnpkg.com/yeoman-generator/-/yeoman-generator-4.6.0.tgz#dce30db1b30d25b03a7e61fd16b43d3149f3d84a"
  integrity sha512-Hq65rLqMNCS0h0n1yakSZjHsEZHm0ZpOM02Nja6O03s2k5WHvAhGOx7uxs93vrJv62zFrJtD9e9mVhgoVbi7CQ==
  dependencies:
    async "^2.6.2"
    chalk "^2.4.2"
    cli-table "^0.3.1"
    cross-spawn "^6.0.5"
    dargs "^6.1.0"
    dateformat "^3.0.3"
    debug "^4.1.1"
    diff "^4.0.1"
    error "^7.0.2"
    find-up "^3.0.0"
    github-username "^3.0.0"
    istextorbinary "^2.5.1"
    lodash "^4.17.11"
    make-dir "^3.0.0"
    mem-fs-editor "^6.0.0"
    minimist "^1.2.0"
    pretty-bytes "^5.2.0"
    read-chunk "^3.2.0"
    read-pkg-up "^5.0.0"
    rimraf "^2.6.3"
    run-async "^2.0.0"
    shelljs "^0.8.3"
    text-table "^0.2.0"
    through2 "^3.0.1"
    yeoman-environment "^2.3.4"
```

**Comment by microud** [comment]
clone了create-umi，锁死了`yeoman-generator`的版本为`4.0.1`，然后node运行可以正常创建，盲猜是这个依赖库的版本更新导致create-umi出问题，看了一下提交是大概六小时前更新的版本= =，让人猝不及防啊，我应该去create-umi下提Bug😂

**Comment by iamMarkchu** [comment]
同类型错误，如果解决？

**Comment by microud** [comment]
@iamMarkchu 临时先clone create-umi到本地然后安装依赖，在别的地方调用使用吧，大致的操作：
```bash
git clone https://github.com/umijs/create-umi

# 进入create-umi并修改package.json，去掉yeoman-generator版本号开头的 ^，然后安装依赖

yarn # 或 npm i

# 然后在想要创建项目的地方执行

node path/to/create-umi/cli.js [project]
```

**Comment by vastmunich** [comment]
我的也是如此，不能创建项目，用的是mpm create umi

**Comment by hiwjcn** [comment]
same issue

**Comment by bkstorm** [comment]
same issue here.

**Comment by MulderLiu** [comment]
npm create umi 使用這個也有同樣的問題
最後直接clone 的源碼...

**Comment by afc163** [comment]
https://github.com/umijs/create-umi/pull/98

**Comment by VATALU** [comment]
@MulderLiu 那必然也是这样的

**Comment by afc163** [comment]
Fixed in create-umi: https://github.com/umijs/create-umi/pull/98#issuecomment-592277166
