### ISSUE TITLE
🐛[BUG] Could not create project

### ISSUE THREAD

**Issue by vedatkilic** [ant-design/ant-design-pro#6021]
### 🐛 bug 描述

yarn create v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-umi@0.20.1" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? TypeScript
? 🦄 Time to use better, faster and latest antd@4! Yes
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at /Users/microud/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:653:22
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/microud/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:668:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments:
Directory: /Users/microud/WebstormProjects/project
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/6020
看这里
