### ISSUE TITLE
🐛[BUG] npm create umi 报错

### ISSUE THREAD

**Issue by iamMarkchu** [ant-design/ant-design-pro#6022]
### 🐛 bug 描述
执行命令 npm create umi test
? Select the boilerplate type ant-design-pro
? � Which language do you want to use? TypeScript
? � Time to use better, faster and latest antd@4! Yes
events.js:298
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at C:\Users\chukui\AppData\Roaming\npm-cache\_npx\4928\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:653:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (C:\Users\chukui\AppData\Roaming\npm-cache\_npx\4928\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:668:20)
    at processImmediate (internal/timers.js:456:21)

### 🏞 期望结果
生成新的项目目录
### © 版本信息

- node v13.9.0
- npm 6.13.7
- 开发环境  win10 家庭版

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/6020
看这个吧
