### ISSUE TITLE
🧐[问题] 用约定路由后，无法重定向

### ISSUE THREAD

**Issue by paulzanmei** [ant-design/ant-design-pro#6118]
### 🧐 用约定路由后，无法重定向

用户了约定路由多布局的方案，用 Redirect to="/user/login"/ 重定向不跳转

### 🚑 下面的错误不知是否是这个错误抛出来的

uncaught at _callee3 at _callee3 
 at _callee7 
 at takeEvery 
 at _callee 
 at _callee 
 Error: TypeError: Cannot read property 'map' of undefined
    at formatter (http://localhost:8000/umi.js:187645:15)
    at fetchMenuData$ (http://localhost:8000/umi.js:187688:26)
    at tryCatch (http://localhost:8000/umi.js:162807:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/umi.js:163033:22)
    at Generator.prototype.<computed> [as next] (http://localhost:8000/umi.js:162859:21)
    at next (http://localhost:8000/umi.js:160841:27)
    at currCb (http://localhost:8000/umi.js:160918:7)
    at http://localhost:8000/umi.js:81788:17
    at http://localhost:8000/umi.js:80933:26
    at onError (http://localhost:8000/umi.js:81789:11)
    at sagaWithCatch$ (http://localhost:8000/umi.js:81213:13)
    at tryCatch (http://localhost:8000/umi.js:162807:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/umi.js:163033:22)
    at Generator.prototype.<computed> [as throw] (http://localhost:8000/umi.js:162859:21)
    at next (http://localhost:8000/umi.js:160819:32)
    at Object.currCb [as cont] (http://localhost:8000/umi.js:160918:7)
    at end (http://localhost:8000/umi.js:160886:23)
    at abort (http://localhost:8000/umi.js:160609:5)
    at Object.task.cont (http://localhost:8000/umi.js:160622:9)
    at next (http://localhost:8000/umi.js:160858:16)
    at currCb (http://localhost:8000/umi.js:160918:7)

**Comment by chenshuai2144** [comment]
竟然不能转给 umi ，你去umi提一下吧，估计触发了边际情况
