### ISSUE TITLE
使用了loadable或react.lazy后报warning ***.d.ts警告

### ISSUE THREAD

**Issue by lattemj** [ant-design/ant-design-pro#6243]
在使用了动态引入组件后：
ImportComponent = loadable((props: any) => import(`../../modules/${props.moduleName}`))

npm start时报如下警告：
warning  in ./src/pages/modules/systemRole/data.d.ts

Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. Output generation failed
    at Object.transpileModule (D:\MiniProgram_VDPShop_Management\node_modules\typescript\lib\typescript.js:120889:29)
    at getTranspilationEmit (D:\MiniProgram_VDPShop_Management\node_modules\ts-loader\dist\index.js:283:74)
    at successLoader (D:\MiniProgram_VDPShop_Management\node_modules\ts-loader\dist\index.js:66:15)
    at Object.loader (D:\MiniProgram_VDPShop_Management\node_modules\ts-loader\dist\index.js:22:12)

 @ ./src/pages/modules lazy ^\.\/.*$ namespace object
 @ ./src/pages/components/displayControls/drawerViewCorrelationData.tsx
 @ ./src/pages/components/index.tsx
 @ ./src/pages/modules/articleCategoryInfo/index.tsx
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

**Comment by chenshuai2144** [comment]
Typescript  dynamic import don't support any dynamic params.
you can look here [Dynamic Import Expressions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#dynamic-import-expressions)
