### ISSUE TITLE
🐛[BUG] yarn create umi 时报错

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#6250]
### 🐛 bug 描述

<img width="857" alt="image" src="https://user-images.githubusercontent.com/507615/77905969-b89c7900-72b9-11ea-88e1-1b3ed5ba839d.png">

### 📷 复现步骤

```
yarn create umi
```

选择 JavaScript 和 complete。

### 🏞 期望结果

无报错。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] latest
- umi 版本：`create-umi@0.21.0`.
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
```
> [Sylvanas] Prepare js environment...
events.js:200
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Support for the experimental syntax 'optionalChaining' isn't currently enabled (28:22):

  26 | 
  27 |   const getRowByKey = (key: string, newData?: TableFormDateType[]) =>
> 28 |     (newData || data)?.filter((item) => item.key === key)[0];
     |                      ^
  29 | 
  30 |   const toggleEditable = (e: React.MouseEvent | React.KeyboardEvent, key: string) => {
  31 |     e.preventDefault();

Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation.
    at Object.raise (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.expectPlugin (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:7647:18)
    at Object.parseSubscript (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8447:12)
    at Object.parseSubscript (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:5268:18)
    at Object.parseSubscripts (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8433:19)
    at Object.parseExprSubscripts (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8422:17)
    at Object.parseMaybeUnary (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8392:21)
    at Object.parseMaybeUnary (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:5648:20)
    at Object.parseExprOps (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8267:23)
    at Object.parseMaybeConditional (/Users/afc163/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8240:23)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (/Users/afc163/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:436:22)
    at processImmediate (internal/timers.js:439:21) {
  pos: 880,
  loc: Position { line: 28, column: 21 },
  missingPlugin: [ 'optionalChaining' ],
  code: 'BABEL_PARSE_ERROR'
}
error Command failed.
Exit code: 1
Command: /Users/afc163/.yarn/bin/create-umi
Arguments: 
Directory: /Users/afc163/Projects/yyy
```

**Comment by shenyinabcd** [comment]
我也遇到这个问题。node.js 版本是13。不选 JavaScript，选择 TypeScript 好了

**Comment by mhpyzzy** [comment]
这个错误还没有解决吗？我现在还是报这个错

**Comment by BingXiong1995** [comment]
这个问题还没有解决吗？我也还是报这个错误

**Comment by hzvictor** [comment]
还没解决

**Comment by adow** [comment]
这个问题没有解决吧，yarn create umi 时选择 Typescrpt 或者 ant design (3.0) 就不会出错

**Comment by sunwu51** [comment]
node14.15.0选ts也报了这个错误鸭
