### ISSUE TITLE
🧐[问题]npm create umi 报错

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design-pro#6256]
### 🧐 问题描述
```
$ npm create umi

internal/modules/cjs/loader.js:488
    throw e;
    ^

Error: Package exports for 'C:\Users\mengyucheng\AppData\Roaming\npm-cache\_npx\12544\node_modules\create-umi\node_modules\clipboardy' do not define a '.' subpath
    at applyExports (internal/modules/cjs/loader.js:485:15)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\mengyucheng\AppData\Roaming\npm-cache\_npx\12544\node_modules\create-umi\lib\run.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by chenshuai2144** [comment]
试试用 npx ，你的本地依赖有点问题了

**Comment by sunguoxing0628** [comment]
我发生了同样的问题，重新安装本地的node后可以正常使用，你可以尝试下 @maxmeng93
