### ISSUE TITLE
🐛[BUG] api.chainWebpack is not a function

### ISSUE THREAD

**Issue by hu272293309** [ant-design/ant-design-pro#6329]
### 🐛 bug 描述
npm start

> ant-design-pro@1.0.0 start /work/work-js/finwise.pc
> umi dev

api.chainWebpack is not a function
TypeError: api.chainWebpack is not a function
    at _default (/Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_preset-ant-design-pro@1.2.0@@umijs/preset-ant-design-pro/lib/index.js:39:7)
    at Service.initPreset (/Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_core@3.1.0@@umijs/core/lib/Service/Service.js:354:25)
    at Service.initPresetsAndPlugins (/Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_core@3.1.0@@umijs/core/lib/Service/Service.js:305:12)
    at /Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_core@3.1.0@@umijs/core/lib/Service/Service.js:227:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_core@3.1.0@@umijs/core/lib/Service/Service.js:106:103)
    at _next (/Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_core@3.1.0@@umijs/core/lib/Service/Service.js:108:194)
    at /Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_core@3.1.0@@umijs/core/lib/Service/Service.js:108:364
    at new Promise (<anonymous>)
    at /Users/zhaohuihu/work/work-js/finwise.pc/node_modules/_@umijs_core@3.1.0@@umijs/core/lib/Service/Service.js:108:97

### 📷 复现步骤
yarn create umi
select javascript
select ant-design-pro
select complete
cnpm i
npm start

### © 版本信息

- Ant Design Pro 版本: last
- umi 版本 last
- 浏览器环境 
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
close by  https://github.com/umijs/plugins/pull/146

**Comment by chenshuai2144** [comment]
虽然不知道为什么，但是就是不能跑

**Comment by Yakima-Teng** [comment]
today I use node v14.15.5 with npm to install dependencies, and this message occurs too.

**Comment by juxuny** [comment]
我 pnpm install 的时候就会出这个错误，npm install 就很畅通
node version: v16.14.2

**Comment by loveyunk** [comment]
> 我 pnpm install 的时候就会出这个错误，npm install 就很畅通 node version: v16.14.2

你把 @umijs/preset-ant-design-pro 更新到最新版本试试
