### ISSUE TITLE
🐛[BUG]空目录下执行 npm create umi 或 yarn create umi 报错:目录已存在

### ISSUE THREAD

**Issue by huaiguoguo** [ant-design/ant-design-pro#6383]
### 🐛 bug 描述

在空目录test 下面执行以下命令：
npm create umi 或 yarn create umi
在进行一系列选择后出现以下一系列错误 | 
但是我用npm create umi  demo 或 yarn create umi demo 是ok的
官方文档说的是建一个空目录，在里面执行npm create umi 或 yarn create umi

```
D:\phpstudy_pro\WWW\test>npm create umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? complete
> 🙈 complete mode can only use the version of antd@4
fatal: destination path 'D:\phpstudy_pro\WWW\test' already exists and is not an empty directory.
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 --branch all-blocks D:\phpstudy_pro\WWW\test
null
null
    at makeError (C:\Users\guofeng\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:174:9)
    at C:\Users\guofeng\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async AntDesignProGenerator.writing (C:\Users\guofeng\AppData\Local\Yarn\Data\global\node_modules\create-umi\lib\generators\ant-design-pro\index.js:118:5)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (C:\Users\guofeng\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:791:20)
    at processImmediate (internal/timers.js:456:21) {
  code: 128,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'git clone https://gitee.com/ant-design/ant-design-pro --depth=1 --branch all-blocks D:\\phpstudy_pro\\WWW\\test',
  timedOut: false,
  killed: false
}

D:\phpstudy_pro\WWW\test>
```

### 📷 复现步骤

在空目录test 下面执行以下命令：
npm create umi 或 yarn create umi

### 🏞 期望结果

期望正常创建antd-pro项目

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]  最新版本 4.x.x
- umi 版本    3.1.1
- 浏览器环境
- 开发环境 [e.g. mac OS]  win10 专业版 1909

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/1888094/79200652-58850580-7e69-11ea-9765-74fbb3825bb6.png)

**Comment by ycjcl868** [comment]
`yarn create umi your-app`

Duplicate https://github.com/ant-design/ant-design-pro/issues/6381
