### ISSUE TITLE
🐛[BUG] 执行后npm run fetch:blocks后出现错误

### ISSUE THREAD

**Issue by nanase-takesi** [ant-design/ant-design-pro#6446]
### 📷 复现步骤
执行后npm run fetch:blocks后出现错误，执行npm run start 提示上述错误

(node:16841) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/ant-design/pro-blocks/git/trees/master failed, reason: connect ECONNREFUSED 13.250.168.23:443
    at ClientRequest.<anonymous> (/Users/takesi/Desktop/antd-design-pro/node_modules/@ant-design/pro-cli/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:16841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by dushaobindoudou** [comment]
像是网络原因

**Comment by nanase-takesi** [comment]
不是网络问题，是下载不到layout文件
![image](https://user-images.githubusercontent.com/38271786/80205384-19bb3080-865d-11ea-8d45-6f13633300b4.png)

**Comment by dushaobindoudou** [comment]
两个好像不是同一个问题

**Comment by chenshuai2144** [comment]
通过 yarn create umi 来获取的所有的区块吧

fetch:blocks 对网络和计算机都有一些需求
