### ISSUE TITLE
npm run build fails on a brand new project

### ISSUE THREAD

**Issue by anselmoshim** [ant-design/ant-design-pro#6523]
Hi, I am getting errors when building a brand new project from scratch. Happens on both javascript and typscript versions of Ant Design Pro v4. The build finishes successfully on Windows, but not on CentOS (linux). Anyone know how to fix this issue?

Steps to reproduce:

```
$ yarn create umi  # or npm create umi

# Choose ant-design-pro:
 Select the boilerplate type (Use arrow keys)
❯ ant-design-pro  - Create project with an layout-only ant-design-pro boilerplate, use together with umi block.
  app             - Create project with a simple boilerplate, support typescript.
  block           - Create a umi block.
  library         - Create a library with umi.
  plugin          - Create a umi plugin.

$ git init
$ npm install
$ npm run build -> errors when running this
```

```
-bash-4.2$ npm run build

> ant-design-pro@1.0.0 build node_modules/myapp-ts
> umi build


✖ Webpack
  Compiled with some errors in 29.67s

 ERROR  Failed to compile with 2 errors                                                                          7:41:04 PM

 error  in ./src/global.less

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at node_modules/myapp-ts/node_modules/mini-css-extract-plugin/dist/loader.js:144:23
    at node_modules/myapp-ts/node_modules/webpack/lib/Compiler.js:343:11
    at node_modules/myapp-ts/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/myapp-ts/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/myapp-ts/node_modules/tapable/lib/Hook.js:154:20)
    at node_modules/myapp-ts/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/myapp-ts/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/myapp-ts/node_modules/tapable/lib/Hook.js:154:20)
    at node_modules/myapp-ts/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/myapp-ts/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/myapp-ts/node_modules/tapable/lib/Hook.js:154:20)
    at node_modules/myapp-ts/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (node_modules/myapp-ts/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at node_modules/myapp-ts/node_modules/uglifyjs-webpack-plugin/dist/index.js:287:11
    at Runner.runTasks (node_modules/myapp-ts/node_modules/uglifyjs-webpack-plugin/dist/uglify/Runner.js:67:9)
    at UglifyJsPlugin.optimizeFn (node_modules/myapp-ts/node_modules/uglifyjs-webpack-plugin/dist/index.js:198:16)
    at node_modules/myapp-ts/node_modules/webpack/lib/NormalModule.js:316:20
    at node_modules/myapp-ts/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at node_modules/myapp-ts/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (node_modules/myapp-ts/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at node_modules/myapp-ts/node_modules/mini-css-extract-plugin/dist/loader.js:144:14
    at node_modules/myapp-ts/node_modules/webpack/lib/Compiler.js:343:11
    at node_modules/myapp-ts/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/myapp-ts/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/myapp-ts/node_modules/tapable/lib/Hook.js:154:20)
    at node_modules/myapp-ts/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/myapp-ts/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/myapp-ts/node_modules/tapable/lib/Hook.js:154:20)
    at node_modules/myapp-ts/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/myapp-ts/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (node_modules/myapp-ts/node_modules/tapable/lib/Hook.js:154:20)
    at node_modules/myapp-ts/node_modules/webpack/lib/Compilation.js:1414:32

 @ ./src/pages/.umi-production/umi.js 219:0-28
 @ multi ./src/pages/.umi-production/umi.js

 error  in ./src/pages/.umi-production/router.js

Module parse failed: Unexpected token (208:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const props = this.props || {};
|     return (
>       <RendererWrapper0>
|         <Router history={history}>{renderRoutes(routes, props)}</Router>
|       </RendererWrapper0>

 @ ./src/pages/.umi-production/umi.js 66:38-57
 @ multi ./src/pages/.umi-production/umi.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-05-03T23_41_04_974Z-debug.log

```

Works on Windows 10
Fails on CentOS

node version  12.16.3
umi version 2.13.0
antd version 4.0.0-rc1

**Comment by anselmoshim** [comment]
Seems like similar issue here: https://github.com/umijs/umi/issues/1623

```
       <RendererWrapper0>
         <Router history={history}>{renderRoutes(routes, props)}</Router>
       </RendererWrapper0>
```

exists in `umi-production.js/router.js`

**Comment by anselmoshim** [comment]
fix for error is https://github.com/TypeStrong/ts-node/issues/922#issuecomment-571734880
