### ISSUE TITLE
🧐[问题]通过umi UI安装模板的时候提示安装失败

### ISSUE THREAD

**Issue by wshuai222333** [ant-design/ant-design-pro#6550]
node:12.16.3
umi:3.1.4

问题：通过umi UI安装模板的时候提示
[Asset Error] Error: spawn git ENOENT
    at notFoundError (C:\mygithub\antdemo\node_modules\@umijs\plugin-ui-blocks\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\mygithub\antdemo\node_modules\@umijs\plugin-ui-blocks\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\mygithub\antdemo\node_modules\@umijs\plugin-ui-blocks\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'clone',
    'https://gitee.com/ant-design/pro-blocks.git',
    'github.com/ant-design/pro-blocks',
    '--recurse-submodules'
  ],
  stdout: undefined,
  stderr: undefined,
  failed: true,
  signal: null,
  cmd: 'git clone https://gitee.com/ant-design/pro-blocks.git github.com/ant-design/pro-blocks --recurse-submodules',
  timedOut: false,
  killed: false
}

**Comment by wshuai222333** [comment]
在环境变量的path里加上“C:\Program Files\Git\bin”就可以了
