### ISSUE TITLE
🧐[问题] yarn create umi ERROR

### ISSUE THREAD

**Issue by lzbabd** [ant-design/ant-design-pro#6556]
### 🧐 
yarn create umi 
...

? Select the boilerplate type ant-design-pro

(node:50280) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Referenced from: /Users/mac/.config/yarn/global/node_modules/eslint-config-airbnb-typescript/index.js
Referenced from:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Plugins.load (/Users/mac/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/Users/mac/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (/Users/mac/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:529:35)
    at load (/Users/mac/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:587:20)
    at configExtends.reduceRight (/Users/mac/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/mac/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:431:26)
(node:50280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------

node  v10.14.0

**Comment by chenshuai2144** [comment]
更新 create umi 的版本即可

**Comment by lzbabd** [comment]
@chenshuai2144  单独更新umi无效, 清空 yarn global 安装目录后好了, 可能是 global 里的 yarn.lock 的问题(以前全局安装过umi)

**Comment by chenshuai2144** [comment]
yarn create umi 就是在全局的

**Comment by mxmtsk** [comment]
@chenshuai2144 I'm facing the same issue. Tried reinstalling `create-umi` but that didn't help.

> (node:18642) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:

**Comment by ahtashamabbasse** [comment]
Facing same issue
![image](https://user-images.githubusercontent.com/25702074/82040289-d41fdf80-96bf-11ea-9c6e-1f78b1caabb8.png)

**Comment by mxmtsk** [comment]
@ahtashamabbasse I was able to proceed when I installed the dependencies globally (there will be a few more that it complains about, after you installed `@typescript-eslint/eslint-plugin`)

**Comment by ahtashamabbasse** [comment]
@mxmtsk I gave it a try but still in the same place. I believe the issue is 
```
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0"
has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
```

**Comment by ahtashamabbasse** [comment]
@mxmtsk interesting thing is when I tried to create the project with ` npm create umi my-app` work like a charm 🚀

**Comment by pwh19920920** [comment]
- - 我也是醉了，用npm create umi是正常的

**Comment by wujunchuan** [comment]
我把所有的umi相关的脚手架删了, 尝试使用 `npm create umi` 后可以了
