### ISSUE TITLE
🧐[问题] 代码只有这么两个页面,少了很多, 在哪里下载完整的代码?

### ISSUE THREAD

**Issue by gclsoft** [ant-design/ant-design-pro#6577]
### 🚑 其他信息

https://preview.pro.ant.design/dashboard/analysis  的截图:

![image](https://user-images.githubusercontent.com/1269898/81797257-1ff84a80-9541-11ea-9216-066456e82988.png)

https://github.com/ant-design/ant-design-pro 的代码只有这么两个页面,少了很多, 在哪里下载完整的代码?
![image](https://user-images.githubusercontent.com/1269898/81797302-2ab2df80-9541-11ea-997a-b184e3f8798f.png)

**Comment by gclsoft** [comment]
npm run fetch:blocks 也还是没下载代码

**Comment by gclsoft** [comment]
````
C:\Users\GZ\ant-design-pro>npm run fetch:blocks

> ant-design-pro@4.0.0 fetch:blocks C:\Users\GZ\ant-design-pro
> pro fetch-blocks --branch=umi@3 && npm run prettier

√ 🧐  find config.ts ...
(node:74120) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/ant-design/pro-blocks/git/trees/master failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\GZ\ant-design-pro\node_modules\_node-fetch@2.6.0@node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:74120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To
 terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> ant-design-pro@4.0.0 prettier C:\Users\GZ\ant-design-pro
> prettier -c --write "**/*"

Checking formatting...
[error] No parser could be inferred for file: .idea\ant-design-pro.iml
[error] No parser could be inferred for file: .idea\inspectionProfiles\Project_Default.xml
[error] No parser could be inferred for file: .idea\misc.xml
[error] No parser could be inferred for file: .idea\modules.xml
[error] No parser could be inferred for file: .idea\vcs.xml
[error] No parser could be inferred for file: .idea\workspace.xml
All matched files use Prettier code style!

````

**Comment by chenshuai2144** [comment]
yarn create umi 中选择全部就好了

**Comment by GreatAuk** [comment]
> yarn create umi 中选择全部就好了

V5 版本没有选择 complete 或 simple 的选项啊
