### ISSUE TITLE
🐛[BUG] Installing error - @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'

### ISSUE THREAD

**Issue by hiep294** [ant-design/ant-design-pro#6594]
### 🐛 bug 描述
Some error when installing Ant Design Pro. Please, help me.
```
? Select the boilerplate type ant-design-pro
(node:5426) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- /home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js
- /home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config.js
- /home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine.js
- /home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/api.js
- /home/hiep294/.config/yarn/global/node_modules/sylvanas/lib/eslintJs.js
- /home/hiep294/.config/yarn/global/node_modules/sylvanas/lib/index.js
- /home/hiep294/.config/yarn/global/node_modules/create-umi/lib/generators/ant-design-pro/index.js
- /home/hiep294/.config/yarn/global/node_modules/create-umi/lib/run.js
- /home/hiep294/.config/yarn/global/node_modules/create-umi/cli.js
Referenced from: /home/hiep294/.config/yarn/global/node_modules/eslint-config-airbnb-typescript/index.js
Referenced from: 
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at Plugins.load (/home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (/home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:529:35)
    at load (/home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:587:20)
    at /home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/home/hiep294/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:431:26)
(node:5426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 5.63s.

```

**Comment by afc163** [comment]
#6310 #6556

**Comment by chenshuai2144** [comment]
应该是全局固定了 ts 的版本，可以试试升级 node.js 和 ts
