### ISSUE TITLE
🐛[BUG]使用yarn create umi xxx创建项目失败

### ISSUE THREAD

**Issue by lz82** [ant-design/ant-design-pro#6600]
### 🐛 bug 描述

使用yarn create umi xxx创建项目失败,如果选择Ts的话，是可以成功创建项目的

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/39956694/82125176-d759bf00-97d6-11ea-8ea7-27ef576deac9.png)

### 🏞 期望结果

成功初始化项目

### 💻 复现代码

yarn create umi
yarn create v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
[4/4] 🔨  Building fresh packages...
success Installed "create-umi@0.23.1" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! Yes
Cloning into '/Users/lz/develop/kefa/gxpert-admin'...
remote: Enumerating objects: 188, done.
remote: Counting objects: 100% (188/188), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 188 (delta 21), reused 58 (delta 8), pack-reused 0
Receiving objects: 100% (188/188), 296.16 KiB | 2.69 MiB/s, done.
Resolving deltas: 100% (21/21), done.
> 🚚 clone success
> [Sylvanas] Prepare js environment...
events.js:174
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Unexpected token (24:12)

  22 | };
  23 |
> 24 | export type { DefaultSettings };
     |             ^
  25 |
  26 | export default proSettings;
  27 |
    at Object.raise (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:7013:17)
    at Object.unexpected (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:8384:16)
    at Object.parseIdentifierName (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:10325:18)
    at Object.parseIdentifier (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:10303:23)
    at Object.tsParseTypeAliasDeclaration (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:5385:20)
    at Object.tsParseDeclaration (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:5702:23)
    at Object.tsTryParseExportDeclaration (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:5609:17)
    at Object.parseExportDeclaration (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:6075:26)
    at Object.maybeParseExportDeclaration (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:11799:31)
    at Object.parseExport (/Users/lz/.config/yarn/global/node_modules/sylvanas/node_modules/@babel/parser/lib/index.js:11729:29)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/lz/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:924:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments:
Directory: /Users/lz/develop/kefa/gxpert-admin
Output:

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境
 mac OS 10.15.4
node 10.16.3
yarn 1.22.4
create-umi 0.23.1

![image](https://user-images.githubusercontent.com/39956694/82125255-40d9cd80-97d7-11ea-8be3-8ebd0469b2f6.png)
有一点很奇怪，在ch查询umi版本时，提示如上图所示

**Comment by lz82** [comment]
试了下，不选antd@4，选Js 也是可以成功创建项目的
所以这是什么情况？能尽快解决吗？

**Comment by chenshuai2144** [comment]
SyntaxError: unknown: Unexpected token

需要升级 ts 的版本了，export type 是 3.8 支持的内容，尽量不要在全局安装 ts  eslint 等经常更新的东西，容易与相应的版本冲突

**Comment by lz82** [comment]
![image](https://user-images.githubusercontent.com/39956694/82135402-fab35700-9834-11ea-84bf-8bd37e26b6fd.png)
@chenshuai2144 其实并没有全局安装过。。。

**Comment by lz82** [comment]
![image](https://user-images.githubusercontent.com/39956694/82135575-de181e80-9836-11ea-8c49-9dc381ce5efc.png)
全局安装了typescript,还是一样的错。。。这个要怎么解决？

@chenshuai2144

**Comment by chenshuai2144** [comment]
node 版本升级到12呢？

**Comment by lz82** [comment]
![image](https://user-images.githubusercontent.com/39956694/82135888-71068800-983a-11ea-8a4c-11d4b9a8249d.png)
还是在export type { DefaultSettings } 这里报错
但是错误信息略有不同了

btw，我怀疑可能是nvm的锅，把nvm也删了

node用原生的安装到了12.16.3

**Comment by lz82** [comment]
@chenshuai2144 麻烦帮忙看下。。

**Comment by chenshuai2144** [comment]
type  是高版本的 ts 需要的我来试试

**Comment by lz82** [comment]
现在提示是说BABEL_PARSE_ERROR
但是按照你的建议，不要全局安装ts，那就是项目自身会去安装高版本ts吗？

那需要我这里做什么吗？

另外就是如果我项目语言选typescript，就不会有问题

**Comment by chenshuai2144** [comment]
我们的项目是用 typescript 写的，选择js其实使用babel 将其转化为了 js，所以和babel有关，推荐用typescript 有了就回不去了

**Comment by lz82** [comment]
是准备用ts的。。。但是还刚开始学。。。公司项目。。直接硬上ts怕死的快。。。
😅
好吧，我试试直接用ts～～谢谢了～

**Comment by chenshuai2144** [comment]
学习速度很快的，ts 和js是兼容的

**Comment by jsdocker** [comment]
看了报错， 是这个包有问题 sylvanas，最终怎么解决的？ @chenshuai2144

**Comment by bboy114crew** [comment]
> 学习速度很快的，ts 和js是兼容的

I had the same problems when create ant-design-pro with javascript language. 
Please check it @chenshuai2144 .
Many thanks.

**Comment by sunxia628** [comment]
@chenshuai2144 公司还有后端人员写前端页面，所以写ts不太现实，现在使用yarn create umi myapp已经没有选择JavaScript的选项了，但是文档还是有这个选择步骤的；所以现在是不打算支持了还是脚手架去掉了这一步，如何切换JavaScript开发语言呢？
