### ISSUE TITLE
Export { 不能导出类类型 }

### ISSUE THREAD

**Issue by jiangf0775** [ant-design/ant-design-pro#6602]
|---src
     |---common
           |---index
index.ts文件内容--  start ---
```
class BizResult {
    msg:string;
    statusCode:number;
    data:any;
    constructor(){
        this.msg = '';
        this.statusCode = 1;
        this.data = [];
    }

    static success(data:any){
        const result = new BizResult();
        result.data = data;
        return result;
    }
    static error(msg:string){
        const result = new BizResult();
        result.msg = msg;
        result.statusCode = -1;
        return result;
    }
}
export {
    BizResult
}; 
```
index.ts文件内容--  end ---

在_mock 使用 import 使用---
`import { Request, Response } from 'express';
import { BizResult } from '@/common';

const Mock = require('mockjs');
export default {
  '/api/auth_routes': {
    '/form/advanced-form': { authority: ['admin', 'user'] },
  },

  'GET  /api/mock': (_: Request, res: Response) => {
    let data = Mock.mock({
      'id': '@integer(1, 100)',
      'name': '@cname',
    })
    //res.send({ message: 'Ok' });
    res.status(200).json(BizResult.success(data));
  },
};`
**在前一个版本的ant design pro中是可以正常使用的，使用新版yarn start就报错了**

**Comment by chenshuai2144** [comment]
有报错信息吗？看起来没毛病

**Comment by jiangf0775** [comment]
> 有报错信息吗？看起来没毛病
yarn start的时候会出现如下的错误信息：
Error: Cannot find module '@/common'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\projects\ui\ant-design-pro-v4\mock\/route.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (E:\projects\ui\ant-design-pro-v4\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .ts] (E:\projects\ui\ant-design-pro-v4\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at files.reduce (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\mock\utils.js:144:17)
    at Array.reduce (<anonymous>)
Error: Error: Cannot find module '@/common'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\projects\ui\ant-design-pro-v4\mock\/route.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (E:\projects\ui\ant-design-pro-v4\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .ts] (E:\projects\ui\ant-design-pro-v4\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at files.reduce (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\mock\utils.js:144:17)
    at Array.reduce (<anonymous>)
    at files.reduce (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\mock\utils.js:150:13)
    at Array.reduce (<anonymous>)
    at getMockConfig (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\mock\utils.js:142:16)
    at getMockData (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\mock\utils.js:130:36)
    at Object.api.addBeforeMiddewares [as fn] (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\mock\mock.js:82:48)
    at E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\core\lib\Service\Service.js:496:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\core\lib\Service\Service.js:106:103)
    at _next (E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\core\lib\Service\Service.js:108:194)
    at E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\core\lib\Service\Service.js:108:364
    at new Promise (<anonymous>)
    at E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\core\lib\Service\Service.js:108:97
    at E:\projects\ui\ant-design-pro-v4\node_modules\@umijs\core\lib\Service\Service.js:501:32
    at _next0 (eval at create (E:\projects\ui\ant-design-pro-v4\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:17:17)
    at _promise0.then._result0 (eval at create (E:\projects\ui\ant-design-pro-v4\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:41:1)
Done in 13.79s.

**Comment by chenshuai2144** [comment]
😯 ，估计不支持别名了，你可以用相对路径来导入。不要用@

**Comment by jiangf0775** [comment]
> 😯 ，估计不支持别名了，你可以用相对路径来导入。不要用@

可以了，
