### ISSUE TITLE
🐛[BUG]yarn install命令 antd2.4.5会报错

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6689]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/13188169/82885874-4de58200-9f78-11ea-9964-12c843a3b2d3.png)

PS C:\Users\joe_du\Documents\GitHub\SmartBuildings> yarn install
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ umi g tmp
Invalid or unexpected token
C:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\antd\lib\style\index.less:1
@import './themes/index';
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.newLoader [as .js] (C:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (C:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\antd\lib\layout\style\index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\Users\joe_du\Documents\GitHub\SmartBuildings>

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
删掉重新安装也是

**Comment by joesdu** [comment]
好像是任何版本都会报错，就很奇怪。我等会上班了看看是不是我代码有问题🤔

**Comment by Liqiankun** [comment]
@joesdu 请问这个是怎么解决的？

**Comment by joesdu** [comment]
> @joesdu 请问这个是怎么解决的？

忘记了，你试试将antd升级最新版看看.

**Comment by Liqiankun** [comment]
@joesdu 我感觉还是代码问题

**Comment by joesdu** [comment]
> @joesdu 我感觉还是代码问题

你现在是什么错误？

**Comment by Liqiankun** [comment]
@joesdu 解决了 `defaultSettings` 文件我在footerReander变成了func
