### ISSUE TITLE
在node v8.11.4环境下npm start失败

### ISSUE THREAD

**Issue by ZellerDorjee** [ant-design/ant-design-pro#6765]
`(node:17661) UnhandledPromiseRejectionWarning: TypeError: text.trimEnd is not a function
    at attachComments (/Users/firewing/study_project/strategy-admin/node_modules/prettier/index.js:14769:60)
    at coreFormat (/Users/firewing/study_project/strategy-admin/node_modules/prettier/index.js:14796:23)
    at format (/Users/firewing/study_project/strategy-admin/node_modules/prettier/index.js:15017:75)
    at formatWithCursor (/Users/firewing/study_project/strategy-admin/node_modules/prettier/index.js:15033:12)
    at args (/Users/firewing/study_project/strategy-admin/node_modules/prettier/index.js:50675:12)
    at Object.format (/Users/firewing/study_project/strategy-admin/node_modules/prettier/index.js:50695:12)
    at /Users/firewing/study_project/strategy-admin/node_modules/@umijs/core/lib/Html/Html.js:275:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/firewing/study_project/strategy-admin/node_modules/@umijs/core/lib/Html/Html.js:86:103)
    at _next (/Users/firewing/study_project/strategy-admin/node_modules/@umijs/core/lib/Html/Html.js:88:194)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:17661) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)`

**Comment by ZellerDorjee** [comment]
初步判断是text.trimEnd这个方法在nodev10以下的版本并不支持。

**Comment by AmberJyh** [comment]
` "engines": {
    "node": ">=10.0.0"
  },`
package.json里配置的要求就是node>10

**Comment by l745230** [comment]
我也是V5代码拉下来,死活启动不了. 然后把node卸了,转到最新版就正常了.
