### ISSUE TITLE
下载pro然后报错🐛[BUG]

### ISSUE THREAD

**Issue by hengxinsky** [ant-design/ant-design-pro#6787]
### 🐛 bug 描述

下载没问题，但是在改js过程中报错
> [Sylvanas] Prepare js environment...
events.js:187
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Unexpected token (24:12)

  22 | };
  23 | 
> 24 | export type { DefaultSettings };
     |             ^
  25 | 
  26 | export default proSettings;
  27 | 
    at Object.raise (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:6387:17)
    at Object.unexpected (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:7704:16)
    at Object.parseIdentifierName (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9592:18)
    at Object.parseIdentifier (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:9570:23)
    at Object.tsParseTypeAliasDeclaration (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:4793:20)
    at Object.tsParseDeclaration (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:5111:23)
    at Object.tsTryParseExportDeclaration (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:5020:17)
    at Object.parseExportDeclaration (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:5497:26)
    at Object.maybeParseExportDeclaration (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:11038:31)
    at Object.parseExport (/Users/hengxinsky/.config/yarn/global/node_modules/@babel/parser/lib/index.js:10967:29)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (/Users/hengxinsky/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:436:22)
    at processImmediate (internal/timers.js:439:21) {
  pos: 441,
  loc: Position { line: 24, column: 12 },
  code: 'BABEL_PARSE_ERROR'
}

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Roland-Zhu** [comment]
这个看了似乎是sylvanas转ts为js出现异常导致的，不知道什么时候能修复啊

**Comment by mtianyan** [comment]
yarn global remove create-umi  yarn global remove prisma 成功修复

**Comment by tsinglemon** [comment]
> yarn global remove create-umi yarn global remove prisma 成功修复
为什么这样可以？这是不是相当于重装umi？

**Comment by chenshuai2144** [comment]
因为你的 ts 版本太低了，pro 中用了 3.8 版本使用的 api

**Comment by hengxinsky** [comment]
> 因为你的ts版本太低了，pro中用了3.8版本中支持的 `export type`

我的用的typescript@3.9.3

**Comment by hengxinsky** [comment]
> 因为你的 ts 版本太低了，pro 中用了 3.8 版本中支持的 `export type`

我发现了，好像不是我的ts版本问题，我使用antd@3就可以，但是antd@4不行，就是在ts转js的时候
