### ISSUE TITLE
🐛[BUG] npm install 安装报错 Ant Design Pro 版本: [5.1] 

### ISSUE THREAD

**Issue by zyu** [ant-design/ant-design-pro#6851]
### 🐛 bug 描述
npm install 安装报错
 
### 📷 复现步骤
ant-design-pro git:(v5.1) npm install
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> esbuild@0.4.14 postinstall /Users/zyf/code/ant-design-pro/node_modules/esbuild
> node install.js

+ esbuild-darwin-64@0.4.14
added 1 package in 4.161s

> ant-design-pro@5.0.0-alpha.0 postinstall /Users/zyf/code/ant-design-pro
> umi g tmp

Validate config "accessLayout" failed, "useModel" is not allowed
ValidationError: "useModel" is not allowed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@5.0.0-alpha.0 postinstall: `umi g tmp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@5.0.0-alpha.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zyf/.npm/_logs/2020-06-16T11_36_48_434Z-debug.log
 
  
### © 版本信息

- Ant Design Pro 版本: [5.1]

**Comment by rong12345** [comment]
问题解决了么 我装的4.0版本的也是这个错

**Comment by chenshuai2144** [comment]
刚刚试了一下，没有问题，有祥细的复现吗

**Comment by ycjcl868** [comment]
> Validate config "accessLayout" failed, "useModel" is not allowed

**Comment by Wayxuan** [comment]
我也有这个bug，怎么解决的

**Comment by chenshuai2144** [comment]
重新安装就好了吧

**Comment by andy136240860** [comment]
已经重新安装了很多次了， node 从10 换成12 再换成14， 还是不行

**Comment by andy136240860** [comment]
> 重新安装就好了吧

已经重新安装了很多次了， node 从10 换成12 再换成14， 还是不行

**Comment by andy136240860** [comment]
> 重新安装就好了吧

已经重新安装多次， node 从10 变成12、14， 移除了本地node_modules用 npm cnpm yarn tyarn 重装依旧不行， 其中 tyarn 安装后， 用 umi dev  启动后错误如下：

`AssertionError [ERR_ASSERTION]: filePath not found of /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/_@umijs_renderer-react@3.5.17@@umijs/renderer-react
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:119:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:64:103)
    at _next (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:194)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:364
    at new Promise (<anonymous>)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:97
    at figureOutExport (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:129:17)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:84:103)
    at _next (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:194)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:364
    at new Promise (<anonymous>)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:97
    at DepBuilder.writeMFFiles (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:195:7)`
