### ISSUE TITLE
pro  安装报错

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6955]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/27960630/86750645-b1cb9200-c070-11ea-872f-a4bea4a24bdf.png)
![image](https://user-images.githubusercontent.com/27960630/86750786-c90a7f80-c070-11ea-9a2d-8adfb559d34a.png)

我本地没有全局安装ts

**Comment by chenshuai2144** [comment]
你的截图对了吗？

**Comment by lovesL** [comment]
@chenshuai2144  
![image](https://user-images.githubusercontent.com/27960630/86881847-c61b9780-c121-11ea-83d6-a9ed7975f4f8.png)

**Comment by lovesL** [comment]
@chenshuai2144 
`
events.js:288
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Unexpected token (24:12)

  22 | };
  23 | 
> 24 | export type { DefaultSettings };
     |             ^
  25 | 
  26 | export default proSettings;
  27 | 
    at Object._raise (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:723:17)
    at Object.raiseWithData (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:716:17)
    at Object.raise (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:710:17)
    at Object.unexpected (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8606:16)
    at Object.parseIdentifierName (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10549:18)
    at Object.parseIdentifier (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10527:23)
    at Object.tsParseTypeAliasDeclaration (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5851:20)
    at Object.tsParseDeclaration (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6174:23)
    at Object.tsTryParseExportDeclaration (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6079:17)
    at Object.parseExportDeclaration (/Users/joen/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6557:26)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (/Users/joen/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:676:20)
    at processImmediate (internal/timers.js:456:21) {
  loc: Position { line: 24, column: 12 },
  pos: 441,
  code: 'BABEL_PARSE_ERROR'
}
`
下面是我选的配置
? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ? Pro V4
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! antd@4

**Comment by kaoding** [comment]
这个应该是 umi 的 bug

**Comment by lovesL** [comment]
@kaoding  我是mac

**Comment by kaoding** [comment]
> @kaoding 我是mac

是不是使用 umi ui 时产生的？

**Comment by kaoding** [comment]
> @kaoding 我是mac

我看错了，不知道是不是这个问题

https://github.com/ant-design/ant-design-pro/issues/6933

**Comment by lovesL** [comment]
@kaoding 他这个报错和我这个报错 不一样

**Comment by lovesL** [comment]
@kaoding 不报错了 yarn remove 就好了 谢谢
