### ISSUE TITLE
cnpm install, omit.js包版本好像有问题，导致无法下载node_modules🐛[BUG]

### ISSUE THREAD

**Issue by tianleyang** [ant-design/ant-design-pro#6972]
✖ Install fail! Error: [antd@4.3.4 › rc-mentions@1.2.0 › rc-menu@8.5.0 › omit.js@^2.0.0] Can't find package omit.js@^2.0.0
Error: [antd@4.3.4 › rc-mentions@1.2.0 › rc-menu@8.5.0 › omit.js@^2.0.0] Can't find package omit.js@^2.0.0
    at resolve (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:80:11)
    at resolve.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at /usr/local/lib/node_modules/cnpm/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:118:63)
    at next (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:99:29)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:69:7)
    at /usr/local/lib/node_modules/cnpm/node_modules/co/index.js:54:5

**Comment by tianleyang** [comment]
我们这边都出现了这个情况，原先的node_modules包删除后，就会出现这个情况

**Comment by huaryliu** [comment]
怎么解决呢？我现在也遇到这个问题

**Comment by tianleyang** [comment]
> 怎么解决呢？我现在也遇到这个问题

淘宝镜像上面，包没同步过去，我刚刚去那边把包给同步了，现在应该能正常安装了

**Comment by huaryliu** [comment]
好的，我试下，多谢
