### ISSUE TITLE
npm run site with error

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#7]
```
Creating an optimized production build...
Compiled successfully in 57.6s.

File sizes after gzip:

  522.04 KB  dist/index.js
  52 KB      dist/index.css

Published
build static success
fs.js:1000
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/Users/afc163/Projects/test2/src/utils/request-temp.js'
    at Error (native)
    at Object.fs.statSync (fs.js:1000:11)
    at Object.statSync (/Users/afc163/Projects/test2/node_modules/_graceful-fs@4.1.11@graceful-fs/polyfills.js:297:22)
    at Object.copySync (/Users/afc163/Projects/test2/node_modules/_fs-extra@4.0.1@fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at clean (/Users/afc163/Projects/test2/node_modules/_roadhog-api-doc@0.1.4@roadhog-api-doc/lib/static.js:47:8)
    at process.<anonymous> (/Users/afc163/Projects/test2/node_modules/_roadhog-api-doc@0.1.4@roadhog-api-doc/lib/static.js:54:5)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
```

**Comment by nikogu** [comment]
我看看，顺便把 commit 改了...之前 git config user name 搞错了，汗 ＝。-

**Comment by afc163** [comment]
现在 run site 的过程中会有临时文件，如果另开一个命令行窗口操作 git 会被影响。

**Comment by nikogu** [comment]
@afc163 是的...要不我把临时文件放到包目录下，这样当前目录就没影响了

**Comment by afc163** [comment]
另建一个临时目录，统一放下面，然后 gitignore 掉。

**Comment by nikogu** [comment]
@afc163 其实有个问题是，会改 `request.js` 的源码，然后再回复过来，这样内容其实还是会影响，不过文件数量和名称不会变

**Comment by afc163** [comment]
能不能把 mock 目录整个 copy 一份再操作？

**Comment by nikogu** [comment]
现在是整个 copy 到 src 的，遇到问题了？

**Comment by afc163** [comment]
copy 到一个 gitignore 的目录里。

> 如果另开一个命令行窗口操作 git 会被影响。

我看到有改动，容易 git commit 或者 git reset 掉。

**Comment by nikogu** [comment]
报错已经修复，临时文件的问题移动到 roadhog-api-doc 里面 https://github.com/nikogu/roadhog-api-doc/issues/2

＝。- build 的时候还改代码 🔨

**Comment by afc163** [comment]
build 的时间很长的，肯定要充分利用。

**Comment by afc163** [comment]
这个问题最好还是彻底解决一下。除了 build 时的 git 被污染以外，如果我 `npm run site` 一半时 ctrl+c，也会留下临时文件。

**Comment by nikogu** [comment]
好，我想想有什么好的办法 =。-

**Comment by chenshuai2144** [comment]
终于可以关掉了
