### ISSUE TITLE
🐛[BUG]git clone ant-design-pro, 本地执行npm i

### ISSUE THREAD

**Issue by YuzhiZhang** [ant-design/ant-design-pro#7031]
### 🐛 bug 描述

1. 从仓库git clone
2. powershell 执行npm i 依赖安装失败
3. 报错日志如下
zhang@DESKTOP-1A8U3VS  D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro   master ≣                                                                                                                        [22:59]
❯ npm i

> ant-design-pro@4.1.0 postinstall D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro
> umi g tmp

D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\config\defaultSettings.ts: Unexpected token (24:12)

  22 | };
  23 | 
> 24 | export type { DefaultSettings };
     |             ^
  25 | 
  26 | export default proSettings;
  27 | 
SyntaxError: D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\config\defaultSettings.ts: Unexpected token (24:12)

  22 | };
  23 | 
> 24 | export type { DefaultSettings };
     |             ^
  25 | 
  26 | export default proSettings;
  27 | 
    at Object._raise (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\location.js:233:45)
    at Object.raiseWithData (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\location.js:228:17)
    at Object.raise (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\location.js:212:17)
    at Object.unexpected (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\util.js:149:16)
    at Object.parseIdentifierName (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\expression.js:2092:18)
    at Object.parseIdentifier (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\expression.js:2059:23)
    at Object.tsParseTypeAliasDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:1171:22)
    at Object.tsParseDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:1547:25)
    at Object.tsTryParseExportDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:1451:19)
    at Object.parseExportDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:2108:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.1.0 postinstall: `umi g tmp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@4.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhang\AppData\Roaming\npm-cache\_logs\2020-07-17T15_00_34_785Z-debug.log
⨯ zhang@DESKTOP-1A8U3VS  D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro   master ≣                                                                                                                      [23:00]
❯ npm list -g typescript
D:\MyDevelopWorkspace\nodejs
`-- (empty)

⨯ zhang@DESKTOP-1A8U3VS  D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro   master ≣                                                                                                                      [23:00]
❯ npm list typescript
ant-design-pro@4.1.0 D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro
+-- @ant-design/pro-cli@1.0.19
| +-- node-import-ts@1.0.5
| | `-- typescript@3.7.2  deduped
| `-- typescript@3.7.2
+-- @umijs/fabric@2.2.2
| `-- typescript@3.9.7
`-- @umijs/plugin-blocks@2.2.1
  `-- @umijs/block-sdk@2.2.1
    `-- umi-uni18n@1.1.7
      `-- typescript@3.7.2  deduped

zhang@DESKTOP-1A8U3VS  D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro   master ≣                                                                                                                        [23:01]
❯ umi
D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\config\defaultSettings.ts: Unexpected token (24:12)

  22 | };
  23 | 
> 24 | export type { DefaultSettings };
     |             ^
  25 | 
  26 | export default proSettings;
  27 | 
SyntaxError: D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\config\defaultSettings.ts: Unexpected token (24:12)

  22 | };
  23 | 
> 24 | export type { DefaultSettings };
     |             ^
  25 | 
  26 | export default proSettings;
  27 | 
    at Object._raise (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\location.js:233:45)
    at Object.raiseWithData (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\location.js:228:17)
    at Object.raise (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\location.js:212:17)
    at Object.unexpected (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\util.js:149:16)
    at Object.parseIdentifierName (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\expression.js:2092:18)
    at Object.parseIdentifier (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\parser\expression.js:2059:23)
    at Object.tsParseTypeAliasDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:1171:22)
    at Object.tsParseDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:1547:25)
    at Object.tsTryParseExportDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:1451:19)
    at Object.parseExportDeclaration (D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro\node_modules\@babel\parser\src\plugins\typescript\index.js:2108:28)
⨯ zhang@DESKTOP-1A8U3VS  D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro   master ≣                                                                                                                      [23:01]
❯ npm list umi
ant-design-pro@4.1.0 D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro
`-- umi@3.2.10

zhang@DESKTOP-1A8U3VS  D:\MyDevelopWorkspace\code\WebstormProjects\ant-design-pro   master ≣                                                                                                                        [23:02]
❯

### 📷 复现步骤

1. 从仓库git clone master代码
2. powershell 执行npm i
or
run umi
### 🏞 期望结果

解决安装报错的问题

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.1.0]
- umi 版本 3.2.10
- 浏览器环境
- 开发环境 win10
- typescript@3.8.2（webstorm bundled）
- node@12.18.2
### 🚑 其他信息

1. 未安装全局的typescript
2. 未安装yarn

**Comment by chenshuai2144** [comment]
升级一下你的 ts 的版本，export type 是 3.8 的 ts 才支持的高级功能

**Comment by YuzhiZhang** [comment]
> 升级一下你的 ts 的版本，export type 是 3.8 的 ts 才支持的高级功能
我本地webstorm bundled的ts版本就是3.8.2的

**Comment by YuzhiZhang** [comment]
> 升级一下你的 ts 的版本，export type 是 3.8 的 ts 才支持的高级功能

我本地webstorm bundled的ts版本就是3.8.2的

**Comment by YuzhiZhang** [comment]
> 升级一下你的 ts 的版本，export type 是 3.8 的 ts 才支持的高级功能

试了安装最新3.9.7，也是一样的报错，这个应该不是ts版本的问题，是执行umi的脚本就会报这个错，win和Mac无一例外
![1595259284(1)](https://user-images.githubusercontent.com/29254365/87956668-e49a6f00-cae1-11ea-91c4-6ef4e91f0ddd.jpg)

**Comment by chenshuai2144** [comment]
Babel的版本呢？也要到最高

**Comment by sagittariusWangjx** [comment]
同样的问题很就了，尽然还没有解决哎

**Comment by YuzhiZhang** [comment]
> Babel的版本呢？也要到最高

babel 版本应该是项目中umi自带的配置，没有安装全局的babel；还需要进行哪些babel设置==
