### ISSUE TITLE
SyntaxError: Unexpected token 🧐[问题]

### ISSUE THREAD

**Issue by Chunghwa-2018** [ant-design/ant-design-pro#7036]
### 🧐 问题描述

使用antd pro 一段时间，之后重新启动 出现 SyntaxError: Unexpected token 错误，然后使用npm install 也是同样的错误，
发现问题发生在 umi g tmp， 当 npm install 执行到 umi g tmp 就会发生  SyntaxError: Unexpected token

### 💻 示例代码

yarn start / npm start   

npm install 
 
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29922837/87871410-994d6700-c9e2-11ea-8874-d926d150ffcc.png)

![image](https://user-images.githubusercontent.com/29922837/87871406-93f01c80-c9e2-11ea-806e-e647463c7e92.png)

**Comment by Chunghwa-2018** [comment]
$ yarn start 
                                                                                         
yarn run v1.22.4
$ umi dev
Unexpected token (3:8)
SyntaxError: Unexpected token (3:8)
    at Object._raise (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:60:45)
    at Object.raiseWithData (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:55:17)
    at Object.raise (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:39:17)
    at Object.unexpected (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/util.js:152:16)
    at Object.parseIdentifierName (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:2185:18)
    at Object.parseIdentifier (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:2154:23)
    at Object.parseImportSpecifier (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/statement.js:2230:31)
    at Object.parseNamedImportSpecifiers (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/statement.js:2224:12)
    at Object.parseImport (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/statement.js:2084:39)
    at Object.parseImport (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/plugins/typescript/index.js:1892:32)
✨  Done in 2.48s.

**Comment by Chunghwa-2018** [comment]
$ npm install

> ant-design-pro@4.1.0 postinstall /Users/zhaohongliang/WebstormProjects/ant-design-pro
> umi g tmp

Unexpected token (3:8)
SyntaxError: Unexpected token (3:8)
    at Object._raise (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:60:45)
    at Object.raiseWithData (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:55:17)
    at Object.raise (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/error.js:39:17)
    at Object.unexpected (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/util.js:152:16)
    at Object.parseIdentifierName (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:2185:18)
    at Object.parseIdentifier (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/expression.js:2154:23)
    at Object.parseImportSpecifier (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/statement.js:2230:31)
    at Object.parseNamedImportSpecifiers (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/statement.js:2224:12)
    at Object.parseImport (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/parser/statement.js:2084:39)
    at Object.parseImport (/Users/zhaohongliang/WebstormProjects/ant-design-pro/node_modules/@umijs/utils/node_modules/@babel/parser/src/plugins/typescript/index.js:1892:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.1.0 postinstall: `umi g tmp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@4.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhaohongliang/.npm/_logs/2020-07-19T09_04_05_977Z-debug.log

**Comment by sorrycc** [comment]
给复现方式。

**Comment by Chunghwa-2018** [comment]
我自己已经复现多次，具体操作是什么导致的还不清楚。但是我能告诉你的是，我删除当前修改的文件、或者文件夹，重新构建和启动是正常的！如果我在webstorm这种工具上，我可以回退代码，回退到可以正常构建和启动的代码记录。 如果我用vscode等其它工具，我就不清楚到底是哪个文件导致的，只能删除当前编辑的目录。

**Comment by meng1932** [comment]
重复出现多次+1

**Comment by lightning-zgc** [comment]
Same issue. In my case, I wrote the JSX `<.../>` incorrectly in the `.js` file (in `src/models`).

**Comment by aminsky00** [comment]
出现了，启动就报Error: Dva model src/index.tsx parse failed, SyntaxError: Unexpected token, expected ","把文件删掉就没问题
