### ISSUE TITLE
umiv3.0 less引入alias图片编辑出错🧐[问题]

### ISSUE THREAD

**Issue by zzj0401** [ant-design/ant-design-pro#7039]
### 🧐 问题描述

umiv3.0 less引入alias图片编辑出错

### 💻 示例代码

```shell
 error  in ./src/pages/documents/components/CategoryDragDrop/index.less?modules

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './@/assets/PNG/delete.png' in 'C:\Users\Administrator\Desktop\another_pro\src\pages\documents\components\CategoryDragDrop'
    at C:\Users\Administrator\Desktop\another_pro\node_modules\webpack\lib\Compilation.js:925:10
    at C:\Users\Administrator\Desktop\another_pro\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at C:\Users\Administrator\Desktop\another_pro\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at C:\Users\Administrator\Desktop\another_pro\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at C:\Users\Administrator\Desktop\another_pro\node_modules\neo-async\async.js:2830:7
    at C:\Users\Administrator\Desktop\another_pro\node_modules\neo-async\async.js:6877:13
    at C:\Users\Administrator\Desktop\another_pro\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at C:\Users\Administrator\Desktop\another_pro\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at C:\Users\Administrator\Desktop\another_pro\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Administrator\Desktop\another_pro\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\Administrator\Desktop\another_pro\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at C:\Users\Administrator\Desktop\another_pro\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Administrator\Desktop\another_pro\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\Administrator\Desktop\another_pro\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (C:\Users\Administrator\Desktop\another_pro\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\Administrator\Desktop\another_pro\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
```
关键less的引入图片部分

```less
// ./src/pages/documents/components/CategoryDragDrop/index.less

.xxx{
  &-delete {
    -webkit-mask: url('@/assets/PNG/delete.png') no-repeat;
    mask: url('@/assets/PNG/delete.png') no-repeat;
  }
}
```

### 希望解决的问题
可以正常使用 alias

**Comment by chenshuai2144** [comment]
@ 是 webpack 支持的，你要写全路径，不支持在 less 中使用别名
