### ISSUE TITLE
Unit tests for Dva connect wrapped components always fail🐛[BUG]

### ISSUE THREAD

**Issue by zsxing99** [ant-design/ant-design-pro#7055]
### 🐛 bug 描述

对于使用 connect 的组件无法测试， 已看文档， 复现代码与文档一致， 这个 bug 被提过没人解决

### 📷 复现步骤

对任意使用 connect 的组件进行 unit test， 例如下面 git repo 对于 Login 写了一个测试

### 🏞 期望结果

正常运行

### 💻 复现代码

https://github.com/zsxing99/Antd-Pro-Unit-Test-Bug

只在 umi 的基础上增加了一个 `.test.js` 文件

### © 版本信息

```
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.1.11",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.0.0",
    "@antv/l7-maps": "^2.0.0",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.isequal": "^4.5.5",
    "antd": "^4.0.0",
    "bizcharts": "^3.5.3-beta.0",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.0",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "mockjs": "^1.0.1-beta3",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "prop-types": "^15.5.10",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.4",
    "react-router": "^4.3.1",
    "umi": "^3.0.14",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
```

### 🚑 其他信息

`npm test`

```
src/pages/user/test/Login.test.js
  ● Test suite failed to run

    TypeError: (0 , _umi.connect) is not a function

      121 | };
      122 | 
    > 123 | export default connect(({ userAndlogin, loading }) => ({
          |                ^
      124 |   userAndlogin,
      125 |   submitting: loading.effects['userAndlogin/login'],
      126 | }))(Login);

      at Object.<anonymous> (src/pages/user/login/index.jsx:123:16)
      at Object.<anonymous> (src/pages/user/test/Login.test.js:3:1)
```

最主要是这行怎么处理
`TypeError: (0 , _umi.connect) is not a function`

**Comment by chenshuai2144** [comment]
这个老问题了，去 umi 问一下?
别名和 mock 也不支持使用，可能要用 e2e 了

**Comment by zsxing99** [comment]
好 谢谢

[文档](https://pro.ant.design/docs/ui-test)更新一下? 一头栽进去 @-@
