### ISSUE TITLE
🧐[问题]区块模式下添加模板提示【ENOENT: no such file or directory, open 'config/config.js】

### ISSUE THREAD

**Issue by XiaoKowloon** [ant-design/ant-design-pro#7060]
### 🧐 问题描述

正常安装启动成功后，区块模式下添加模板提示【ENOENT: no such file or directory, open 'config/config.js】

Execute task error Error: Error: ENOENT: no such file or directory, open 'config/config.js'
    at F:\qianduancode\monitor\monitor\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:89:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\qianduancode\monitor\monitor\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:46:103)
    at _next (F:\qianduancode\monitor\monitor\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:48:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by XiaoKowloon** [comment]
1
