### ISSUE TITLE
🧐[问题]  **code: 'BABEL_PARSE_ERROR'**

### ISSUE THREAD

**Issue by hellozhang** [ant-design/ant-design-pro#7063]
🚚 clone success
> [Sylvanas] Prepare js environment...
events.js:288
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Unexpected token (24:12)

  22 | };
  23 |
> 24 | export type { DefaultSettings };
     |             ^
  25 |
  26 | export default proSettings;
  27 |
    at Object._raise (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:723:17)
    at Object.raiseWithData (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:716:17)
    at Object.raise (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:710:17)
    at Object.unexpected (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:8610:16)
    at Object.parseIdentifierName (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:10583:18)
    at Object.parseIdentifier (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:10561:23)
    at Object.tsParseTypeAliasDeclaration (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:5851:20)
    at Object.tsParseDeclaration (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:6174:23)
    at Object.tsTryParseExportDeclaration (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:6079:17)
    at Object.parseExportDeclaration (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\@babel\parser\lib\index.js:6557:26)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (C:\Users\ZH\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:1007:20)
    at processImmediate (internal/timers.js:456:21) {
  loc: Position { line: 24, column: 12 },
  pos: 459,

>   **code: 'BABEL_PARSE_ERROR'**

}
error Command failed.
Exit code: 1
Command: C:\Users\ZH\AppData\Local\Yarn\bin\create-umi
Arguments:
Directory: F:\ReactANT\Ant

**Comment by chenshuai2144** [comment]
升级一下babel的版本吧，看来要搞个在线版本了，不然总是有这种本地的全局安装版本问题
