### ISSUE TITLE
🐛[BUG]基于create-umi创建的antd-pro v4空工程无法通过test:all测试

### ISSUE THREAD

**Issue by yisiqi** [ant-design/ant-design-pro#7080]
### 🐛 bug 描述

使用create-umi创建的antd pro v4工程模板无法通过完整的测试（yarn test:all失败）

### 📷 复现步骤

node：v12.13.0
yarn：1.22.0
typescritp: 3.9.7

```shell
$ yarn create umi
...
$ yarn
...
$ PUPPETEER_DOWNLOAD_HOST=https://storage.googleapis.com.cnpmjs.org yarn test:all
yarn run v1.22.0
$ node ./tests/run-tests.js
Starting development server for e2e tests...
npm
 WARN lifecycle The node binary used for scripts is /tmp/yarn--1595588179053-0.8711497356802547/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.


> ant-design-pro@4.2.0 start /build/api-gateway-statics
> umi dev


Cannot find module 'react'
Require stack:
- /build/api-gateway-statics/node_modules/react-router/cjs/react-router.js
- /build/api-gateway-statics/node_modules/react-router/index.js
- /build/api-gateway-statics/node_modules/react-router-dom/cjs/react-router-dom.js
- /build/api-gateway-statics/node_modules/react-router-dom/index.js
- /build/api-gateway-statics/node_modules/@umijs/runtime/dist/index.js
- /build/api-gateway-statics/node_modules/umi/lib/cjs.js
- /build/api-gateway-statics/node_modules/umi/index.js
- /build/api-gateway-statics/config/config.ts
- /build/api-gateway-statics/node_modules/@umijs/core/lib/Config/Config.js
- /build/api-gateway-statics/node_modules/@umijs/core/lib/index.js
- /build/api-gateway-statics/node_modules/umi/lib/ServiceWithBuiltIn.js
- /build/api-gateway-statics/node_modules/umi/lib/forkedDev.js

Error: Cannot find module 'react'
Require stack:
- /build/api-gateway-statics/node_modules/react-router/cjs/react-router.js
- /build/api-gateway-statics/node_modules/react-router/index.js
- /build/api-gateway-statics/node_modules/react-router-dom/cjs/react-router-dom.js
- /build/api-gateway-statics/node_modules/react-router-dom/index.js
- /build/api-gateway-statics/node_modules/@umijs/runtime/dist/index.js
- /build/api-gateway-statics/node_modules/umi/lib/cjs.js
- /build/api-gateway-statics/node_modules/umi/index.js
- /build/api-gateway-statics/config/config.ts
- /build/api-gateway-statics/node_modules/@umijs/core/lib/Config/Config.js
- /build/api-gateway-statics/node_modules/@umijs/core/lib/index.js
- /build/api-gateway-statics/node_modules/umi/lib/ServiceWithBuiltIn.js
- /build/api-gateway-statics/node_modules/umi/lib/forkedDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/build/api-gateway-statics/node_modules/react-router/cjs/react-router.js:5:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._compile (/build/api-gateway-statics/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.newLoader [as .js] (/build/api-gateway-statics/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

### 🏞 期望结果

应当成功完成测试

### 💻 复现代码

基于docker镜像（yisiqi/antd-pro-builder:lts）执行上述命令

### © 版本信息

- Ant Design Pro 版本：4.2.0
- umi 版本：^3.2.0
- 浏览器环境：puppeteer@^5.2.1
- 开发环境：mac OS 10.15.5，Docker 19.03.8

**Comment by chenshuai2144** [comment]
先安装依赖？

**Comment by yisiqi** [comment]
@chenshuai2144 执行过yarn了，node_modules里能看到react包

> 先安装依赖？

**Comment by chenshuai2144** [comment]
是不是有lock什么的  clean -dfx然后重新安装一下这种问题一般都是依赖没装对

**Comment by yisiqi** [comment]
> 是不是有lock什么的 clean -dfx然后重新安装一下这种问题一般都是依赖没装对

每次都是使用docker创建的全新环境，只挂在git签出的原始工程，按说跟缓存什么的没关系
