### ISSUE TITLE
🐛[BUG]只安装生产依赖，打包后报错

### ISSUE THREAD

**Issue by LbhFront-end** [ant-design/ant-design-pro#7126]
### 🐛 bug 描述

只安装生产依赖，打包后报错

### 📷 复现步骤

1.从官方clone项目，
2.docker 运行安装依赖，并后续执行打包命令，
3.报错，报错内容需要的依赖在开发环境里面

### 🏞 期望结果

只安装生产依赖，可以打包

### 💻 复现代码
Dockerfile:

```dockerfile
FROM node:12.6.0-alpine as builder

WORKDIR /home/app/np
ADD package.json /home/app/np

USER root

RUN  npm install --registry=https://registry.npm.taobao.org --production

ADD . /home/app/np

EXPOSE 3000

CMD ["npm", "run", "build"]

```

安装过程：

```shell
FROM node:12.6.0-alpine as builder

WORKDIR /home/app/np
ADD package.json /home/app/np

USER root

RUN  npm install --registry=https://registry.npm.taobao.org --production

ADD . /home/app/np

EXPOSE 3000

CMD ["npm", "run", "build"]

```

打包后报错内容:

```shell
2020-08-01T02:44:59.274057119Z 
> ant-design-pro@4.2.0 build /home/app/np
> umi build
2020-08-01T02:44:59.274114487Z 
Cannot find module '@umijs/preset-ant-design-pro' from '/home/app/np'
Error: Cannot find module '@umijs/preset-ant-design-pro' from '/home/app/np'
    at Function.resolveSync [as sync] (/home/app/np/node_modules/resolve/lib/sync.js:89:15)
    at /home/app/np/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:90:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (/home/app/np/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
    at resolvePresets (/home/app/np/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:169:23)
    at new Service (/home/app/np/node_modules/@umijs/core/lib/Service/Service.js:181:59)
    at new Service (/home/app/np/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at /home/app/np/node_modules/umi/lib/cli.js:98:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/app/np/node_modules/umi/lib/cli.js:53:103)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.2.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@4.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-08-01T02:45:00.449296202Z 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-01T02_45_00_446Z-debug.log
```
### © 版本信息

- Ant Design Pro 版本: [4.2.0]
- umi 3.2.13
- 浏览器环境 谷歌
- 开发环境 [docker ubuntu]

### 🚑 其他信息

报错内容：
![image](https://user-images.githubusercontent.com/30042334/89092509-026eaa80-d3e5-11ea-8f5d-aca67c4d88a8.png)

**Comment by chenshuai2144** [comment]
额，脚手架项目的生产和开发分界线不明显，一般开发里面的都是 webpack 和 node 系的，最好全部安装。
umi 有些插件是 runtime 和 node 公用的
