### ISSUE TITLE
🐛[BUG] Cannot run when project path contains special characters

### ISSUE THREAD

**Issue by jsonbruce** [ant-design/ant-design-pro#7148]
### 🐛 bug 描述

执行 `npm start` 报错:

```
Starting the development server...
Cannot find module '/Users/test/Ant/Users/test/Ant@Design/srcDesign/src/layouts/BlankLayout'
Require stack:
- /Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/utils.js
- /Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/index.js
- /Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/index.js
- /Users/test/Ant@Design/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js
- /Users/test/Ant@Design/node_modules/@umijs/core/lib/Service/Service.js
- /Users/test/Ant@Design/node_modules/@umijs/core/lib/index.js
- /Users/test/Ant@Design/node_modules/umi/lib/ServiceWithBuiltIn.js
- /Users/test/Ant@Design/node_modules/umi/lib/forkedDev.js
Error: Cannot find module '/Users/test/Ant/Users/test/Ant@Design/srcDesign/src/layouts/BlankLayout'
Require stack:
- /Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/utils.js
- /Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/index.js
- /Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/index.js
- /Users/test/Ant@Design/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js
- /Users/test/Ant@Design/node_modules/@umijs/core/lib/Service/Service.js
- /Users/test/Ant@Design/node_modules/@umijs/core/lib/index.js
- /Users/test/Ant@Design/node_modules/umi/lib/ServiceWithBuiltIn.js
- /Users/test/Ant@Design/node_modules/umi/lib/forkedDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.resolve (internal/modules/cjs/helpers.js:81:19)
    at /Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/utils.js:55:75
    at Array.reduce (<anonymous>)
    at getComponents (/Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/utils.js:48:42)
    at getRouteComponents (/Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/utils.js:66:22)
    at Object.<anonymous> (/Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/index.js:80:61)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/index.js:60:103)
    at _next (/Users/test/Ant@Design/node_modules/@umijs/plugin-ui-blocks/lib/ui/index.js:62:194)
```

### 📷 复现步骤

在包含 `@` 符号的空目录(如 `/Users/test/Ant@Design/`) 执行 `npm create umi`
初始化完成后执行 `npm install && npm start` 报错.

### 🏞 期望结果

能正常运行.

### 💻 复现代码

```
npm create umi
npm install
npm start
```

### © 版本信息

- Ant Design Pro 版本: `4.4.0`
- umi 版本: `3.2.14`
- 浏览器环境: `Chrome 83.0.4103.116`
- 开发环境: `macOS 10.15.6`

### 🚑 其他信息

经测试，仅当路径包含 `@` 符号时会出现这个 BUG, 其它情况正常.

**Comment by chenshuai2144** [comment]
@sorrycc 这种的需要支持一下吗？

**Comment by chenshuai2144** [comment]
暂时不会支持的，你有兴趣可以提 pr 来帮忙解决掉这个问题。

建议换个名字

**Comment by bonkboykz** [comment]
Hello!

The issue with special characters, like '@' symbol, in the path to the project still persist
