### ISSUE TITLE
🧐[问题] There appears to be trouble with your network connection. Retrying..

### ISSUE THREAD

**Issue by orchie** [ant-design/ant-design-pro#7184]
### 🧐 问题描述
在 yarn create umi my-app 之后 
执行 yarn 时 
安装了部分package后 会提示 
 There appears to be trouble with your network connection. Retrying...

![image](https://user-images.githubusercontent.com/29848298/90008576-26789880-dccf-11ea-8b2e-e841c5353761.png)

### 💻 示例代码
尝试过 设置 npm 和yarn的源 
 yarn config set registry https://registry.npm.taobao.org
也尝试过 设置 proxy 
还尝试过 在mac上执行 
都是这个错
没招了....hello world都跑不出来....help

### 🚑 其他信息
LOG TRACE
```
Trace: 
  Error: https://registry.npm.taobao.org/@ant-design%2ficons: tunneling socket could not be established, cause=write EPROTO 27112:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
  
      at ClientRequest.onError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:152234:17)
      at Object.onceWrapper (events.js:421:26)
      at ClientRequest.emit (events.js:314:20)
      at TLSSocket.socketErrorListener (_http_client.js:469:9)
      at TLSSocket.emit (events.js:314:20)
      at emitErrorNT (internal/streams/destroy.js:100:8)
      at emitErrorCloseNT (internal/streams/destroy.js:68:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by mtbadi39** [comment]
Hi
same issue !

**Comment by chenshuai2144** [comment]
try use tyarn or cnpm

**Comment by joket1999** [comment]
修改 ~/.config/yarn/global(windows的应该在用户文件夹)里的yarn.lock， 统一把里面所有依赖的源域名地址改成https://registry.npm.taobao.org的或者https://registry.yarnpkg.com
