### ISSUE TITLE
选择v4，simple，JS版本create成功后，install失败🧐[问题]

### ISSUE THREAD

**Issue by xsfirst** [ant-design/ant-design-pro#7243]
### 🧐 问题描述
选择v4，simple，JS版本create成功后，install失败
```
? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ? Pro V4
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! antd@4
```

```
> ant-design-pro@4.2.0 postinstall /work/demo/self_node_modules/react_antd_pages
> umi g tmp

Unexpected token {
/work/demo/self_node_modules/react_antd_pages/config/config.js:2
import { defineConfig } from 'umi';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Module._compile (/work/demo/self_node_modules/react_antd_pages/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.newLoader [as .js] (/work/demo/self_node_modules/react_antd_pages/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /work/demo/self_node_modules/react_antd_pages/node_modules/@umijs/core/lib/Config/Config.js:226:69
    at Array.map (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.2.0 postinstall: `umi g tmp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@4.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by liangxp** [comment]
一直没有成功过！
