### ISSUE TITLE
🐛[BUG] yarn create umi 选择javascript环境报错

### ISSUE THREAD

**Issue by lynshir** [ant-design/ant-design-pro#7247]
### 🐛 bug 描述

```
[Sylvanas] Prepare js environment...
events.js:174
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Support for the experimental syntax 'optionalChaining' isn't currently enabled (60:18):

  58 |     if (ref.current) {
  59 |       // eslint-disable-next-line no-unused-expressions
> 60 |       ref.current?.focus();
     |                  ^
  61 |     }
  62 |   };
  63 |

Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation.

 at Object.raise (/Users/xxx/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.expectPlugin (/Users/xxx/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7647:18)
    at Object.parseSubscript (/Users/xxx/.config/yarn/global/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8447:12)
...
```

### 📷 复现步骤

1.`yarn create umi`
2. `select Pro V4`
3. `complete scaffold`

### 🏞 期望结果

期望正常安装

### © 版本信息

- Ant Design Pro 版本: 4.0
- umi 版本 3.2.0
- 浏览器环境
- 开发环境  mac os

### 🚑 其他信息

node 12.18.1

**Comment by liangxp** [comment]
卧槽  一样的错误，求解决

**Comment by zcSkr** [comment]
已经很久了、而且选择javascript，生成的模板还是tsx的文件
