### ISSUE TITLE
🐛[BUG] ant pro v4 js环境新安装报错Error: Failed to load plugin 'eslint-comments' declared in 'BaseConfig

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design-pro#7290]
### 🐛 bug 描述
ant pro4 js环境安装不了了，按照默认流程下来，提示umi缺少模块
报错如下
> 有很多都报这个错误，这里只截一小段 Error: Failed to load plugin 'eslint-comments' declared in 'BaseConfig
```
Error: Failed to load plugin 'eslint-comments' declared in 'BaseConfig » /Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/@umijs/fabric/dist/eslint.js': Cannot find module 'eslint-plugin-eslint-comments'
Require stack:
- /Library/WebServer/Documents/cn.51baopen/admin/v1.04/__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.resolve (internal/modules/cjs/helpers.js:81:19)
    at Object.resolve (/Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/eslint/lib/shared/relative-module-resolver.js:40:50)
    at ConfigArrayFactory._loadPlugin (/Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/eslint/lib/cli-engine/config-array-factory.js:1004:39)
    at /Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/eslint/lib/cli-engine/config-array-factory.js:895:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/eslint/lib/cli-engine/config-array-factory.js:891:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/eslint/lib/cli-engine/config-array-factory.js:719:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/eslint/lib/cli-engine/config-array-factory.js:659:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Library/WebServer/Documents/cn.51baopen/admin/v1.04/__placeholder__.js'
  ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: 'eslint-plugin-eslint-comments',
    resolvePluginsRelativeTo: '/Library/WebServer/Documents/cn.51baopen/admin/v1.04',
    importerName: 'BaseConfig » /Users/liwei/.npm/_npx/51710/lib/node_modules/create-umi/node_modules/@umijs/fabric/dist/eslint.js'
  }
}
```

### 📷 复现步骤
仅安装pro4 js环境

### 🏞 期望结果
应该不报错

### 💻 复现代码
```
npm create umi
? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ? Pro V4
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! antd@4
```

### © 版本信息

- Ant Design Pro 版本: Pro V4
- umi 版本：umi@3
- 浏览器环境：不需要浏览器
- 开发环境：mac OS

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/578141/91836207-0d835780-ec7d-11ea-9c3f-f34b40c559c0.png)

**Comment by chenshuai2144** [comment]
@aiyuchen  使用 yarn create 

或者 npm remove create-umi 然后再进行安装

**Comment by compasss** [comment]
yarn create 出现同样问题

**Comment by chenshuai2144** [comment]
`npm remove create-umi ` 一下，你需要拉最新的 umi-create

**Comment by jacobsun** [comment]
yarn create 出现同样问题

**Comment by Vaneste** [comment]
Hi @jacobsun & @compasss 
Let's says you followed the command on pro.ant.design (let's pro section) : 
_yarn create umi my-app_
=> you got all this messages about eslint-comments
What you could do is : 

_cd my-app
npm remove create-umi_
then, still in my-app folder : 
_yarn start_    
wait for some - long - time and then you'll get:

App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.1.177:8000

Hope this helps _:)_
