### ISSUE TITLE
🐛[BUG]npm create umi  创建报错

### ISSUE THREAD

**Issue by superDuo** [ant-design/ant-design-pro#7366]
1、新建文件夹umi
2、cd umi 执行npm create umi
3、选择 ant-design-pro 
![123123123](https://user-images.githubusercontent.com/47852410/93590685-899dcf00-f9e1-11ea-8938-0e188a4b5abe.png)

**Comment by chenshuai2144** [comment]
是不是node版本太低导致的。

**Comment by RobinGitHub** [comment]
`yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@umijs/create-umi-app > @umijs/utils > @babel/register@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@3.10.1" has unmet peer dependency "@typescript-eslint/parser@^3.0.0".
warning "create-umi > sylvanas > @umijs/fabric > eslint-config-airbnb@18.2.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^6.3.0".
warning "create-umi > sylvanas > @umijs/fabric > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
[4/4] Building fresh packages...
success Installed "create-umi@0.25.0" with binaries:
? Select the boilerplate type ant-design-pro
? �🧙 Be the first to experience the new umi@3 ? Pro V4
? �🤓 Which language do you want to use? TypeScript
? �🚀 Do you need all the blocks or a simple scaffold? comple
> �🙈 complete mode can only use the version of antd
Cloning into 'E:\repos\React\antComplexV4'...
remote: Enumerating objects: 564, done.
remote: Counting objects: 100% (564/564), done.
remote: Compressing objects: 100% (481/481), done.
remote: Total 564 (delta 88), reused 318 (delta 62), pack-reused 0 eceiving objects:  99% (559/564), 372.00 KiB | 358.00 KiB/s
Receiving objects: 100% (564/564), 461.55 KiB | 379.00 KiB/s, done.
Resolving deltas: 100% (88/88), done.
> �🚚 clone succe
> Clean up...
events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: EBUSY: resource busy or locked, unlink 'E:\repos\React\antComplexV4\.git\objects\pack\tmp_pack_YaQwna'
    at Object.unlinkSync (fs.js:1035:3)
    at rimrafSync (C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:254:15)
    at C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at rimrafSync (C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (C:\Users\huawei\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\index.js:924:20)
    at processImmediate (internal/timers.js:439:21) {
  errno: -4082,
  syscall: 'unlink',
  code: 'EBUSY',
  path: 'E:\\repos\\React\\antComplexV4\\.git\\objects\\pack\\tmp_pack_YaQwna'
}
error Command failed.
Exit code: 1`

我刚刚创建的也报错

**Comment by GeorgeChen-666** [comment]
好久没用了，最近发现更新了使用umi了，感觉乱糟糟的，一会yarn一会npm，umi老报错，感觉以前挺好的，umi这个玩意很优秀么？

**Comment by chenshuai2144** [comment]
@RobinGitHub  文件死锁了，换个目录吧

**Comment by chenshuai2144** [comment]
> 好久没用了，最近发现更新了使用umi了，感觉乱糟糟的，一会yarn一会npm，umi老报错，感觉以前挺好的，umi这个玩意很优秀么？

用yarn 和 npm 是因为 npm 有很多奇怪的设计，我们希望用 yarn ，yarn 的体验更好。

umi 可以减少很多配置，pro的底座就是umi
