### ISSUE TITLE
创建初始化失败报错🐛[BUG]

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design-pro#7395]
### 🐛 bug 描述

使用yarn create umi或npm create umi，选择antdesign-pro,执行过程报错，创建项目失败
### 📷 复现步骤

PS E:\antdesign-workspace> yarn create umi                                                                              yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@3.10.1" has unmet peer dependency "@typescript-eslint/parser@^3.0.0".
[4/4] Building fresh packages...
success Installed "create-umi@0.25.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
(node:6616) UnhandledPromiseRejectionWarning: C:\Users\dream\AppData\Local\Yarn\Data\global\node_modules\eslint\lib\cli-engine\cli-engine.js:406
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\dream\AppData\Local\Yarn\Data\global\node_modules\eslint\lib\cli-engine\index.js:3:23)
(node:6616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 22.18s.
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]   win10

**Comment by chengzequn** [comment]
是我nodejs版本太低了
