### ISSUE TITLE
pro V5 run build error

### ISSUE THREAD

**Issue by lattemj** [ant-design/ant-design-pro#7462]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@5.0.0-beta.0~prebuild: ant-design-pro@5.0.0-beta.0
6 info lifecycle ant-design-pro@5.0.0-beta.0~build: ant-design-pro@5.0.0-beta.0
7 verbose lifecycle ant-design-pro@5.0.0-beta.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@5.0.0-beta.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\**********\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Redis\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Users\**********\AppData\Local\Microsoft\WindowsApps;;C:\Users\**********\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\**********\AppData\Roaming\npm;C:\Users\**********\AppData\Local\Yarn\bin;C:\Users\**********\.dotnet\tools
9 verbose lifecycle ant-design-pro@5.0.0-beta.0~build: CWD: D:\**********
10 silly lifecycle ant-design-pro@5.0.0-beta.0~build: Args: [ '/d /s /c', 'umi build' ]
11 silly lifecycle ant-design-pro@5.0.0-beta.0~build: Returned: code: 134  signal: null
12 info lifecycle ant-design-pro@5.0.0-beta.0~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@5.0.0-beta.0 build: `umi build`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid ant-design-pro@5.0.0-beta.0
15 verbose cwd D:\*********
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 134
22 error ant-design-pro@5.0.0-beta.0 build: `umi build`
22 error Exit status 134
23 error Failed at the ant-design-pro@5.0.0-beta.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

**Comment by lattemj** [comment]
问题解决，由于项目过大，设置了全局内存： setx  /M  NODE_OPTIONS --max_old_space_size=10240   （10GB）才编译通过，遇到此问题的朋友打开性能查看编译时的资源消耗
