### ISSUE TITLE
package.json npm install 出来的node_modules包少了@babel/core这个目录

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design-pro#775]
package.json npm install 出来的node_modules包少了@babel/core这个目录
之前npm install 的时候是有的
```
{
  "name": "ant-design-pro",
  "version": "1.0.1",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "cross-env DISABLE_ESLINT=true roadhog dev",
    "start:no-proxy": "cross-env NO_PROXY=true DISABLE_ESLINT=true roadhog dev",
    "build": "cross-env DISABLE_ESLINT=true roadhog build",
    "site": "roadhog-api-doc static && gh-pages -d dist",
    "analyze": "cross-env ANALYZE=true roadhog build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "roadhog test",
    "test:component": "roadhog test ./src/components",
    "test:all": "node ./tests/run-tests.js"
  },
  "dependencies": {
    "@antv/data-set": "^0.8.0",
    "@babel/polyfill": "^7.0.0-beta.36",
    "antd": "^3.1.0",
    "babel-runtime": "^6.9.2",
    "bizcharts": "^3.1.0-beta.4",
    "bizcharts-plugin-slider": "^2.0.1",
    "classnames": "^2.2.5",
    "dva": "^2.1.0",
    "dva-loading": "^1.0.4",
    "enquire-js": "^0.1.1",
    "fastclick": "^1.0.6",
    "lodash": "^4.17.4",
    "lodash-decorators": "^4.4.1",
    "moment": "^2.19.1",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "rc-drawer-menu": "^0.5.0",
    "react": "^16.2.0",
    "react-container-query": "^0.9.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.2.0",
    "react-fittext": "^1.0.0",
    "url-polyfill": "^1.0.10"
  },
  "devDependencies": {
    "babel-eslint": "^8.1.2",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.1.0",
    "eslint": "^4.14.0",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-compat": "^2.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.0.1",
    "gh-pages": "^1.0.0",
    "husky": "^0.14.3",
    "lint-staged": "^6.0.0",
    "mockjs": "^1.0.1-beta3",
    "pro-download": "^1.0.1",
    "redbox-react": "^1.5.0",
    "regenerator-runtime": "^0.11.1",
    "roadhog": "^2.1.0",
    "roadhog-api-doc": "^0.3.4",
    "rollbar": "^2.3.4",
    "stylelint": "^8.4.0",
    "stylelint-config-standard": "^18.0.0"
  },
  "optionalDependencies": {
    "nightmare": "^2.10.0"
  },
  "lint-staged": {
    "**/*.{js,jsx}": "lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}

```

**Comment by afc163** [comment]
@babel/core 在生产环境不是必须的。

**Comment by smithyj** [comment]
意思是说得全局装？ @afc163

**Comment by afc163** [comment]
你不需要这个库。

**Comment by smithyj** [comment]
没有这个库就会报错 @afc163

**Comment by afc163** [comment]
报了什么错，直接描述问题、环境和重现步骤。

**Comment by smithyj** [comment]
这是报错的问题项目：https://github.com/smithyj/backend.yangyj.com
报错提示：
```
➜  backend.yangyj.com git:(master) npm start

> @ start /Users/yyj/Docker/www/frontend/backend.yangyj.com
> roadhog dev

module.js:557
    throw err;
    ^

Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yyj/Docker/www/frontend/backend.yangyj.com/node_modules/@babel/register/lib/cache.js:16:37)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yyj/Docker/www/frontend/backend.yangyj.com/node_modules/@babel/register/lib/node.js:11:45)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

```

**Comment by smithyj** [comment]
解决了，要全局安装roadhog才可以

**Comment by ychow** [comment]
我在npm run build 时，会提示缺少@babel/core 模块，导致编译失败。









![1](https://user-images.githubusercontent.com/6530996/37516193-4e419f84-2948-11e8-9921-a0db84ca1e14.jpeg)
