### ISSUE TITLE
🐛[BUG] npm run fetch:blocks | UserRegisterResult don't exists

### ISSUE THREAD

**Issue by zhuangjinxin** [ant-design/ant-design-pro#7796]
### 🐛 bug 描述

```
➜  ant-design-pro git:(master) ✗ cnpm run fetch:blocks
npm WARN npm npm does not support Node.js v12.12.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN npm npm does not support Node.js v12.12.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/

> ant-design-pro@4.5.0 fetch:blocks /Users/USER_NAME/workspace/github/USER_NAME/ant-design-pro
> pro fetch-blocks && npm run prettier

✔ 🧐  find config.ts ...
📦  install login  to: /user/login
WARN [WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json
- 😁  Parse url and args
✔ 😁  Parse url and args
- 🔍  clone git repo from https://gitee.com/ant-design/pro-blocks.git
Cloning into 'github.com/ant-design/pro-blocks'...
👌  install login  to: /user/login success
📦  install register  to: /user/register
WARN [WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json
- 😁  Parse url and args
✔ 😁  Parse url and args
- 🚛  sync file for git repo --branch master
error: pathspec 'master' did not match any file(s) known to git.
✖ 🚛  sync file for git repo --branch master
ℹ  info      发生错误，请尝试 `umi block clear`
✖  error     AssertionError [ERR_ASSERTION]: /Users/USER_NAME/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegister don't exists
    at /Users/USER_NAME/workspace/github/USER_NAME/ant-design-pro/node_modules/_@umijs_block-sdk@2.2.2@@umijs/block-sdk/lib/addBlock.js:222:27
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/USER_NAME/workspace/github/USER_NAME/ant-design-pro/node_modules/_@umijs_block-sdk@2.2.2@@umijs/block-sdk/lib/addBlock.js:110:103)
    at _throw (/Users/USER_NAME/workspace/github/USER_NAME/ant-design-pro/node_modules/_@umijs_block-sdk@2.2.2@@umijs/block-sdk/lib/addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
👌  install register  to: /user/register success
📦  install register.result  to: /user/register-result
WARN [WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json
- 😁  Parse url and args
✔ 😁  Parse url and args
- 🚛  sync file for git repo --branch master
error: pathspec 'master' did not match any file(s) known to git.
✖ 🚛  sync file for git repo --branch master
ℹ  info      发生错误，请尝试 `umi block clear`
✖  error     AssertionError [ERR_ASSERTION]: /Users/USER_NAME/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegisterResult don't exists
    at /Users/USER_NAME/workspace/github/USER_NAME/ant-design-pro/node_modules/_@umijs_block-sdk@2.2.2@@umijs/block-sdk/lib/addBlock.js:222:27
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/USER_NAME/workspace/github/USER_NAME/ant-design-pro/node_modules/_@umijs_block-sdk@2.2.2@@umijs/block-sdk/lib/addBlock.js:110:103)
    at _throw (/Users/USER_NAME/workspace/github/USER_NAME/ant-design-pro/node_modules/_@umijs_block-sdk@2.2.2@@umijs/block-sdk/lib/addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### 📷 复现步骤

新clone本项目，在本项目根目录执行 `npm run fetch:blocks` 即可复现。

### 🏞 期望结果

期望不报错，正确安装 `UserRegister`区块

### 💻 复现代码

根目录执行 `npm run fetch:blocks` 

### © 版本信息

- Ant Design Pro 版本: [v4]
- umi 版本
- 浏览器环境 [Chrome]
- 开发环境 [mac OS]

### 🚑 其他信息

详见上方错误提示。

**Comment by chenshuai2144** [comment]
umi block clear

执行一下呗
