### ISSUE TITLE
🐛[BUG]V5 logo使用本地资源的问题

### ISSUE THREAD

**Issue by Renderz** [ant-design/ant-design-pro#7842]
### 🐛 bug 描述
v5版本logo使用本地资源, 修改defaultSetting.ts的时候, 在start状态下. 能显示成功. 但是重启项目, 会报编译错误.
```
yarn run v1.22.0
$ umi dev
Invalid or unexpected token
/Users/renderz/github/newApp/public/logo.png:1
�PNG


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.newLoader [as .js] (/Users/renderz/github/newApp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/renderz/github/newApp/config/config.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
✨  Done in 1.30s.
```

### 📷 复现步骤
1. 修改defaultSetting.ts. 
```import { Settings as LayoutSettings } from '@ant-design/pro-layout';
import Logo from '../public/logo.png'

const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: 'test',
  pwa: false,
  // logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
  logo: Logo,
  iconfontUrl: '',
};
```

export default Settings;

### © 版本信息

- Ant Design Pro 版本: v5
- @ant-design/pro-layout: 6.5.0

### 🚑 其他信息
1. 看了其他相关issue, 有在app.tsx里修改的. 确实可以. 但是这个地方修改应该也要成功才对.
2. 看了下pro-layout源码是说logo参数是ReactNode类型. 为什么在defaultConfig.ts里面是string类型?

**Comment by chenshuai2144** [comment]
config.js 是 node 环境，里面不会编译的。而 Object 里面是不能放二进制的

app.tsx 里面生效是 webpack 帮你转化成了 url。

**Comment by AmagiDDmxh** [comment]
附加：在 `app.tsx` 里进行添加。
不过这相应的带来一个疑问，请问哪些文件是 webpack 包括的，哪些不是呢？这个问题常常遇到。

**Comment by chenshuai2144** [comment]
src里面的是webpack 剩下的都是node环境

**Comment by koupeng** [comment]
> src里面的是webpack 剩下的都是node环境

没明白，这个问题怎么解决的？


E:\unicomsource\dingportal\src\assets\framework\spring.png:1
�PNG


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (E:\unicomsource\dingportal\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\unicomsource\dingportal\src\pages\DevCenter\components\DevFramework\/_mock.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (E:\unicomsource\dingportal\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (E:\unicomsource\dingportal\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
Error: E:\unicomsource\dingportal\src\assets\framework\spring.png:1
�PNG


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (E:\unicomsource\dingportal\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Comment by chenshuai2144** [comment]
在 app.tsx 里面设置 logo
