### ISSUE TITLE
运行时报错events.js:292  throw er; // Unhandled 'error' event🧐[问题]

### ISSUE THREAD

**Issue by zhiji502** [ant-design/ant-design-pro#8020]
### 🧐 问题描述
webstrom运行时报错，报错信息如下：

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\workspace\ant-design-pro\node_modules\esbuild\esbuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn D:\\workspace\\ant-design-pro\\node_modules\\esbuild\\esbuild.exe',
  path: 'D:\\workspace\\ant-design-pro\\node_modules\\esbuild\\esbuild.exe',
  spawnargs: [ '--service=0.8.36' ]

**Comment by chenshuai2144** [comment]
`esbuild:{}` 在 config.ts 的删除一下。
