### ISSUE TITLE
npm run build之后报错 Cannot read property 'notifyCount' of undefined

### ISSUE THREAD

**Issue by yclnycl** [ant-design/ant-design-pro#805]
系统 ubuntu
node v8.9.4
npm v5.6.0
npm install demo 打包到nginx之后浏览器打开页面报错
index.79e77b31.js:1 TypeError: Cannot read property 'notifyCount' of undefined
    at e.value (index.79e77b31.js:1)
    at u (index.79e77b31.js:1)
    at beginWork (index.79e77b31.js:1)
    at o (index.79e77b31.js:1)
    at a (index.79e77b31.js:1)
    at s (index.79e77b31.js:1)
    at w (index.79e77b31.js:1)
    at x (index.79e77b31.js:1)
    at h (index.79e77b31.js:1)
    at d (index.79e77b31.js:1)
u @ index.79e77b31.js:1
s @ index.79e77b31.js:1
w @ index.79e77b31.js:1
x @ index.79e77b31.js:1
h @ index.79e77b31.js:1
d @ index.79e77b31.js:1
enqueueSetState @ index.79e77b31.js:1
o.setState @ index.79e77b31.js:1
i.onStateChange @ index.79e77b31.js:1
s @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
dispatch @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
r @ index.79e77b31.js:1
s @ index.79e77b31.js:1
o @ index.79e77b31.js:1
C @ index.79e77b31.js:1
x @ index.79e77b31.js:1
c @ index.79e77b31.js:1
n @ index.79e77b31.js:1
Promise resolved (async)
w @ index.79e77b31.js:1
S @ index.79e77b31.js:1
x @ index.79e77b31.js:1
c @ index.79e77b31.js:1
s @ index.79e77b31.js:1
_ @ index.79e77b31.js:1
x @ index.79e77b31.js:1
c @ index.79e77b31.js:1
n @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
r @ index.79e77b31.js:1
s @ index.79e77b31.js:1
o @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
e @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
value @ index.79e77b31.js:1
commitLifeCycles @ index.79e77b31.js:1
e @ index.79e77b31.js:1
w @ index.79e77b31.js:1
x @ index.79e77b31.js:1
h @ index.79e77b31.js:1
d @ index.79e77b31.js:1
updateContainer @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
unbatchedUpdates @ index.79e77b31.js:1
gn @ index.79e77b31.js:1
render @ index.79e77b31.js:1
s @ index.79e77b31.js:1
e @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
e @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
(anonymous) @ index.79e77b31.js:1
index.79e77b31.js:1 uncaught at e TypeError: Cannot read property 'notifyCount' of undefined
    at e.value (http://127.0.0.1:1234/index.79e77b31.js:1:1947446)
    at u (http://127.0.0.1:1234/index.79e77b31.js:1:1770237)
    at beginWork (http://127.0.0.1:1234/index.79e77b31.js:1:1771955)
    at o (http://127.0.0.1:1234/index.79e77b31.js:1:1784076)
    at a (http://127.0.0.1:1234/index.79e77b31.js:1:1784397)
    at s (http://127.0.0.1:1234/index.79e77b31.js:1:1784635)
    at w (http://127.0.0.1:1234/index.79e77b31.js:1:1788178)
    at x (http://127.0.0.1:1234/index.79e77b31.js:1:1787915)
    at h (http://127.0.0.1:1234/index.79e77b31.js:1:1787043)
    at d (http://127.0.0.1:1234/index.79e77b31.js:1:1786433)

**Comment by chenshuai2144** [comment]
前台界面 需要后端配合才能工作 开发项目mock。正式项目是没有的

**Comment by zeybar** [comment]
具体如何配合呢？
