### ISSUE TITLE
🐛[BUG] Error starting the project

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#8074]
### 🐛 bug 描述
I want to switch my project to ant design pro beta v2. First, I created a new template, then I asked npm install to install the requirements, after the installation is completed, I get this error when I start running.

**Register plugin C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\umi-plugin-antd-icon-config\lib\index.js failed, since Cannot use import statement outside a module**
Error: Register plugin C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\umi-plugin-antd-icon-config\lib\index.js failed, since Cannot use import statement outside a module
    at Object.apply (C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:159:15)
    at C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\Service.js:348:22
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\Service.js:108:103)
    at _next (C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\Service.js:110:194)
    at C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\Service.js:110:364
    at new Promise (<anonymous>)
    at C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\Service.js:110:97
    at Service.applyAPI (C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\Service.js:355:7)    at C:\Users\mypc\Desktop\myproject\myproject-cli\node_modules\@umijs\core\lib\Service\Service.js:438:20

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by j511002** [comment]
I have this problem too...
![image](https://user-images.githubusercontent.com/14238111/107440840-3f271580-6b6f-11eb-8fdf-cc60d58fa5d1.png)

**Comment by thinwind** [comment]
一样的问题
![image](https://user-images.githubusercontent.com/10788262/107448835-697fcf80-6b7d-11eb-9790-ad320e4e1e58.png)

**Comment by thinwind** [comment]
一样的问题

OS: macOS 11
node: v12.20.0

按照快速入门操作

**Comment by whoisje** [comment]
package.json加入"resolutions": { "@ant-design/colors": "5.0.0" }暂时这么解决吧

**Comment by easeava** [comment]
#8076

**Comment by j511002** [comment]
项目里直接 yarn upgrade 就可以了

**Comment by chenshuai2144** [comment]
`@ant-design/colors` 已经发布了最新版本，可以关掉锁包了。
更新最新依赖版本即可


------


`@ant-design/colors` has released the latest version, you can turn off the lock package.
Update the latest dependency version
