### ISSUE TITLE
部署的问题？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#82]
第一步：npm run build，生成dist目录及文件
第二步：serve -s dist，**有好几个页面不能显示**（# Dashboard->工作台，列表页下所有的页面）

**Comment by NingYuanLee** [comment]
@kaoding 我也是，你解决了么

**Comment by nikogu** [comment]
@kaoding 报错了？提示什么？

**Comment by kaoding** [comment]
就是显示不了

**Comment by kaoding** [comment]
@NingYuanLee 我没有解决

**Comment by nikogu** [comment]
@kaoding 不能显示指的是：白屏？还是组件渲染不出来？有可以预览的项目或者线上地址吗？

**Comment by kaoding** [comment]
@nikogu 显示是白屏，应该组件渲染出错，现在没有线上地址。
下面是组件渲染出现白屏时浏览器出错的信息，只有这几个页面会出错（dashboard->工作台，列表页->标准列表、搜索列表的三页），在win10，node 8.9.1，server -s dist 做了build后的静态环境下的表现。
index.js:1 TypeError: r.map is not a function
    at t.value (index.js:1)
    at s (index.js:1)
    at beginWork (index.js:1)
    at o (index.js:1)
    at s (index.js:1)
    at c (index.js:1)
    at m (index.js:1)
    at h (index.js:1)
    at Object.enqueueSetState (index.js:1)
    at c.a.setState (index.js:1)
f @ index.js:1
index.js:1 uncaught at s TypeError: r.map is not a function
    at t.value (http://localhost:5000/index.js:1:1037742)
    at s (http://localhost:5000/index.js:1:468091)
    at beginWork (http://localhost:5000/index.js:1:469591)
    at o (http://localhost:5000/index.js:1:481883)
    at s (http://localhost:5000/index.js:1:482399)
    at c (http://localhost:5000/index.js:1:482874)
    at m (http://localhost:5000/index.js:1:484896)
    at h (http://localhost:5000/index.js:1:484405)
    at Object.enqueueSetState (http://localhost:5000/index.js:1:465672)
    at c.a.setState (http://localhost:5000/index.js:1:381634)
d @ index.js:1

**Comment by NingYuanLee** [comment]
@nikogu  

http://liningyuan.com:5000

http://liningyuan.com:5000/#/dashboard/workplace

TypeError: r.map is not a function

**Comment by afc163** [comment]
原因是因为那几个页面依赖了相应的请求，而部署的静态版本都没有实现相应的请求，导致页面报错。我在上面的提交中进行了下列修正：

1. 优化了错误请求的界面响应，现在会弹出 notification 提示请求有问题。
2. 对 fetch 回来的结果进行了容错处理，界面不再白屏。

对于应用开发者来说，还是要注意处理请求，看下网络面板。

<img width="692" alt="image" src="https://user-images.githubusercontent.com/507615/32362001-a99ff92c-c0a0-11e7-9b69-69837966b9b7.png">

**Comment by Bobcui001** [comment]
使用 hashHistory模式，页面元素没问题，但异步接口报404. 有什么办法解决吗？谢谢。
![image](https://user-images.githubusercontent.com/18111032/33481800-054a2392-d6d1-11e7-987b-481cec559645.png)

**Comment by freedomljt** [comment]
npm run build 之后，nginx也配置了try_files $uri /index.html;结果还是白屏，有什么解决方法么？
