### ISSUE TITLE
🧐[问题] 创建v5时 [openAPIConfig].flat is not a function

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design-pro#8245]
### 🧐 问题描述

如题，创建v4 ts不会，是少了什么，还是冲突?

### 💻 示例代码

error:
```
[openAPIConfig].flat is not a function
TypeError: [openAPIConfig].flat is not a function
    at Object.api.onGenerateFiles [as fn] (F:\wingo\ant-design-pro-blank\node_modules\@umijs\plugin-openapi\lib\index.js:144:27)
    at F:\wingo\ant-design-pro-blank\node_modules\@umijs\core\lib\Service\Service.js:609:28
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\wingo\ant-design-pro-blank\node_modules\@umijs\core\lib\Service\Service.js:108:103)
    at _next (F:\wingo\ant-design-pro-blank\node_modules\@umijs\core\lib\Service\Service.js:110:194)
    at F:\wingo\ant-design-pro-blank\node_modules\@umijs\core\lib\Service\Service.js:110:364
    at new Promise (<anonymous>)
    at F:\wingo\ant-design-pro-blank\node_modules\@umijs\core\lib\Service\Service.js:110:97
    at _next16 (eval at create (F:\wingo\ant-design-pro-blank\node_modules\@umijs\deps\compiled\tapable\index.js:1:7845), <anonymous>:17:18)
    at _promise16.then._result16 (eval at create (F:\wingo\ant-design-pro-blank\node_modules\@umijs\deps\compiled\tapable\index.js:1:7845), <anonymous>:42:1)
error Command failed with exit code 1.
```

**Comment by chenshuai2144** [comment]
修掉了，这个不支持 node10 版本，有兴趣可以升级下版本。或者等 新版本发布
