### ISSUE TITLE
🧐[问题]openapi 又错了

### ISSUE THREAD

**Issue by baiheinet** [ant-design/ant-design-pro#8255]
### 🧐 问题描述

antd pro "version": "5.0.0-beta.2",
   "@umijs/openapi": "^1.1.14",
  "@umijs/plugin-openapi": "^1.2.0",

### 💻 错误提示代码
`yarn run v1.22.5
$ umi openapi
[GenSDK] gen service param error: TypeError: Cannot read property 'replace' of undefined
    at Object.stripDot (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\util.js:183:16)
    at C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:254:59
    at Array.map (<anonymous>)
    at C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:241:18
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:234:14)
    at ServiceGenerator.genFile (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:210:14)
    at generateService (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\index.js:60:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1500) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.stripDot (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\util.js:183:16)
    at C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:254:59
    at Array.map (<anonymous>)
    at C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:241:18
    at Array.map (<anonymous>)
    at ServiceGenerator.getServiceTP (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:234:14)
    at ServiceGenerator.genFile (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\serviceGenerator.js:210:14)
    at generateService (C:\Users\baihe\Documents\GitHub\segplus\node_modules\@umijs\plugin-openapi\node_modules\@umijs\openapi\dist\index.js:60:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 8.51s.`

**Comment by fangqibin** [comment]
文件给的json配置错了，确认是一下是否缺少operationId这个字段

**Comment by baiheinet** [comment]
我是用[@midwayjs/swagger ](https://github.com/fsd-nodejs/service-mw2) 示例 ，确实少了operationId字段  真是高手 一眼就看出问题

**Comment by fangqibin** [comment]
> 我是用[@midwayjs/swagger ](https://github.com/fsd-nodejs/service-mw2) 示例 ，确实少了operationId字段 真是高手 一眼就看出问题

不是什么高手，我前几天刚好碰到这个问题。

**Comment by chenshuai2144** [comment]
@baiheinet 贴出来给我一下，我提示错误，直接挂了就不好了

**Comment by xxmt** [comment]
这个问题还有其他解决办法吗 如果后端生成的json中确实缺少operationId

**Comment by xxmt** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
加一个呢？按照规范这玩意是必填的
