### ISSUE TITLE
🐛[BUG]使用OPENAPI生成时报错 Cannot read property 'mock' of undefined

### ISSUE THREAD

**Issue by cardinalblues7** [ant-design/ant-design-pro#8286]
### 📷 复现步骤
> ant-design-pro@4.5.0 openapi D:\chemical_facility_management\cfm_frontend
> umi openapi

(node:15772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mock' of undefined
    at D:\chemical_facility_management\cfm_frontend\node_modules\@umijs\plugin-openapi\lib\index.js:197:40
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\chemical_facility_management\cfm_frontend\node_modules\@umijs\plugin-openapi\lib\index.js:76:103)
    at _next (D:\chemical_facility_management\cfm_frontend\node_modules\@umijs\plugin-openapi\lib\index.js:78:194)
    at D:\chemical_facility_management\cfm_frontend\node_modules\@umijs\plugin-openapi\lib\index.js:78:364
    at new Promise (<anonymous>)
    at D:\chemical_facility_management\cfm_frontend\node_modules\@umijs\plugin-openapi\lib\index.js:78:97
    at genAllFiles (D:\chemical_facility_management\cfm_frontend\node_modules\@umijs\plugin-openapi\lib\index.js:219:20)
    at D:\chemical_facility_management\cfm_frontend\node_modules\@umijs\plugin-openapi\lib\index.js:234:9
    at Generator.next (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### © 版本信息
node 14.15.5
"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.32.0",
    "@umijs/plugin-openapi": "^1.2.1",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.12.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^16.14.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.4.1",
    "umi-request": "^1.0.8"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.28",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.5.1",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "chalk": "^4.0.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.0.3"
  },

**Comment by cardinalblues7** [comment]
用的是4.5.0 就是报这个错误

**Comment by cardinalblues7** [comment]
已经解决了，按照文档写的openapi的配置用的是大括号，改用中括号就好了
