### ISSUE TITLE
test:all error

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design-pro#83]
Clone https://github.com/ant-design/ant-design-pro.git.
Then, run `npm run test:all`. But throw errors, as follow:
### console
![error](https://user-images.githubusercontent.com/4525647/32318411-2b49e550-bff2-11e7-8742-d192fac8243d.png)

### debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:all' ]
2 info using npm@5.5.1
3 info using node@v9.0.0
4 verbose run-script [ 'pretest:all', 'test:all', 'posttest:all' ]
5 info lifecycle ant-design-pro@0.2.1~pretest:all: ant-design-pro@0.2.1
6 info lifecycle ant-design-pro@0.2.1~test:all: ant-design-pro@0.2.1
7 verbose lifecycle ant-design-pro@0.2.1~test:all: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@0.2.1~test:all: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\workspace\ant-design-pro\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Subversion\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_91\bin;C:\workspace\gradle-3.4\bin;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\Users\Xu Qiang\AppData\Local\Microsoft\WindowsApps;C:\Users\Xu Qiang\AppData\Roaming\npm
9 verbose lifecycle ant-design-pro@0.2.1~test:all: CWD: C:\workspace\ant-design-pro
10 silly lifecycle ant-design-pro@0.2.1~test:all: Args: [ '/d /s /c', 'node ./tests/run-tests.js' ]
11 silly lifecycle ant-design-pro@0.2.1~test:all: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@0.2.1~test:all: Failed to exec test:all script
13 verbose stack Error: ant-design-pro@0.2.1 test:all: `node ./tests/run-tests.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at EventEmitter.emit (events.js:224:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at ChildProcess.emit (events.js:224:7)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid ant-design-pro@0.2.1
15 verbose cwd C:\workspace\ant-design-pro
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:all"
18 verbose node v9.0.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@0.2.1 test:all: `node ./tests/run-tests.js`
22 error Exit status 1
23 error Failed at the ant-design-pro@0.2.1 test:all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nikogu** [comment]
看起来像是 `npm` 版本的问题

**Comment by kairi1227** [comment]
@nikogu 之前node版本是7.9.0，报这个异常。然后我就升到最新版本。
正常跑的是哪个版本？

**Comment by nikogu** [comment]
我用的 `v8.5.0` 是可以跑的

**Comment by afc163** [comment]
也可能是 windows 的缘故，信息有点少。

**Comment by kairi1227** [comment]
换到8.5.0，还是不能跑。log日志就这么多。还可以从哪里看异常信息。@afc163

**Comment by afc163** [comment]
https://ci.appveyor.com/project/afc163/ant-design-pro/build/1.0.1

Windows 下确实有问题。

**Comment by afc163** [comment]
https://stackoverflow.com/a/43285131/3040605
