### ISSUE TITLE
🧐[问题] 升级umi3的一个问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design-pro#8354]
### 🧐 问题描述

按照 pro文档和 umi文档，对 package.json 和 config 进行了修改了，但 run 的时候抛出以下错误，可能的原因是？

### 💻 示例代码

抛了个dva的错误， 试过删除 node_modules 和 yarn.lock 重装还是不行

> **error code：**

```
Dva model src/models/login.js parse failed, SyntaxError: Unexpected token, expected "," (116:29)
    Error: Dva model src/models/login.js parse failed, SyntaxError: Unexpected token, expected "," (116:29)
    at F:\wingo\netmas-web-react-v2\node_modules\@umijs\plugin-dva\lib\getModels\getModels.js:66:13
    at Array.filter (<anonymous>)
    at getModels (F:\wingo\netmas-web-react-v2\node_modules\@umijs\plugin-dva\lib\getModels\getModels.js:55:106)
    at getAllModels (F:\wingo\netmas-web-react-v2\node_modules\@umijs\plugin-dva\lib\index.js:108:53)
    at Object.fn (F:\wingo\netmas-web-react-v2\node_modules\@umijs\plugin-dva\lib\index.js:125:17)
    at F:\wingo\netmas-web-react-v2\node_modules\@umijs\core\lib\Service\Service.js:609:28
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\wingo\netmas-web-react-v2\node_modules\@umijs\core\lib\Service\Service.js:108:103)
    at _next (F:\wingo\netmas-web-react-v2\node_modules\@umijs\core\lib\Service\Service.js:110:194)
    at F:\wingo\netmas-web-react-v2\node_modules\@umijs\core\lib\Service\Service.js:110:364
```

### 🚑 其他信息

> **依赖：**

```
  "dependencies": {
    "@ant-design/compatible": "^1.0.2",
    "@ant-design/icons": "@4.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "@icon-park/react": "^1.2.0",
    "ahooks": "^2.9.3",
    "animate.css": "^3.7.0",
    "ant-virtual-table": "^0.1.11",
    "antd": "^4.15.0",
    "classnames": "^2.2.6",
    "echarts": "5.0.0",
    "echarts-for-react": "^3.0.1",
    "enquire-js": "^0.2.1",
    "exceljs": "^4.2.0",
    "g-mask": "^0.2.0",
    "hash.js": "^1.1.5",
    "js-cookie": "^2.2.0",
    "lodash": "^4.17.10",
    "lodash-decorators": "^6.0.0",
    "memoize-one": "^4.0.0",
    "moment": "^2.22.2",
    "node-rsa": "^1.0.3",
    "nprogress": "^0.2.0",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^2.4.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.2",
    "rc-animate": "^2.4.4",
    "react": "16.8.0",
    "react-activation": "^0.9.1",
    "react-color": "^2.19.3",
    "react-container-query": "^0.11.0",
    "react-document-title": "^2.0.3",
    "react-dom": "16.8.0",
    "react-grid-layout": "^1.2.4",
    "react-keep-alive": "^2.5.2",
    "react-lazy": "^1.1.0",
    "react-router-config": "^1.0.0-beta.4",
    "react-router-dom": "^4.3.1",
    "react-syntax-highlighter": "^12.2.1",
    "react.eval": "^1.4.14",
    "reactcss": "^1.2.3",
    "reqwest": "^2.0.5",
    "umi-plugin-keep-alive": "^0.0.1-beta.26",
    "vis-network": "^9.0.4",
    "umi": "3.4.1"
  },
  "devDependencies": {
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/preset-ui": "^2.2.9",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "antd-pro-merge-less": "^0.0.9",
    "antd-pro-theme-webpack-plugin": "^1.1.8",
    "babel-eslint": "^9.0.0",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.4.4",
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^6.3.0",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-compat": "^2.5.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.11.1",
    "gh-pages": "^1.2.0",
    "lint-staged": "^7.2.0",
    "merge-umi-mock-data": "^0.0.3",
    "mockjs": "^1.0.1-beta3",
    "prettier": "1.14.2",
    "pro-download": "^1.0.1",
    "stylelint": "^9.4.0",
    "stylelint-config-prettier": "^4.0.0",
    "stylelint-config-standard": "^18.0.0"
  }
```

> **config：**

```
export default defineConfig({
  antd: {},
  dva: {
    hmr: true,
  },
  locale: {
    default: 'zh-CN',
    antd: true,
    baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
  },
  dynamicImport: {
    loading: './components/PageLoading/index',
  },
  ...(!process.env.TEST && os.platform() === 'darwin'
    ? {
      dll: {
        include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
        exclude: ['@babel/runtime'],
      },
      hardSource: true,
    }
    : {}),
  define: {
    APP_TYPE: process.env.APP_TYPE || '',
  },
  targets: {
    chrome: 58,
    ie: 11,
    firefox: 45,
    safari: 10,
    edge: 13,
    ios: 10
  },
  hash: true,
  routes: pageRoutes,
  base: '/netmas',
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  "proxy": {
    "/api": {
      "target": proxyPath,
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  },
  externals: {
    '@antv/data-set': 'DataSet',
  },
  ignoreMomentLocale: true,
  lessLoader: {
    javascriptEnabled: true,
  },
  cssLoader: {
    modules: {
      getLocalIdent: (context, localIdentName, localName) => {
        if (
          context.resourcePath.includes('node_modules') ||
          context.resourcePath.includes('ant.design.pro.less') ||
          context.resourcePath.includes('global.less')
        ) {
          return localName;
        }
        const match = context.resourcePath.match(/src(.*)/);
        if (match && match[1]) {
          const antdProPath = match[1].replace('.less', '');
          const arr = antdProPath
            .split('/')
            .map(a => a.replace(/([A-Z])/g, '-$1'))
            .map(a => a.toLowerCase());
          return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
        }
        return localName;
      }
    }
  },
  chainWebpack: webpackplugin,
  cssnano: {
    mergeRules: false,
  },
});

```

**Comment by chenshuai2144** [comment]
看起来有点像是读取文件的时候文件里面用了不支持的语法

**Comment by theDoinb** [comment]
找到原因了，login 里面使用了 Modal.confirm ，里面的 content 是 ReactNode 

现在在 model 里面存在 jsx 这种会有问题吗？

该如何解决?

**Comment by theDoinb** [comment]
先屏蔽这段代码，将 link, connect 引入 修改完后，又出现以下错误：
```
These dependencies were not found:

* core-js/modules/web.dom-collections.for-each.js in ./node_modules/@babel/polyfill/lib/noConflict.js
* core-js/modules/web.dom-collections.iterator.js in ./node_modules/@babel/polyfill/lib/noConflict.js
* core-js/modules/web.queue-microtask.js in ./node_modules/@babel/polyfill/lib/noConflict.js
* core-js/modules/web.url-search-params.js in ./node_modules/@babel/polyfill/lib/noConflict.js
* core-js/modules/web.url.js in ./node_modules/@babel/polyfill/lib/noConflict.js
* core-js/modules/web.url.to-json.js in ./node_modules/@babel/polyfill/lib/noConflict.js

To install them, you can run: npm install --save core-js/modules/web.dom-collections.for-each.js core-js/modules/web.dom-collections.iterator.js core-js/modules/web.queue-microtask.js core-js/modules/web.url-search-params.js core-js/modules/web.url.js core-js/modules/web.url.to-json.js
```

**Comment by chenshuai2144** [comment]
model里面不允许写 jsx的。你要全部清理掉

**Comment by theDoinb** [comment]
我看看jsx放哪吧，
 上边那个错误我把 global.js 的 import '@babel/polyfill' 删除就正常了，
目前好像没其他问题，先关闭了
