### ISSUE TITLE
yarn create umi myapp 安装报错

### ISSUE THREAD

**Issue by zhuzhengjing** [ant-design/ant-design-pro#8383]
yarn create umi myapp
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-umi@0.26.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
(node:5373) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'react' declared in 'BaseConfig » /Users/bruce/.config/yarn/global/node_modules/@umijs/fabric/dist/eslint.js': Cannot find module 'eslint-plugin-react'
Require stack:
- /Users/bruce/.config/yarn/global/node_modules/sylvanas/__placeholder__.js
Referenced from: /Users/bruce/.config/yarn/global/node_modules/@umijs/fabric/dist/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.resolve (/Users/bruce/.config/yarn/global/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/Users/bruce/.config/yarn/global/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/bruce/.config/yarn/global/node_modules/@eslint/eslintrc/lib/config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (/Users/bruce/.config/yarn/global/node_modules/@eslint/eslintrc/lib/config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/bruce/.config/yarn/global/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/bruce/.config/yarn/global/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 8.44s.

**Comment by zhuzhengjing** [comment]
已解决，删除.config/yarn/global这个文件夹所有内容，重新安装一下就Ok了。
