### ISSUE TITLE
🐛[BUG]TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#8643]
INFO cache in :D:/Project/Precise/source/website/node_modules/.plugin-theme
INFO 💄  build theme
🔩 less render start!
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1460:5)
    at loop (D:\Project\Precise\source\website\node_modules\antd-pro-merge-less\index.js:287:12)
    at build (D:\Project\Precise\source\website\node_modules\antd-pro-merge-less\index.js:299:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

遇到一个这样的问题，搜到一个去年的问题，不知道修复了吗？

**Comment by chenshuai2144** [comment]
看起来是 node 版本的问题，升级一下node吧

**Comment by shaohuatsou** [comment]
> 看起来是 node 版本的问题，升级一下node吧

好的，我去试试。
