### ISSUE TITLE
🐛[BUG] Fails to setup v5 

### ISSUE THREAD

**Issue by AaronNBrock** [ant-design/ant-design-pro#8665]
### 🐛 bug 描述

Following [Getting Started](https://beta-pro.ant.design/docs/getting-started) and selecting `v5` I get the following error:

```
? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ? Pro V5
Cloning into 'hello-ant-design'...
warning: Could not find remote branch v5 to clone.
fatal: Remote branch v5 not found in upstream origin
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: git clone https://github.com/ant-design/ant-design-pro --depth=1 --branch v5 hello-ant-design
null
null
    at makeError (/home/me/.npm/_npx/10719/lib/node_modules/create-umi/node_modules/execa/index.js:174:9)
    at /home/me/.npm/_npx/10719/lib/node_modules/create-umi/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async AntDesignProGenerator.writing (/home/me/.npm/_npx/10719/lib/node_modules/create-umi/lib/generators/ant-design-pro/index.js:156:5)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (/home/me/.npm/_npx/10719/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:1022:20)
    at processImmediate (internal/timers.js:464:21) {
  code: 128,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'git clone https://github.com/ant-design/ant-design-pro --depth=1 --branch v5 hello-ant-design',
  timedOut: false,
  killed: false
}
```

### 📷 复现步骤

Running:
```bash
yarn create umi myapp
```
& selecting `v5` as the version

### 🏞 期望结果

I expect to to setup the project

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xXAvoraXx** [comment]
same error

**Comment by yinzixie** [comment]
same error！！！！！ 

And if  you choose v4   -> simple, you will get a v5.

离谱。

**Comment by chenshuai2144** [comment]
`git clone https://github.com/ant-design/ant-design-pro --depth=1 --branch v5 hello-ant-design`


你看看你们是不是连不上 github
