### ISSUE TITLE
🐛[BUG]　v5 remove i18n error

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#8688]
### 🐛 bug 描述

npm run i18n-remove

result:
```
> ant-design-pro@5.0.0 i18n-remove
> pro i18n-remove --locale=zh-CN --write

/develop/react/antd_pro_v5/node_modules/@ant-design/pro-cli/src/i18n/removeLocale.js:169
      if (path.node.source?.value === 'umi' && !path.node.specifiers.length) {
                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/develop/react/antd_pro_v5/node_modules/@ant-design/pro-cli/src/i18n/index.js:10:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

Process finished with exit code 1

```

### © 版本信息

- Ant Design Pro 版本: [5.0.0.0]
- umi 版本: 3.5.0
- 浏览器环境
- 开发环境 [mac OS]

**Comment by kisslove** [comment]
我也碰到了，相同的问题

**Comment by chenshuai2144** [comment]
升级一下 node 版本，你们的版本太低了不支持这个语法
