### ISSUE TITLE
🐛[BUG] EACCES: permission denied, mkdir '/app/src/.umi-production/core'

### ISSUE THREAD

**Issue by oldthreefeng** [ant-design/ant-design-pro#8800]
### 📷 复现步骤

dockerfile

```
$ cat Dockerfile 
circleci/node:latest-browsers  as node-builder

WORKDIR /app

USER root

COPY package.json .

RUN yarn

COPY . .

RUN npm run build
....

```

run docker build . 

but failed

```
#14 2.410 > ant-design-pro@5.0.0-beta.3 build
#14 2.410 > umi build
#14 2.410 
#14 3.642 Babel could not read cache file: /root/.babel.7.14.0.production.json
#14 3.642 due to a permission issue. Cache is disabled.
#14 8.981 EACCES: permission denied, mkdir '/app/src/.umi-production/core'
#14 8.983 Error: EACCES: permission denied, mkdir '/app/src/.umi-production/core'
#14 8.983     at Object.mkdirSync (node:fs:1324:3)
#14 8.983     at d (/app/node_modules/@umijs/deps/compiled/mkdirp/index.js:1:2145)
#14 8.983     at Function.f [as sync] (/app/node_modules/@umijs/deps/compiled/mkdirp/index.js:1:372)
#14 8.983     at Proxy.fn (/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/registerMethods.js:78:24)
#14 8.983     at Object.<anonymous> (/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:83:9)
#14 8.983     at Generator.next (<anonymous>)
#14 8.983     at asyncGeneratorStep (/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:48:103)
#14 8.983     at _next (/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:50:194)
#14 8.983     at /app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:50:364
#14 8.983     at new Promise (<anonymous>)
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
docker 镜像的权限问题，你默认用admin权限运行好了

**Comment by oldthreefeng** [comment]
USER admin ?  @chenshuai2144

**Comment by chenshuai2144** [comment]
docker默认不是的，需要专门配置

**Comment by oldthreefeng** [comment]
有文档么? 能否给个文档 @chenshuai2144  玩的少..

**Comment by chenshuai2144** [comment]
https://www.cnblogs.com/hyry/p/13653251.html

docker很难的，加油

**Comment by oldthreefeng** [comment]
谢谢啦~
