### ISSUE TITLE
🐛[BUG] Ant pro build failed using webpack 5 

### ISSUE THREAD

**Issue by amol222patil** [ant-design/ant-design-pro#8828]
### 🐛 bug description
We are getting issue while build the application using webpack 5 with Jenkin pipeline. When we try to build manually using webpack 5, its successful building the application, but when we try build application using Jenkins pipeline using same command `npm run build:dev` its failing.

In Jenkin we are getting following output as error 
**Error Log:**
```
Bundle with webpack 5...
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
    at Object.webpack (/var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:138983:9)
    at /var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/bundler-webpack/lib/index.js:143:44
    at new Promise (<anonymous>)
    at /var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/bundler-webpack/lib/index.js:142:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/bundler-webpack/lib/index.js:95:103)
    at _next (/var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/bundler-webpack/lib/index.js:97:194)
    at /var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/bundler-webpack/lib/index.js:97:364
    at new Promise (<anonymous>)
    at /var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/bundler-webpack/lib/index.js:97:97
    at Bundler.build (/var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/bundler-webpack/lib/index.js:186:7)
    at /var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/build/build.js:93:54
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/build/build.js:54:103)
    at _next (/var/lib/jenkins/workspace/test-pipeline/byts/ui/node_modules/@umijs/preset-built-in/lib/plugins/commands/build/build.js:56:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

We are tried to clear npm cache, reinstall npm and node JS. 

### 📷 Steps to reproduce
git pull 
npm install
npm run build:dev

This where above log encountered when we try to build using Jenkin pipeline. 
### 🏞 Expected results

Build should be successful.

### © Version Information

-Ant Design Pro version:  4.12.0
-umi versio: 3.4.1
-Development environment: Ubuntu
-OS Version: Ubuntu 20.04.2 LTS
-Node version: v12.22.2
-Npm version: 6.14.13
-Webpack version: 5

**Comment by tejparekh** [comment]
Following

**Comment by Youmyin** [comment]
Following

**Comment by tejparekh** [comment]
All, if you are looking for the solution to this issue. @Youmyin 

There may be a "**webpack5**" key in your config.js file for Ant Pro setup. 
 
```
export default defineConfig({
  webpack5: {},  // remove this empty object
  define: {
    REACT_APP_ENV: 'dev'
  },
});
```
The webpack5 empty object is not matched with is expected input hence the build fails. 
I hope this information helps. 
Cheers!

**Comment by Youmyin** [comment]
> All, if you are looking for the solution to this issue. @Youmyin
> 
> There may be a "**webpack5**" key in your config.js file for Ant Pro setup.
> 
> ```
> export default defineConfig({
>   webpack5: {},  // if this is empty then remove the line from defineConfig
>   define: {
>     REACT_APP_ENV: 'dev'
>   },
> });
> ```
> 
> The webpack5 empty object is not matched with is expected input hence the build fails.
> I hope this information helps.
> Cheers!

Thank you!!
