### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by langengel** [ant-design/ant-design-pro#8934]
这个编译正常吗？
<img width="880" alt="WX20210816-181727@2x" src="https://user-images.githubusercontent.com/59662045/129549032-014a135c-0410-4eb9-b867-e41628b9a5e7.png">
<img width="1152" alt="WX20210816-181810@2x" src="https://user-images.githubusercontent.com/59662045/129549060-8196a301-90f1-4fe4-a4db-676e002a8726.png">

(node:49331) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors(node:49331) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:49331) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
(node:49331) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

**Comment by hyzx86** [comment]
无法打包发布。。。
这个怎么关了啊？

**Comment by hyzx86** [comment]
到 92% 就挂了
打包过程中
![image](https://user-images.githubusercontent.com/15613121/205511856-7e8bec02-d914-4a82-b16d-53059ddf35d1.png)

![image](https://user-images.githubusercontent.com/15613121/205511948-47f0aca0-4042-4b5c-a61f-afe3834e5924.png)

**Comment by hyzx86** [comment]
``` LOG
* Webpack █████████████████████████ cache (99%)                                                                                                                                                      begin idle                                                                                                                                                                                                                                                                                                                                                                                             (node:23880) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors                         (Use `node --trace-deprecation ...` to show where the warning was created)                                                                                                                          (node:23880) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)                                                                                                                                                                      
Browserslist: caniuse-lite is outdated. Please run:                                                                                                                                                 
npx browserslist@latest --update-db                                                                                                                                                                 
                                                                                                                                                                                                    
Why you should do it regularly:                                                                                                                                                                     
https://github.com/browserslist/browserslist#browsers-data-updating                                                                                                                                 
(node:23880) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.                                                    
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.                                                                                                 
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.                                                                                                                     
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
[Error: EINVAL: invalid argument, mkdir 'D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\dist\*'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'D:\\SourceCodes\\JZSoft\\EasyOC.OrchardCore\\EasyOC.LowCode\\dist\\*'
}
 info  如果你需要进交流群，请访问 https://fb.umijs.org
build failed
Error: build failed
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\bundler-webpack\lib\index.js:177:29
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114591:14
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114422:12
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38249:7
    at done (D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38284:11)
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38237:7
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114419:8
    at arrayEach (D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:37824:9)
    at Object.each (D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38265:9)
    at nodeDone (D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114413:21)
    at finalCallback (D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:95870:32)
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:95897:22
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:96293:14
    at D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38249:7
    at done (D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:38936:9)
    at writeOut (D:\SourceCodes\JZSoft\EasyOC.OrchardCore\EasyOC.LowCode\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:96041:23)
 info  如果你需要进交流群，请访问 https://fb.umijs.org
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 *  终端进程“C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn run build:prod”已终止，退出代码: 1。 
 *  终端将被任务重用，按任意键关闭。 
```
