### ISSUE TITLE
🧐[问题]　突然控制台一大堆报　initialValues 只在 form 初始化时生效，如果你需要异步加载推荐使用 request，或者 initialValues ? <Form/> : null

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#8952]
### 🧐 问题描述

之前都没有　我把node_models删除后，只要在有form的地方全都报这个警告看着都烦死了。删除了装还是这样子，快要抑郁了！

```
initialValues 只在 form 初始化时生效，如果你需要异步加载推荐使用 request，或者 initialValues ? <Form/> : null
```

### 🚑 其他信息
```
react_devtools_backend.js:2842 Note: initialValues 只在 form 初始化时生效，如果你需要异步加载推荐使用 request，或者 initialValues ? <Form/> : null  
    at BaseForm (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:413:24)
    at RequestForm (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:671:23)
    at ReactResizeObserver (http://localhost:8000/mf-dep_vendors-node_modules___umijs_use-params_1_0_4_umijs_use-params_es_index_js-node_modules__antd-d97acb.93f949af.async.js:255:87)
    at QueryFilter (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:4980:32)
    at BetaSchemaForm (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:2577:23)
    at div
    at FormRender (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:1792:23)
    at FormSearch (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:1971:5)
    at div
    at TableRender (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:151:22)
    at ProTable (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:339:28)
    at ErrorBoundary (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-utils_1_20_4_ant-design_pro-utils_es_components_ErrorBo-162c54.560fff27.async.js:49:5)
    at ConfigProviderWrap (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-provider_1_4_16_ant-design_pro-provider_es_index_js-nod-7f3147.7fe0bd7f.async.js:218:23)
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:5805:31)
    at ProviderWarp (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:781:70)
    at div
    at div
    at div
    at WaterMark (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:3564:24)
    at div
    at div
    at GridContent (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:1266:64)
    at div
    at PageContainer (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:1501:24)
    at Page (http://localhost:8000/p__merchant__settlement__list.js:214:25)
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules___umijs_runtime_3_5_17_umijs_runtime_dist_index_esm_js.d706c50b.async.js:414:68)
    at Route
    at Switch
    at WithExceptionOpChildren (http://localhost:8000/.umi__plugin-layout__Layout.js:232:24)
    at main
    at Basic (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:426:25)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:409:66)
    at ConfigProviderWrap (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-provider_1_4_16_ant-design_pro-provider_es_index_js-nod-7f3147.7fe0bd7f.async.js:218:23)
    at WrapContent (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:957:21)
    at div
    at section
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:441:63)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:409:66)
    at div
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:5805:31)
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:306:66)
    at BasicLayout (http://localhost:8000/.umi__plugin-layout__Layout.js:716:24)
    at http://localhost:8000/.umi__plugin-layout__Layout.js:41:19
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules___umijs_runtime_3_5_17_umijs_runtime_dist_index_esm_js.d706c50b.async.js:414:68)
    at Route
    at Switch
    at Router (http://localhost:8000/mf-dep_vendors-node_modules___umijs_runtime_3_5_17_umijs_runtime_dist_index_esm_js.d706c50b.async.js:3046:30)
    at RouterComponent (http://localhost:8000/mf-dep_vendors-node_modules___babel_runtime_7_15_3_babel_runtime_helpers_esm_objectWithoutProperties-9e08e6.b2431910.async.js:610:23)
    at AccessProvider (http://localhost:8000/umi.js:1278:24)
    at http://localhost:8000/umi.js:1908:24
    at FormProvider (http://localhost:8000/mf-dep_vendors-node_modules__rc-field-form_1_20_1_rc-field-form_es_index_js.175f194e.async.js:2588:31)
    at LocaleProvider (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_index_js-node_modules__antd_4_16_1-1b08d7.7ac78db0.async.js:258:87)
    at ProviderChildren (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_index_js-node_modules__antd_4_16_1-1b08d7.7ac78db0.async.js:90:24)
    at LocaleReceiver (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_context_js.758a6407.async.js:720:87)
    at ConfigProvider (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_index_js-node_modules__antd_4_16_1-1b08d7.7ac78db0.async.js:198:13)
    at _LocaleContainer (http://localhost:8000/umi.js:3133:31)
    at http://localhost:8000/umi.js:3714:23
overrideMethod @ react_devtools_backend.js:2842
note @ mf-dep_vendors-node_modules___ant-design_icons_4_6_3_ant-design_icons_es_components_AntdIcon_js.03f1fc37.async.js:465
call @ mf-dep_vendors-node_modules___ant-design_icons_4_6_3_ant-design_icons_es_components_AntdIcon_js.03f1fc37.async.js:473
noteOnce @ mf-dep_vendors-node_modules___ant-design_icons_4_6_3_ant-design_icons_es_components_AntdIcon_js.03f1fc37.async.js:481
(anonymous) @ mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:547
invokePassiveEffectCreate @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23491
callCallback @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:3954
invokeGuardedCallbackDev @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:4003
invokeGuardedCallback @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:4065
flushPassiveEffectsImpl @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23578
unstable_runWithPriority @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:27147
runWithPriority$1 @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:11285
flushPassiveEffects @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23451
(anonymous) @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23328
workLoop @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:27096
flushWork @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:27069
performWorkUntilDeadline @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:26836
react_devtools_backend.js:2842 Note: The initialValues only take effect when the form is initialized, if you need to load asynchronously recommended request, or the initialValues ? <Form/> : null  
    at BaseForm (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:413:24)
    at RequestForm (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:671:23)
    at ReactResizeObserver (http://localhost:8000/mf-dep_vendors-node_modules___umijs_use-params_1_0_4_umijs_use-params_es_index_js-node_modules__antd-d97acb.93f949af.async.js:255:87)
    at QueryFilter (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:4980:32)
    at BetaSchemaForm (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:2577:23)
    at div
    at FormRender (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:1792:23)
    at FormSearch (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:1971:5)
    at div
    at TableRender (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:151:22)
    at ProTable (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:339:28)
    at ErrorBoundary (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-utils_1_20_4_ant-design_pro-utils_es_components_ErrorBo-162c54.560fff27.async.js:49:5)
    at ConfigProviderWrap (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-provider_1_4_16_ant-design_pro-provider_es_index_js-nod-7f3147.7fe0bd7f.async.js:218:23)
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:5805:31)
    at ProviderWarp (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-table_2_48_0_ant-design_pro-table_es_index_js-node_modu-a31141.441a42ef.async.js:781:70)
    at div
    at div
    at div
    at WaterMark (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:3564:24)
    at div
    at div
    at GridContent (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:1266:64)
    at div
    at PageContainer (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:1501:24)
    at Page (http://localhost:8000/p__merchant__settlement__list.js:214:25)
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules___umijs_runtime_3_5_17_umijs_runtime_dist_index_esm_js.d706c50b.async.js:414:68)
    at Route
    at Switch
    at WithExceptionOpChildren (http://localhost:8000/.umi__plugin-layout__Layout.js:232:24)
    at main
    at Basic (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:426:25)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:409:66)
    at ConfigProviderWrap (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-provider_1_4_16_ant-design_pro-provider_es_index_js-nod-7f3147.7fe0bd7f.async.js:218:23)
    at WrapContent (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:957:21)
    at div
    at section
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:441:63)
    at Adapter (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_menu_index_js.5943221a.async.js:409:66)
    at div
    at Provider (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:5805:31)
    at BasicLayout (http://localhost:8000/mf-dep_vendors-node_modules___ant-design_pro-layout_6_24_0_ant-design_pro-layout_es_index_js-node_mo-436bef.19b5431f.async.js:306:66)
    at BasicLayout (http://localhost:8000/.umi__plugin-layout__Layout.js:716:24)
    at http://localhost:8000/.umi__plugin-layout__Layout.js:41:19
    at LoadableComponent (http://localhost:8000/mf-dep_vendors-node_modules___umijs_runtime_3_5_17_umijs_runtime_dist_index_esm_js.d706c50b.async.js:414:68)
    at Route
    at Switch
    at Router (http://localhost:8000/mf-dep_vendors-node_modules___umijs_runtime_3_5_17_umijs_runtime_dist_index_esm_js.d706c50b.async.js:3046:30)
    at RouterComponent (http://localhost:8000/mf-dep_vendors-node_modules___babel_runtime_7_15_3_babel_runtime_helpers_esm_objectWithoutProperties-9e08e6.b2431910.async.js:610:23)
    at AccessProvider (http://localhost:8000/umi.js:1278:24)
    at http://localhost:8000/umi.js:1908:24
    at FormProvider (http://localhost:8000/mf-dep_vendors-node_modules__rc-field-form_1_20_1_rc-field-form_es_index_js.175f194e.async.js:2588:31)
    at LocaleProvider (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_index_js-node_modules__antd_4_16_1-1b08d7.7ac78db0.async.js:258:87)
    at ProviderChildren (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_index_js-node_modules__antd_4_16_1-1b08d7.7ac78db0.async.js:90:24)
    at LocaleReceiver (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_context_js.758a6407.async.js:720:87)
    at ConfigProvider (http://localhost:8000/mf-dep_vendors-node_modules__antd_4_16_12_antd_es_config-provider_index_js-node_modules__antd_4_16_1-1b08d7.7ac78db0.async.js:198:13)
    at _LocaleContainer (http://localhost:8000/umi.js:3133:31)
    at http://localhost:8000/umi.js:3714:23
overrideMethod @ react_devtools_backend.js:2842
note @ mf-dep_vendors-node_modules___ant-design_icons_4_6_3_ant-design_icons_es_components_AntdIcon_js.03f1fc37.async.js:465
call @ mf-dep_vendors-node_modules___ant-design_icons_4_6_3_ant-design_icons_es_components_AntdIcon_js.03f1fc37.async.js:473
noteOnce @ mf-dep_vendors-node_modules___ant-design_icons_4_6_3_ant-design_icons_es_components_AntdIcon_js.03f1fc37.async.js:481
(anonymous) @ mf-dep_vendors-node_modules___ant-design_pro-form_1_34_0_ant-design_pro-form_es_components_SchemaFor-d20f88.577e98f7.async.js:548
invokePassiveEffectCreate @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23491
callCallback @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:3954
invokeGuardedCallbackDev @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:4003
invokeGuardedCallback @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:4065
flushPassiveEffectsImpl @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23578
unstable_runWithPriority @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:27147
runWithPriority$1 @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:11285
flushPassiveEffects @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23451
(anonymous) @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:23328
workLoop @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:27096
flushWork @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:27069
performWorkUntilDeadline @ mf-dep_vendors-node_modules__react-dom_17_0_2_react-dom_index_js.14b7869b.async.js:26836
```

**Comment by chenshuai2144** [comment]
这个是因为 initialvalues的误用导致的。
