### ISSUE TITLE
🧐[问题]使用npm run openapi报错

### ISSUE THREAD

**Issue by Loomark** [ant-design/ant-design-pro#8954]
### 🧐 问题描述
执行npm run api报错
```
npm run openapi

> ant-design-pro@5.0.0-beta.2 openapi
> umi openapi

(node:54306) UnhandledPromiseRejectionWarning: Error: not support Intl or zh-CN language.
    at parse (/Users/Tao/Documents/myapps/weaf/node_modules/tiny-pinyin/dist/core.js:126:11)
    at Object.convertToPinyin (/Users/Tao/Documents/myapps/weaf/node_modules/tiny-pinyin/dist/core.js:139:12)
    at resolveTypeName (/Users/Tao/Documents/myapps/weaf/node_modules/@umijs/openapi/dist/serviceGenerator.js:32:34)
    at /Users/Tao/Documents/myapps/weaf/node_modules/@umijs/openapi/dist/serviceGenerator.js:193:33
    at Array.forEach (<anonymous>)
    at /Users/Tao/Documents/myapps/weaf/node_modules/@umijs/openapi/dist/serviceGenerator.js:192:22
    at Array.forEach (<anonymous>)
    at /Users/Tao/Documents/myapps/weaf/node_modules/@umijs/openapi/dist/serviceGenerator.js:182:55
    at Array.forEach (<anonymous>)
    at new ServiceGenerator (/Users/Tao/Documents/myapps/weaf/node_modules/@umijs/openapi/dist/serviceGenerator.js:180:46)
```
之前运行时可以的，配置代码如下：
openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'http://localhost:8080/v3/api-docs',
      projectName: 'server-api',
      mock: false,
    },
  ],

请求帮忙谢谢

**Comment by Loomark** [comment]
解决了 对版本有要求 道友们注意下 我用node :13.14 可以
