### ISSUE TITLE
🐛[BUG] npm run start 后非常卡，然后内存报错崩溃

### ISSUE THREAD

**Issue by andy136240860** [ant-design/ant-design-pro#8978]
### 🐛 bug 描述

npm run start 后， build很久， 开启 MFSU 或者不开启都是一样很慢， 感觉应该是 umi 包造成的， 崩溃后报错信息如下

`
<--- Last few GCs --->

[2606:0x102d56000]   145238 ms: Scavenge 2027.3 (2050.6) -> 2026.7 (2050.8) MB, 7.1 / 0.0 ms  (average mu = 0.316, current mu = 0.325) allocation failure 
[2606:0x102d56000]   145249 ms: Scavenge 2027.5 (2050.8) -> 2026.9 (2051.1) MB, 6.0 / 0.0 ms  (average mu = 0.316, current mu = 0.325) allocation failure 
[2606:0x102d56000]   146217 ms: Mark-sweep 2027.7 (2051.1) -> 2026.5 (2051.1) MB, 963.1 / 0.9 ms  (average mu = 0.365, current mu = 0.408) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1009ce8d9]
    1: StubFrame [pc: 0x100953a43]
Security context: 0x3af27fec08d1 <JSObject>
    2: join [0x3af2190d3fe9] [path.js:~1033] [pc=0x3de87215183d](this=0x3af23c87fb71 <Object map = 0x3af2db3b0639>)
    3: arguments adaptor frame: 2->0
    4: /* anonymous */ [0x3af26e0d3cc1] [/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/_@umijs_deps@3.5.17@@umijs/deps/compiled/webpack/5/bundle5.js:...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1011bdf85 node::Abort() (.cold.1) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 2: 0x10009d569 node::Abort() [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 3: 0x10009d6cf node::OnFatalError(char const*, char const*) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 4: 0x1001de957 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 5: 0x1001de8f7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 6: 0x100364635 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 7: 0x100365e8a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 8: 0x10036290e v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
 9: 0x1003606c0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
10: 0x10036c4ea v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
11: 0x10036c571 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
12: 0x10033a78a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
13: 0x100689858 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
14: 0x1009ce8d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
15: 0x100953a43 Builtins_StringSubstring [/Users/guo/.nvm/versions/node/v12.18.2/bin/node]
`

### 📷 复现步骤

git clone 后，  node V12 版本，  cnpm i  安装后 npm run start

- Ant Design Pro 版本: 5.0.0
- umi 版本 3.5.17
- 浏览器环境 Chrome 92
- 开发环境 mac OS

**Comment by andy136240860** [comment]
已经重新安装多次， node 从10 变成12、14， 移除了本地node_modules用 npm cnpm yarn tyarn 重装依旧不行， 其中 tyarn 安装后， 用 umi dev  启动后错误如下：

`AssertionError [ERR_ASSERTION]: filePath not found of /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/_@umijs_renderer-react@3.5.17@@umijs/renderer-react
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:119:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:64:103)
    at _next (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:194)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:364
    at new Promise (<anonymous>)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:97
    at figureOutExport (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:129:17)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:84:103)
    at _next (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:194)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:364
    at new Promise (<anonymous>)
    at /Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:97
    at DepBuilder.writeMFFiles (/Users/guo/Documents/project2021/underwater_robot_admin_h5/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:195:7)`

**Comment by chenxizhang** [comment]
之前遇到过一次，安装LTS版本node就可以了。但不知道你这个问题的情况是否有所不同。

**Comment by chenshuai2144** [comment]
这个一般是全局装了什么node 包导致，清空一下缓存，重新装node把
