### ISSUE TITLE
获取Ant Design Pro V5模板后安装module依赖报错🐛[BUG]

### ISSUE THREAD

**Issue by tilkofjin** [ant-design/ant-design-pro#9176]
### 🐛 bug 描述
获取模板成功后，执行 `yarn` 或 `npm i` 安装依赖后报错，错误信息如下：
```bash
[5/5] Building fresh packages...
success Saved lockfile.
$ umi g tmp
EISDIR: illegal operation on a directory, symlink 'E:/AntProV5\' -> 'E:\AntProV5\node_modules\ant-design-pro'
Error: EISDIR: illegal operation on a directory, symlink 'E:/AntProV5\' -> 'E:\AntProV5\node_modules\ant-design-pro'
    at Object.symlinkSync (node:fs:1651:3)
    at _default (E:\AntProV5\node_modules\@umijs\preset-dumi\lib\utils\symlink.js:54:17)
    at E:\AntProV5\node_modules\@umijs\preset-dumi\lib\plugins\features\symlink.js:54:28
    at Array.forEach (<anonymous>)
    at _default (E:\AntProV5\node_modules\@umijs\preset-dumi\lib\plugins\features\symlink.js:48:16)
    at E:\AntProV5\node_modules\@umijs\core\lib\Service\Service.js:364:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\AntProV5\node_modules\@umijs\core\lib\Service\Service.js:110:103)
    at _next (E:\AntProV5\node_modules\@umijs\core\lib\Service\Service.js:112:194)
    at E:\AntProV5\node_modules\@umijs\core\lib\Service\Service.js:112:364
error Command failed with exit code 1.
```

### 📷 复现步骤
查到是因为系统硬盘格式非 NTFS 导致，我安装项目的硬盘格式为 **exFAT** ，另人疑惑的是 AntD-Pro-V4 的模板不存在此问题，虽然修改硬盘格式可以解决此问题，但希望官方能解决，而不是让用户重新格式化硬盘！

### 🏞 期望结果
项目正常安装依赖，正常启动

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本: [e.g. ^3.5.0]
- 浏览器环境
- 开发环境 [e.g. Win10]

### 🚑 其他信息
Antd-Pro-V5的官方模板

**Comment by chenshuai2144** [comment]
git clean -dfx 一下，你把权限弄坏了。


对操作系统理解不深的话最好用的 mac 或者linux 。windows 上面的小坑很多
