### ISSUE TITLE
🐛[BUG]流水线构建pro项目失败

### ISSUE THREAD

**Issue by MachoManCk** [ant-design/ant-design-pro#9483]
[16:19:43] [User Command] + cnpm install
[16:19:43] npm info it worked if it ends with ok
[16:19:43] npm info using npm@6.14.7
[16:19:43] npm info using node@v14.8.0
[16:19:43] npm timing npm Completed in 32ms
[16:19:43] npm info ok 
[16:19:44] npm info it worked if it ends with ok
[16:19:44] npm info using npm@6.14.7
[16:19:44] npm info using node@v14.8.0
[16:19:44] npm timing npm Completed in 31ms
[16:19:44] npm info ok 
[16:19:44] npm info it worked if it ends with ok
[16:19:44] npm info using npm@6.14.7
[16:19:44] npm info using node@v14.8.0
[16:19:44] npm timing npm Completed in 31ms
[16:19:44] npm info ok 
[16:19:51] ✖ Install fail! Error: Unsupported URL Type: workspace:*
[16:19:51] Error: Unsupported URL Type: workspace:*
[16:19:51]     at parseUrl (/usr/local/lib/node_modules/cnpm/node_modules/npm-package-arg/npa.js:186:13)
[16:19:51]     at npa (/usr/local/lib/node_modules/cnpm/node_modules/npm-package-arg/npa.js:79:12)
[16:19:51]     at _install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:62:11)
[16:19:51]     at _install.next (<anonymous>)
[16:19:51]     at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
[16:19:51]     at /usr/local/lib/node_modules/cnpm/node_modules/co/index.js:54:5
[16:19:51]     at new Promise (<anonymous>)
[16:19:51]     at co (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:50:10)
[16:19:51]     at toPromise (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:118:63)
[16:19:51]     at next (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:99:29)
[16:19:51] npminstall version: 3.28.0
[16:19:51] npminstall args: /root/.nvm/versions/node/v14.8.0/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org
[16:19:51] [ERROR] BUILD ERROR
[16:19:51] [ERROR] 38325044
[16:19:51] [ERROR] 1

**Comment by chenshuai2144** [comment]
我百度了一下说是因为npm 的版本太低导致的，你试试升级一下。
