### ISSUE TITLE
Deprecated nomnom@1.6.2: Package no longer supported

### ISSUE THREAD

**Issue by lordent** [ant-design/ant-design-pro#952]
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.

https://www.npmjs.com/package/nomnom

**Comment by chenshuai2144** [comment]
We do not depend on this library directly

**Comment by andy1247008998** [comment]
@chenshuai2144 我也遇到了这个情况

```
andydeMac-mini:ant-design-pro andy$ npm install
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
events.js:182░░░░░░⸩ ⠇ extract:rc-hammerjs: sill extract isomorphic-fetch@2.2.1
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:120:20)
    at ReadEntry.emit (events.js:210:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:115:13)
    at Unzip.emit (events.js:210:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)

> fsevents@1.1.3 install /Users/andy/test/ant-design-pro/node_modules/fsevents
> node install

[fsevents] Success: "/Users/andy/test/ant-design-pro/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> husky@0.14.3 install /Users/andy/test/ant-design-pro/node_modules/husky
> node ./bin/install.js
```

**Comment by qzm** [comment]
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
-----
pro cli 1.0.0

**Comment by jianhunxia** [comment]
用cnpm i 试下，我的就是这样弄好的，原因不明。

**Comment by qzm** [comment]
npm install --registry=https://registry.npm.taobao.org
可以解决问题
