### ISSUE TITLE
🐛[BUG]使用pnpm选择complete模板start报错

### ISSUE THREAD

**Issue by weiheli** [ant-design/ant-design-pro#9587]
### 🐛 bug 描述

如题，选择complete模板会启动失败，simple模板可以正常启动。

### 📷 复现步骤

```
pnpx create-umi myapp
```

```
+ create-umi 0.27.0
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? TypeScript
? 🚀 Do you need all the blocks or a simple scaffold? complete
> 🙈 complete mode can only use the version of antd@4
```

安装依赖

```
pnpm i
```

安装成功后，启动

```
pnpm start
```

报错

```
Starting the development server...

✖ Webpack
  Compiled with some errors in 28.21s

 ERROR  Failed to compile with 3 errors                                                                                                                           上午11:44:31

 error  in ./src/.umi/plugin-openapi/openapi.tsx

Module build failed (from ./node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep swagger-ui-react/swagger-ui.css which is imported from @/.umi/plugin-openapi/openapi.tsx
    at getDepVersion (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:129:27)
    at DepInfo.addTmpDep (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:141:56)
    at Object.onTransformDeps (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:327:23)
    at PluginPass.exit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+babel-plugin-import-to-await-require@3.5.20/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:217:140)
    at newFn (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56887:8)
    at TraversalContext.visitQueue (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)
    at Function.traverse.node (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56506:17)
    at traverse (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56486:12)
    at transformFile (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:6224:29)
    at transformFile.next (<anonymous>)
    at run (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:6152:12)

 error  in ./src/components/HeaderSearch/index.tsx

Module build failed (from ./node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep rc-util/es/hooks/useMergedState which is imported from @/components/HeaderSearch/index.tsx
    at getDepVersion (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:129:27)
    at DepInfo.addTmpDep (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:141:56)
    at Object.onTransformDeps (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:327:23)
    at PluginPass.exit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+babel-plugin-import-to-await-require@3.5.20/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:217:140)
    at newFn (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56887:8)
    at TraversalContext.visitQueue (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)
    at Function.traverse.node (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56506:17)
    at traverse (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56486:12)
    at transformFile (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:6224:29)
    at transformFile.next (<anonymous>)
    at run (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:6152:12)

 error  in ./src/components/NoticeIcon/NoticeIcon.tsx

Module build failed (from ./node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep rc-util/es/hooks/useMergedState which is imported from @/components/NoticeIcon/NoticeIcon.tsx
    at getDepVersion (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/getDepVersion.js:129:27)
    at DepInfo.addTmpDep (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepInfo.js:141:56)
    at Object.onTransformDeps (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+preset-built-in@3.5.20_react-dom@16.14.0+react@16.14.0/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/mfsu.js:327:23)
    at PluginPass.exit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+babel-plugin-import-to-await-require@3.5.20/node_modules/@umijs/babel-plugin-import-to-await-require/lib/index.js:217:140)
    at newFn (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:62022:21)
    at NodePath._call (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56841:20)
    at NodePath.call (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56828:17)
    at NodePath.visit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56887:8)
    at TraversalContext.visitQueue (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56353:16)
    at TraversalContext.visitSingle (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56322:19)
    at TraversalContext.visit (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56381:19)
    at Function.traverse.node (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56506:17)
    at traverse (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:56486:12)
    at transformFile (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:6224:29)
    at transformFile.next (<anonymous>)
    at run (/Users/weiheli/Test/antd-pro-complete2/node_modules/.pnpm/@umijs+deps@3.5.20/node_modules/@umijs/deps/compiled/babel/bundle.js:6152:12)
```

### 🏞 期望结果

不报错

### 💻 复现代码

稳稳的，每次都这样

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- 开发环境 mac OS
- Node v16.13.1
- pnpm 6.24.4

**Comment by a8b7** [comment]
在package.json 中 devDependencies 添加 swagger-ui-react 和rc-util 的包试试

**Comment by chenshuai2144** [comment]
已经修复掉了，现在出错了也不会堵塞

**Comment by seadog16** [comment]
用pnpm会出现同样的错，装几次都一样

**Comment by h7ml** [comment]
同，请问这个问题解决了吗

**Comment by fullee** [comment]
安装依赖：swagger-ui-dist和rc-resize-observer
```shell
pnpm add swagger-ui-dist rc-resize-observer -D
```

**Comment by EricWong1994** [comment]
> 安装依赖：swagger-ui-dist和rc-resize-observer
> 
> ```shell
> pnpm add swagger-ui-dist rc-resize-observer -D
> ```

很管用，在哪里看到的

**Comment by fullee** [comment]
报错提示里面有



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月02日 22:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ant-design/ant-design-pro] 🐛[BUG]使用pnpm选择complete模板start报错 (Issue #9587) |

安装依赖：swagger-ui-dist和rc-resize-observer

pnpm add swagger-ui-dist rc-resize-observer -D

很管用，在哪里看到的
