### ISSUE TITLE
运行 npm start 报错

### ISSUE THREAD

**Issue by dengjiayao** [ant-design/ant-design-pro#962]
PS D:\yao\gitProject\jkyao\admin> npm start

> life@0.0.1 start D:\yao\gitProject\jkyao\admin
> cross-env DISABLE_ESLINT=true roadhog dev

D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:128
      throw e;
      ^

Error: [BABEL] D:\yao\gitProject\jkyao\admin\src\theme.js: You gave us a visitor for the node type OptionalCallExpression but it's not a valid type

把项目clone下来， 运行cnpm i 再运行npm  start 就报这个错了， 不懂为什么

**Comment by chenshuai2144** [comment]
theme.js写错了？

**Comment by dengjiayao** [comment]
// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
module.exports = {
  // 'primary-color': '#10e99b',
  'card-actions-background': '#f5f8fa',
};
它长这样

**Comment by chenshuai2144** [comment]
```
// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
module.exports = {
  // 'primary-color': '#10e99b',
  'card-actions-background': '#f5f8fa',
};

```
试试这样

**Comment by dengjiayao** [comment]
改了哪里(⊙﹏⊙)

**Comment by chenshuai2144** [comment]
直接覆盖一下。。。。。

**Comment by dengjiayao** [comment]
还是报那个错

**Comment by dengjiayao** [comment]
整个错误是这样
PS D:\yao\gitProject\jkyao\admin> npm start

> file@0.0.1 start D:\yao\gitProject\jkyao\admin
> cross-env DISABLE_ESLINT=true roadhog dev

D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:128
      throw e;
      ^

Error: [BABEL] D:\yao\gitProject\jkyao\admin\src\theme.js: You gave us a visitor for the node type OptionalCallExpression but it's not a valid type
    at verify (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_traverse@7.0.0-beta.31@@babel\traverse\lib\visitors.js:143:13)
    at Function.explode (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_traverse@7.0.0-beta.31@@babel\traverse\lib\visitors.js:46:3)
    at D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:271:21
    at cachedFunction (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\caching.js:48:17)
    at loadPluginDescriptor (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:249:10)
    at D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:55:14
    at Array.map (<anonymous>)
    at OptionManager.mergeOptions (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:54:34)
    at D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:77:15
    at Array.forEach (<anonymous>)
    at OptionManager.mergeOptions (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:76:15)
    at D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:77:15
    at Array.forEach (<anonymous>)
    at OptionManager.mergeOptions (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:76:15)
    at OptionManager.init (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:121:14)
    at manageOptions (D:\yao\gitProject\jkyao\admin\node_modules\_@babel_core@7.0.0-beta.31@@babel\core\lib\config\option-manager.js:37:30)
[graceful-process#13128] exit with code:0

**Comment by chenshuai2144** [comment]
重新装一下 babel 这些的吧
解析错误了。
应该是 babel 的问题

**Comment by dengjiayao** [comment]
怎么重新装babel @chenshuai2144

**Comment by ityao** [comment]
我发现把 roadhog升级到2.2.0版本也会报这个错误, 然后指定用2.1.0就没这个错误了

**Comment by youqingxiaozhua** [comment]
我的是这样的错误。。。
`\.roadhogrc.mock.js:1
(function (exports, require, module, __filename, __dirname) { import mockjs from 'mockjs';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Module._compile (D:\OneDrive\frontend\node_modules\_pirates@3.0.2@pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:671:10)
`

**Comment by chenshuai2144** [comment]
roadhog 用2.1试一试呢？

**Comment by xoptimal** [comment]
@chenshuai2144  我的是2.1.0  也这样

**Comment by chenshuai2144** [comment]
试试最新的

**Comment by xoptimal** [comment]
我直接 pro new 创建的项目, 同样也运行不起来 ~  

具体错误信息 :
```
E:\web\agency-distribution>npm start

> ant-design-pro@1.1.0 start E:\web\agency-distribution
> cross-env DISABLE_ESLINT=true roadhog dev

'cross-env' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.1.0 start: `cross-env DISABLE_ESLINT=true roadhog dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-03-08T12_12_05_422Z-debug.log

```
node 版本: 8.10.0  / pro : 1.0.0

**Comment by xoptimal** [comment]
cnpm install 结果: 
```
E:\web\agency-distribution>cnpm install
√ Installed 55 packages
√ Linked 0 latest versions
√ Run 0 scripts
√ All packages installed (used 30ms, speed 0B/s, json 0(0B), tarball 0B)
```

**Comment by xoptimal** [comment]
尝试把 node_modules / bin 删除,  并没有效果~

**Comment by skyFi** [comment]
同样的问题，突然出现的。

```ruby
Build failed: [BABEL] /Users/xxx/yyy/.webpackrc.js: You gave us a visitor for the node type OptionalCallExpression but it's not a valid type
```

**Comment by skyFi** [comment]
reopen this issue? @chenshuai2144

**Comment by skyFi** [comment]
如下解决方案，解决了我的问题。

### 修改package.json

```
{
  // ....
  "@babel/runtime": "7.0.0-beta.41",
  // ....
}
```

### 执行命令

```shell
rm -rf node_modules && rm -rf package-lock.json && npm install
```

> PS：不要在生产环境使用`beta`的包，老哥！！会害人的。
