### ISSUE TITLE
🧐[问题] error: Transforming for-await loops to the configured target environment is not supported yet

### ISSUE THREAD

**Issue by GloriaCHL** [ant-design/ant-design-pro#9647]
### 🧐 问题描述

项目初始化后，安装了一个第三方js库后，build报错如下：

### 💻 示例代码

```
HookWebpackError: Transform failed with 1 error:
474.7b607fa9.async.js:8:407582: error: Transforming for-await loops to the configured target environment is not supported yet
    at makeWebpackError (/Users/xxx/Documents/workspaces/excalidraw-react-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:108568:9)
    at /Users/xxx/Documents/workspaces/excalidraw-react-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93433:12
    at eval (eval at create (/Users/xxx/Documents/workspaces/excalidraw-react-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:55:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 🚑 其他信息

使用 cra 初始化的项目安装这个第三方库是可以正常打包的。查了下说是tsconfig的build配置问题。但不知怎么修改配置，望指教

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#nodemodulestransform

打开一下这个配置。

建议不要用这种库，在编译产物里用浏览器还没支持的 api，兼容性会非常差
