### ISSUE TITLE
解析.mjs报错🧐[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#9717]
### 🧐 问题描述
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/27960630/160746268-d1faa329-a042-47ec-a1dd-b85ab65f0e50.png">

"umi": "^3.5.20",
"@ant-design/pro-cli": "^2.1.0",

**Comment by chenshuai2144** [comment]
你用了什么奇怪的库？

**Comment by lovesL** [comment]
> 你用了什么奇怪的库？

minio

**Comment by chenshuai2144** [comment]
大佬关掉了你的issue，说没法复现

**Comment by lunajing** [comment]
我也是用了minio， 也报错了；
`Uncaught TypeError: Class extends value undefined is not a constructor or null
at 13861 (umi.59585bed.js:1032:64725)
    at __webpack_require__ (umi.59585bed.js:1250:7724)
    at 82525 (umi.59585bed.js:1026:37975)
    at __webpack_require__ (umi.59585bed.js:1250:7724)
    at 60595 (umi.59585bed.js:366:28818)
    at __webpack_require__ (umi.59585bed.js:1250:7724)
    at zc (umi.59585bed.js:1300:56227)
    at initialValue (umi.59585bed.js:1300:57023)
    at umi.59585bed.js:414:7342
    at umi.59585bed.js:1300:57175`

请问楼主解决了吗?

**Comment by chenshuai2144** [comment]
升级一下umi版本应该就可以了
