### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by kobona** [ant-design/ant-design-pro#9729]
### 🐛 bug 描述

使用 `npx create-umi myapp` 创建应用后，执行  `npm install` 与  `npm start` 正常，但是执行 `npm run build` 构建失败，构建日志如下：
```

● Webpack █████████████████████████ cache (99%) begin idle
 IdleFileCachePlugin

(node:75623) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:75623) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:75623) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
HookWebpackError: The service is no longer running
    at makeWebpackError (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:108568:9)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93433:12
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:55:1)
-- inner error --
Error: The service is no longer running
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1020:33
    at sendRequest (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:538:14)
    at start (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1018:13)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1068:9)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:14)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1268:26)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:69:50
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:67:14)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:38:43
    at fn (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:91431:19)
    at _next1 (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:46:17)
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:68:1)
caused by plugins in Compilation.hooks.processAssets
Error: The service is no longer running
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1020:33
    at sendRequest (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:538:14)
    at start (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1018:13)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1068:9)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:14)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1268:26)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:69:50
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:67:14)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:38:43
    at fn (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:91431:19)
    at _next1 (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:46:17)
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:68:1)
build failed
Error: build failed
    at /Users/Jack/goliath-ui/node_modules/@umijs/bundler-webpack/lib/index.js:172:29
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114591:14
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114422:12
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38249:7
    at done (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38284:11)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38237:7
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114419:8
    at arrayEach (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:37824:9)
    at Object.each (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38265:9)
    at nodeDone (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114413:21)
    at finalCallback (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:95870:32)
    at onCompiled (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:95879:20)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:96554:25
    at finalCallback (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93172:11)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93432:18
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:55:1)
```

### 📷 复现步骤

只需执行 `npm install` 与 `npm run build` 即可复现

### 🏞 期望结果

能正常执行 `npm run build`

### 💻 复现代码

代码上传至仓库 https://github.com/kobona/goliath-ui

### © 版本信息

```json
{
  'ant-design-pro': '5.2.0',
  npm: '8.3.0',
  node: '16.10.0',
  v8: '9.3.345.19-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

![image](https://user-images.githubusercontent.com/40238536/162015087-60a2388c-a6db-495d-95c4-4f82f094fc19.png)

**Comment by hardwin1014** [comment]
我也遇到了这个问题，请问解决了吗
