### ISSUE TITLE
🐛[BUG]新建空项目 npm build 失败

### ISSUE THREAD

**Issue by kobona** [ant-design/ant-design-pro#9730]
### 🐛 bug 描述

最近使用 Ant Design Pro 5 开发项目，开发体验良好，未发现任何问题。最近项目准备部署至测试环境，在执行 `npm run build` 的过程中报错，无法进行下去。

尝试使用 `npx create-umi myapp` 创建空应用，执行 `npm run build` 构建同样也失败，构建日志如下：
```

● Webpack █████████████████████████ cache (99%) begin idle
 IdleFileCachePlugin

(node:75623) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:75623) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:75623) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
HookWebpackError: The service is no longer running
    at makeWebpackError (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:108568:9)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93433:12
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:55:1)
-- inner error --
Error: The service is no longer running
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1020:33
    at sendRequest (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:538:14)
    at start (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1018:13)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1068:9)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:14)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1268:26)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:69:50
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:67:14)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:38:43
    at fn (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:91431:19)
    at _next1 (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:46:17)
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:68:1)
caused by plugins in Compilation.hooks.processAssets
Error: The service is no longer running
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1020:33
    at sendRequest (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:538:14)
    at start (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1018:13)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1068:9)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1419:14)
    at Object.transform (/Users/Jack/goliath-ui/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1268:26)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:69:50
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:67:14)
    at /Users/Jack/goliath-ui/node_modules/esbuild-loader/dist/minify-plugin.js:38:43
    at fn (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:91431:19)
    at _next1 (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:46:17)
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:68:1)
build failed
Error: build failed
    at /Users/Jack/goliath-ui/node_modules/@umijs/bundler-webpack/lib/index.js:172:29
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114591:14
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114422:12
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38249:7
    at done (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38284:11)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38237:7
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114419:8
    at arrayEach (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:37824:9)
    at Object.each (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38265:9)
    at nodeDone (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114413:21)
    at finalCallback (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:95870:32)
    at onCompiled (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:95879:20)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:96554:25
    at finalCallback (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93172:11)
    at /Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93432:18
    at eval (eval at create (/Users/Jack/goliath-ui/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:55:1)
```

在下是个前端小白，有误之处请各位多多包涵。

### 📷 复现步骤

只需执行 `npm install` 与 `npm run build` 即可复现

### 🏞 期望结果

能正常执行 `npm run build`

### 💻 复现代码

代码上传至仓库 https://github.com/kobona/goliath-ui

### © 版本信息

```json
{
  'ant-design-pro': '5.2.0',
  npm: '8.3.0',
  node: '16.10.0',
  v8: '9.3.345.19-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

![image](https://user-images.githubusercontent.com/40238536/162015087-60a2388c-a6db-495d-95c4-4f82f094fc19.png)

**Comment by chenshuai2144** [comment]
把 node 版本升级到 16 吧

**Comment by kobona** [comment]
你好，目前已经是 16 了。
```
  npm: '8.3.0',
  node: '16.10.0',
```
今天我尝试在 linux 下打包是成功的，难道是 mac os 的兼容性问题？
```
[INFO]
[INFO] Why you should do it regularly:
[INFO] https://github.com/browserslist/browserslist#browsers-data-updating
[INFO] (node:10844) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
[INFO] BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
[INFO] 	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
[INFO] 	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
[INFO] ✔ Webpack: Compiled successfully in 11.49s
[INFO]  DONE  Compiled successfully in 11519ms11:01:53 AM
[INFO]
[INFO]  File                                         Size           Gzipped
[INFO]
[INFO]  dist/umi.1875915e.js                         1.2 MB         375.6 KB
[INFO]  dist/p__QuoteData.60f292a9.async.js          1.0 MB         352.1 KB
[INFO]  dist/764.bda7a7c4.async.js                   221.6 KB       68.1 KB
[INFO]  dist/590.a071f7e1.async.js                   83.3 KB        28.6 KB
[INFO]  dist/124.5b1b5ed6.async.js                   77.3 KB        22.8 KB
[INFO]  dist/t__plugin-layout__Layout.bced6899.      71.6 KB        24.1 KB
[INFO]  async.js
[INFO]  dist/914.cea3e514.async.js                   65.1 KB        20.0 KB
[INFO]  dist/883.45426bf3.async.js                   61.2 KB        19.9 KB
[INFO]  dist/265.91cd6559.async.js                   60.3 KB        21.6 KB
[INFO]  dist/799.f321cbac.async.js                   45.0 KB        16.0 KB
[INFO]  dist/247.ac1153bb.async.js                   40.5 KB        12.7 KB
[INFO]  dist/p__DraftGroup.2cfb4fad.async.js         30.4 KB        11.5 KB
[INFO]  dist/701.f5a100f1.async.js                   27.9 KB        10.4 KB
[INFO]  dist/773.0e78bbae.async.js                   21.9 KB        7.9 KB
[INFO]  dist/724.f724ae30.async.js                   19.6 KB        6.7 KB
[INFO]  dist/p__BatchJob.01b8589c.async.js           17.1 KB        6.0 KB
[INFO]  dist/945.ade4b965.async.js                   17.1 KB        7.0 KB
[INFO]  dist/597.f04ba3bc.async.js                   11.0 KB        4.1 KB
[INFO]  dist/p__StockEvent.877c6637.async.js         7.3 KB         2.8 KB
[INFO]  dist/p__DraftTicket.f022c93d.async.js        4.1 KB         1.7 KB
[INFO]  dist/p__TickerData.c71a384f.async.js         3.6 KB         1.6 KB
[INFO]  dist/p__user__Login.ee4a5e06.async.js        3.3 KB         1.4 KB
[INFO]  dist/p__Welcome.b07125da.async.js            1.6 KB         684.0 B
[INFO]  dist/p__404.5822969b.async.js                442.0 B        324.0 B
[INFO]  dist/umi.de45462c.css                        257.1 KB       31.3 KB
[INFO]  dist/764.7cb8da3b.chunk.css                  79.1 KB        10.8 KB
[INFO]  dist/590.90daa11f.chunk.css                  56.6 KB        8.1 KB
[INFO]  dist/914.f98a6d7b.chunk.css                  32.0 KB        4.6 KB
[INFO]  dist/724.4f273d41.chunk.css                  26.0 KB        3.4 KB
[INFO]  dist/265.474756e4.chunk.css                  24.7 KB        3.7 KB
[INFO]  dist/340.c66f6562.chunk.css                  20.1 KB        3.3 KB
[INFO]  dist/701.505a9a79.chunk.css                  18.6 KB        3.6 KB
[INFO]  dist/t__plugin-layout__Layout.488c2be5.      16.6 KB        3.0 KB
[INFO]  chunk.css
[INFO]  dist/p__QuoteData.b343e38d.chunk.css         16.4 KB        3.0 KB
[INFO]  dist/p__Welcome.55142631.chunk.css           14.1 KB        3.0 KB
[INFO]  dist/p__BatchJob.29f464e6.chunk.css          10.8 KB        2.2 KB
[INFO]  dist/p__TickerData.661ee886.chunk.css        6.6 KB         1.7 KB
[INFO]  dist/p__404.572eeed8.chunk.css               2.5 KB         717.0 B
[INFO]  dist/p__user__Login.b2ad585f.chunk.css       769.0 B        439.0 B
[INFO]
[INFO]   Images and other types of assets omitted.
[INFO]
[INFO]
[INFO] The bundle size is significantly larger than recommended.
[INFO] Consider reducing it with code splitting: https://umijs.org/docs/load-on-demand
[INFO] You can also analyze the project dependencies using ANALYZE=1
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ goliath-admin ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for goliath 1.0-SNAPSHOT:
[INFO]
[INFO] goliath ............................................ SUCCESS [  0.002 s]
[INFO] goliath-common ..................................... SUCCESS [  9.981 s]
[INFO] goliath-admin ...................................... SUCCESS [ 48.285 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by chenshuai2144** [comment]
HookWebpackError: The service is no longer running

这个是esbuild的兼容性问题，去 esbuild 看看额

**Comment by kobona** [comment]
> HookWebpackError: The service is no longer running
> 
> 这个是esbuild的兼容性问题，去 esbuild 看看额

好的，谢谢

**Comment by florida0723** [comment]
咋解决的？
