### ISSUE TITLE
🧐[问题] npm run build 失败，esbuild报The service is no longer running，npm run start没问题，无法编译部署

### ISSUE THREAD

**Issue by sillyMoney** [ant-design/ant-design-pro#9752]
### 🧐 问题描述
依赖环境:
node: v16.14.2
npm: 8.5.0
错误堆栈：
HookWebpackError: The service is no longer running
    at makeWebpackError (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:108568:9)
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93433:12
    at eval (eval at create (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:55:1)
-- inner error --
Error: The service is no longer running
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1021:33
    at sendRequest (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:539:14)
    at start (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1019:13)
    at Object.transform (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1069:9)
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1422:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1422:14)
    at Object.transform (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1269:26)
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/dist/minify-plugin.js:69:50
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/dist/minify-plugin.js:67:14)
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/dist/minify-plugin.js:38:43
    at fn (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:91431:19)
    at _next1 (eval at create (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:46:17)
    at eval (eval at create (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:68:1)
caused by plugins in Compilation.hooks.processAssets
Error: The service is no longer running
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1021:33
    at sendRequest (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:539:14)
    at start (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1019:13)
    at Object.transform (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1069:9)
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1422:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1422:14)
    at Object.transform (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1269:26)
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/dist/minify-plugin.js:69:50
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/dist/minify-plugin.js:67:14)
    at /Users/sf/Documents/work/front-code/manager/node_modules/esbuild-loader/dist/minify-plugin.js:38:43
    at fn (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:91431:19)
    at _next1 (eval at create (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:46:17)
    at eval (eval at create (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:68:1)
build failed
Error: build failed
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/bundler-webpack/lib/index.js:172:29
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114591:14
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114422:12
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38249:7
    at done (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38284:11)
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38237:7
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114419:8
    at arrayEach (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:37824:9)
    at Object.each (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:38265:9)
    at nodeDone (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114413:21)
    at finalCallback (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:95870:32)
    at onCompiled (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:95879:20)
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:96554:25
    at finalCallback (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93172:11)
    at /Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:93432:18
    at eval (eval at create (/Users/sf/Documents/work/front-code/manager/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:50186:10), <anonymous>:55:1)

### 💻 示例代码
按照官方文档初始化完脚手架
npm run build报上述异常

### 🚑 其他信息

package.json:
{
  "name": "ant-design-pro",
  "version": "5.2.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "openapi": "umi openapi",
    "playwright": "playwright install && playwright test",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "test": "umi test",
    "test:component": "umi test ./src/components",
    "test:e2e": "node ./tests/run-tests.js",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": ["prettier --write"]
  },
  "browserslist": ["defaults", "maintained node versions", "not IE 11"],
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.60.0",
    "@ant-design/pro-layout": "^6.34.0",
    "@ant-design/pro-table": "^2.69.0",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.18.0",
    "classnames": "^2.3.0",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "umi": "^3.5.20"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.8.0",
    "@umijs/openapi": "^1.3.0",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.1",
    "@umijs/plugin-openapi": "^1.3.0",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^1.8.17",
    "@umijs/yorkie": "^2.0.5",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "eslint": "^7.32.0",
    "gh-pages": "^3.2.0",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "stylelint": "^13.0.0",
    "swagger-ui-react": "^3.52.0",
    "typescript": "^4.5.0",
    "umi-serve": "^1.9.10"
  },
  "engines": { "node": ">=12.0.0" },
  "gitHooks": { "commit-msg": "fabric verify-commit" }
}

**Comment by chenshuai2144** [comment]
着急的话 esbuild 先关掉一下吧。

**Comment by chenshuai2144** [comment]
https://github.com/angular/angular-cli/issues/22338#:~:text=The%20service%20is%20no%20longer%20running%20indicates%20that,the%20system%20is%20critically%20low%20on%20memory.%20Author?msclkid=5981a4ddbed411ecb5fd084d493dc3ad

这个issue 里有个解决方案你试试

**Comment by sillyMoney** [comment]
用tyarn去install和build就解决问题了

**Comment by chenendian** [comment]
遇到过同样的问题，，固定 esbuild  这个依赖的版本就行了   不得不说  建议官方做好版本固定
