### ISSUE TITLE
🧐[问题] 初始化按照报错 Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design-pro#9802]
### 🧐 问题描述

使用 Yarn 进行初始化项目

### 💻 示例代码

```cmd
# 使用 yarn
yarn create umi myapp
```

### 🚑 其他信息

```
yarn create v1.22.17
[1/4] Resolving packages...
warning create-umi > sylvanas > @umijs/fabric > stylelint > @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
warning create-umi > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning create-umi > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning create-umi > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning create-umi > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-umi@0.27.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
D:\node\yarn_global\node_modules\create-umi\lib\generators\ant-design-pro\index.js:11
const sortPackage = require('sort-package-json');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\node\yarn_global\node_modules\sort-package-json\index.js from D:\node\yarn_global\node_modules\create-umi\lib\generators\ant-design-pro\index.js not supported.
Instead change the require of D:\node\yarn_global\node_modules\sort-package-json\index.js in D:\node\yarn_global\node_modules\create-umi\lib\generators\ant-design-pro\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\node\yarn_global\node_modules\create-umi\lib\generators\ant-design-pro\index.js:11:21)
    at D:\node\yarn_global\node_modules\create-umi\lib\run.js:27:23
    at new Promise (<anonymous>)
    at runGenerator (D:\node\yarn_global\node_modules\create-umi\lib\run.js:21:10)
    at run (D:\node\yarn_global\node_modules\create-umi\lib\run.js:69:12)
    at async D:\node\yarn_global\node_modules\create-umi\cli.js:31:3 {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed.
Exit code: 1
```

**Comment by zjxpcyc** [comment]
直译错误好像是 `const sortPackage = require('sort-package-json');` 这一行应该是改用 `import`

**Comment by who7708** [comment]
> 

我也是遇到了同样的问题，sort-package-json 这个依赖刚好在今天14:00左右mq刚升级到 1.56.0 版本导致的。
解决方法：
1. npm install -g create-umi
2. 安装 create-umi 目录中的 package.json 修改版本为： "sort-package-json": "1.55.0"
3. 重新安装 一下 create-umi 依赖 npm install 或 yarn install
4. 重新创建项目 create-umi myapp 没有报错即解决
![image](https://user-images.githubusercontent.com/10089256/166138910-24bd73d3-09ae-47bf-886d-754f4a3dbdf0.png)

**Comment by momtboy** [comment]
我也遇到相同的问题了

**Comment by pengyuwei** [comment]
遇到了相同的问题：

```
$ npm config set registry https://registry.npm.taobao.org
$ npm update

up to date, audited 1 package in 219ms

found 0 vulnerabilities
$ npx create-umi myadp
? Select the boilerplate type ant-design-pro
/home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/lib/generators/ant-design-pro/index.js:11
const sortPackage = require('sort-package-json');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/sort-package-json/index.js from /home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/lib/generators/ant-design-pro/index.js not supported.
Instead change the require of /home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/sort-package-json/index.js in /home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/lib/generators/ant-design-pro/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/lib/generators/ant-design-pro/index.js:11:21)
    at /home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/lib/run.js:27:23
    at new Promise (<anonymous>)
    at runGenerator (/home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/lib/run.js:21:10)
    at run (/home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/lib/run.js:69:12)
    at async /home/ubuntu/.npm/_npx/1789ec8a15edf54c/node_modules/create-umi/cli.js:31:3 {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by evan-gyy** [comment]
我也遇到了，node版本17.1.0，sort-package-json版本1.22.1

**Comment by evan-gyy** [comment]
解决方法：
1.  找到create-umi下的package.json查看sort-package-json的依赖版本，比如1.22.1
2.  然后更新版本：`yarn upgrade sort-package-json@1.22.1`
3.  用create-umi代替create umi创建项目：`yarn create-umi myapp`
4.  创建效果如下图所示，没有报错了
![image](https://user-images.githubusercontent.com/49489433/166195867-c037fa50-76f6-41a2-95f2-39a08ab9a96a.png)

**Comment by daqidaqi** [comment]
解决：
v5版本
使用 npm i @ant-design/pro-cli -g 安装后，进入@ant-design/pro-cli 目录下，修改 package.json，在 deependencies 中添加 "sort-package-json": "1.55.0"，然后再 pro-cli 目录下 npm i，之后再用 pro create xxxx 创建
![image](https://user-images.githubusercontent.com/101492621/215133613-e3e3e031-8292-4179-ae2b-814ee177bdff.png)
![image](https://user-images.githubusercontent.com/101492621/215133750-abc475ef-c274-4ecd-8f35-51056ef1e0a6.png)
