### ISSUE TITLE
🧐[问题] 初始化项目之后，yarn start 报错 swagger-ui 中 btoa 找不到

### ISSUE THREAD

**Issue by Sallyfafafa** [ant-design/ant-design-pro#9924]
## 步骤
根据官方说明，执行了以下命令
```
npx create-umi myapp
cd myapp
yarn install
yarn start
```

错误信息：
```
ERROR in ./node_modules/swagger-ui-react/swagger-ui.js 2:107055-107070
Module not found: Error: Can't resolve 'btoa' in '/Users/sally/Documents/oneApp/node_modules/swagger-ui-react'
 @ ./node_modules/swagger-ui-react/index.js 13:0-61 59:15-35 65:53-65
 @ ./src/.umi/.cache/.mfsu/mf-va_swagger-ui-react.js 1:0-33 2:15-16
 @ container entry ./swagger-ui-react[0]

webpack compiled with 1 error
null
Error: build failed
    at /Users/sally/Documents/oneApp/node_modules/@umijs/bundler-webpack/lib/index.js:172:29
    at /Users/sally/Documents/oneApp/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114591:14
    at processQueueWorker (/Users/sally/Documents/oneApp/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114529:6)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)

```

### 🚑 其他信息

node 版本：v18.3.0
yarn 版本：1.22.19

<img width="718" alt="image" src="https://user-images.githubusercontent.com/40735740/174220994-f9467250-e647-452c-b724-2f1c92b48396.png">

**Comment by yuwenzhuifeng** [comment]
yarn add swagger-ui-react --save

**Comment by Sallyfafafa** [comment]
yarn add btoa --save 解决了

**Comment by 569202812** [comment]
> 

弥豆子酱，我是谁
